List<String> classicRock = [
  'Take On Me by a-ha',
  'Hells Bells by AC/DC',
  'Highway To Hell by AC/DC',
  'Shoot To Thrill by AC/DC',
  'T.N.T. by AC/DC',
  'Thunderstruck by AC/DC',
  'Touch Too Much by AC/DC',
  'Angel by Aerosmith',
  'Back in the Saddle by Aerosmith',
  'Crazy by Aerosmith',
  'Cryin\' by Aerosmith',
  'Dream On by Aerosmith',
  'Janie\'s Got A Gun by Aerosmith',
  'Last Child by Aerosmith',
  'Rag Doll by Aerosmith',
  'Same Old Song and Dance by Aerosmith',
  'Sweet Emotion by Aerosmith',
  'The Other Side by Aerosmith',
  'Walk This Way by Aerosmith',
  'A Horse With No Name by America',
  'Ventura Highway by America',
  'AIN\'T NO SUNSHINE by Bill Withers',
  'Piano Man by Billy Joel',
  'The Stranger by Billy Joel',
  'Exodus by Bob Marley',
  'Jamming by Bob Marley',
  'No Woman, No Cry by Bob Marley',
  'One Love by Bob Marley',
  'Against The Wind by Bob Seger',
  'Old Time Rock & Roll by Bob Seger',
  'Turn The Page by Bob Seger',
  'Livin\' On A Prayer by Bon Jovi',
  'You Give Love A Bad Name by Bon Jovi',
  'Green Onions by Booker T. and the MG\'s',
  'More Than a Feeling by Boston',
  'Born In the U.S.A. by Bruce Springsteen',
  'Run to You by Bryan Adams',
  'Bad Moon Rising by Creedence Clearwater Revival',
  'Fortunate Son by Creedence Clearwater Revival',
  'Have You Ever Seen the Rain? by Creedence Clearwater Revival',
  'I Heard It Through the Grapevine by Creedence Clearwater Revival',
  'Lookin\' Out My Back Door by Creedence Clearwater Revival',
  'Suzie Q by Creedence Clearwater Revival',
  'Helplessly Hoping by Crosby, Stills & Nash',
  'Moonage Daydream by David Bowie',
  'Rebel Rebel by David Bowie',
  'Child In Time by Deep Purple',
  'Hush by Deep Purple',
  'Smoke On The Water by Deep Purple',
  'Brothers In Arms by Dire Straits',
  'Money for Nothing by Dire Straits',
  'Sultans of Swing by Dire Straits',
  'Walk of Life by Dire Straits',
  'Desperado by Eagles',
  'Hotel California by Eagles',
  'I Can\'t Tell You Why by Eagles',
  'Life in the Fast Lane by Eagles',
  'Lyin\' Eyes by Eagles',
  'New Kid In Town by Eagles',
  'One of These Nights by Eagles',
  'Peaceful Easy Feeling by Eagles',
  'Take It Easy by Eagles',
  'Take It to the Limit by Eagles',
  'Tequila Sunrise by Eagles',
  'The Best of My Love by Eagles',
  'Victim of Love by Eagles',
  'Witchy Woman by Eagles',
  'Bennie And The Jets by Elton John',
  'Crocodile Rock by Elton John',
  'DANIEL by Elton John',
  'Funeral for a Friend (Love Lies Bleeding) by Elton John',
  'Goodbye Yellow Brick Road by Elton John',
  'Rocket Man by Elton John',
  'Tiny Dancer by Elton John',
  'Your Song by Elton John',
  'Cocaine by Eric Clapton',
  'Layla by Eric Clapton',
  'Tears In Heaven by Eric Clapton',
  'The Final Countdown by Europe',
  'Sweet Dreams (Are Made of This) by Eurythmics',
  'More Than Words by Extreme',
  'Don\'t Stop by Fleetwood Mac',
  'Dreams by Fleetwood Mac',
  'Never Going Back Again by Fleetwood Mac',
  'Rhiannon by Fleetwood Mac',
  'The Chain by Fleetwood Mac',
  'Boulevard Of Broken Dreams by Green Day',
  'Good Riddance (Time Of Your Life) by Green Day',
  'Holiday by Green Day',
  'Civil War by Guns N\' Roses',
  'Don\'t Cry by Guns N\' Roses',
  'Knockin\' On Heaven\'s Door by Guns N\' Roses',
  'November Rain by Guns N\' Roses',
  'Paradise City by Guns N\' Roses',
  'Patience by Guns N\' Roses',
  'Sweet Child O\' Mine by Guns N\' Roses',
  'Welcome to the Jungle by Guns N\' Roses',
  'Long Cool Woman by Hollies',
  'Monster men by Iggy Pop',
  'The Passenger by Iggy Pop',
  'Radioactive by Imagine Dragons',
  'TIME IN A BOTTLE by Jim Croce',
  'All Along the Watchtower by Jimi Hendrix',
  'Hey Joe by Jimi Hendrix',
  'Purple Haze by Jimi Hendrix',
  'Imagine by John Lennon',
  'Don\'t Stop Believin\' by Journey',
  'Breaking The Law by Judas Priest',
  'Dust In The Wind by Kansas',
  'Footloose by Kenny Loggins',
  'Babe I\'m Gonna Leave You by Led Zeppelin',
  'Immigrant Song by Led Zeppelin',
  'Kashmir by Led Zeppelin',
  'Stairway to Heaven by Led Zeppelin',
  'Whole Lotta Love by Led Zeppelin',
  'Are You Gonna Go My Way by Lenny Kravitz',
  'Fly Away by Lenny Kravitz',
  'Sweet Home Alabama by Lynyrd Skynyrd',
  'Down Under by Men At Work',
  'Enter Sandman by Metallica',
  'Fade To Black by Metallica',
  'Nothing Else Matters by Metallica',
  'One by Metallica',
  'The Unforgiven by Metallica',
  'In the Summertime by Mungo Jerry',
  'Heart of Gold by Neil Young',
  'How You Remind Me by Nickelback',
  'About a Girl by Nirvana',
  'Come As You Are by Nirvana',
  'Smells Like Teen Spirit by Nirvana',
  'The Man Who Sold the World by Nirvana',
  'Wonderwall by Oasis',
  'Live and Let Die by Paul McCartney & Wings',
  'Last Kiss by Pearl Jam',
  'Another Brick in the Wall, Pt. 2 by Pink Floyd',
  'Arnold Layne by Pink Floyd',
  'Astronomy Domine by Pink Floyd',
  'Brain Damage by Pink Floyd',
  'Eclipse by Pink Floyd',
  'Comfortably Numb by Pink Floyd',
  'Goodbye Blue Sky by Pink Floyd',
  'Have a Cigar by Pink Floyd',
  'Hey You by Pink Floyd',
  'Learning to Fly by Pink Floyd',
  'Money by Pink Floyd',
  'Mother by Pink Floyd',
  'See Emily Play by Pink Floyd',
  'Shine On You Crazy Diamond by Pink Floyd',
  'Time by Pink Floyd',
  'Welcome To The Machine by Pink Floyd',
  'Wish You Were Here by Pink Floyd',
  'A Whiter Shade of Pale by Procol Harum',
  'Another One Bites the Dust by Queen',
  'Bohemian Rhapsody by Queen',
  'Crazy Little Thing Called Love by Queen',
  'Don\'t Stop Me Now by Queen',
  'Killer Queen by Queen',
  'Somebody To Love by Queen',
  'Under Pressure by Queen',
  'We Are the Champions by Queen',
  'We Will Rock You by Queen',
  'You\'re My Best Friend by Queen',
  'Under Pressure by Queen / David Bowie',
  'Cum On Feel the Noize by Quiet Riot',
  'Losing My Religion by R.E.M.',
  'Californication by Red Hot Chili Peppers',
  'Dani California by Red Hot Chili Peppers',
  'Give It Away by Red Hot Chili Peppers',
  'Under the Bridge by Red Hot Chili Peppers',
  'The Logical Song by The Supertramp',
  '(I Can\'t Get No) Satisfaction by Rolling Stones',
  'Angie by Rolling Stones',
  'Brown Sugar by Rolling Stones',
  'Gimme Shelter by Rolling Stones',
  'Honky Tonk Women by Rolling Stones',
  'Miss You by Rolling Stones',
  'Paint It Black by Rolling Stones',
  'Start Me Up by Rolling Stones',
  'Sympathy For The Devil by Rolling Stones',
  'Under My Thumb by Rolling Stones',
  'Wild Horses by Rolling Stones',
  'Black Magic Woman by Santana',
  'Oye Como Va by Santana',
  'Du bist so Schmutzig by Scorpions',
  'Holiday by Scorpions',
  'No One Like You by Scorpions',
  'Rock You Like a Hurricane by Scorpions',
  'Still Loving You by Scorpions',
  'Wind Of Change by Scorpions',
  'Mrs. Robinson by Simon & Garfunkel',
  'The Sounds Of Silence by Simon & Garfunkel',
  'Born to Be Wild by Steppenwolf',
  'Superstition by Stevie Wonder',
  'Breakfast in America by Supertramp',
  'Goodbye Stranger by Supertramp',
  'Take the Long Way Home by Supertramp',
  'The Logical Song by Supertramp',
  'Eye of the Tiger by Survivor',
  'Psycho Killer by Talking Heads',
  'We gotta get out of this place by The Animals',
  'House Of The Rising Sun by The Animals',
  'The Weight by The Band',
  'Good Vibrations by The Beach Boys',
  'God only knows by The Beach Boys',
  'Surfin USA by The Beach Boys',
  'Barbara Ann by The Beach Boys',
  'I get around by The Beach Boys',
  'Wouldn\'t it be nicer by The Beach Boys',
  'A Day In The Life by The Beatles',
  'A Hard Day\'s Night by The Beatles',
  'Across The Universe by The Beatles',
  'All My Loving by The Beatles',
  'All You Need Is Love by The Beatles',
  'And Your Bird Can Sing by The Beatles',
  'ANYTIME AT ALL by The Beatles',
  'Baby You\'re A Rich Man by The Beatles',
  'Back In the U.S.S.R. by The Beatles',
  'BAD BOY by The Beatles',
  'BALLAD OF JOHN AND YOKO by The Beatles',
  'Birthday by The Beatles',
  'Blackbird by The Beatles',
  'Can\'t Buy Me Love by The Beatles',
  'Come Together by The Beatles',
  'Cry For A Shadow by The Beatles',
  'Day Tripper by The Beatles',
  'Dear Prudence by The Beatles',
  'Don\'t Let Me Down by The Beatles',
  'Drive My Car by The Beatles',
  'Eight Days A Week by The Beatles',
  'Eleanor Rigby by The Beatles',
  'Everybody\'s Got Something To Hide Except Me And My Monk by The Beatles',
  'Fixing A Hole by The Beatles',
  'From Me To You by The Beatles',
  'Get Back by The Beatles',
  'Getting Better by The Beatles',
  'GIRL by The Beatles',
  'Golden Slumbers by The Beatles',
  'Good Day Sunshine by The Beatles',
  'Got To Get You Into My Life by The Beatles',
  'Hello Goodbye by The Beatles',
  'Help! by The Beatles',
  'Helter Skelter by The Beatles',
  'Here Comes The Sun by The Beatles',
  'Hey Jude by The Beatles',
  'I Am the Walrus by The Beatles',
  'I Feel Fine by The Beatles',
  'I Saw Her Standing There by The Beatles',
  'I Want To Hold Your Hand by The Beatles',
  'I Want You (She\'s So Heavy) by The Beatles',
  'I\'ll Follow The Sun by The Beatles',
  'I\'m A Loser by The Beatles',
  'I\'m Down by The Beatles',
  'I\'ve Got A Feeling by The Beatles',
  'I\'ve Just Seen A Face by The Beatles',
  'IN MY LIFE by The Beatles',
  'IT WON\'T BE LONG by The Beatles',
  'Lady Madonna by The Beatles',
  'Let It Be by The Beatles',
  'LITTLE CHILD by The Beatles',
  'Love Me Do by The Beatles',
  'Lovely Rita by The Beatles',
  'Lucy In The Sky With Diamonds by The Beatles',
  'Magical Mystery Tour by The Beatles',
  'Maxwell\'s Silver Hammer by The Beatles',
  'Norwegian Wood by The Beatles',
  'NOWHERE MAN by The Beatles',
  'Ob-la-di, Ob-la-da by The Beatles',
  'OH DARLING by The Beatles',
  'P.s. I Love You by The Beatles',
  'Paperback Writer by The Beatles',
  'Penny Lane by The Beatles',
  'Please Please Me by The Beatles',
  'Reprise / Day in the Life by The Beatles',
  'Revolution by The Beatles',
  'ROCK AND ROLL MUSIC by The Beatles',
  'Rocky Raccoon by The Beatles',
  'Roll Over Beethoven by The Beatles',
  'Sgt. Pepper Inner Groove by The Beatles',
  'Sgt. Pepper\'s Lonely Hearts Club Band by The Beatles',
  'Sgt. Pepper\'s Lonely Hearts Club Band (Reprise) by The Beatles',
  'Sgt. Pepper/a Day In The Life by The Beatles',
  'Sgt. Pepper/with A Little Help From My Friends by The Beatles',
  'She Loves You by The Beatles',
  'SHE\'S A WOMAN by The Beatles',
  'She\'s Leaving Home by The Beatles',
  'Something by The Beatles',
  'Strawberry Fields Forever by The Beatles',
  'Sun King by The Beatles',
  'The Ballad Of John And Yoko by The Beatles',
  'THE CONTINUING STORY OF BUNG by The Beatles',
  'The Fool On The Hill by The Beatles',
  'The Long And Winding Road by The Beatles',
  'The Word by The Beatles',
  'Things We Said Today by The Beatles',
  'Ticket to Ride by The Beatles',
  'Twist and Shout by The Beatles',
  'Two Of Us by The Beatles',
  'We Can Work It Out by The Beatles',
  'When I\'m 64 by The Beatles',
  'While My Guitar Gently Weeps by The Beatles',
  'Wild Honey Pie by The Beatles',
  'With a Little Help From My Friends by The Beatles',
  'Yellow Submarine by The Beatles',
  'Yesterday by The Beatles',
  'You Never Give Me Your Money by The Beatles',
  'You\'re Going To Lose That Girl by The Beatles',
  'YOUR MOTHER SHOULD KNOW by The Beatles',
  'London Calling by The Clash',
  'Listen To The Music by The Doobie Brothers',
  'Long Train Runnin\' by The Doobie Brothers',
  'What a Fool Believes by The Doobie Brothers',
  'Break On Through by The Doors',
  'Hello, I Love You by The Doors',
  'L.A. Woman by The Doors',
  'Light My Fire by The Doors',
  'Love Her Madly by The Doors',
  'Love Me Two Times by The Doors',
  'Peace Frog by The Doors',
  'People Are Strange by The Doors',
  'Riders On The Storm by The Doors',
  'Roadhouse Blues by The Doors',
  'Soul Kitchen by The Doors',
  'The Changeling by The Doors',
  'The Crystal Ship by The Doors',
  'Touch Me by The Doors',
  'Twentieth Century Fox by The Doors',
  'Waiting For The Sun by The Doors',
  'When the Music\'s Over by The Doors',
  'Sunny Afternoon by The Kinks',
  'You Really Got Me by The Kinks',
  'CALIFORNIA DREAMIN\' by The Mamas and the Papas',
  'Every Breath You Take by The Police',
  'Message In A Bottle by The Police',
  'Roxanne by The Police',
  'So Lonely by The Police',
  'Seven Nation Army by The White Stripes',
  'Baba O\'Reilly by The Who'
      'My Generation by The Who',
  'Won\'t Get Fooled Again by The Who',
  'AFRICA by Toto',
  'Hold The Line by Toto',
  'Happy Together by Turtles',
  'I Wanna Rock by Twisted Sister',
  'One by U2',
  'Sunday Bloody Sunday by U2',
  'With Or Without You by U2',
  'Red Red Wine by UB40',
  'Jump by Van Halen',
  'Time of the Season by Zombies',
];
