List<List<String>> michael = [
  mj,
  smoothCriminal,
  beatIt,
  tdtcau,
  yana,
  billieJean,
  rtt,
  htw,
  wbss,
  bow,
  humanNature,
  thriller,
  wii,
  rmichael,
];

List<String> mimichael = [
  'Michael Jackson',
  'Smooth Criminal',
  'Beat It',
  'They Don\'t Care About Us',
  'You Are Not Alone',
  'Billie Jean',
  'Remember the Time',
  'Heal the World',
  'Wanna Be Startin’ Somethin’',
  'Black or White',
  'Human Nature',
  'Thriller',
  'Who Is It',
  'Random MJ',
];

List<String> rmichael = [
  ...mj,
  ...smoothCriminal,
  ...beatIt,
  ...tdtcau,
  ...yana,
  ...billieJean,
  ...rtt,
  ...htw,
  ...wbss,
  ...bow,
  ...humanNature,
  ...thriller,
  ...wii,
];

List<String> mj = [
  'Chanson',
  '2 Bad',
  '2000 Watts',
  'Another Part of Me',
  'Al Capone',
  'Baby Be Mine',
  'Bad',
  'Beat It',
  'Beautiful Girl',
  'Behind the Mask',
  'Best of Joy',
  'Billie Jean',
  'Black or White',
  'Blood on the Dance Floor',
  'Break of Dawn',
  'Breaking News',
  'Burn This Disco Out',
  'Butterflies',
  'Can\'t Get Outta the Rain',
  'Can\'t Let Her Get Away',
  'Carousel',
  'Cheater',
  'Childhood',
  'Come Together',
  'Cry',
  'D.S.',
  'Dangerous',
  'Dirty Diana',
  'Don\'t Be Messin\' \'Round',
  'Don\'t Stop \'Til You Get Enough',
  'Don\'t Walk Away',
  'Earth Song',
  'Fall Again',
  'Fly Away',
  'Free',
  'For All Time',
  'Get on the Floor',
  'Ghosts',
  'Girlfriend',
  'Give in to Me',
  'Gone Too Soon',
  'Got the Hots',
  'Heal the World',
  'Heartbreaker',
  'Heaven Can Wait',
  'HIStory',
  'Hold My Hand',
  'Hollywood Tonight',
  'Human Nature',
  'I\'m So Blue',
  'I Can\'t Help It',
  '(I Can\'t Make It) Another Day',
  'I Just Can\'t Stop Loving You',
  '(I Like) The Way You Love Me',
  'In the Back',
  'In the Closet',
  'Invincible',
  'Is It Scary',
  'It\'s the Falling in Love',
  'Jam',
  'Je ne veux pas la fin de nous',
  'Just Good Friends',
  'Keep the Faith',
  'Keep Your Head Up',
  'Leave Me Alone',
  'Liberian Girl',
  'Little Susie',
  'Love Never Felt So Good',
  'Loving You',
  'Man in the Mirror',
  'Mind Is the Magic',
  'Money',
  'Monkey Business',
  'Monster',
  'Morphine',
  'Much Too Soon',
  'Off the Wall',
  'On the Line',
  'One More Chance',
  'P. Y. T. (Pretty Young Thing)',
  'Planet Earth',
  'Price of Fame',
  'Privacy',
  'Remember the Time',
  'Rock with You',
  'Scared of the Moon',
  'Scream',
  'She Drives Me Wild',
  'She\'s Out of My Life',
  'Shout',
  'Smile',
  'Smooth Criminal',
  'Someone in the Dark',
  'Someone Put Your Hand Out',
  'Song Groove (alias Abortion Papers)',
  'Speechless',
  'Speed Demon',
  'Stranger in Moscow',
  'Streetwalker',
  'Sunset Driver',
  'Superfly Sister',
  'Tabloid Junkie',
  'The Girl Is Mine',
  'The Lady in My Life',
  'The Lost Children',
  'The Way You Make Me Feel',
  'They Don\'t Care About Us',
  'This Is It',
  'This Time Around',
  'Threatened',
  'Thriller',
  'Todo Mi Amor Eres Tu',
  'Todo Para Ti',
  'Unbreakable',
  'Wanna Be Startin\' Somethin\'',
  'We Are Here to Change the World',
  'We Are the World',
  'We\'ve Had Enough',
  'What More Can I Give',
  'Whatever Happens',
  'Who Is It',
  'Why You Wanna Trip on Me',
  'Will You Be There',
  'Workin\' Day and Night',
  'You Are My Life',
  'You Are Not Alone',
  'You Rock My World',
  'Blame It on the Boogie',
  'Enjoy Yourself',
  'Can You Feel It',
  'Say Say Say',
  'Why',
];

List<String> smoothCriminal = [
  'Sounding heartbeats, intimidation',
  'You were struck down (Dag gone it)',
  'Shoo-cha-choo-cha!',
  'It was your doom Annie (Aaow!)',
  'Cha!',
  'And they end up never knowing',
  'Hoo!',
  'Okay, I want everybody to clear the area right now!',
  'He left the bloodstains on the carpet',
  'A Smooth Criminal',
  'Mouth-to-mouth resuscitation',
  'Choo-cha, choo-cha',
  'He came into her apartment',
  "Then he struck you, a crescendo Annie? (I don't know)",
  "Will you tell us that you're okay?",
  'Aaow!',
  'She ran underneath the table',
  'It was Sunday, what a black day',
  "There's a sound at the window",
  "There's a sound at the window (Dag gone it-baby)",
  'There were no clues, they’re behind him',
  'Then he struck you, a crescendo Annie (Hoo! Hoo!)',
  'He came into your apartment',
  'So she ran into the bedroom',
  "Left bloodstains on the carpet (I don't know why, baby)",
  'It was your doom',
  'As he came into the window',
  "You've been hit by—",
  'It was your doom Annie (Dag gone it)',
  'Left bloodstains on the carpet (Hoo!)',
  "Annie, are you okay? (I don't know)",
  'Left the bloodstains on the carpet',
  'He could see she was unable',
  'So they came into the outway',
  "He came into your apartment (I don't know)",
  'He came into your apartment, (Dag gone it)',
  'So, Annie, are you okay? Are you okay, Annie?',
  "There's a sound at the window (I don't know)",
  "Will you tell us that you're okay? (I don't know)",
  'Shoo-cha-choo, shoo-cha-choo!',
  'Who’s the suspect or what to expect',
  'She was struck down, it was her doom',
  'You were struck down',
  'Annie, are you okay? Annie, are you okay?',
  'And then you ran into the bedroom (Help me)',
  "Will you tell us that you're okay? (Dag gone it-baby)",
  'Was a sound of a crescendo',
  'Annie, are you okay?',
  'And then you ran into the bedroom',
  "You've been struck by—",
  'Then he struck you — a crescendo, Annie',
  'Every time I tried to find him',
  'Are you okay, Annie?',
  'Annie are you okay? (Dag gone it-baby)',
  'Annie, are you okay? Are you okay?',
  'And then you ran into the bedroom (Hoo! Hoo!)'
];

List<String> beatIt = [
  'They told him, "Don\'t you ever come around here',
  'Just beat it (Beat it, beat it, beat it)',
  "You're playin' with your life, this ain't no truth or dare (Ooh!)",
  "It doesn't matter who's wrong or right (Who's right)",
  "They're out to get you, better leave while you can",
  'Don\'t wanna see your face, you better disappear"',
  "Don't wanna see no blood, don't be a macho man (Ooh!)",
  'Just beat it, beat it, beat it, beat it (Hoo-hoo!)',
  'Just beat it, beat it, beat it, beat it',
  "You have to show them that you're really not scared (Ooh!)",
  'Beat it, beat it, beat it, beat it',
  "It doesn't matter who's wrong or right",
  'You better run, you better do what you can',
  'So beat it, but you wanna be bad',
  "They'll kick you, then they'll beat you, then they'll tell you it's fair",
  'No one wants to be defeated (Oh-no!)',
  'Just beat it (Beat it)',
  'No one wants to be defeated',
  'You wanna stay alive, better do what you can',
  'So beat it, just beat it (Ooh!)',
  'Beat it (Beat it, beat it)',
  "Showin' how funky (Hoo-hoo!) and strong is your fight (Hee-hee! Hoo!)",
  'You wanna be tough, better do what you can',
  "Showin' how funky and strong is your fight",
  "Showin' how funky (Hee-hee!) and strong is your fight (Hee-hee-hee!)",
  "Don't wanna be a boy, you wanna be a man",
  'No one wants to be defeated (Oh, lord)',
  'Just beat it (Beat it, uh)',
  'Beat it (Beat it, beat it, ha, ha, ha, ha)',
  "The fire's in their eyes and their words are really clear"
];

List<String> tdtcau = [
  "Am I invisible 'cause you ignore me?",
  'Skin head, dead head, everybody gone bad',
  'I look to heaven to fulfill its prophecy, set me free',
  "But if Martin Luther was livin'",
  "All I wanna say is that they don't really care about us",
  'In the suit, on the news, everybody, dog food',
  "The government don't wanna see",
  '(Overlapping voices)',
  "I can't believe this is the land from which I came",
  'Some things in life',
  "I'm tired of being the victim of hate",
  "They're throwing me in a class with a bad name",
  'Situation, aggravation, everybody, allegation',
  'Trepidation, speculation, everybody, allegation',
  'I have a wife and two children who love me',
  "Kick me, kike me, don't you black or white me",
  'Enough is enough of this garbage',
  'I am the victim of police brutality, now',
  "You're ripping me of my pride, oh, for God's sake",
  'Beat me, bash me, you can never trash me',
  "I'm tired of being the victim of shame",
  'Situation, speculation, everybody, litigation',
  "Kick me, kike me, don't you wrong or right me",
  "Bang bang, shot dead, everybody's gone mad",
  "But if Roosevelt was livin'",
  "All I want to say is that they don't really care about us",
  'Jew me, sue me, everybody do me',
  'Your proclamation promised me free liberty, now',
  'Will me, thrill me, you can never kill me',
  "Skin head, dead head, everybody's gone bad",
  "They just don't wanna see",
  'You know, I really do hate to say it',
  'Hit me, kick me, you can never get me',
  'Tell me, what has become of my rights?',
  'Situation, segregation, everybody, allegation',
  "Don't worry what people say, we know the truth",
  "He wouldn't let this be, no, no",
  'Tell me, what has become of my life?',
  'Black male, blackmail, throw the brother in jail',
  'Beat me, hate me, you can never break me'
];

List<String> yana = [
  'I am here with you',
  'Someone tell me why',
  'Not alone, not alone',
  "You're always in my heart",
  'But you are not alone (You are always in my heart)',
  "You're not here with me",
  'And leave my world so cold',
  'In the morning, in the evening',
  "Though you're far away",
  'I am here to stay',
  'You and me, not alone, oh!',
  "I'm still all alone",
  'Did you have to go',
  'But you are not alone',
  'Just the other night',
  'That you are not alone (You are not alone)',
  'You believe in me!',
  'And hold you in my arms',
  "And girl you know that I'll be there",
  'Together, together',
  'Asking me to come',
  'Your burdens I will bear',
  'Say it again',
  'Every day I sit and ask myself',
  'Another day has gone',
  'Then forever can begin',
  'For you are not alone (Not alone, oh)',
  "Though you're far away (Though you're far away, you and me)",
  "Why, 'lone",
  'If you just reach out for me, girl',
  'How did love slip away',
  'Something whispers in my ear and says',
  "I'll be there",
  "Though we're far apart",
  'How could this be',
  'I thought I heard you cry',
  "'Lone, 'lone",
  'You are not alone',
  'I am here with you (I am here with you)',
  'You never said goodbye',
  'That you are not alone',
  'I can hear your prayers',
  'But first I need your hand',
  "Oh, whisper three words and I'll come running",
  'Not not being alone!'
];

List<String> billieJean = [
  'No-no-no, no-no-no-no (No-no-no, no-no-no-no)',
  'But the kid is not my son (Hee-hee-hee, no-no-no, hee-hee-hee)',
  'She called me to her room (Ha-oh, hoo!)',
  'This happened much too soon (Ha-oh, ha-ooh)',
  'For forty days and for forty nights, law was on her side',
  'Hoo!',
  'But the kid is not my son (No, hee-hee!)',
  'She says I am the one (Oh, baby)',
  "But who can stand when she's in demand?",
  'But she came and stood right by me',
  '(You know what you did to me, baby)',
  'Who will dance on the floor, in the round',
  'As she caused a scene',
  "(Don't think twice) Do think twice! (A-hoo!)",
  'Billie Jean is not my lover',
  'I said, "Don\'t mind, but what do you mean, I am the one',
  'Billie Jean is not my lover (She is just a girl)',
  'She says I am the one (You know what you did)',
  'She says I am the one',
  'Then showed a photo my baby cried, his eyes were like mine (Oh, no)',
  "(Hoo!) (She's not at the scene)",
  'Who will dance on the floor in the round?"',
  'Hee!',
  "(Don't break no hearts!) (Hee-hee)",
  'She was more like a beauty queen from a movie scene',
  'People always told me, "Be careful of what you do',
  'And be careful of what you do (Oh-oh)',
  'She says I am the one (Oh baby)',
  'Ah, hee-hee-hee!',
  'So take my strong advice, just remember to always think twice',
  "'Cause we'd danced on the floor in the round, baby",
  'Billie Jean is not (Hee! Aaow! Ooh!)',
  'But the kid is not my son, hoo!',
  'No-no-no, hoo! (Ouw!)',
  'And don\'t go around breakin\' young girls\' hearts"',
  "She's just a girl who claims that I am the one",
  "She's just a girl who claims that I am the one (Oh, baby)",
  'But the kid is not my son',
  '(Ooh, hee-hee-hee)',
  "(Don't call me Billie Jean)",
  'No-no-no, no-no-no-no-no-no (Hoo!)',
  'She says I am the one, but the kid is not my son',
  'Just the smell of sweet perfume (Ha-oh)',
  "She told my baby we'd danced ‘til three, then she looked at me",
  'Who will dance on the floor in the round',
  "Then every head turned with eyes that dreamed of bein' the one",
  'Billie Jean is not my lover (Hoo!)',
  'Her schemes and plans',
  "'Cause we danced on the floor in the round, hee!",
  'She said I am the one',
  'She told me her name was Billie Jean',
  'But the kid is not my son (Oh, no, no)',
  'But the kid is not my son (No-no-no-no)',
  'Don\'t go around breakin\' young girls\' hearts" (Hee-hee)',
  '\'Cause the lie becomes the truth" (Oh-oh)',
  'Hee! Hoo!',
  "She says he is my son (Breakin' my heart, babe)",
  'Billie Jean is',
  "She's just a girl who claims that I am the one (Oh baby)",
  'And mother always told me, "Be careful of who you love'
];

List<String> rtt = [
  'And girl no matter what was said',
  'Do you, do you, do you?',
  'When we first met, girl',
  'Yeah, yeah, hoo!',
  'Hoo!',
  'Do you remember, back in the spring?',
  'In the back of my mind',
  'We were young and innocent then',
  '(Remember the time)',
  'Will always be dear to me',
  'Now baby',
  '(Remember the time, remember the time)',
  "They'll just go on and on",
  'In the park, on the beach',
  'Grrrrrat, tat tat, tat',
  '(Cause I remember)',
  'Do you, do you?',
  'After dark, do you, do you, do you?',
  'When we fell in love',
  'Do you remember those special times?',
  'I will never forget what we had',
  'What about us, girl?',
  'You and me, in Spain',
  'Do you remember when we fell in love?',
  'Do you remember how it all began?',
  'Every morning, birds would sing',
  '(Remember, my baby)',
  '(Oh, I)',
  'Do you remember, back in the fall?',
  'What about, what about',
  'Till dawn, two or three',
  '(All in my mind, girl)',
  'Do you remember us holding hands?',
  'Tell me',
  'On the phone, you and me',
  'Do you, do you, do you, did you?',
  'Every time you see',
  'Those sweet memories',
  'Hoo! In the park',
  'Like, "I love you so, I\'ll never let you go"',
  "I don't know, bet you wanna try",
  'Do you remember, girl?',
  'Do you remember the time?',
  "We'd be together all day long",
  "In each other's eyes, we'd stare",
  'Do you remember how we used to talk?',
  'It just seemed like heaven, so why did it end?',
  'Grrrrrat, tat tat',
  "You know, we'd stay on the phone at night till dawn",
  'Do you remember all the things we said?'
];

List<String> htw = [
  "Love's enough for us growing",
  'This world is heavenly',
  '(You and for me)',
  "There's a place in your heart",
  'Save it for our children',
  'To make a better place',
  'So make a better world',
  "In this place, you will feel there's no hurt or sorrow",
  'And if you really try',
  'And the entire human race',
  'Make a better place (You and for me)',
  'In this bliss, we cannot feel',
  'If you cared enough for the living',
  'And I know that it is love',
  'If we try, we shall see',
  'Fear or dread, we stop existing and start living',
  'If you care enough for the living',
  'Make a little space',
  'Heal the world (Heal the world)',
  'Heal the world we live in (You and for me)',
  'Let our spirits never die',
  'And the dream we were conceived in will reveal a joyful face',
  'There are ways to get there',
  'Heal the world',
  'Make a better place',
  'Make a better place for you and for me',
  'If you want to know why',
  'Then it feels that always',
  'And this place could be much brighter than tomorrow',
  'Make it a better place',
  "Though it's plain to see",
  'We could fly so high',
  'Ploughshares',
  "Think about the generations and say that we wanna make it a better place for our children, and our children's children, so that they, they, they know it's a better world for them, and think, if they can make it a better place...",
  "Be God's glow",
  'For you and for me',
  'There are people dying',
  'Then why do we keep strangling life?',
  'See the nations turn their swords into',
  "You'll find there's no need to cry",
  'And the world we once believed in will shine again in grace',
  'Save it for our children (You and for me)',
  'To make a better world',
  'Create a world with no fear',
  'We could really get there',
  'Love is strong, it only cares for joyful giving',
  "Together, we'll cry happy tears",
  'Would this Earth crucify its soul?',
  "There's a love that cannot lie",
  'In my heart, I feel you are all my brothers',
  'For you and for me and the entire human race'
];

List<String> wbss = [
  '(Hee-hee-hee!)',
  '(Yeah, sing it to the world, sing it out loud, hoo-hoo!)',
  "Treacherous, cunnin', declinin'",
  "Talkin', squealin', spyin'",
  "You're a vegetable, aaow!",
  "Now baby's slowly dyin'",
  "You're just a buffet (You're just a buffet)",
  'But nothing he found',
  "When you're always up to no good",
  'They eat off of you (They eat off of you)',
  "It's too high to get over (Yeah, yeah)",
  "Hustlin', stealin', lyin'",
  'Help me sing it',
  'So your tongue became a razor',
  '(Hee-hee!)',
  "To keep my baby cryin'",
  "If you can't feed your baby (Yeah, yeah)",
  '"I know I am someone," and let the truth unfurl (Hee-haw!)',
  'Aaow!',
  '(Help me sing it, babe)',
  "Talkin', squealin', lyin'",
  "Someone's always tryin'",
  "You really can't make him hate her",
  '(Hoo-hoo!)',
  "You got to be startin' somethin'",
  'They said she had a breakdown',
  "You're stuck in the middle (Yeah, yeah)",
  '(Sing it to the world)',
  'Lift your head up high and scream out to the world',
  'Still they hate you (Still they hate you)',
  'So they called her mouth a motor',
  "You love to pretend that you're good",
  "You're too low to get under (Yeah, yeah)",
  '(Help me sing it)',
  "Then don't have a baby (Yeah, yeah)",
  "I said you wanna be startin' somethin'",
  'Hee-haw! (Ooh!)',
  "You're a vegetable (You're a vegetable)",
  'Yes, I believe in me, so do believe in you',
  "Sayin' you just want to be startin' somethin'",
  "Tellin' lies and rubbin' shoulders",
  'I took my baby to the doctor with a fever',
  "You'll be always tryin'",
  "No one can hurt you now because you know what's true",
  'By the time this hit the street',
  "To stop that child from cryin'",
  'And the pain is thunder (Yeah, yeah)',
  'Ma ma se, ma ma sa, ma ma coo sa',
  "You got my baby cryin' (Hee)",
  "And don't think maybe (Yeah, yeah)",
  "Billie Jean is always talkin' when nobody else is talkin'",
  "To start my baby cryin'"
];

List<String> bow = [
  'You’ve got things to do tomorrow',
  'I am tired of this devil',
  "I ain't scared of your brother",
  'And a miracle has happened tonight',
  "It's black, it's white",
  'Hoo!',
  "Yes, we're one and the same",
  "And I told 'em about equality",
  'Gone withca girl!',
  "I said if you're thinking of being my brother",
  'Ah, dah, ah (Ooh, ooh, ooh, ooh)',
  'Alright (Ooh, ooh, ooh, ooh)',
  'So when the going gets rough',
  'Boy, is that girl with you?',
  'Hee!',
  'Aaow!',
  "And it's true, either you're wrong or you're right",
  "I ain't scared of nobody",
  'Causing grief in human relations',
  'Turn it off!',
  'I am tired of this business',
  'Protection for gangs, clubs and nations',
  "It's a turf war on a global scale",
  "Shamone, don't",
  'Dah, ah, dah, alright',
  'It’s too late for this, turn it off!',
  'What?',
  'Just places, faces',
  "It's tough for you to get by (Ooh, ooh, yeah, yeah, yeah)",
  'No!',
  "It don't matter if you're black or white",
  'Now, I believe in miracles',
  "I'd rather hear both sides of the tale",
  "I've seen the bright get duller",
  "But, if you're thinking about my baby",
  'Ooh!',
  "I ain't scared of no sheets",
  'Ooh, ooh, yeah, yeah, yeah now',
  'No, this is the, I want to listen to it, okay?',
  'Dad, this is the best part, come on!',
  'Alright, alright (Ooh, ooh, ooh, ooh)',
  "It's black, it's white, hoo! (Ooh, ooh, ooh, ooh)",
  "Don't tell me you agree with me",
  'Hey!',
  "I said if you're thinking of being my baby",
  "I'm not going to spend my life being a color",
  'Dad, this is the best part!',
  "See, it's not about races",
  'No, turn it off now!',
  "It's black, it's white, hoo! (Shamone, dah)",
  'Yeah, right. Too late. Sure. Eat this',
  'Where your blood comes from is where your space is',
  'Turn that off!',
  'They print my message in the Saturday sun',
  "I had to tell them I ain't second to none",
  'When I saw you kicking dirt in my eye',
  'Girl, when the going gets mean',
  'Hee-hee!',
  'Alright, alright',
  'I am tired of this stuff',
  'I took my baby on a Saturday bang'
];

List<String> humanNature = [
  'Looking out, across the morning',
  'Reaching out to touch a stranger',
  'I like living this way',
  'She likes the way I stare',
  'If they say why (why?), why (why?)',
  'The city winks a sleepless eye',
  "See that girl, she knows I'm watching",
  "I like livin' this way",
  "Ooh, tell 'em!",
  '(That way) Why? Oh, why?',
  'Sweet seducing sighs',
  "(She's keeping him by, keeping him around)",
  "The city's heart begins to beat",
  'Da-da-da-da-da-da-da-da',
  'Why? Oh, why? (that way)',
  'If this town is just an apple',
  'Get me out, into the nighttime',
  "Ooh-ooh, tell 'em!",
  "Four walls won't hold me tonight",
  'Then let me take a bite',
  'Looking out, across the nighttime',
  "Tell them that it's human nature",
  'If they say why (why? why?), why (why? why? why?)',
  "Ooh-ooh, tell 'em! (aah-ah)",
  'Cha-da-cha-sha-sha-sha-sha-sha (aah-ah)',
  'Why (why?), why (why?), does he do me that way?',
  "I like lovin' this way",
  'Electric eyes are everywhere',
  'If they say why (why?), why (why?), why (why?)',
  'Hear her voice, shake my window',
  'Reaching out, I touch her shoulder',
  "I'm dreaming of the street"
];

List<String> thriller = [
  'And hope that this is just imagination',
  "I'm gonna thrill you tonight",
  'This is the end of your life, ooh',
  'The midnight hour is close at hand',
  "'Cause this is thriller, thriller night",
  'You see a sight that almost stops your heart',
  'But all the while',
  '(Thriller night, thriller)',
  'Thriller, thriller night',
  'All through the night',
  'For no mere mortal can resist',
  "You know it's thriller",
  "'Cause this is thriller",
  'You start to freeze',
  'Inside a killer',
  'Inside a killer, thriller tonight',
  'And share a killer, thriller, chiller',
  'The evil of the thriller!',
  "You're out of time",
  'You hear the door slam',
  'And share a killer, thriller',
  "And realize there's nowhere left to run",
  'You close your eyes',
  'Night creatures call and the dead start to walk in their masquerade',
  'AHAHAHAHAHAHAHAHA',
  'But terror takes the sound before you make it',
  'For you and I to cuddle close together, yeah',
  "I'll make you see",
  "I'll save you from the terror on the screen",
  'The foulest stench is in the air',
  "You're paralyzed",
  'You feel the cold hand',
  'Now is the time',
  'And grisly ghouls from every tomb',
  'Must stand and face the hounds of hell',
  'They will possess you',
  '(Thriller, ooh, thriller)',
  'So let me hold you tight',
  "There's demons closing in on every side",
  "It's close to midnight",
  'As horror looks you right between your eyes',
  'From the beast about to strike',
  'That this is thriller, thriller night',
  'The funk of forty thousand years (Thriller night, thriller)',
  "Ooh, babe, I'm gonna thrill you tonight",
  "'Cause I can thrill you more",
  'Than any ghoul would ever dare try',
  '(Ooh, ooh)',
  'Thriller night, babe',
  'Unless you change that number on your dial',
  'Girl, I can thrill you more',
  "There ain't no second chance",
  'Darkness falls across the land',
  "They're open wide",
  "Something evil's lurking in the dark",
  "To terrorize y'all's neighborhood",
  'Are closing in to seal your doom',
  'Creatures crawl in search of blood',
  'Thriller tonight, yeah, ooh',
  'Under the moonlight',
  'And though you fight to stay alive',
  '(Ooh)',
  '(Girl)',
  "They're out to get you",
  "You're fighting for your life",
  'You try to scream',
  "Your body starts to shiver (I'm gonna thrill you tonight)",
  'You hear a creature creeping up behind',
  'And whosoever shall be found',
  'Against the thing with 40 eyes, girl',
  'Without the soul for getting down',
  "And wonder if you'll ever see the sun",
  "And rot inside a corpse's shell",
  "And no one's gonna save you",
  "There's no escaping the jaws of the alien this time",
  'AHAHAHAHAHAHAHAHA!',
  'Thriller night',
  'Thriller here tonight'
];

List<String> wii = [
  'I gave her money',
  "To me, I'm bothered!",
  'Tell me what will I do?',
  "(Don't be, don't be)",
  'And she promised me forever',
  "(She don't, she don't, she don't need it)",
  "(Don't bother me)",
  'Is it my brother?',
  'Would have mercy on me',
  '(Da da da da)',
  "Don't try, quit it",
  'I gave her everything',
  'Woe unto thee',
  "'Cause I'm bothered every day",
  '(Think of another brother)',
  'Did she find in someone else?',
  'She just up and ran away',
  '(Is it my brother?)',
  "That we'd live our life as one",
  "‘Cause I'm bothered everyday",
  'And the reason why she left me',
  'But see what will I do',
  '(Who is it?)',
  'I pray this punishment',
  "And it doesn't seem to matter (Hee-hee!)",
  'I am the agony inside',
  'I can’t take this stuff no more',
  "Don't try to pick me",
  'She just upped and ran away',
  "(Don't bother me, you just couldn't)",
  "We'd live a love so true",
  "'Cause the will has brought no fortune",
  'And secrets so untold',
  'The dying head',
  "And it doesn't seem right (Hee-hee!)",
  "(Don't be judging)",
  "And it doesn't seem right",
  'It is a friend of mine?',
  'My very soul',
  'We made our vows',
  "(She don't, she don't want it)",
  "Don't you judge of my composure",
  "(I can't take it 'cause I'm lonely)",
  "And she didn't leave a letter",
  "(Don't be, don't be, don't be judging)",
  'I am the damned',
  "(Can't take it 'cause I'm lonely)",
  'This is injustice',
  "(You can really say I'm lonely)",
  "'Cause I'm lying to myself",
  'And a day we’d live as one',
  "Just won't stop",
  'It’s a promise so untrue',
  'Inside one heart could find',
  'We’d live a life anew',
  'Somebody hurt my soul, now',
  "I can't take it cause I'm lonely",
  "Don't you judge of my composure (Hee!)",
  'I am the dead',
  "'Cause I'm lying to myself (Hee!)",
  'I gave her passion',
  '‘Cause the will has brought no fortune',
  "And it doesn't seem to matter",
  "That she'd love me for all time",
  'It seems that she has left me',
  'I need to find the truth',
  'And she promised me in secret',
  'I gave her time',
  'Still I cry alone at night',
  "‘Cause I'm lying to myself",
  'I never was, I never would',
  "(Can't you really feel I'm lonely?)",
  "(This won't cut it)",
  "Don't you judge of my composure (Body)",
  'Hee-hee, hee-hee!',
  "(She don't, she don't want me)",
  '(Da da, da da, da da, da)',
  'I gave her promises',
  "Don't bother me",
  "(Don't be, don't do)",
  'For such reasons unexplained'
];
