List<String> anime = [
  '.hack//SIGN',
  '.hack//Legend of Twilight',
  '.hack//Roots',
  '.Hack//Terminal Disk',
  '.hack//Quantum',
  '07-Ghost',
  '009-1',
  '3X3 Eyes',
  '7 Seeds',
  '11eyes',
  '12-Sai. ~Chiccha na Mune no Tokimeki~',
  '18 If',
  '22/7',
  '30-sai no hoken taiiku',
  '3D Kanojo: Real Girl',
  '91 Days',
  '100-man no Inochi no Ue ni Ore wa Tatte Iru',
  'A3! Season Spring & Summer',
  'A-Channel',
  'A Day Before Us',
  'A Little Snow Fairy Sugar',
  'Absolute Duo',
  'Acchi Kocchi',
  'Ace Attorney',
  'Accel World',
  'Active Raid',
  'ACTORS -Songs Connection-',
  'Adachi to Shimamura',
  'Africa no Salaryman',
  'Afro Samurai',
  'Agent Aika',
  'Aggressive Retsuko',
  'Ah! My Goddess',
  'Ahiru no Sora',
  'Aho Girl',
  'A.I.C.O.: Incarnation',
  'Ai Mai! Moe Can Change!',
  'Ai no Kusabi',
  'AIKa',
  'Air Gear',
  'Air Master',
  'Air (TV)',
  'Aishiteruze Baby',
  'Aiura',
  'Ajimu: Kaigan Monogatari',
  'Ajin',
  'Akane-Iro ni Somaru Saka',
  'Akanesasu Shoujo',
  'Akatsuki No Yona',
  'AKB0048',
  'Akiba’s Trip',
  'Akikan!',
  'Akkun to Kanojo',
  'Aku no Hana',
  'Akudama Drive',
  'Akuma no Riddle',
  'Albator 84',
  'Aldnoah.Zero',
  'Alice or Alice',
  'Alice to Zouroku',
  'Allison to Lillia',
  'Amaama to Inazuma',
  'Amaenaide yo!!',
  'Amagami SS',
  'Amagi Brilliant Park',
  'Amanchu!',
  'Amatsuki',
  'Amazing Stranger',
  'Amnesia',
  'Ane Log: Moyako Neesan no Tomaranai Monologue',
  'Ange Vierge',
  'Angel Beats!',
  'Angel Densetsu',
  'Angel Heart',
  'Angolmois: Genkou Kassenki',
  'Ani ni Tsukeru Kusuri wa Nai!',
  'Anima Yell!',
  'Anime de Wakaru Shinryounaika',
  'Anitore! EX',
  'Anne Happy♪',
  'Ano Natsu de Matteru',
  'AnoHana',
  'Another',
  'Another World',
  'Ao Haru Ride',
  'Ao no Kanata no Four Rhythm',
  'Ao Oni The Animation',
  'Aoharu x Kikanjuu',
  'Aoi Bungaku Series',
  'Aoi Hana',
  'Aoi Sekai no Chūshin de',
  'Aoki Hagane no Arpeggio: Ars Nova',
  'Appare-Ranman!',
  'Aquarion Evol',
  'Araburu Kisetsu no Otome-domo yo',
  'Arakawa under the bridge',
  'Araiya-san!: Ore to Aitsu ga Onnayu de!?',
  'Arata Kangatari',
  'Arcana Famiglia',
  'Area no kishi',
  'Arifureta Shokugyou de Sekai Saikyou',
  'Arslan Senki',
  'Arte',
  'Asa Made Jugyou Chu!',
  'Ascendance of a Bookworm',
  'Asobi Asobase',
  'Asobi ni Iku yo!',
  'Assassination Classroom',
  'Assassins Pride',
  'Assault Lily: Bouquet',
  'Astarotte no omocha!',
  'Asu no Yoichi',
  'Asura Cryin’',
  'Atelier Escha & Logy',
  'Atom – The Beginning',
  'Ayakashi',
  'Ayakashi – Japanese Classic Horror',
  'Ayashi no Ceres',
  'B Gata H Kei',
  'B-PROJECT: Kodou Ambitious',
  'B: The Beginning',
  'B-PROJECT: Kodou Ambitious',
  'Baby Princess 3D Paradise 0 [Love]',
  'Baby Steps',
  'Babylon',
  'Baccano!',
  'Back Street Girls: Gokudolls',
  'Bai Ye Ling Long',
  'Baka to test to shoukanjuu',
  'Bakemonogatari',
  'Baki The Grappler',
  'Baki (2018)',
  'Bakuman. 3',
  'Bakumatsu Kikansetsu Irohanihoheto',
  'Bakumatsu Rock',
  'Bakuon!!',
  'Ballroom e Youkoso',
  'Bamboo Blade',
  'Banana Fish',
  'Bananya',
  'BanG Dream!',
  'BanG Dream! Garupa☆Pico',
  'Barakamon',
  'Basilisk: Kouga Ninpou Chou',
  'Basilisk: Ouka Ninpouchou',
  'Basquash!',
  'Battery',
  'Battle Girl High-school',
  'Beastars',
  'Beatless',
  'Beck',
  'Beelzebub-jou no Okinimesu mama.',
  'Bem',
  'Ben-To',
  'Bermuda Triangle: Colorful Pastrale',
  'Berserk',
  'Berserk (2016)',
  'Beyblade Burst',
  'Big Order',
  'Bikini Warriors',
  'Binbougami Ga!',
  'Black Blood Brothers',
  'Black Bullet',
  'Black Cat',
  'Black Clover',
  'Black Jack 21',
  'Black Lagoon',
  'Black ★ Rock Shooter',
  'Blade & Soul',
  'Blassreiter',
  'BlazBlue Alter Memory',
  'Blend S',
  'Blood+',
  'Blood-C',
  'Blood Lad',
  'Bloodivores',
  'Blue Exorcist',
  'Blue Gender',
  'BOFURI: Je suis pas venue ici pour souffrir alors j’ai tout mis en défense',
  'Boku no Tonari ni Ankoku Hakaishin ga Imasu.',
  'Boku wa Tomodachi ga Sukuna',
  'Bokura ga ita',
  'Bokura wa Minna Kawaisou',
  'Bokurano',
  'Bokusatsu Tenshi Dokuro-chan',
  'Bokutachi wa Benkyou ga Dekinai',
  'Bonjour♪ Koiaji Pâtisserie',
  'Boruto: Naruto Next Generations',
  'Bounen no Xamdou',
  'Brand New Animal',
  'Brave 10',
  'Brave Witches',
  'Break Blade',
  'Brothers Conflict',
  'Brotherhood: Final Fantasy XV',
  'BTOOOM!',
  'Buddy Complex',
  'Buddy Go!',
  'Bungaku Shoujo',
  'Bungou Stray Dogs',
  'Bungou Stray Dogs Wan!',
  'Bungou to Alchemist: Shinpan no Haguruma',
  'Burn the Witch',
  'Burst Angel',
  'Busou Shinki',
  'Busou Shoujo Machiavellism',
  'Buzzer Beater',
  'C -Control',
  'C³: Cube × Cursed × Curious',
  'Caligula',
  'Campione !',
  'Canaan',
  'Candy☆Boy',
  'Cannon Busters',
  'Captain Earth',
  'Card Captor Sakura',
  'Card Captor Sakura – Clear Card-hen',
  'Carnival Phantasm',
  'Carole & Tuesday',
  'Casshern Sins',
  'Castlevania',
  'Cautious Hero: The Hero Is Overpowered but Overly Cautious',
  'Centaur no Nayami',
  'Chain Chronicle',
  'ChäoS;HEAd',
  'ChäoS;Child',
  'Charlotte',
  'Cheating Craft',
  'Cheer Danshi!!',
  'Chihayafuru',
  'Chiruran Nibun no Ichi',
  'Chobits',
  'Chocola et Vanilla',
  'Chocolat no Mahou',
  'Chocotan!',
  'Choujigen Game Neptune The Animation',
  'Chouyuu Sekai : Being the Reality',
  'Chrno Crusade',
  'Chu-Bra!!',
  'Chu Feng: B.E.E',
  'Chuukan Kanriroku Tonegawa',
  'Cike Wu Liu Qi',
  'Circlet Princess',
  'Citrus',
  'Clannad',
  'Clannad After Story',
  'Classroom☆Crisis',
  'Classroom of the Elite',
  'Claymore',
  'Clione no Akari',
  'Code:Breaker',
  'Code Geass',
  'Code:Realize: Sousei no Himegimi',
  'Comet Lucifer',
  'Comic Girls',
  'Conception',
  'Cop Craft',
  'Coppelion',
  'Corpse Party',
  'Cowboy Bebop',
  'Cross Ange: Tenshi to Ryuu no Rondo',
  'Cupid’s Chocolates',
  'Cuticle Detective Inaba',
  'Cute High Earth Defense Club LOVE!',
  'Cutie Honey Universe',
  'Cyclops Shoujo Saipu',
  'D-Frag!',
  'D.Gray-man',
  'D4DJ: First Mix',
  'Dakaretai Otoko 1-i ni Odosarete Imasu.',
  'Daitoshokan no Hitsujikai',
  'Dakara boku wa, H ga Dekinai',
  'Dance in the Vampire Bund',
  'Danchigai',
  'Danganronpa: The Animation',
  'Danganronpa 3: Mirai-hen',
  'Danganronpa 3: Zetsubou-hen',
  'DanMachi',
  'Danna ga Nani wo Itteiru ka Wakaranai Ken',
  'Danshi Koukousei no Nichijou',
  'Dantalian no Shoka',
  'Darker than Black',
  'DARLING in the FRANXX',
  'Dansai Bunri no Crime Edge',
  'Date A Live',
  'Day Break Illusion',
  'Deadman Wonderland',
  'Dear Boys',
  'DearS',
  'Death Billiards',
  'Death March to the Parallel World Rhapsody',
  'Death Note',
  'Death Parade',
  'Deca-Dence',
  'Denki-Gai no Honya-san',
  'Demi-chan wa Kataritai',
  'Demon Spirit Seed Manual',
  'Denpa Kyōshi',
  'Denpa Onna to Seishun Otoko',
  'Denpa Teki na Kanojo',
  'Densetsu no yuusha no densetsu',
  'Désenchantée',
  'Détective Conan',
  'Detroit Metal City',
  'Devil May Cry',
  'Devil Survivor 2 The Animation',
  'Devilman Crybaby',
  'Devilman Lady',
  'Di Wang Gong Lue',
  'Diabolik Lovers',
  'Die Now',
  'Dies Irae',
  'Digimon Adventure: (2020)',
  'Dive!!',
  'Divine Gate',
  'D.N.Angel',
  'DNA²',
  'Do You Love Your Mom and Her Two-Hit Multi-Target Attacks?',
  'Dog Days',
  'Dogeza de Tanondemita',
  'Dokyuu Hentai HxEros',
  'Donten ni Warau',
  'Dorohedoro',
  'Dororo',
  'Double Decker! Doug & Kirill',
  'Doukyonin wa Hiza, Tokidoki, Atama no Ue.',
  'Dr. Stone',
  'Dragonaut: The Resonance',
  'Dragon Ball',
  'Dragon Ball Super',
  'Dragon Ball Z',
  'Dragon Ball GT',
  'Dragon Crisis',
  'Dragon’s Dogma',
  'Dragon Quest: Abel Yuusha',
  'Dragon Quest: Dai no Daibouken (2020)',
  'DRAMAtical Murder',
  'Dream Festival!',
  'Druaga no Tou: The Aegis of Uruk',
  'Dumbbell Nan-Kilo Moteru?',
  'Durarara!!',
  'Ebiten: Kouritsu Ebisugawa Koukou Tenmon-Bu',
  'ef: A Tale of Memories.',
  'Egao no Daika',
  'Eiken: Eikenbu yori Ai wo Komete',
  '“Eiyuu” Kaitai',
  'Eizouken ni wa Te wo Dasu na!',
  'El Cazador de la Bruja',
  'Elfen Lied',
  'Elsword El Lady',
  'Emiya-san Chi no Kyou no Gohan',
  'Endro~!',
  'Enfer et Paradis',
  'Enmusubi no Youko-chan',
  'Ensemble Stars!',
  'Erased',
  'Ergo Proxy',
  'Eromanga Sensei',
  'Etotama',
  'Eureka Seven',
  'Eureka Seven AO',
  'Evangelion',
  'Eve no Jikan',
  'Evil or Live',
  'Excel Saga',
  'Eyeshield 21',
  'Fairy Gone',
  'Fairy Tail',
  'Fantasista Doll',
  'Fate Stay Night',
  'Fate/Zero',
  'Fate/Prototype',
  'Fate/Kaleid Liner Prisma Illya',
  'Fate/Stay Night: Unlimited Blade Works',
  'Fate/Apocrypha',
  'Fate/Extra Last Encore',
  'Fate/Grand Order: Moonlight/Lostroom',
  'Fate/Grand Order: Zettai Majuu Sensen Babylonia',
  'Fate/Grand Order x Koorimuro no Tenchi: 7-nin no Saikyou Ijin Hen',
  'Fight Ippatsu! Juuden-Chan!!',
  'Fight League: Gear Gadget Generators',
  'Final Approach',
  'Final Fantasy Unlimited',
  'Final Fantasy: Legend of the Crystals',
  'Final Fantasy XV : Episode Ardyn – Prologue',
  'Fire Force',
  'FLCL',
  'Flip Flappers',
  'Flying Witch',
  'Fortune Arterial : Akai Yakusoku',
  'Fractale',
  'Free!',
  'Frame Arms Girl',
  'Freezing',
  'Fruits Basket',
  'Fruits Basket (2019)',
  'Fudanshi Koukou Seikatsu',
  'Fugou Keiji: Balance:Unlimited',
  'Fukigen na Mononokean',
  'Fukumenkei Noise',
  'Full Moon wo sagashite',
  'Fullmetal alchemist',
  'Fullmetal Alchemist: Brotherhood',
  'Full Metal Panic!',
  'Fumikiri Jikan',
  'Fune wo Amu',
  'Futakoi',
  'Futari Ecchi (2014)',
  'Futsuu no Joshikousei ga [Locodol] Yatte Mita.',
  'Fuuka',
  'Fuun Ishin Dai Shogun',
  'Fuyu no Sonata',
  'Ga-Rei: Zero',
  'Gabriel DropOut',
  'Gaikotsu Shotenin Honda-san',
  'Gakuen Alice',
  'Gakuen Heaven',
  'Gakusen Toshi Asterisk',
  'Galilei Donna',
  'Gamers!',
  'Gangsta',
  'Gantz',
  'Garo: Honoo no Kokuin',
  'Garo: Guren no Tsuki',
  'Garo: Vanishing Line',
  'Gatchaman Crowds',
  'Gate Keepers',
  'Gekkan Shoujo Nozaki-kun',
  'Get Backers',
  'Getsuyoubi no Tawawa',
  'Ghost Hunt',
  'Ghost in The Shell',
  'Ghost in the Shell: Arise -Alternative Architecture-',
  'Ghost in the Shell: SAC_2045',
  'Giant Killing',
  'Gibiate',
  'Gift ~eternal rainbow~',
  'Gin no Guardian',
  'Gin no Saji',
  'Ginban Kaleidoscope',
  'Ginga Kikoutai Majestic Prince',
  'Gintama',
  'Girl Friend Beta',
  'Girls Bravo',
  'Girls’ Last Tour',
  'Girls und Panzer',
  'Girly Air Force',
  'Given',
  'GJ-bu',
  'Glasslip',
  'Gleipnir',
  'Gochuumon wa Usagi Desu ka?',
  'Gokujo: Gokurakuin Joshikou Ryou Monogatari',
  'Gokukoku no Brynhildr',
  'Golden Boy',
  'Golden Kamui',
  'Golden Time',
  'Goshuushou-sama Ninomiya-kun',
  'Gosick',
  'Gotoubun no Hanayome',
  'Granbelm',
  'Granblue Fantasy The Animation',
  'Grancrest Senki',
  'Grand Blue',
  'Gravitation',
  'Gravity Daze The Animation OAV',
  'Great Pretender',
  'Green Green',
  'Grenadier: Hohoemi no Senshi',
  'Grimoire of Zero',
  'Grisaia no Kajitsu',
  'Gugure! Kokkuri-san',
  'Guilty Crown',
  'Gundam Build Fighters',
  'Gundam Build Fighters Try',
  'Gungrave',
  'Gunjou no Magmel',
  'GUNNM',
  'Gunparade March: Arata Naru Kougunka',
  'Gunslinger Girl',
  'Gunslinger Stratos: The Animation',
  'Guraburu!',
  'H2O: Footprints In The Sand',
  'Hachimitsu to Clover',
  'Hacka Doll The Animation',
  'Hagure Yuusha no Aesthetica',
  'Haikyuu!!',
  'Haiyore! Nyaruko-san',
  'Hajime no Ippo',
  'Hajimete no Gal',
  'Hakata Tonkotsu Ramens',
  'Hakkenden Touhou Hakken Ibun',
  'Hakuouki',
  'Hakuouki Otogisoushi',
  'Hakushaku to Yousei',
  'Hakyuu Houshin Engi',
  'Hamatora The Animation',
  'Hanada Shounen-shi',
  'Hanamaru Youchien',
  'Hanasaku Iroha',
  'Hanaukyo Maid-tai: La Vérité',
  'Hanaukyo Maid-tai',
  'Hanayaka Nari, Waga Ichizoku: Kinetograph',
  'Hanayamata',
  'Hanbun no Tsuki ga Noboru Sora',
  'Hand Shakers',
  'Handa-kun',
  'Hanebado!',
  'Hangyakusei Million Arthur',
  'Hantsu x Trash',
  'Hanyou no Yashahime: Sengoku Otogizoushi',
  'Happy Sugar Life',
  'Haru wo Daiteita',
  'Hashiri Tsuzukete Yokattatte.',
  'Hataage! Kemono Michi',
  'Hataraku Maou-sama!',
  'Hataraku Saibou',
  'Hataraku Saibou BLACK',
  'Hatena☆Illusion',
  'Hatenkou Yuugi',
  'Hatsukoi Limited',
  'He Is My Master',
  'Hellsing',
  'Hellsing Ultimate',
  'Hen Zemi',
  'Henkei Shoujo',
  'Hentai Ouji to Warawanai Neko',
  'Hentail! (Nitopan)',
  'Hero Mask',
  'Heroic Age',
  'Heya Camp△',
  'Hibike! Euphonium',
  'Hidan No Aria',
  'Higashi no Eden',
  'High School DxD',
  'High School Fleet',
  'Highschool Of The Dead',
  'High School Prodigies Have It Easy Even In Another World',
  'High School Star Musical',
  'High Score',
  'High Score Girl',
  'Higurashi no Naku Koro ni',
  'Hiiro no Kakera',
  'Hikaru no Go',
  'Himegoto',
  'Himitsukessha Taka no Tsume: Golden Spell',
  'Himote House',
  'Himōto! Umaru-chan',
  'Hina Logi: From Luck & Logic',
  'Hinako Note',
  'Hinamatsuri',
  'Hinomaru Zumou',
  'Hisone to Masotan',
  'Hitori no Shita: The Outcast',
  'Hitoribocchi no ○○ Seikatsu',
  'Hitorijime My Hero',
  'Hitsugi no Chaika',
  'Hiyokoi',
  'Holy Knight',
  'Honey x Honey Drops',
  'Honobono Log',
  'Hoozuki no Reitetsu',
  'Horimiya',
  'Hori-san to Miyamura-kun',
  'Hortensia Saga',
  'Hoshiai no Sora',
  'Hoshizora e kakaru hashi',
  'Houkago no Pleiades',
  'Houkago Saikoro Club',
  'Houkago Teibou Nisshi',
  'Hourou Musuko',
  'Housekisho Richard-shi no Nazo Kantei',
  'How To Keep A Mummy',
  'Huan Jie Wang',
  'Hundred',
  'Hunter x Hunter (1999)',
  'Hyakka Ryouran Samurai Girls',
  'Hyakuren no Haou to Seiyaku no Valkyria',
  'Hybrid Child',
  'Hyouka',
  'Hyperventilation',
  'Hypnosis Mic -Division Rap Battle- Rhyme Anima',
  'Ichiban Ushiro no Daimaou',
  'Ichigo 100%',
  'ID-0',
  'ID:Invaded',
  'IDOLiSH7',
  'IDOLiSH7 Vibrato',
  'If It’s for My Daughter, I’d Even Defeat a Demon Lord',
  'Ikebukuro West Gate Park',
  'Ikkitousen',
  'Ikoku Ironkoi Romatan',
  'Ikoku Meiro no Croisée',
  'Ikusa × Koi',
  'Imawa no Kuni no Alice',
  'I, My, Me – Strawberry Eggs',
  'Imouto sae Ireba Ii.',
  'Inari, Konkon, Koi Iroha',
  'Inazuma Eleven: Ares no Tenbin',
  'Inazuma Eleven: Orion',
  'Infini-T Force',
  'Infinite Dendrogram',
  'Infinite Stratos',
  'Ingress: The Animation',
  'Inou Battle wa Nichijoukei no Naka de',
  'Inu to Hasami wa Tsukaiyou',
  'Inu x Boku SS',
  'Inugami-san to Nekoyama-san',
  'Inukami!',
  'Inuyasha: Kanketsu-hen',
  'Inuyashiki',
  'Irozuku Sekai No Ashita Kara',
  'Isekai Izakaya: Koto Aitheria no Izakaya Nobu',
  'Isekai Maou to Shoukan Shoujo no Dorei Majutsu',
  'Isekai no Seikishi Monogatari',
  'Isekai Quartet',
  'Isekai Shokudou',
  'Isekai wa Smartphone to Tomo ni.',
  'Ishida to Asakura',
  'Island',
  'Isshuukan Friends',
  'Isuca',
  'It’s My Life',
  'Itazura na Kiss',
  'Itsudatte Bokura no Koi wa 10 cm Datta.',
  'Ito Junji: Collection',
  'Itsuka Tenma no Kuro Usagi',
  'Iwa kakeru! Climbing Girls',
  'Ixion Saga DT',
  'Iya na Kao Sarenagara Opantsu Misete Moraitai',
  'Jaku-Chara Tomozaki-kun',
  'Japan Sinks 2020',
  'Jashin-chan Dropkick',
  'Jibaku Shounen Hanako-kun',
  'Jie Yao',
  'Jigoku Shoujo',
  'Jikan no Shihaisha',
  'Jingai-san no Yome',
  'Jinrui wa Suitai Shimashita',
  'Jinsei',
  'Jitsu wa Watashi wa',
  'Jojo’s Bizarre Adventure',
  'Joju Senjin!! Mushibugyo',
  'Joker Game',
  'Jormungand',
  'Joshi Kausei',
  'Joshikousei no Mudazukai',
  'Joukamachi no Dandelion',
  'Jujutsu Kaisen',
  'Junjou Romantica',
  'Junketsu no Maria',
  'Just Because!',
  'Juuni Taisen',
  'Juuou Mujin no Fafnir',
  'Juushin Enbu: Hero Tales',
  'Juushinki Pandora',
  'Jyu Oh Sei',
  'K-ON!',
  'K Project',
  'K-Projet: K-Seven Stories',
  'Kabukichou Sherlock',
  'Kachou no Koi',
  'Kaguya-sama: Love Is War',
  'Kaibutsu Oujo',
  'Kaichou wa Maid-sama!',
  'Kaichuu!',
  'Kage Kara Mamoru',
  'Kaiba',
  'Kaifuku Jutsushi no Yarinaoshi',
  'Kaiji',
  'Kakegurui',
  'Kakumeiki Valvrave',
  'Kakuriyo no Yadomeshi',
  'Kakushigoto',
  'Kamen no Maid Guy',
  'Kami no Tou -Tower of God-',
  'Kami nomi zo shiru sekai (Que sa volonté soit faite)',
  'Kami-tachi ni Hirowareta Otoko',
  'Kamichama Karin',
  'Kamigami no Asobi',
  'Kamisama Dolls',
  'Kamisama Kazoku',
  'Kamisama ni Natta Hi',
  'Kamisama no Inai Nichiyoubi',
  'Kamisama no Memo-chou',
  'Kämpfer',
  'Kanamemo',
  'Kanata no Astra',
  'Kandagawa Jet Girls',
  'Kannagi',
  'Kannazuki no Miko',
  'Kanojo ga Flag wo Oraretara',
  'Kanojo, Okarishimasu',
  'Kanojo to Kanojo no Neko',
  'Kanokon',
  'Kanon (2006)',
  'Kantai Collection: KanColle',
  'Kara no Kyoukai',
  'Karakai Jouzu no Takagi-san',
  'Karakuri Circus',
  'Karin',
  'Karneval',
  'Kashimashi ~Girl Meets Girl~',
  'Katanagatari',
  'Katsugeki/Touken Ranbu',
  'Katsute Kami Datta Kemono-tachi e',
  'Katte ni Kaizō',
  'Kaze ga Tsuyoku Fuiteiru',
  'Kaze no Stigma',
  'Keijo!!!!!!!!',
  'Keishichou Tokumu Bu Tokushu Kyouakuhan Taisaku Shitsu Dai Nana Ka: Tokunana',
  'Kemeko Deluxe!',
  'Kemono Friends',
  'Kemono Jihen',
  'Kemurikusa',
  'Ken En Ken: Aoki Kagayaki',
  'Ken le survivant (Hokuto no ken)',
  'Kengan Ashura',
  'Kenja no Mago',
  'Kenka Banchou Otome: Girl Beats Boys',
  'Kenko Zenrakei Suieibu Umisho',
  'Kenshin Le Vagabond',
  'Kenzen Robo Daimidaler',
  'Keppeki Danshi! Aoyama-kun',
  'Kiba',
  'Kiitarou Shounen no Youkai Enikki',
  'Kill Me Baby',
  'Killing Bites',
  'Kimetsu no Yaiba',
  'Kimi ga Aruji de Shitsuji ga Ore de',
  'Kimi ga Nozomu Eien',
  'Kimi ni todoke',
  'Kimi no Hikari : Asagao to Kase-san.',
  'Kimi no Iru Machi',
  'Kimi no Sumu Machi',
  'Kimi to Boku.',
  'Kimi to Boku no Saigo no Senjou, Aruiwa Sekai ga Hajimaru Seisen',
  'Kimikiss pure rouge',
  'King of Prism – Shiny Seven Stars',
  'Kingdom',
  'King’s Game The Animation',
  'Kiniro Mosaic',
  'Kino no Tabi : The Beautiful World',
  'Kirepapa',
  'Kishin Houkou DemonBane',
  'Kishuku Gakkou no Juliet',
  'KisKis! Wo De Nan You Shi Bo He Tang',
  'Kiss x Sis',
  'Kitsutsuki Tantei-Dokoro',
  'Kitsune no Koe',
  'Kizuna',
  'Knight’s & Magic',
  'Knights of Sidonia',
  'Kobayashi ga Kawai Sugite Tsurai!!',
  'Kobayashi-san Chi no Maid Dragon',
  'Kobato.',
  'Kochoki: Wakaki Nobunaga',
  'Kodomo no Jikan',
  'Koe de Oshigoto! The Animation',
  'Koharu Biyori',
  'Koi Kaze',
  'Koi to Producer: Evol x Love',
  'Koi to senkyo to Chocolate',
  'Koi wa Ameagari no You ni',
  'Koihime†Musou',
  'Koikishi Purely☆Kiss: The Animation',
  'Koisuru Asteroid',
  'Koisuru Boukun',
  'Kokkoku',
  'Kokoro Connect',
  'Komori-san wa Kotowarenai!',
  'Konbini Kareshi',
  'Kono Bijutsubu ni wa Mondai ga Aru',
  'Kono Danshi',
  'Kono Minikukumo Utsukushii Sekai',
  'Kono Naka ni Hitori Imouto ga Iru',
  'Kono Subarashii Sekai ni Shukufuku o!',
  'Kono Yo no Hate de Koi wo Utau Shoujo YU-NO',
  'Konohana Kitan',
  'Kore wa Zombie desu ka?',
  'Koroshiya-san',
  'Kotoura-san',
  'Koukaku no Pandora: Ghost Urn',
  'Koukaku no Regios',
  'Koukou Tekken-den Tough',
  'Koutetsujou no Kabaneri',
  'Kouya no Kotobuki Hikoutai',
  'Koyomimonogatari',
  'Kubikiri Cycle',
  'Kujira no Kora wa Sajou ni Utau',
  'Kuma Kuma Kuma Bear',
  'Kumo Desu ga, Nani ka?',
  'Kurenai',
  'Kurogane no Linebarrels',
  'Kurokami The Animation',
  'Kuroko no Basket',
  'Kuromukuro',
  'Kurozuka',
  'Kusoge tte Iuna! Animation',
  'Kuttsukiboshi',
  'Kuutei Dragons',
  'Kuzu no Honkai',
  'Kyō no Asuka Show',
  'Kyojinzoku no Hanayome',
  'Kyokou Suiri',
  'Kyoto Teramachi Sanjou no Holmes',
  'Kyoukai Senjou no Horizon',
  'Kyoushoku Soukou Guyver',
  'Kyousogiga',
  'L’Autre Monde',
  'La Corda D’Oro',
  'La Corda D’Oro Blue Sky',
  'La Légende de Korra',
  'La Sorcière de l’Ouest',
  'Ladies versus Butlers!',
  'Lan Mo De Hua',
  'Lance N’ Masques',
  'Lapis Re :LiGHTs',
  'Last Period: Owarinaki Rasen no Monogatari',
  'Layton Mystery Tanteisha – Katori no Nazotoki Files',
  'Legend of Basara',
  'Les 12 Royaumes (Juuni Kokuki)',
  'Level E',
  'Levius',
  'Listeners',
  'Little Busters!',
  'Little Witch Academia',
  'Log Horizon',
  'Long Riders!',
  'Lord El-Melloi II-sei no Jikenbo',
  'Lost Song',
  'Love♥Love?',
  'Love and Lies',
  'Love Hina',
  'Love Lab',
  'Love Live! School Idol Project',
  'Love Live! Sunshine!!',
  'Love Live! Nijigasaki Gakuen School Idol Doukoukai',
  'Love Stage !!',
  'Loveless',
  'Lovely Complex',
  'Luck & Logic',
  'Lucky Star',
  'Luger Code 1951',
  'Lupin III',
  'Lupin III: Mine Fujiko to Iu Onna',
  'Lupin III: Part V',
  'M3: Sono Kuroki Hagane',
  'Maburaho',
  'Macademi Wasshoi!',
  'Machikado Mazoku',
  'Machine-Doll wa Kizutsukanai',
  'Macross Frontier',
  'Macross Delta',
  'Madan no Ou to Vanadis',
  'Made in Abyss',
  'Madlax',
  'Maesetsu! Opening Act',
  'Magatsu Wahrheit: Zuerst',
  'Magi: Sinbad no Bouken',
  'Magi: The Labyrinth of Magic',
  'Magia Record: Mahou Shoujo Madoka☆Magica Gaiden',
  'Magic Kaito',
  'Magic Kaito 1412',
  'Magic-Kyun! Renaissance',
  'Magikano',
  'Mahou Sensei Negima!',
  'Mahou Sensou',
  'Mahou Shoujo Ikusei Keikaku',
  'Mahou Shoujo Lyrical Nanoha',
  'Mahou Shoujo Ore',
  'Mahou Shoujo Site',
  'Mahou Tsukai no Yome',
  'Mahoujin Guru Guru (2017)',
  'Mahouka Koukou no Rettousei',
  'Mahoutsukai ni Taisetsu na Koto: Natsu no Sora',
  'Mai-HiME',
  'Mai-Otome',
  'Mairimashita! Iruma-kun',
  'Maji de Watashi ni Koi Shinasai!!',
  'Majin Tantei Nougami Neuro',
  'Majimoji Rurumo',
  'Majo no Tabitabi',
  'Major',
  'Majutsushi Orphen Hagure Tabi',
  'Makai Ouji Devils and Realist',
  'Makai Senki Disgaea',
  'Maken-Ki!',
  'Mamoru-kun ni Megami no Shukufuku wo!',
  'Manga de Wakaru! Fate/Grand Order',
  'Mangaka-san to Assistant-san to',
  'Manyuu Hiken-chou',
  'Maou-sama, Retry!',
  'Maoyuu Maou Yuusha',
  'Märchen Mädchen',
  'Maria†Holic',
  'Masamune-kun no Revenge',
  'Mashiro-iro symphony',
  'Masou Gakuen HxH',
  'Mawaru Penguindrum',
  'Mayo Chiki!',
  'Mayoi Neko Overrun',
  'Mayoiga',
  'Mayonaka no Occult Koumuin',
  'Medaka box',
  'Megazone 23',
  'Meiji Tokyo Renka',
  'Mekakucity Actors',
  'Meng Qi Shi Shen',
  'Metaman',
  'Mi Yu Xing Zhe',
  'Michiko to Hatchin',
  'Midara na Ao-chan wa Benkyou ga Dekinai',
  'Midori Days',
  'Mikagura Gakuen Kumikyoku',
  'Mikakunin De Shinkoukei',
  'Military!',
  'Minami Kamakura Koukou Joshi Jitenshabu',
  'Mini Toji',
  'Minuscule',
  'Mirai Nikki',
  'Miru Tights',
  'Mitsuboshi Colors',
  'Mitsudomoe',
  'MM!',
  'Mnemosyne: Mnemosyne no Musume-tachi',
  'Mo Dao Zu Shi',
  'Mob Psycho 100',
  'Mobile Fighter G Gundam',
  'Mobile Suit Gundam SEED',
  'Mobile Suit Gundam SEED Destiny',
  'Mobile Suit Gundam 00',
  'Mobile Suit Gundam: Tekketsu no Orphans',
  'Mobile Suit Gundam The origin Advent of the Red Comet',
  'Mobile Suit Gundam Thunderbolt',
  'Moetan',
  'Momo Kyun Sword',
  'Momokuri',
  'Mondaiji tachi ga',
  'Monochrome Factor',
  'Monogatari: Seconde saison',
  'Mononoke',
  'Monster Girl Doctor',
  'Monster Hunter Stories RIDE ON',
  'Monster Musume no Iru Nichijô',
  'Mugen no Juunin',
  'Mugen no Juunin (2019)',
  'Muhyo to Rouji no Mahouritsu Soudan Jimusho',
  'Mujaki no Rakuen',
  'Munou na Nana',
  'Munto',
  'Murder Princess',
  'Murenase! Seton Gakuen',
  'Musaigen no Phantom World',
  'Mushi-Uta',
  'Mushikago no Cagaster',
  'Mushishi',
  'Mushoku Tensei: Isekai Ittara Honki Dasu',
  'Muv-Luv Alternative: Total Eclipse',
  'My Girlfriend Is Too Much To Handle',
  'My Hero Academia',
  'My Next Life as a Villainess: All Routes Lead to Doom!',
  'Myself ; Yourself',
  'Nabari no Ou',
  'Nadia, le secret de l’eau bleue',
  'Nagareboshi Lens',
  'Nagasarete Airantou',
  'Nagi no Asukara',
  'Nami yo Kiitekure',
  'Namiuchigiwa no Muromi-san',
  'Namu Amida Butsu!: Rendai Utena',
  'Nana',
  'Nana to Kaoru',
  'Nanamaru Sanbatsu',
  'Nanana’s Buried Treasure',
  'Nanatsu no Bitoku',
  'Nanatsu no Taizai',
  'Nanatsu no Taizai: Seisen no Shirushi',
  'Nanatsuiro Drops',
  'Nanbaka',
  'Nande Koko ni Sensei ga?!',
  'Narutaru ~Mukuro naru Hoshi·Tama taru Ko~',
  'Naruto',
  'Natsume Yuujinchou',
  'Natsuyuki Rendez-vous',
  'Nazo no kanojo X',
  'Needless',
  'Nejimaki Seirei Senki: Tenkyou no Alderamin',
  'Nekopara',
  'Neo Angelique Abyss',
  'Net-juu no Susume',
  'Netoge no Yome',
  'Netsuzô Trap -NTR-',
  'New Game!',
  'NHK ni Youkoso!',
  'Nichijou',
  'Night Head Genesis',
  'Nijiiro☆Prism Girl',
  'Nil Admirari no Tenbin: Teito Genwaku Kitan',
  'Ninja Collection',
  'Nisekoi',
  'Nisemonogatari',
  'No. 6',
  'No Guns Life',
  'Noblesse',
  'Nobunaga-sensei no Osanazuma',
  'Nobunaga the Fool',
  'Nobunagun',
  'Nodame Cantabile',
  'Nogizaka Haruka no Himitsu',
  'Noir',
  'Non Non Biyori',
  'Nora to Oujo to Noraneko Heart',
  'Norn9',
  'Nourin',
  'Nozo x Kimi',
  'Null Peta',
  'Number24',
  'Nurarihyon no Mago',
  'Nyan Koi !',
  'Nyanko Days',
  'Nyanpire The Animation',
  'Occultic;Nine',
  'Oda Cinnamon Nobunaga',
  'Oda Nobuna no Yabou',
  'Ojisan to Marshmallow',
  'Okane ga Nai',
  'Okusama ga Seitokaichou!',
  'Okusama wa Joshikousei',
  'Omae wa Mada Gunma wo Shiranai',
  'Omamori Himari',
  'One Outs',
  'One Piece (Saison 1 à 11)',
  'One Piece (Saison 12 à ?)',
  'One Punch-Man',
  'One Room',
  'Onee-chan ga Kita',
  'Onegai Teacher',
  'Ongaku Shoujo',
  'Onigiri',
  'Onihei',
  'Onii-chan Dakedo Ai Sae Areba Kankeinai yo',
  'Oniichan no Koto Nanka Zenzen Suki Janain Dakara ne—!!',
  'Onsen Yousei Hakone-chan',
  'Onyx Equinox',
  'Ookami Kakushi',
  'Ookami-san to Shichinin no Nakama-tachi',
  'Ookami Shoujo to Kuro Ouji',
  'Ooya-san wa Shishunki!',
  'Orange',
  'Ore dake Haireru Kakushi Dungeon',
  'Ore ga Suki nano wa Imouto dakedo Imouto ja Nai',
  'Ore, Twintail ni Narimasu',
  'Ore Monogatari!!',
  'Ore no Imouto ga Konna ni Kawaii Wake ga Nai',
  'Ore no Kanojo to Osananajimi (Oreshura)',
  'Ore no Nounai Sentakushi ga',
  'Ore wo Suki nano wa Omae dake ka yo',
  'Orenchi no Furo Jijou',
  'Oretachi ni Tsubasa wa Nai',
  'Oruchuban Ebichu',
  'Osake wa Fuufu ni Natte Kara',
  'Oshi ga Budoukan Ittekuretara Shinu',
  'Oshiete Galko-chan',
  'Osomatsu-san',
  'Otogi Story Tenshi no Shippo',
  'Otome wa Boku ni Koishiteru',
  'Otome Youkai Zakuro',
  'Otona no Bouguya-san',
  'Ouran High School Host Club',
  'Oushitsu Kyoushi Heine',
  'Outbreak Company',
  'Over Drive',
  'Overlord',
  'Owari no Seraph',
  'Owarimonogatari',
  'Ozma',
  'Ozmafia!!',
  'Pan de Peace!',
  'Pandora Hearts',
  'Panty & Stocking with Garterbelt',
  'Papa no Iukoto wo Kikinasai!',
  'Papa to Kiss in the Dark',
  'Paranoia Agent',
  'Parasite',
  'Peach Girl',
  'Persona 3 The Movie',
  'Persona 4: The Animation',
  'Persona 4 The Golden Animation',
  'Persona 5 The Animation',
  'Persona: Trinity Soul',
  'Pet',
  'Peter Grill to Kenja no Jikan',
  'Phantasy Star Online 2: The Animation',
  'Phantom in the Twilight',
  'Phantom: Requiem for the Phantom',
  'Photo Kano',
  'Piano no Mori',
  'PIKO-TARO no Lullaby Lu-llaby',
  'Ping Pong The Animation',
  'Planet With',
  'Plastic Memories',
  'Plastic Neesan',
  'Plunderer',
  'Pokemon: The Origin',
  'Pop Team Epic',
  'Precure All Stars',
  'Prince of Tennis',
  'Princess Connect! Re :Dive',
  'Princess Jellyfish',
  'Princess Lover!',
  'Princess Princess',
  'Princess Principal',
  'Prism Ark',
  'Prism Magical: Prism Generations!',
  'Prison School',
  'Pretear',
  'Promare',
  'Psycho-pass',
  'Punchline',
  'Pupa',
  'Pupipo!',
  'Qualidea Code',
  'Quanzhi Fashi',
  'Quan Zhi Gao Shou',
  'Queen’s Blade',
  'R-15',
  'Ragnarök the Animation',
  'Ragnastrike Angels',
  'Rail Romanesque',
  'Rail Wars!',
  'Rainbow: Nisha Rokubō no Shichinin',
  'Rakudai Kishi no Cavalry',
  'Ramen Daisuki Koizumi-san',
  'Ranpo Kitan: Game of Laplace',
  'Rave Master',
  'RDG: Red Data Girl',
  'Re-Kan!',
  'Re:Creators',
  'Reborn!',
  'Rec',
  'Regalia: The Three Sacred Stars',
  'Reikenzan: Hoshikuzu-tachi no Utage',
  'ReLIFE',
  'Release the Spyce',
  'Renai Boukun',
  'Rental Magica',
  'RErideD: Toki Koe no Derrida',
  'Revisions',
  'Rewrite',
  'Re:Zero kara Hajimeru Isekai Seikatsu',
  'Rick et Morty',
  'RideBack',
  'Rifle is Beautiful',
  'Rikei ga Koi ni Ochita no de Shoumei shitemita.',
  'Rinne no Lagrange',
  'Rinshi!! Ekoda-chan',
  'Road to You',
  'RobiHaci',
  'RobiHaci',
  'Robomasters The Animated Series',
  'Robotics;Notes',
  'Ro-Kyu-bu!',
  'Rokka no Yuusha',
  'Rokudenashi Majutsu Koushi to Akashic',
  'Rokuhoudou Yotsuiro Biyori',
  'Rokujouma no Shinryakusha!?',
  'Romeo x Juliet',
  'Rosario + Vampire',
  'Rozen Maiden',
  'Rozen Maiden (2013)',
  'Runway de Waratte',
  'RWBY',
  'Sabagebu!',
  'Sacred Seven',
  'Saenai Heroine no Sodatekata',
  'Saijaku Muhai no Bahamut',
  'Saiki Kusuo no Ψ Nan',
  'Saikin, Imouto no Yousu ga Chotto Okaishii',
  'Sailor Moon Crystal',
  'Saishuu Heiki Kanojo',
  'Saiyuki Reload Blast',
  'Sakamichi no Apollon',
  'Sakamoto desu ga?',
  'Saki',
  'Saki: Achiga-hen – Episode of Side-A',
  'Sakura Quest',
  'Sakura Trick',
  'Sakurasou no Pet na Kanojo',
  'Samurai 7',
  'Samurai Champloo',
  'Samurai Deeper Kyo',
  'Sankarea',
  'Sanrio Danshi',
  'Sansha Sanyou',
  'Sarai-ya Goyou',
  'Sarazanmai',
  'Sasameki Koto',
  'Satsuriku no Tenshi',
  'Sayonara Zetsubo Sensei',
  'Scared Rider Xechs',
  'School Days',
  'School-Live!',
  'School Rumble',
  'Schoolgirl Strikers: Animation Channel',
  'Schwarzesmarken',
  'Seikai Suru Kado',
  'Seiken no blacksmith',
  'Seiken Tsukai no World Break',
  'Seikimatsu Occult Gakuin',
  'Seikoku no Dragonar',
  'Seikon No Qwaser',
  'Seirei no Moribito',
  'Seirei Tsukai no Blade Dance',
  'Seiren',
  'Seisen Cerberus : Ryuu Koku no Fatalite',
  'Seishun Buta Yarou wa Bunny Girl Senpai no Yume wo Minai',
  'Seitokai no Ichizon',
  'Seitokai yakuindomo',
  'Seitokaichou ni Chukoku',
  'Sekai de Ichiban Tsuyoku Naritai!',
  'Sekai Seifuku: Le Complot de Zvezda',
  'Sekaiichi Hatsukoi',
  'Sekirei',
  'Selector infected WIXOSS',
  'Sengoku Basara',
  'Sengoku Musou',
  'Sengoku Night Blood',
  'Sengoku Otome: Momoiro Paradox',
  'Senjou no valkyria: Gallian Chronicles',
  'Senjuushi',
  'Senki Zesshou Symphogear',
  'Senkou no Night Raid',
  'Senran Kagura',
  'Senryuu Shoujo',
  'Senyoku no Sigrdrifa',
  'Senyuu.',
  'Serial Experiments Lain',
  'Servamp',
  'Servant × Service',
  'Seto no Hanayome',
  'Sewayaki Kitsune no Senko-san',
  'Shachou, Battle no Jikan Desu!',
  'Shaman King',
  'Shangri-la',
  'Shakugan No Shana',
  'Shakunetsu no Takkyuu Musume',
  'Shelter',
  'Shichisei no Subaru',
  'Shigofumi',
  'Shigurui',
  'Shijou Saikyou no Deshi Kenichi',
  'Shikabane Hime',
  'Shiki',
  'Shin Chuuka Ichiban!',
  'Shin prince of Tennis',
  'Shin Sakura Taisen The Animation',
  'Shin Tenchi Muyo!',
  'Shingeki no Bahamut: Genesis',
  'Shingeki no Bahamut: Virgin Soul',
  'Shingeki no Bahamut: Manaria Friends',
  'Shingeki No Kyojin (Attaque des Titans)',
  'Shingeki no Kyojin: Kuinaki Sentaku',
  'Shingeki no Kyojin: Lost Girls',
  'Shingetsutan Tsukihime',
  'Shinigami no Ballad',
  'Shining Hearts: Shiawase no Pan',
  'Shining Tears X Wind',
  'Shinkyoku Soukai Polyphonica',
  'Shinmai Maou no Testament',
  'Shinrei tantei yakumo',
  'Shinreigari: Ghost Hound',
  'Shinryaku! Ika Musume',
  'Shinsekai Yori',
  'Shinya! Tensai Bakabon',
  'Shion no Ou',
  'Shirobako',
  'Shirogane no Ishi Argevollen',
  'Shironeko Project: Zero Chronicle',
  'Shiyan Pin Jiating',
  'Shokugeki no Soma (Food Wars!)',
  'Shomin Sample',
  'Shoumetsu Toshi',
  'Shoujo Kakumei Utena',
  'Shoujo-tachi wa Kouya wo Mezasu',
  'Shoujo☆Conte All Starlight',
  'Shoujo☆Kageki Revue Starlight',
  'Shoukoku no Altair',
  'Shounen Maid',
  'Shounen Onmyouji',
  'Show by Rock!!',
  'Show by Rock!! Mashumairesh!!',
  'Shuangsheng Lingtan',
  'Shuffle!',
  'Shugo Chara!',
  'Shukufuku no Campanella',
  'Shuumatsu no Izetta',
  'Sin : Nanatsu no Taizai',
  'Sirius the Jaeger',
  'SK8 the Infinity',
  'Sket Dance',
  'Skip Beat!',
  'Sky Girls',
  'Slow Start',
  'So Ra No Wo To',
  'Sola',
  'Somali to Mori no Kamisama',
  'SoniAni: Super Sonico The Animation',
  'Sono Toki, Kanojo wa.',
  'Sora no Manimani',
  'Sora no Method',
  'Sora no Otoshimono',
  'Sora to Umi no Aida',
  'Sora yori mo Tooi Basho',
  'Sore dake ga Neck',
  'Soredemo Sekai wa Utsukushii',
  'Soul Buster',
  'Soul Eater',
  'Soul Eater Not!',
  'Soul Worker',
  'Sounan desu ka?',
  'Sousei no Onmyouji (Twin Star Exorcists)',
  'Soushin Shoujo Matoi',
  'Soutai Sekai',
  'Souten Kouro',
  'Special A',
  'Spice and Wolf',
  'Spiral: Suiri no Kizuna',
  'Spirit Pact',
  'SSSS.Gridman',
  'Stand My Heroes',
  'Star Driver: Kagayaki no Takuto',
  'Steins;Gate',
  'Steins;Gate 0',
  'Stella Jogakuin Koutouka C3-Bu',
  'Stella no Mahou',
  'Strawberry Panic!',
  'Strait Jacket',
  'Strike the Blood',
  'Strike Witches',
  'Strike Witches: 501 Butai Hasshin Shimasu!',
  'Subete ga F ni Naru: The Perfect Insider',
  'Sugar*Soldier',
  'Suisei no Gargantia',
  'SukaSuka',
  'Sukitte ii na yo',
  'Sumomomo Momomo',
  'Sunoharasou no Kanrinin-san',
  'Super Danganronpa 2.5: Komaeda Nagito',
  'Super Lovers',
  'Super Seisyun Brothers',
  'Suzuka',
  'Sweat Punch',
  'Sword Art Online : Alicization',
  'Sword Art Online Alternative: Gun Gale Online',
  'Sword Gai: The Animation',
  'Taboo Tattoo',
  'Tachibanakan Triangle',
  'Taisou Zamurai',
  'Takashi Taniguchi',
  'Takunomi.',
  'Tamayomi',
  'Tales of Eternia',
  'Tales of Symphonia',
  'Tales of the Abyss',
  'Tales of Zestiria the X',
  'Tamako Market',
  'Tanaka-kun wa Itsumo Kedaruge',
  'Tari Tari',
  'Tasogare Otome x Amnesia',
  'Tate no Yuusha no Nariagari',
  'Tatoeba Last Dungeon Mae no Mura no Shounen ga Joban no Machi de Kurasu Youna Monogatari',
  'Tayutama: Kiss on my Deity',
  'Tears to Tiara',
  'Tegami Bachi',
  'Tejina Senpai',
  'Tenchi Muyo!',
  'Tenchi Muyo! GXP',
  'Tenka Hyakken: Meiji-kan e Youkoso!',
  'Tensei Shitara Slime Datta Ken',
  'Tenshi Kinryouku',
  'Tenshi no 3P!',
  'Terra Formars',
  'Texhnolyze',
  'The 8th son? Are you kidding me?',
  'The Daily Life of The Immortal King',
  'The God of High School',
  'The IDOLM@STER',
  'The iDOLM@STER Cinderella Girls',
  'The Island of Giant Insects',
  'The Melody of Oblivion',
  'The Misfit of Demon King Academy',
  'The Ones Within',
  'The Promised Neverland',
  'The Reflection',
  'The Rolling Girls',
  'Tian Guan Ci Fu',
  'Tide-Line Blue',
  'Tiger & Bunny',
  'Tight-rope',
  'Time Travel Shoujo',
  'To Aru Kagaku no Railgun',
  'To Aru Majutsu no Index',
  'To Be Hero',
  'To Be Heroine',
  'Toaru Hikuushi e no Koiuta',
  'Toaru Kagaku no Accelerator',
  'Togainu no chi',
  'Toji no Miko',
  'Tokimeki memorial Only Love',
  'Tokkô',
  'Tokyo ESP',
  'Tokyo Magnitude 8.0',
  'Tokyo Majin Gakuen Kenpucho',
  'Tokyo Ravens',
  'To Love-Ru Darkness (Saison 3 & 4)',
  'To Love-Ru Trouble (Saison 1 & 2)',
  'Tonagura!',
  'Tonari no Kaibutsu-kun',
  'Tonari no Kyuuketsuki-san',
  'Tonari no Seki-kun',
  'Tong Ling Fei',
  'Tonikaku Kawaii',
  'Toradora',
  'Toriko',
  'Toshokan Sensou',
  'Touhai Densetsu Akagi: Yami ni Maiorita Tensai',
  'Touhou Gensou Mangekyou',
  'Touken Ranbu – Hanamaru',
  'Towa no Quon',
  'Triage X',
  'Trickster',
  'Trigun',
  'Trinity Blood',
  'Trinity Seven',
  'True Tears',
  'Try Knights',
  'Tsubasa Chronicle',
  'Tsubasa to Hotaru',
  'Tsugumomo',
  'Tsuki ga Kirei',
  'Tsuki wa Higashi ni Hi wa Nishi ni – Operation Sanctuary',
  'Tsukipro The Animation',
  'Tsukiuta. The Animation',
  'Tsukumogami Kashimasu',
  'Tsukuyomi: Moon Phase',
  'Tsuredure Children',
  'Tsurune: Kazemai Koukou Kyuudoubu',
  'Uchi no Maid ga Uzasugiru!',
  'Uchitama?! Have you seen my Tama?',
  'Uchuu Kaizoku Captain Harlock',
  'Uchuu no Stellvia',
  'Uchuu Patrol Luluco',
  'Uchuu Senkan Yamato 2199',
  'Uchuu Senkan Yamato 2202: Ai no Senshi-tachi',
  'Ueki no Housoku',
  'Ueno-san wa Bukiyou',
  'UFO Princess Valkyrie',
  'Ultra Maniac',
  'Ultraman',
  'Ultraviolet: Code 044',
  'Ulysses: Jeanne d’Arc to Renkin no Kishi',
  'Uma Musume: Pretty Derby',
  'Umayon',
  'Umi Monogatari: Anata ga Ite Kureta Koto',
  'Umineko no naku koro ni',
  'Un-Go',
  'Under The Dog',
  'Upotte!!',
  'UQ Holder! Mahou Sensei Negima! 2',
  'Uragiri wa Boku no Namae wo Shitteiru',
  'Urahara',
  'Urara Meirochou',
  'Urasekai Picnic',
  'Urashimasakatasen no Nichijou',
  'Usagi Drop',
  'Ushinawareta Mirai wo Motomete',
  'Uta no☆Prince-sama♪',
  'Uzaki-chan wa Asobitai!',
  'Valkyrie Drive: Mermaid',
  'Vampire Hunter',
  'Vampire Knight',
  'Vandread',
  'Video Girl Ai',
  'Vinland Saga',
  'Violet Evergarden',
  'Virtual-san wa Miteiru',
  'Visions d’Escaflowne',
  'ViVid Strike!',
  'Vividred Operation',
  'Wagamama High Spec',
  'Wagaya no Oinari-sama',
  'Wake Up, Girls!',
  'Walkure Romanze',
  'Wangan Midnight',
  'Warau Salesman NEW',
  'Watamote',
  'Watashi ga Motete ga Dosunda',
  'Watashi ni Tenshi ga Maiorita!',
  'Watashi, Nouryoku wa Heikinchi de tte Itta yo ne!',
  'Weiss Survive',
  'White Album',
  'Wild Adapter',
  'Witch Hunter Robin',
  'Witchblade',
  'Witchcraft Works',
  'Wizard Barristers : Benmashi Cecil',
  'Wo De Ni Tian Shen Qi',
  'Wo De Tian Jie Nv You',
  'Wonder Egg Priority',
  'Working!!',
  'World Destruction: Sekai Bokumetsu no Rokunin',
  'World Trigger',
  'Wotaku ni Koi wa Muzukashii',
  'Wu Shan Wu Xing',
  'W’z',
  'X-Men (2011)',
  'Xiang Ling Ji',
  'Xie Wang Zhui Qi',
  'xxxHOLiC',
  'Yagate Kimi ni Naru',
  'Yahari Ore no Seishun Love Come wa Machigatteiru',
  'Yamada-kun to 7-nin no Majo',
  'Yamato Nadeshiko Shichi Henge',
  'Yami no Matsuei',
  'Yaoguai Mingdan',
  'Yatogame-chan Kansatsu Nikki',
  'Yawara!',
  'Yebisu Celebrities',
  'Yesterday wo Utatte',
  'Yichang Sheng Wu Jian Wen Lu',
  'Yoake Mae Yori Ruri Iro Na: Crescent Love',
  'Yôjo Senki: Saga of Tanya the Evil',
  'Yojouhan Shinwa Taikei',
  'Yomigaeru Sora: Rescue Wings',
  'Yondemasu yo, Azazel-san. Z',
  'Yosuga no Sora',
  'Youkai Apartment no Yuuga na Nichijou',
  'Young GTO: Shonan Junai Gumi',
  'Your lie in April',
  'Yowamushi Pedal',
  'Yozakura Quartet',
  'Yu-Gi-Oh! Jeu des Ténèbres',
  'Yu Yu Hakusho',
  'Yume Oukoku to Nemureru 100-nin no Ouji-sama',
  'Yumeiro pâtissière',
  'Yumekui Merry',
  'Yumekuri',
  'Yuragi-sou no Yuuna-san',
  'Yuri Kuma Arashi',
  'Yuri!!! on Ice',
  'Yuru Camp△',
  'Yuru Yuri',
  'Yuuki Yuuna wa Yuusha de Aru',
  'Yuukoku no Moriarty',
  'Yuushibu',
  'Yuyushiki',
  'Zashiki Warashi no Tatami-chan',
  'Zatch Bell',
  'Zenonzard: The Animation',
  'Zero no Tsukaima',
  'Zetsuen no Tempest',
  'Zetman',
  'Zettai Bouei Leviathan',
  'Zettai Junpaku: Mahou Shoujo',
  'Zettai Karen Children: The Unlimited – Hyoubu Kyousuke',
  'Zhen Hun Jie',
  'Zoku Owarimonogatari',
  'Zombie Loan',
  'Zombieland Saga',
  'Z/X Code reunion',
  'Z/X Ignition',
];
