List<String> classicRock = [
  'Caught Up in You by .38 Special',
  'Fantasy Girl by .38 Special',
  'Hold On Loosely by .38 Special',
  'Rockin\' Into the Night by .38 Special',
  'Art For Arts Sake by 10cc',
  'Kryptonite by 3 Doors Down',
  'Loser by 3 Doors Down',
  'When I\'m Gone by 3 Doors Down',
  'What\'s Up? by 4 Non Blondes',
  'Take On Me by a-ha',
  'Baby, Please Don\'t Go by AC/DC',
  'Back In Black by AC/DC',
  'Big Gun by AC/DC',
  'CAN\'T STOP ROCK\'N\'ROLL by AC/DC',
  'Dirty Deeds Done Dirt Cheap by AC/DC',
  'For Those About To Rock by AC/DC',
  'Girls Got Rhythm by AC/DC',
  'Hard As A Rock by AC/DC',
  'Have a Drink On Me by AC/DC',
  'Hells Bells by AC/DC',
  'Highway To Hell by AC/DC',
  'It\'s A Long Way To The Top by AC/DC',
  'Jailbreak by AC/DC',
  'Let There Be Rock by AC/DC',
  'Let\'s Get It Up by AC/DC',
  'Live Wire by AC/DC',
  'Moneytalks by AC/DC',
  'Night Prowler by AC/DC',
  'Rock and Roll Ain\'t Noise Pollution by AC/DC',
  'Shoot To Thrill by AC/DC',
  'Shot Down In Flames by AC/DC',
  'Sin City by AC/DC',
  'T.N.T. by AC/DC',
  'Thunderstruck by AC/DC',
  'Touch Too Much by AC/DC',
  'What Do You Do For Money Honey by AC/DC',
  'Who Made Who by AC/DC',
  'Whole Lotta Rosie by AC/DC',
  'You Shook Me All Night Long by AC/DC',
  'How Long by Ace',
  'Dog On A Leash by Adelitas Way',
  'Angel by Aerosmith',
  'Baby, Please Don\'t Go by Aerosmith',
  'Back in the Saddle by Aerosmith',
  'Big Ten Inch by Aerosmith',
  'Come Together by Aerosmith',
  'Crazy by Aerosmith',
  'Cryin\' by Aerosmith',
  'Draw The Line by Aerosmith',
  'Dream On by Aerosmith',
  'Dude (Looks Like a Lady) by Aerosmith',
  'Jaded by Aerosmith',
  'Janie\'s Got A Gun by Aerosmith',
  'Kings and Queens by Aerosmith',
  'Last Child by Aerosmith',
  'Let the Music Do the Talking by Aerosmith',
  'Livin\' On The Edge by Aerosmith',
  'Love In An Elevator by Aerosmith',
  'Mama Kin by Aerosmith',
  'No More No More by Aerosmith',
  'One Way Street by Aerosmith',
  'Pink by Aerosmith',
  'Rag Doll by Aerosmith',
  'Same Old Song and Dance by Aerosmith',
  'Seasons of Wither by Aerosmith',
  'Sweet Emotion by Aerosmith',
  'The Other Side by Aerosmith',
  'Toys in the Attic by Aerosmith',
  'Train Kept A-Rollin\' by Aerosmith',
  'Walk This Way by Aerosmith',
  'What It Takes by Aerosmith',
  'You See Me Crying by Aerosmith',
  'Hand In My Pocket by Alanis Morissette',
  'You Oughta Know by Alanis Morissette',
  'Black Velvet by Alannah Myles',
  'Fantasy by Aldo Nova',
  'BE MY LOVER by Alice Cooper',
  'Billion Dollar Babies by Alice Cooper',
  'Eighteen by Alice Cooper',
  'Elected by Alice Cooper',
  'House Of Fire by Alice Cooper',
  'I\'m Eighteen by Alice Cooper',
  'No More Mr. Nice Guy by Alice Cooper',
  'School\'s Out by Alice Cooper',
  'Under My Wheels by Alice Cooper',
  'Welcome To My Nightmare by Alice Cooper',
  'Down in a Hole by Alice In Chains',
  'Man In The Box by Alice In Chains',
  'No Excuses by Alice In Chains',
  'Rooster by Alice In Chains',
  'Them Bones by Alice In Chains',
  'Would? by Alice In Chains',
  'Ain\'t Wastin\' Time No More by Allman Brothers Band',
  'Blue Sky by Allman Brothers Band',
  'Good Clean Fun by Allman Brothers Band',
  'In Memory Of Elizabeth Reed by Allman Brothers Band',
  'Jessica by Allman Brothers Band',
  'Melissa by Allman Brothers Band',
  'Midnight Rider by Allman Brothers Band',
  'No One to Run With by Allman Brothers Band',
  'One Way Out by Allman Brothers Band',
  'Ramblin\' Man by Allman Brothers Band',
  'Southbound by Allman Brothers Band',
  'Statesboro Blues by Allman Brothers Band',
  'Whippin\' Post by Allman Brothers Band',
  'A Horse With No Name by America',
  'Sister Golden Hair by America',
  'Ventura Highway by America',
  'Don\'t Bring Me Down by Animals II',
  'Don\'t Let Me Be Misunderstood by Animals II',
  'Immigrant Song by Ann Wilson',
  'Roller by April Wine',
  'Hold Your Head Up by Argent',
  'Coming into Los Angeles by Arlo Guthrie',
  'Wayside by Artful Dodger',
  'Heat of the Moment by Asia',
  'Only Time Will Tell by Asia',
  'So Into You by Atlanta Rhythm Section',
  'Spooky by Atlanta Rhythm Section',
  'Like a Stone by Audioslave',
  'Blondes In Black Cars by Autograph',
  'Turn Up the Radio by Autograph',
  'Rock And Roll Party In The Streets by Axe',
  'Let It Ride by Bachman-Turner Overdrive',
  'Roll On Down The Highway by Bachman-Turner Overdrive',
  'Takin\' Care Of Business by Bachman-Turner Overdrive',
  'You Ain\'t Seen Nothin\' Yet by Bachman-Turner Overdrive',
  'Bad Company by Bad Company',
  'Burnin\' Sky by Bad Company',
  'Can\'t Get Enough by Bad Company',
  'Feel Like Makin\' Love by Bad Company',
  'Gone Gone Gone by Bad Company',
  'Good Lovin\' Gone Bad by Bad Company',
  'Movin\' On by Bad Company',
  'Ready For Love by Bad Company',
  'Rock \'n\' Roll Fantasy by Bad Company',
  'Rock Steady by Bad Company',
  'Run With The Pack by Bad Company',
  'Seagull by Bad Company',
  'Shooting Star by Bad Company',
  'Silver, Blue And Gold by Bad Company',
  'When I See You Smile by Bad English',
  'No Matter What by Badfinger',
  'Walks Like A Woman by Baton Rouge',
  '(You Gotta) Fight for Your Right (To Party) by Beastie Boys',
  'No Sleep Till Brooklyn by Beastie Boys',
  'Loser by Beck',
  'In a Big Country by Big Country',
  'Rock Around the Clock by Bill Haley',
  'AIN\'T NO SUNSHINE by Bill Withers',
  'Cradle of Love by Billy Idol',
  'Dancing With Myself by Billy Idol',
  'Eyes Without a Face by Billy Idol',
  'Mony Mony by Billy Idol',
  'Rebel Yell by Billy Idol',
  'White Wedding by Billy Idol',
  'Allentown by Billy Joel',
  'Big Shot by Billy Joel',
  'Captain Jack by Billy Joel',
  'Don\'t Ask Me Why by Billy Joel',
  'Goodnight Saigon by Billy Joel',
  'It\'s Still Rock And Roll To Me by Billy Joel',
  'Miami 2017 {seen The Lights Go Out On Broadway} (live 1 by Billy Joel',
  'Movin\' Out (Anthony\'s Song) by Billy Joel',
  'My Life by Billy Joel',
  'New York State Of Mind by Billy Joel',
  'Only The Good Die Young by Billy Joel',
  'Piano Man by Billy Joel',
  'Prelude/angry Young Man by Billy Joel',
  'Scenes From An Italian Restaurant by Billy Joel',
  'SHE\'S ALWAYS A WOMAN by Billy Joel',
  'Sometimes A Fantasy by Billy Joel',
  'The Ballad Of Billy The Kid by Billy Joel',
  'The Stranger by Billy Joel',
  'You May Be Right by Billy Joel',
  'Baby Come Back by Billy Rankin',
  'Everybody Wants You by Billy Squier',
  'In the Dark by Billy Squier',
  'Lonely Is the Night by Billy Squier',
  'My Kinda Lover by Billy Squier',
  'Rock Me Tonight by Billy Squier',
  'She\'s a Runner by Billy Squier',
  'The Stroke by Billy Squier',
  'Children Of The Sun by Billy Thorpe',
  'Fairies Wear Boots by Black Sabbath',
  'Heaven and Hell by Black Sabbath',
  'Iron Man by Black Sabbath',
  'N.i.b. by Black Sabbath',
  'Neon Knights by Black Sabbath',
  'Paranoid by Black Sabbath',
  'Sweet Leaf by Black Sabbath',
  'The Wizard by Black Sabbath',
  'War Pigs by Black Sabbath',
  'Highway Song by Blackfoot',
  'Train, Train by Blackfoot',
  'Can\'t Find My Way Home by Blind Faith',
  'Presence of the Lord by Blind Faith',
  'No Rain by Blind Melon',
  'Presence of the Lord by Blind Melon',
  'All the Small Things by Blink-182',
  'Call Me by Blondie',
  'Heart of Glass by Blondie',
  'One Way Or Another by Blondie',
  '(Don\'t Fear) The Reaper by Blue Oyster Cult',
  'Bucks Boogie by Blue Oyster Cult',
  'Burnin\' for You by Blue Oyster Cult',
  'Godzilla by Blue Oyster Cult',
  'I Love the Night by Blue Oyster Cult',
  'Summertime Blues by Blue Oyster Cult',
  'Song 2 by Blur',
  'Just Like A Woman by Bob Dylan',
  'Knockin\' On Heaven\'s Door by Bob Dylan',
  'Like a Rolling Stone by Bob Dylan',
  'Positively 4th Street by Bob Dylan',
  'Subterranean Homesick Blues by Bob Dylan',
  'Tangled Up In Blue by Bob Dylan',
  'Exodus by Bob Marley',
  'Jamming by Bob Marley',
  'No Woman, No Cry by Bob Marley',
  'One Love by Bob Marley',
  'Stir It Up by Bob Marley',
  'Three Little Birds by Bob Marley',
  'Against The Wind by Bob Seger',
  'Betty Lou\'s Gettin\' Out Tonigh by Bob Seger',
  'Come to Poppa by Bob Seger',
  'Feel Like a Number by Bob Seger',
  'Fire Down Below by Bob Seger',
  'Get Out of Denver by Bob Seger',
  'Her Strut by Bob Seger',
  'Hollywood Nights by Bob Seger',
  'Horizontal Bop by Bob Seger',
  'Katmandu by Bob Seger',
  'Mainstreet by Bob Seger',
  'Night Moves by Bob Seger',
  'Old Time Rock & Roll by Bob Seger',
  'Ramblin\' Gamblin\' Man by Bob Seger',
  'Rock And Roll Never Forgets by Bob Seger',
  'Roll Me Away by Bob Seger',
  'Still the Same by Bob Seger',
  'Sunspot Baby by Bob Seger',
  'The Fire Down Below by Bob Seger',
  'Travelin\' Man by Bob Seger',
  'Turn On Your Love Light by Bob Seger',
  'Turn The Page by Bob Seger',
  'We\'ve Got Tonite by Bob Seger',
  'You\'ll Accompany Me by Bob Seger',
  'Hypnotized by Bob Welch',
  'Bad Medicine by Bon Jovi',
  'Blaze of Glory by Bon Jovi',
  'Born To Be My Baby by Bon Jovi',
  'Lay Your Hands On Me by Bon Jovi',
  'Livin\' On A Prayer by Bon Jovi',
  'Raise Your Hands by Bon Jovi',
  'Runaway by Bon Jovi',
  'She Don\'t Know Me by Bon Jovi',
  'Wanted Dead or Alive by Bon Jovi',
  'You Give Love A Bad Name by Bon Jovi',
  'Wait For You by Bonham',
  'Green Onions by Booker T. and the MG\'s',
  'A Man I\'ll Never Be by Boston',
  'Amanda by Boston',
  'Cool The Engines by Boston',
  'Don\'t Look Back by Boston',
  'Feelin\' Satisfied by Boston',
  'Foreplay (Long Time) by Boston',
  'Hitch A Ride by Boston',
  'Let Me Take You Home Tonight by Boston',
  'More Than a Feeling by Boston',
  'Party by Boston',
  'Peace of Mind by Boston',
  'Rock & Roll Band by Boston',
  'Smokin\' by Boston',
  'Something About You by Boston',
  'The Journey/It\'s Easy by Boston',
  'Used To Bad News by Boston',
  'We\'re Ready by Boston',
  'Lido Shuffle by Boz Scaggs',
  'Lowdown by Boz Scaggs',
  'Tarkio Road by Brewer & Shipley',
  'The Way It Is by Bruce Hornsby & The Range',
  'Atlantic City by Bruce Springsteen',
  'Backstreets by Bruce Springsteen',
  'Badlands by Bruce Springsteen',
  'Blinded By the Light by Bruce Springsteen',
  'Born In the U.S.A. by Bruce Springsteen',
  'Born To Run by Bruce Springsteen',
  'Cover Me by Bruce Springsteen',
  'Dancing In the Dark by Bruce Springsteen',
  'Glory Days by Bruce Springsteen',
  'Growin\' Up by Bruce Springsteen',
  'Hungry Heart by Bruce Springsteen',
  'I\'m On Fire by Bruce Springsteen',
  'It\'s Hard to Be a Saint in the City by Bruce Springsteen',
  'Jersey Girl by Bruce Springsteen',
  'Jungleland by Bruce Springsteen',
  'Pink Cadillac by Bruce Springsteen',
  'Prove It All Night by Bruce Springsteen',
  'Racing in the Streets by Bruce Springsteen',
  'Rosalita (Come Out Tonight) by Bruce Springsteen',
  'She\'s The One by Bruce Springsteen',
  'Spirit In The Night by Bruce Springsteen',
  'Tenth Avenue Freeze-Out by Bruce Springsteen',
  'Thunder Road by Bruce Springsteen',
  'Cuts Like a Knife by Bryan Adams',
  'Heaven by Bryan Adams',
  'Run to You by Bryan Adams',
  'Somebody by Bryan Adams',
  'Summer Of \'69 by Bryan Adams',
  'Sorry by Buckcherry',
  'For What It\'s Worth by Buffalo Springfield',
  'Mr. Soul by Buffalo Springfield',
  'Rock & Roll Woman by Buffalo Springfield',
  'Comedown by Bush',
  'Machinehead by Bush',
  'Far Behind by Candlebox',
  'Goin\' up the Country by Canned Heat',
  'On the Road Again by Canned Heat',
  'IT\'S TOO LATE by Carole King',
  'Oh Very Young by Cat Stevens',
  'WILD WORLD by Cat Stevens',
  'In America by Charlie Daniels Band',
  'Long Haired Country Boy by Charlie Daniels Band',
  'The Devil Went Down To Georgia by Charlie Daniels Band',
  'The Legend Of Wooley Swamp by Charlie Daniels Band',
  'The South\'s Gonna Do It Again by Charlie Daniels Band',
  'Uneasy Rider by Charlie Daniels Band',
  'Ain\'t That a Shame by Cheap Trick',
  'Dream Police by Cheap Trick',
  'I Want You to Want Me by Cheap Trick',
  'She\'s Tight by Cheap Trick',
  'Surrender by Cheap Trick',
  'Take Out The Gunman by Chevelle',
  '25 Or 6 To 4 by Chicago',
  'Beginnings by Chicago',
  'Feeling Stronger Every by Chicago',
  'I\'m a Man by Chicago',
  'JUST YOU AND ME by Chicago',
  'Make Me Smile by Chicago',
  'Questions 67 and 68 by Chicago',
  'Saturday In the Park by Chicago',
  'South California Purples by Chicago',
  'JOHNNY B. GOODE by Chuck Berry',
  'Coming Home by Cinderella',
  'Don\'t Know What You Got by Cinderella',
  'Gypsy Road by Cinderella',
  'Nobody\'s Fool by Cinderella',
  'Somebody Save Me by Cinderella',
  'Better Off Without You by Clarks',
  'Born Too Late by Clarks',
  'Cigarette by Clarks',
  'Hey You by Clarks',
  'Maybe by Clarks',
  'Penny On The Floor by Clarks',
  'The River by Clarks',
  'December by Collective Soul',
  'Shine by Collective Soul',
  'The World I Know by Collective Soul',
  'Hot Rod Lincoln by Commander Cody',
  'Monkey Bars by Coney Hatch',
  'Mr. Jones by Counting Crows',
  'Low by Cracker',
  'Badge by Cream',
  'Born Under A Bad Sign by Cream',
  'Crossroads by Cream',
  'I\'m So Glad by Cream',
  'Sunshine of Your Love by Cream',
  'Tales Of Brave Ulysses by Cream',
  'White Room by Cream',
  'Higher by Creed',
  'My Sacrifice by Creed',
  'With Arms Wide Open by Creed',
  'Bad Moon Rising by Creedence Clearwater Revival',
  'Born On the Bayou by Creedence Clearwater Revival',
  'Commotion by Creedence Clearwater Revival',
  'Down On the Corner by Creedence Clearwater Revival',
  'Fortunate Son by Creedence Clearwater Revival',
  'Green River by Creedence Clearwater Revival',
  'Have You Ever Seen the Rain? by Creedence Clearwater Revival',
  'I Heard It Through the Grapevine by Creedence Clearwater Revival',
  'Lodi by Creedence Clearwater Revival',
  'Lookin\' Out My Back Door by Creedence Clearwater Revival',
  'Proud Mary by Creedence Clearwater Revival',
  'Run Through the Jungle by Creedence Clearwater Revival',
  'Suzie Q by Creedence Clearwater Revival',
  'Sweet Hitch Hiker by Creedence Clearwater Revival',
  'The Midnight Special by Creedence Clearwater Revival',
  'Travelin\' Band by Creedence Clearwater Revival',
  'Up Around the Bend by Creedence Clearwater Revival',
  'Who\'ll Stop the Rain by Creedence Clearwater Revival',
  'Fire Woman by Crosby, Stills & Nash',
  'Helplessly Hoping by Crosby, Stills & Nash',
  'Long Time Gone by Crosby, Stills & Nash',
  'Southern Cross by Crosby, Stills & Nash',
  'Suite: Judy Blue Eyes by Crosby, Stills & Nash',
  'Carry On by Crosby, Stills, Nash & Young',
  'Ohio by Crosby, Stills, Nash & Young',
  'Woodstock by Crosby, Stills, Nash & Young',
  '(I Just) Died in Your Arms by Cutting Crew',
  'High Enough by Damn Yankees',
  'I HEAR YOU KNOCKING by Dave Edmunds',
  'Headkeeper by Dave Mason',
  'Only You Know And I Know by Dave Mason',
  'We Just Disagree by Dave Mason',
  'Welcome To The Boomtown by David & David',
  'Changes by David Bowie',
  'China Girl by David Bowie',
  'Diamond Dogs by David Bowie',
  'Fame by David Bowie',
  'Fashion by David Bowie',
  'Friday on My Mind by David Bowie',
  'Golden Years by David Bowie',
  'Heroes by David Bowie',
  'Jean Genie by David Bowie',
  'Let\'s Dance by David Bowie',
  'Modern Love by David Bowie',
  'Panic in Detroit by David Bowie',
  'Rebel Rebel by David Bowie',
  'Space Oddity by David Bowie',
  'Starman by David Bowie',
  'Stay by David Bowie',
  'Suffragette City by David Bowie',
  'Young Americans by David Bowie',
  'Ziggy Stardust by David Bowie',
  'Rock On by David Essex',
  'There\'s No Way Out Of Here by David Essex',
  'There\'s No Way Out Of Here by David Gilmour',
  'Frenchette by David Johansen',
  'California Girls by David Lee Roth',
  'Just A Gigolo / I Ain\'t Got Nobody by David Lee Roth',
  'Yankee Rose by David Lee Roth',
  'Burn by Deep Purple',
  'Child In Time by Deep Purple',
  'Highway Star by Deep Purple',
  'Hush by Deep Purple',
  'Kentucky Woman by Deep Purple',
  'Knocking At Your Backdoo by Deep Purple',
  'Lazy by Deep Purple',
  'Perfect Strangers by Deep Purple',
  'Smoke On The Water by Deep Purple',
  'Space Truckin\' by Deep Purple',
  'Woman From Tokyo by Deep Purple',
  'Animal by Def Leppard',
  'Armageddon It by Def Leppard',
  'Bringin\' On The Heartbreak by Def Leppard',
  'Foolin\' by Def Leppard',
  'Hysteria by Def Leppard',
  'Love Bites by Def Leppard',
  'On Through The Night by Def Leppard',
  'Photograph by Def Leppard',
  'Pour Some Sugar On Me by Def Leppard',
  'Rock of Ages by Def Leppard',
  'Rock Rock by Def Leppard',
  'Rocket by Def Leppard',
  'Too Late for Love by Def Leppard',
  'Enjoy the Silence by Depeche Mode',
  'Bell Bottom Blues by Derek & The Dominos',
  'Have You Ever Loved a Woman by Derek & The Dominos',
  'Layla by Derek & The Dominos',
  'Recognition by Detective',
  'ANGELOS by Dick Siegel',
  'Holy Diver by Dio',
  'Rainbow In the Dark by Dio',
  'The Last In Line by Dio',
  'Brothers In Arms by Dire Straits',
  'Down To The Waterline by Dire Straits',
  'Expresso Love by Dire Straits',
  'Industrial Disease by Dire Straits',
  'Lady Writer by Dire Straits',
  'Money for Nothing by Dire Straits',
  'Romeo And Juliet by Dire Straits',
  'So Far Away by Dire Straits',
  'Solid Rock by Dire Straits',
  'Sultans of Swing by Dire Straits',
  'Walk of Life by Dire Straits',
  'Counting Blue Cars by Dishwalla',
  'Drift Away by Dobie Gray',
  'Alone Again by Dokken',
  'In My Dreams by Dokken',
  'Into The Fire by Dokken',
  'Heavy Metal by Don Felder',
  'All She Wants to Do Is Dance by Don Henley',
  'Dirty Laundry by Don Henley',
  'Sunset Grill by Don Henley',
  'The Boys Of Summer by Don Henley',
  'The Heart of the Matter by Don Henley',
  'The Last Worthless Evening by Don Henley',
  'American Pie by Don McLean',
  'Ah! Leah! by Donnie Iris',
  'Love Is Like A Rock by Donnie Iris',
  'Season of the Witch by Donovan',
  'Sunshine Superman by Donovan',
  'COVER OF THE ROLLING STONE by Dr. Hook & the Medicine Show',
  'Right Place Wrong Time by Dr. John',
  'Anything, Anything by Dramarama',
  'Hey, Hey (What Can I Do?) by Led Zeppelin',
  'Rio by Duran Duran',
  'Already Gone by Eagles',
  'Desperado by Eagles',
  'Heartache Tonight by Eagles',
  'Hotel California by Eagles',
  'I Can\'t Tell You Why by Eagles',
  'In The City by Eagles',
  'Life in the Fast Lane by Eagles',
  'Lyin\' Eyes by Eagles',
  'New Kid In Town by Eagles',
  'One of These Nights by Eagles',
  'Peaceful Easy Feeling by Eagles',
  'Seven Bridges Road by Eagles',
  'Take It Easy by Eagles',
  'Take It to the Limit by Eagles',
  'Tequila Sunrise by Eagles',
  'The Best of My Love by Eagles',
  'The Long Run by Eagles',
  'Those Shoes by Eagles',
  'Victim of Love by Eagles',
  'Witchy Woman by Eagles',
  'Baby Hold On by Eddie Money',
  'Gimme Some Water by Eddie Money',
  'Shakin\' by Eddie Money',
  'Take Me Home Tonight by Eddie Money',
  'Think I\'m In Love by Eddie Money',
  'Two Tickets To Paradise by Eddie Money',
  'Frankenstein by Edgar Winter Group',
  'Free Ride by Edgar Winter Group',
  'WAR by Edwin Starr',
  'CAN\'T GET IT OUT OF MY HEAD by Electric Light Orchestra',
  'Do Ya by Electric Light Orchestra',
  'Don\'t Bring Me Down by Electric Light Orchestra',
  'Evil Woman by Electric Light Orchestra',
  'Fire On High by Electric Light Orchestra',
  'Livin\' Thing by Electric Light Orchestra',
  'Roll Over Beethoven by Electric Light Orchestra',
  'Strange Magic by Electric Light Orchestra',
  'Sweet Talkin\' Woman by Electric Light Orchestra',
  'Telephone Line by Electric Light Orchestra',
  'Turn To Stone by Electric Light Orchestra',
  'All The Girls Love Alice by Elton John',
  'Bennie And The Jets by Elton John',
  'Candle in the Wind by Elton John',
  'Captain Fantastic by Elton John',
  'Crocodile Rock by Elton John',
  'DANIEL by Elton John',
  'Don\'t Let The Sun Go Down On Me by Elton John',
  'Funeral for a Friend (Love Lies Bleeding) by Elton John',
  'Goodbye Yellow Brick Road by Elton John',
  'Harmony by Elton John',
  'Honky Cat by Elton John',
  'Levon by Elton John',
  'Madman Across The Water by Elton John',
  'Rocket Man by Elton John',
  'Saturday Night\'s Alright for Fighting by Elton John',
  'Someone Saved My Life Tonight by Elton John',
  'Take Me to the Pilot by Elton John',
  'Teacher I Need You by Elton John',
  'THE BITCH IS BACK by Elton John',
  'Tiny Dancer by Elton John',
  'Where To Now St. Peter by Elton John',
  'Your Song by Elton John',
  'Fooled around and Fell in Love by Elvin Bishop',
  'Alison by Elvis Costello',
  'Pump It Up by Elvis Costello',
  'Veronica by Elvis Costello',
  'From the Beginning by Emerson, Lake & Palmer',
  'Hoedown by Emerson, Lake & Palmer',
  'Karn Evil 9 by Emerson, Lake & Palmer',
  'Lucky Man by Emerson, Lake & Palmer',
  'Still You Turn Me On by Emerson, Lake & Palmer',
  'After Midnight by Eric Clapton',
  'Bad Love by Eric Clapton',
  'Call Me the Breeze by Eric Clapton',
  'Cocaine by Eric Clapton',
  'Don\'t Think Twice, It\'s Alright by Eric Clapton',
  'Forever Man by Eric Clapton',
  'I Can\'t Stand It by Eric Clapton',
  'I Shot The Sheriff by Eric Clapton',
  'I\'ve Got a Rock \'N\' Roll Heart by Eric Clapton',
  'It\'s In The Way That You Use It by Eric Clapton',
  'Knockin\' On Heaven\'s Door by Eric Clapton',
  'Lay Down Sally by Eric Clapton',
  'Layla by Eric Clapton',
  'Let It Grow by Eric Clapton',
  'Let It Rain by Eric Clapton',
  'Pretending by Eric Clapton',
  'She\'s Waiting by Eric Clapton',
  'Tears In Heaven by Eric Clapton',
  'The Core by Eric Clapton',
  'Willie and the Hand Jive by Eric Clapton',
  'Wonderful Tonight by Eric Clapton',
  'Cliffs Of Dover by Eric Johnson',
  'The Final Countdown by Europe',
  'Sweet Dreams (Are Made of This) by Eurythmics',
  'Inside Out by Eve 6',
  'Santa Monica by Everclear',
  'The Boys Are Back In Town by Everclear',
  'What It\'s Like by Everlast',
  'More Than Words by Extreme',
  'Mutha (Don\'t Wanna Go To School Today) by Extreme',
  'Ooh La La by Faces',
  'Stay With Me by Faces',
  'Epic by Faith No More',
  'House Of Pain by Faster Pussycat',
  'All The Kings Horses by Firm',
  'Signs by Five Man Electrical Band',
  'Blue Letter by Fleetwood Mac',
  'Don\'t Stop by Fleetwood Mac',
  'Dreams by Fleetwood Mac',
  'Go Your Own Way by Fleetwood Mac',
  'Gold Dust Woman by Fleetwood Mac',
  'Gypsy by Fleetwood Mac',
  'Hold Me by Fleetwood Mac',
  'Hypnotized by Fleetwood Mac',
  'I Don\'t Want To Know by Fleetwood Mac',
  'I\'m So Afraid by Fleetwood Mac',
  'Landslide by Fleetwood Mac',
  'Little Lies by Fleetwood Mac',
  'Monday Morning by Fleetwood Mac',
  'Never Going Back Again by Fleetwood Mac',
  'Oh Well by Fleetwood Mac',
  'Rhiannon by Fleetwood Mac',
  'Sara by Fleetwood Mac',
  'Say You Love Me by Fleetwood Mac',
  'Second Hand News by Fleetwood Mac',
  'Sentimental Lady by Fleetwood Mac',
  'The Chain by Fleetwood Mac',
  'Tusk by Fleetwood Mac',
  'World Turning by Fleetwood Mac',
  'You Make Loving Fun by Fleetwood Mac',
  'Hocus Pocus by Focus',
  'Dreamer by Foghat',
  'Fool For The City by Foghat',
  'I Just Want To Make Love To You by Foghat',
  'Slow Ride by Foghat',
  'All My Life by Foo Fighters',
  'Baker Street by Foo Fighters',
  'Best of You by Foo Fighters',
  'Everlong by Foo Fighters',
  'Learn To Fly by Foo Fighters',
  'Monkey Wrench by Foo Fighters',
  'My Hero by Foo Fighters',
  'The Pretender by Foo Fighters',
  'These Days by Foo Fighters',
  'Times Like These by Foo Fighters',
  'Blue Morning, Blue Day by Foreigner',
  'Cold As Ice by Foreigner',
  'Dirty White Boy by Foreigner',
  'Double Vision by Foreigner',
  'Feels Like the First Time by Foreigner',
  'Head Games by Foreigner',
  'Hot Blooded by Foreigner',
  'I Want to Know What Love Is by Foreigner',
  'Juke Box Hero by Foreigner',
  'Long, Long Way From Home by Foreigner',
  'Love Has Taken Its Toll by Foreigner',
  'Starrider by Foreigner',
  'That Was Yesterday by Foreigner',
  'Urgent by Foreigner',
  'Waiting for a Girl Like You by Foreigner',
  'Women by Foreigner',
  'Joe\'s Garage by Frank Zappa',
  'Peaches En Regalia by Frank Zappa',
  'All Right Now by Free',
  'Hemorrhage by Free',
  'Wishing Well by Free',
  'Maggot Brain by Funkadelic',
  'CARS by Gary Numan',
  'Dream Weaver by Gary Wright',
  'Love Is Alive by Gary Wright',
  'A Trick of the Tail by Genesis',
  'Abacab by Genesis',
  'Behind The Lines by Genesis',
  'Carpet Crawlers by Genesis',
  'Follow You Follow Me by Genesis',
  'Home by the Sea/Second Home by the Sea by Genesis',
  'Just A Job To Do by Genesis',
  'Land Of Confusion by Genesis',
  'Mama by Genesis',
  'Man On The Corner by Genesis',
  'Misunderstanding by Genesis',
  'No Reply At All by Genesis',
  'That\'s All by Genesis',
  'The Lamb Lies Down On Broadway by Genesis',
  'Tonight Tonight (live) by Genesis',
  'Turn It On Again by Genesis',
  'Give Me Love by George Harrison',
  'GOT MY MIND SET ON YOU by George Harrison',
  'My Sweet Lord by George Harrison',
  'Bad to the Bone by George Thorogood',
  'Delaware Slide by George Thorogood',
  'Get A Haircut by George Thorogood',
  'I Drink Alone by George Thorogood',
  'It Wasn\'t Me by George Thorogood',
  'Move It On Over by George Thorogood',
  'One Bourbon, One Scotch, One Beer by George Thorogood',
  'Who Do You Love by George Thorogood',
  'Keep Your Hands To Yourself by Georgia Satellites',
  'Baker Street by Gerry Rafferty',
  'Right Down the Line by Gerry Rafferty',
  'Found Out About You by Gin Blossoms',
  'Hey Jealousy by Gin Blossoms',
  'Smuggler\'s Blues by Glenn Frey',
  'You Belong to the City by Glenn Frey',
  'Marakesh Express by Gold Star Ballroom Orchestra',
  'Are You Receiving Me by Golden Earring',
  'Radar Love by Golden Earring',
  'Twilight Zone by Golden Earring',
  'Sundown by Gordon Lightfoot',
  'Soulshine by Gov\'t Mule',
  'Bad Time by Grand Funk Railroad',
  'Closer To Home (I\'m Your Captain) by Grand Funk Railroad',
  'Loco-Motion by Grand Funk Railroad',
  'Shinin\' On by Grand Funk Railroad',
  'Some Kind of Wonderful by Grand Funk Railroad',
  'We\'re an American Band by Grand Funk Railroad',
  'Alabama Getaway by Grateful Dead',
  'Black-Throated Wind by Grateful Dead',
  'Casey Jones by Grateful Dead',
  'CHINA TOWN SHUFFLE  by Grateful Dead',
  'Friend Of The Devil by Grateful Dead',
  'Hell in a Bucket by Grateful Dead',
  'Loser by Grateful Dead',
  'Me and Bobby McGee by Grateful Dead',
  'NOT FADEAWAY/GOING /AWAY by Grateful Dead',
  'Scarlet Begonias by Grateful Dead',
  'Shakedown Street by Grateful Dead',
  'Sugar Magnolia by Grateful Dead',
  'Touch of Grey by Grateful Dead',
  'Truckin\' by Grateful Dead',
  'Turn On Your Lovelight by Grateful Dead',
  'U.S. Blues by Grateful Dead',
  'Uncle John\'s Band by Grateful Dead',
  'Mista Bone by Great White',
  'Once Bitten, Twice Shy by Great White',
  'Rock Me by Great White',
  'Rollin\' Stoned by Great White',
  'Save Your Love by Great White',
  'Basket Case by Green Day',
  'Boulevard Of Broken Dreams by Green Day',
  'Brain Stew/Jaded by Green Day',
  'Good Riddance (Time Of Your Life) by Green Day',
  'Holiday (Live) by Green Day',
  'Holiday / Boulevard of Broken Dreams by Green Day',
  'Longview by Green Day',
  'When I Come Around by Green Day',
  'The Break Up Song by Greg Kihn Band',
  'I\'m No Angel by Gregg Allman',
  'Midnight Rider by Gregg Allman',
  'American Woman by Guess Who',
  'Friends Of Mine by Guess Who',
  'No Sugar Tonight / New Mother Nature by Guess Who',
  'No Time by Guess Who',
  'THESE EYES by Guess Who',
  'Civil War by Guns N\' Roses',
  'Don\'t Cry by Guns N\' Roses',
  'Knockin\' On Heaven\'s Door by Guns N\' Roses',
  'Live and Let Die by Guns N\' Roses',
  'Mr. Brownstone by Guns N\' Roses',
  'My Michelle by Guns N\' Roses',
  'November Rain by Guns N\' Roses',
  'Paradise City by Guns N\' Roses',
  'Patience by Guns N\' Roses',
  'Sweet Child O\' Mine by Guns N\' Roses',
  'Used To Love Her by Guns N\' Roses',
  'Welcome to the Jungle by Guns N\' Roses',
  'You Could Be Mine by Guns N\' Roses',
  'AS FAR AS YOU CAN SEE (AS MU by Gypsy',
  'Axel F Theme by Harold Faltermeyer',
  'Cat\'s In The Cradle by Harry Chapin',
  'W*O*L*D* by Harry Chapin',
  'Jump into the Fire by Harry Nilsson',
  'Never Been Any Reason by Head East',
  'All I Wanna Do Is Make Love to You by Heart',
  'Alone by Heart',
  'Barracuda by Heart',
  'Bebe le Strange by Heart',
  'Crazy On You by Heart',
  'Dog & Butterfly by Heart',
  'Dreamboat Annie by Heart',
  'Even It Up by Heart',
  'Heartless by Heart',
  'How Can I Refuse by Heart',
  'If Looks Could Kill by Heart',
  'Kick It Out by Heart',
  'Little Queen by Heart',
  'Love Alive by Heart',
  'Magic Man by Heart',
  'Mistral Wind by Heart',
  'Never by Heart',
  'Nothin\' at All by Heart',
  'Rock And Roll by Heart',
  'Stairway To Heaven by Heart',
  'Straight On by Heart',
  'Tell It Like It Is by Heart',
  'What About Love? by Heart',
  'Who Will You Run To by Heart',
  'House Of Living by Heartsfield',
  'Sangre Por Sangre by HellYeah',
  'Grey Ghost by Henry Paul Band',
  'Long Cool Woman by Hollies',
  'New Girl Now by Honeymoon Suite',
  'ALL YOU ZOMBIES by Hooters',
  'AND WE DANCED by Hooters',
  'I Want A New Drug by Huey Lewis & The News',
  '30 Days In the Hole by Humble Pie',
  'Lust for Life by Iggy Pop',
  'The Passenger by Iggy Pop',
  'Radioactive by Imagine Dragons',
  'Devil Inside by INXS',
  'Need You Tonight by INXS',
  'New Sensation by INXS',
  'What You Need by INXS',
  'In A Gadda Da Vida by Iron Butterfly',
  'Flight Of Icarus by Iron Maiden',
  'Run To The Hills by Iron Maiden',
  'The Number Of The Beast by Iron Maiden',
  'The Trooper by Iron Maiden',
  'Wasted Years by Iron Maiden',
  'Centerfold by J. Geils Band',
  'Freeze-frame by J. Geils Band',
  'Give It To Me by J. Geils Band',
  'Houseparty by J. Geils Band',
  'Looking For A Love by J. Geils Band',
  'Love Stinks by J. Geils Band',
  'Must of Got Lost by J. Geils Band',
  'Night Time by J. Geils Band',
  'Whammer Jammer by J. Geils Band',
  'Boulevard by Jackson Browne',
  'Doctor My Eyes by Jackson Browne',
  'Load Out/Stay by Jackson Browne',
  'Redneck Friend by Jackson Browne',
  'Running On Empty by Jackson Browne',
  'Somebody\'s Baby by Jackson Browne',
  'Take It Easy by Jackson Browne',
  'The Load-out/stay by Jackson Browne',
  'The Road and the Sky by Jackson Browne',
  'Funk #49 by James Gang',
  'Walk Away by James Gang',
  'YOU\'VE GOT A FRIEND by JAMES TAYLOR',
  'Been Caught Stealing by Jane\'s Addiction',
  'Jane Says by Jane\'s Addiction',
  'Get It While You Can by Janis Joplin',
  'Me and Bobby McGee by Janis Joplin',
  'Move Over by Janis Joplin',
  'Piece of My Heart by Janis Joplin',
  'Summertime by Janis Joplin',
  'Shakedown Cruise by Jay Ferguson',
  'Thunder Island by Jay Ferguson',
  'Freeway Jam by Jeff Beck',
  'Rice Pudding by Jeff Beck',
  'Somebody to Love by Jefferson Airplane',
  'White Rabbit by Jefferson Airplane',
  'Find Your Way Back by Jefferson Starship',
  'Jane by Jefferson Starship',
  'Ride the Tiger by Jefferson Starship',
  'We Built This City by Jefferson Starship',
  'Right Here Right Now by Jesus Jones',
  'Are You Gonna Be My Girl by Jet',
  'Cold Hard Bitch by Jet',
  'Aqualung by Jethro Tull',
  'Bungle In The Jungle by Jethro Tull',
  'Cross-eyed Mary by Jethro Tull',
  'Hymn 43 by Jethro Tull',
  'Living In The Past by Jethro Tull',
  'Locomotive Breath by Jethro Tull',
  'Nothing Is Easy by Jethro Tull',
  'Teacher by Jethro Tull',
  'Thick As A Brick by Jethro Tull',
  'Too Old To Rock \'n\' Roll by Jethro Tull',
  'TIME IN A BOTTLE by Jim Croce',
  'All Along the Watchtower by Jimi Hendrix',
  'Angel by Jimi Hendrix',
  'Are You Experienced? by Jimi Hendrix',
  'Crosstown Traffic by Jimi Hendrix',
  'Dolly Dagger by Jimi Hendrix',
  'Fire by Jimi Hendrix',
  'Foxey Lady by Jimi Hendrix',
  'Hey Joe by Jimi Hendrix',
  'If 6 Was 9 by Jimi Hendrix',
  'Like a Rolling Stone by Jimi Hendrix',
  'Little Wing by Jimi Hendrix',
  'Manic Depression by Jimi Hendrix',
  'Purple Haze by Jimi Hendrix',
  'Red House by Jimi Hendrix',
  'Stone Free by Jimi Hendrix',
  'The Wind Cries Mary by Jimi Hendrix',
  'Third Stone From The Sun by Jimi Hendrix',
  'Voodoo Child (Slight Return) by Jimi Hendrix',
  'Margaritaville by Jimmy Buffett',
  'Son of a Son of a Sailor by Jimmy Buffett',
  'Why Don\'t We Get Drunk by Jimmy Buffett',
  'Bad Reputation by Joan Jett',
  'Crimson And Clover by Joan Jett',
  'I Hate Myself For Loving You by Joan Jett',
  'I Love Rock \'n Roll by Joan Jett',
  'Cry Me a River by Joe Cocker',
  'Feelin\' Alright by Joe Cocker',
  'The Letter by Joe Cocker',
  'With A Little Help From My Friends by Joe Cocker',
  'You Can Leave Your Hat On (Live) by Joe Cocker',
  'Is She Really Going Out With Him? by Joe Jackson',
  'Always With Me, Always With You by Joe Satriani',
  'Summer Song by Joe Satriani',
  'A Life Of Illusion by Joe Walsh',
  'All Night Long by Joe Walsh',
  'Analog Man by Joe Walsh',
  'Funk #49 by Joe Walsh',
  'In the City by Joe Walsh',
  'Life\'s Been Good by Joe Walsh',
  'Ordinary Average Guy by Joe Walsh',
  'Rocky Mountain Way by Joe Walsh',
  'The Confessor by Joe Walsh',
  'Turn To Stone by Joe Walsh',
  'On the Dark Side by John Cafferty',
  'Centerfield by John Fogerty',
  'The Old Man Down The Road by John Fogerty',
  '#9 Dream by John Lennon',
  'Imagine by John Lennon',
  'Instant Karma by John Lennon',
  'Mind Games by John Lennon',
  'Watching the Wheels by John Lennon',
  'Woman by John Lennon',
  'Again Tonight by John Mellencamp',
  'Ain\'t Even Done With the Night by John Mellencamp',
  'Authority Song by John Mellencamp',
  'Check It Out by John Mellencamp',
  'Cherry Bomb by John Mellencamp',
  'Crumblin\' Down by John Mellencamp',
  'Hurts So Good by John Mellencamp',
  'I Need A Lover by John Mellencamp',
  'Jack & Diane by John Mellencamp',
  'Lonely Ol\' Night by John Mellencamp',
  'Paper in Fire by John Mellencamp',
  'Pink Houses by John Mellencamp',
  'R.O.C.K. In the U.S.A. by John Mellencamp',
  'Rain On The Scarecrow by John Mellencamp',
  'Small Town by John Mellencamp',
  'What If I Came Knocking by John Mellencamp',
  'Illegal Smile by John Prine',
  'I CAN SEE CLEARLY NOW by Johnny Nash',
  'Brickyard Road by Johnny Van Zant',
  'Shanty by Jonathan Edwards',
  'Roadrunner by Jonathan Richman',
  'Any Way You Want It by Journey',
  'City of the Angels by Journey',
  'Don\'t Stop Believin\' by Journey',
  'Escape by Journey',
  'Faithfully by Journey',
  'Feeling That Way by Journey',
  'Just the Same Way by Journey',
  'Lights by Journey',
  'Look Into The Future by Journey',
  'Lovin\', Touchin\' Squeezin\' by Journey',
  'Only the Young by Journey',
  'Open Arms by Journey',
  'Send Her My Love by Journey',
  'Separate Ways (Worlds Apart) by Journey',
  'Stone In Love by Journey',
  'Wheel in the Sky by Journey',
  'Who\'s Crying Now by Journey',
  'Breaking The Law by Judas Priest',
  'Diamonds And Rust by Judas Priest',
  'Electric Eye by Judas Priest',
  'Heading Out To The Highway by Judas Priest',
  'Hot Rockin\' by Judas Priest',
  'Living After Midnight by Judas Priest',
  'The Ripper by Judas Priest',
  'Turbo Lover by Judas Priest',
  'You\'ve Got Another Thing Comin\' by Judas Priest',
  'Simple Man by Junkyard',
  'Carry On Wayward Son by Kansas',
  'Dust In The Wind by Kansas',
  'Play the Game Tonight by Kansas',
  'Point of Know Return by Kansas',
  'I\'m Alright by Kenny Loggins',
  'Just Dropped In by Kenny Loggins',
  'Blue On Black by Kenny Wayne Shepherd',
  'Somehow, Somewhere, Someway by Kenny Wayne Shepherd',
  'All Summer Long by Kid Rock',
  'Cowboy by Kid Rock',
  'Let\'s Ride by Kid Rock',
  'If I Say by Kingofthehill',
  'Sex On Fire by Kings of Leon',
  'Use Somebody by Kings of Leon',
  'Beth by Kiss',
  'Calling Dr. Love by Kiss',
  'Christeen Sixteen by Kiss',
  'Cold Gin by Kiss',
  'Detroit Rock City by Kiss',
  'Heaven\'s On Fire by Kiss',
  'Lick It Up by Kiss',
  'Rock And Roll All Nite by Kiss',
  'Shout It out Loud by Kiss',
  'Strutter by Kiss',
  'Tears Are Falling by Kiss',
  'Long Stick Goes Boom by Krokus',
  'Screaming In The Night by Krokus',
  'Stayed Awake All Night by Krokus',
  'Sex Action by L.A. Guns',
  'Key To The Rhyme by Lake',
  'All My Love by Led Zeppelin',
  'Babe I\'m Gonna Leave You by Led Zeppelin',
  'Black Dog by Led Zeppelin',
  'Black Mountain Side by Led Zeppelin',
  'Bonzo\'s Montreaux by Led Zeppelin',
  'Boogie With Stu by Led Zeppelin',
  'Bring It On Home by Led Zeppelin',
  'Bron-y-aur Stomp by Led Zeppelin',
  'Celebration Day by Led Zeppelin',
  'Communication Breakdown by Led Zeppelin',
  'Custard Pie by Led Zeppelin',
  'D\'Yer Mak\'er by Led Zeppelin',
  'Dancing Days by Led Zeppelin',
  'Darlene by Led Zeppelin',
  'Dazed and Confused by Led Zeppelin',
  'Down By The Seaside by Led Zeppelin',
  'Fool In the Rain by Led Zeppelin',
  'For Your Life by Led Zeppelin',
  'Four Sticks by Led Zeppelin',
  'Friends by Led Zeppelin',
  'Gallows Pole by Led Zeppelin',
  'Going to California by Led Zeppelin',
  'Good Times Bad Times by Led Zeppelin',
  'Hats Off To {roy} Harper by Led Zeppelin',
  'Heartbreaker/living Loving Maid {she\'s Just A Woman} by Led Zeppelin',
  'Hey Hey What Can I Do by Led Zeppelin',
  'Hot Dog by Led Zeppelin',
  'Houses of the Holy by Led Zeppelin',
  'How Many More Times by Led Zeppelin',
  'I Can\'t Quit You Baby by Led Zeppelin',
  'Immigrant Song by Led Zeppelin',
  'In My Time of Dying by Led Zeppelin',
  'In the Evening by Led Zeppelin',
  'In the Light by Led Zeppelin',
  'Kashmir by Led Zeppelin',
  'Living Loving Maid (She\'s Just a Woman) by Led Zeppelin',
  'Misty Mountain Hop by Led Zeppelin',
  'Moby Dick by Led Zeppelin',
  'NIGHT FLIGHT by Led Zeppelin',
  'No Quarter by Led Zeppelin',
  'Nobody\'s Fault But Mine by Led Zeppelin',
  'Out On The Tiles by Led Zeppelin',
  'Over the Hills and Far Away by Led Zeppelin',
  'Ramble On by Led Zeppelin',
  'Rock and Roll by Led Zeppelin',
  'Royal Orleans by Led Zeppelin',
  'Since I\'ve Been Loving You by Led Zeppelin',
  'South Bound Saurez by Led Zeppelin',
  'Stairway to Heaven by Led Zeppelin',
  'TANGERINE by Led Zeppelin',
  'Ten Years Gone by Led Zeppelin',
  'Thank You by Led Zeppelin',
  'That\'s the Way by Led Zeppelin',
  'The Battle Of Evermore by Led Zeppelin',
  'The Crunge by Led Zeppelin',
  'The Lemon Song by Led Zeppelin',
  'The Ocean by Led Zeppelin',
  'The Rain Song by Led Zeppelin',
  'The Rover by Led Zeppelin',
  'The Song Remains the Same by Led Zeppelin',
  'THE WANTON SONG by Led Zeppelin',
  'Trampled Under Foot by Led Zeppelin',
  'Traveling Riverside Blues by Led Zeppelin',
  'What Is and What Should Never Be by Led Zeppelin',
  'When The Levee Breaks by Led Zeppelin',
  'Whole Lotta Love by Led Zeppelin',
  'You Shook Me by Led Zeppelin',
  'Your Time Is Gonna Come by Led Zeppelin',
  'Do You Know What I Mean by Lee Michaels',
  'Woman by Legs Diamond',
  'American Woman by Lenny Kravitz',
  'Are You Gonna Go My Way by Lenny Kravitz',
  'Fly Away by Lenny Kravitz',
  'Stranger In A Strange Land by Leon Russell',
  'My Own Worst Enemy by Lit',
  'Close My Eyes Forever by Lita Ford',
  'Kiss Me Deadly by Lita Ford',
  'All That You Dream by Little Feat',
  'Dixie Chicken by Little Feat',
  'I Alone by Live',
  'Lightning Crashes by Live',
  'Cult Of Personality by Living Colour',
  'Bound for the Floor by Local H',
  'Conquistador by London Symphony Orchestra',
  'Midnight Blue by Lou Gramm',
  'Sweet Jane (Live) by Lou Reed',
  'Walk On The Wild Side by Lou Reed',
  'Lovin\' Every Minute of It by Loverboy',
  'The Kid Is Hot Tonite by Loverboy',
  'Turn Me Loose by Loverboy',
  'Working for the Weekend by Loverboy',
  'Wicked Sensation by Lynch Mob',
  'Call Me the Breeze by Lynyrd Skynyrd',
  'Dixie/Sweet Home Alabama by Lynyrd Skynyrd',
  'Don\'t Ask Me No Questions by Lynyrd Skynyrd',
  'Free Bird by Lynyrd Skynyrd',
  'Gimme Back My Bullets by Lynyrd Skynyrd',
  'Gimme Three Steps by Lynyrd Skynyrd',
  'I Know a Little by Lynyrd Skynyrd',
  'Saturday Night Special by Lynyrd Skynyrd',
  'Simple Man by Lynyrd Skynyrd',
  'Sweet Home Alabama by Lynyrd Skynyrd',
  'That Smell by Lynyrd Skynyrd',
  'The Ballad Of Curtis Loew by Lynyrd Skynyrd',
  'Tuesday\'s Gone by Lynyrd Skynyrd',
  'What\'s Your Name by Lynyrd Skynyrd',
  'You Got That Right by Lynyrd Skynyrd',
  'Merry-Go-Round by Mama\'s Pride',
  'Blinded by the Light by Manfred Mann',
  'Do Wah Diddy Diddy by Manfred Mann',
  'Sex and Candy by Marcy Playground',
  'Paradise By The Dashboard Light by Meat Loaf',
  'TWO OUT OF THREE AIN\'T BAD by Meat Loaf',
  'You Took The Words Right Out Of My Mouth by Meat Loaf',
  'I\'m the Only One by Melissa Etheridge',
  'Down Under by Men At Work',
  'Who Can It Be Now? by Men At Work',
  'Breadfan by Metallica',
  'Enter Sandman by Metallica',
  'Fade To Black by Metallica',
  'For Whom The Bell Tolls by Metallica',
  'Fuel by Metallica',
  'Harvester Of Sorrow by Metallica',
  'Hero of the Day by Metallica',
  'Lords of Summer (First Pass Version) by Metallica',
  'Master of Puppets by Metallica',
  'No Leaf Clover by Metallica',
  'Nothing Else Matters by Metallica',
  'One by Metallica',
  'Sad But True by Metallica',
  'Seek & Destroy by Metallica',
  'The Memory Remains by Metallica',
  'The Unforgiven by Metallica',
  'Turn The Page by Metallica',
  'Until It Sleeps by Metallica',
  'Wherever I May Roam by Metallica',
  'Whiskey In The Jar by Metallica',
  'Cruisin\' by Michael Nesmith',
  'Drinkin\' in the Driveway by Michael Stanley',
  'He Can\'t Love You by Michael Stanley',
  'Let\'s Get the Show on the Road by Michael Stanley',
  'My Town by Michael Stanley',
  'Rosewood Bitters by Michael Stanley',
  'Strike up the Band by Michael Stanley',
  'Beds Are Burning by Midnight Oil',
  'Devil With the Blue Dress On by Mitch Ryder',
  'I Melt With You by Modern English',
  'Sugar Boogie by Molkie Cole',
  'Dreams I\'ll Never See by Molly Hatchet',
  'Flirtin\' With Disaster by Molly Hatchet',
  'What Do All The People Know by Monroes',
  'Bad Motor Scooter by Montrose',
  'Rock Candy by Montrose',
  'Space Station #5 by Montrose',
  'Don\'t Go Away Mad (Just Go Away) by Motley Crue',
  'Dr. Feelgood by Motley Crue',
  'Girls, Girls, Girls by Motley Crue',
  'Home Sweet Home by Motley Crue',
  'Kickstart My Heart by Motley Crue',
  'Looks That Kill by Motley Crue',
  'Piece of Your Action by Motley Crue',
  'Same Ol\' Situation by Motley Crue',
  'Shout at the Devil by Motley Crue',
  'Smokin\' in the Boys Room by Motley Crue',
  'Wild Side by Motley Crue',
  'All the Young Dudes by Mott the Hoople',
  'Mississippi Queen by Mountain',
  'Moon Rider by Moxy',
  'Addicted To That Rush by Mr. Big',
  'In the Summertime by Mungo Jerry',
  'Hair Of The Dog by Nazareth',
  'Love Hurts by Nazareth',
  'Cinnamon Girl by Neil Young',
  'Down by the River by Neil Young',
  'Everybody Knows This Is Nowhere by Neil Young',
  'Heart of Gold by Neil Young',
  'Hey Hey, My My by Neil Young',
  'Like a Hurricane by Neil Young',
  'My My, Hey Hey by Neil Young',
  'Old Man by Neil Young',
  'Powderfinger by Neil Young',
  'Rockin\' In the Free World by Neil Young',
  'Southern Man by Neil Young',
  'Sugar Mountain by Neil Young',
  'The Needle and the Damage Done by Neil Young',
  'When You Dance I Can Really Love by Neil Young',
  'Show Me The Way by Nektar',
  'How You Remind Me by Nickelback',
  'Photograph by Nickelback',
  'Rockstar by Nickelback',
  'Someday (Single Mix) by Nickelback',
  '(You Can Still) Rock in America by Night Ranger',
  'Don\'t Tell Me You Love Me by Night Ranger',
  'Rumors In The Air by Night Ranger',
  'Sister Christian by Night Ranger',
  'When You Close Your Eyes by Night Ranger',
  'About a Girl by Nirvana',
  'All Apologies by Nirvana',
  'Come As You Are by Nirvana',
  'Dumb by Nirvana',
  'In Bloom by Nirvana',
  'Lithium by Nirvana',
  'On a Plain by Nirvana',
  'Polly by Nirvana',
  'Smells Like Teen Spirit by Nirvana',
  'The Man Who Sold the World by Nirvana',
  'Spirit In The Sky by Norman Greenbaum',
  'This Is The Time by Nothing More',
  'Wonderwall by Oasis',
  'STILL THE ONE by Orleans',
  '(Sittin\' On) The Dock of the Bay by Otis Redding',
  'If You Wanna Get to Heaven by Ozark Mountain Daredevils',
  'Jackie Blue by Ozark Mountain Daredevils',
  'Bark At The Moon by Ozzy Osbourne',
  'Changes by Ozzy Osbourne',
  'Crazy Train by Ozzy Osbourne',
  'Diary Of A Madman by Ozzy Osbourne',
  'Flying High Again by Ozzy Osbourne',
  'Goodbye To Romance by Ozzy Osbourne',
  'I Don\'t Know by Ozzy Osbourne',
  'Mama, I\'m Coming Home by Ozzy Osbourne',
  'Mr. Crowley by Ozzy Osbourne',
  'Mr. Tinkertrain by Ozzy Osbourne',
  'No More Tears by Ozzy Osbourne',
  'Over the Mountain by Ozzy Osbourne',
  'Perry Mason by Ozzy Osbourne',
  'Purple Haze by Ozzy Osbourne',
  'Road To Nowhere by Ozzy Osbourne',
  'Rocky Mountain Way by Ozzy Osbourne',
  'See You on the Other Side by Ozzy Osbourne',
  'Shot in the Dark by Ozzy Osbourne',
  'Time After Time by Ozzy Osbourne',
  'Fire and Ice by Pat Benatar',
  'Heartbreaker by Pat Benatar',
  'Hell Is for Children by Pat Benatar',
  'Hit Me With Your Best Shot by Pat Benatar',
  'Invincible by Pat Benatar',
  'Love Is A Battlefield by Pat Benatar',
  'Shadows Of The Night by Pat Benatar',
  'Treat Me Right by Pat Benatar',
  'We Belong by Pat Benatar',
  'You Better Run by Pat Benatar',
  'Boom Boom/ by Pat Travers',
  'Snortin Whiskey by Pat Travers',
  'The Back Seat Of My Car by Paul McCartney & Linda McCartney',
  'Too Many People by Paul McCartney & Linda McCartney',
  'Uncle Albert/Admiral Halsey by Paul McCartney & Linda McCartney',
  'Another Day by Paul McCartney & Wings',
  'Band on the Run by Paul McCartney & Wings',
  'Birthday (Live) by Paul McCartney & Wings',
  'Coming Up by Paul McCartney & Wings',
  'Day Tripper by Paul McCartney & Wings',
  'Helen Wheels by Paul McCartney & Wings',
  'Hello Goodbye by Paul McCartney & Wings',
  'Helter Skelter by Paul McCartney & Wings',
  'Hey Jude (Live) by Paul McCartney & Wings',
  'Hi Hi Hi by Paul McCartney & Wings',
  'Jet by Paul McCartney & Wings',
  'Junior\'s Farm by Paul McCartney & Wings',
  'Let \'Em In by Paul McCartney & Wings',
  'Let Me Roll It by Paul McCartney & Wings',
  'Listen To What The Man Says by Paul McCartney & Wings',
  'Live and Let Die by Paul McCartney & Wings',
  'Maybe I\'m Amazed by Paul McCartney & Wings',
  'My Love by Paul McCartney & Wings',
  'Nineteen Hundred and Eighty Five by Paul McCartney & Wings',
  'Silly Love Songs by Paul McCartney & Wings',
  'Uncle Albert/Admiral Halsey by Paul McCartney & Wings',
  'Venus and Mars/Rock Show by Paul McCartney & Wings',
  'With a Little Luck by Paul McCartney & Wings',
  '50 Ways to Leave Your Lover by Paul Simon',
  'Kodachrome by Paul Simon',
  'Loves Me Like a Rock by Paul Simon',
  'Me And Julio Down By The Schoolyard by Paul Simon',
  'You Can Call Me Al by Paul Simon',
  'Alive by Pearl Jam',
  'Better Man by Pearl Jam',
  'Black by Pearl Jam',
  'Daughter by Pearl Jam',
  'Dissident by Pearl Jam',
  'Elderly Woman Behind the Counter in a Small Town by Pearl Jam',
  'Even Flow by Pearl Jam',
  'Jeremy by Pearl Jam',
  'Last Kiss by Pearl Jam',
  'Lightning Bolt by Pearl Jam',
  'Not for You by Pearl Jam',
  'Sirens by Pearl Jam',
  'Yellow Ledbetter by Pearl Jam',
  'GONNA GET YA by Pete Townshend',
  'Let My Love Open the Door by Pete Townshend',
  'Rough Boys by Pete Townshend',
  'Baby, I Love Your Way by Peter Frampton',
  'Do You Feel Like We Do by Peter Frampton',
  'Show Me the Way by Peter Frampton',
  'Something\'s Happening/ by Peter Frampton',
  'Big Time by Peter Gabriel',
  'Games Without Frontiers by Peter Gabriel',
  'In Your Eyes by Peter Gabriel',
  'Red Rain by Peter Gabriel',
  'SHOCK THE MONKEY by Peter Gabriel',
  'Sledgehammer by Peter Gabriel',
  'Solsbury Hill by Peter Gabriel',
  'Don\'t Lose My Number by Phil Collins',
  'I Don\'t Care Anymore by Phil Collins',
  'In the Air Tonight by Phil Collins',
  'Another Brick In The Wall by Pink Floyd',
  'Another Brick in the Wall, Pt. 2 by Pink Floyd',
  'Any Colour You Like by Pink Floyd',
  'Arnold Layne by Pink Floyd',
  'Astronomy Domine by Pink Floyd',
  'Brain Damage by Pink Floyd',
  'Brain Damage /Eclipse by Pink Floyd',
  'Breathe by Pink Floyd',
  'Careful With That Axe, Eugene by Pink Floyd',
  'Comfortably Numb by Pink Floyd',
  'Dogs by Pink Floyd',
  'Empty Spaces by Pink Floyd',
  'Empty Spaces/young Lust by Pink Floyd',
  'Fearless by Pink Floyd',
  'Goodbye Blue Sky by Pink Floyd',
  'Have a Cigar by Pink Floyd',
  'Hey You by Pink Floyd',
  'Keep Talking by Pink Floyd',
  'Learning to Fly by Pink Floyd',
  'Money by Pink Floyd',
  'Mother by Pink Floyd',
  'On The Turning Away by Pink Floyd',
  'One Of These Days by Pink Floyd',
  'One Slip by Pink Floyd',
  'Run Like Hell by Pink Floyd',
  'See Emily Play by Pink Floyd',
  'Set The Controls For The Heart Of The Sun by Pink Floyd',
  'Shine On You Crazy Diamond by Pink Floyd',
  'Speak to Me/Breathe by Pink Floyd',
  'Take It Back by Pink Floyd',
  'The Dogs Of War by Pink Floyd',
  'The Great Gig In the Sky by Pink Floyd',
  'The Happiest Days Of Our Lives/another Brick In The Wall by Pink Floyd',
  'Time by Pink Floyd',
  'Time/Gig in The Sky by Pink Floyd',
  'Us and Them by Pink Floyd',
  'Welcome To The Machine by Pink Floyd',
  'Wish You Were Here by Pink Floyd',
  'Young Lust by Pink Floyd',
  'Every Rose Has Its Thorn by Poison',
  'Look What The Cat Dragged In by Poison',
  'Nothin\' But A Good Time by Poison',
  'Something To Believe In by Poison',
  'Talk Dirty To Me by Poison',
  'A Salty Dog by Procol Harum',
  'A Whiter Shade of Pale by Procol Harum',
  'Blurry by Puddle of Mudd',
  'Amie by Pure Prairie League',
  'Another One Bites the Dust by Queen',
  'Bicycle Race by Queen',
  'Bicycle Race/fat Bottomed Girls by Queen',
  'Bohemian Rhapsody by Queen',
  'Crazy Little Thing Called Love by Queen',
  'Don\'t Stop Me Now by Queen',
  'Fat Bottomed Girls by Queen',
  'It\'s Late by Queen',
  'Keep Yourself Alive by Queen',
  'Killer Queen by Queen',
  'One Vision by Queen',
  'Somebody To Love by Queen',
  'THESE ARE THE DAYS OF OUR LI by Queen',
  'Tie Your Mother Down by Queen',
  'Under Pressure by Queen',
  'We Are the Champions by Queen',
  'We Will Rock You by Queen',
  'We Will Rock You/We Are The Champions by Queen',
  'You\'re My Best Friend by Queen',
  'Under Pressure by Queen / David Bowie',
  'No One Knows by Queens of the Stone Age',
  'Another Rainy Night by Queensryche',
  'Eyes Of A Stranger by Queensryche',
  'I Don\'t Believe In Love by Queensryche',
  'Jet City Woman by Queensryche',
  'Silent Lucidity by Queensryche',
  'Fresh Air by Quicksilver Messenger Service',
  'Pride of Man by Quicksilver Messenger Service',
  'Bang Your Head by Quiet Riot',
  'Cum On Feel the Noize by Quiet Riot',
  'Metal Health by Quiet Riot',
  'It\'s the End of the World As We Know It (And I Feel Fine) by R.E.M.',
  'Losing My Religion by R.E.M.',
  'Man On the Moon by R.E.M.',
  'Orange Crush by R.E.M.',
  'Stand by R.E.M.',
  'The One I Love by R.E.M.',
  'Man On The Silver Mountain by Rainbow',
  'Since You Been Gone by Rainbow',
  'Stone Cold by Rainbow',
  'Street Of Dreams by Rainbow',
  'Black Betty by Ram Jam',
  'Back for More by Ratt',
  'Round and Round by Ratt',
  'Way Cool Jr. by Ratt',
  'Breaking the Girl by Red Hot Chili Peppers',
  'By the Way by Red Hot Chili Peppers',
  'Californication by Red Hot Chili Peppers',
  'Dani California by Red Hot Chili Peppers',
  'Give It Away by Red Hot Chili Peppers',
  'Scar Tissue by Red Hot Chili Peppers',
  'Soul to Squeeze by Red Hot Chili Peppers',
  'Under the Bridge by Red Hot Chili Peppers',
  'Lunatic Fringe by Red Rider',
  'Back On The Road Again by REO Speedwagon',
  'Don\'t Let Him Go by REO Speedwagon',
  'Golden Country by REO Speedwagon',
  'I Can\'t Fight This Feeling by REO Speedwagon',
  'Keep On Loving You by REO Speedwagon',
  'Keep Pushin\'  1977 by REO Speedwagon',
  'Like You Do by REO Speedwagon',
  'Ridin\' the Storm Out by REO Speedwagon',
  'Roll With the Changes by REO Speedwagon',
  'Take It on the Run by REO Speedwagon',
  'Time For Me To Fly by REO Speedwagon',
  'Rock And Roll, Hoochie Koo by Rick Derringer',
  'Jessie\'s Girl by Rick Springfield',
  'Back Off Boogaloo by Ringo Starr',
  'Early 1970 [*] by Ringo Starr',
  'It Don\'t Come Easy by Ringo Starr',
  'No No Song by Ringo Starr',
  'Photograph by Ringo Starr',
  'Your\'re Sixteen by Ringo Starr',
  'Addicted to Love by Robert Palmer',
  'Bad Case Of Lovin\' You by Robert Palmer',
  'Simply Irresistible by Robert Palmer',
  'Big Log by Robert Plant',
  'In The Mood by Robert Plant',
  'Little By Little by Robert Plant',
  'No Easy Way Out by Robert Tepper',
  'Bridge of Sighs by Robin Trower',
  'Little Bit of Sympathy by Robin Trower',
  'Too Rolling Stoned by Robin Trower',
  'Oh, Well by Rockets',
  'Tired Of Toein\' The Line by Rocky Burnette',
  'Every Picture Tells A Story by Rod Stewart',
  'Hot Legs by Rod Stewart',
  'I Know I\'m Losing You by Rod Stewart',
  'Maggie May by Rod Stewart',
  'Reason to Believe by Rod Stewart',
  'Stay with Me by Rod Stewart',
  'The First Cut Is The Deepest by Rod Stewart',
  'Tonight\'s the Night (Gonna Be Alright) by Rod Stewart',
  'You Wear It Well by Rod Stewart',
  'You\'re In My Heart (The Final Acclaim) by Rod Stewart',
  'Free Me by Roger Daltry',
  'Had a Dream (Sleeping With the Enemy) by Roger Hodgson',
  'The Logical Song by Roger Hodgson',
  '(I Can\'t Get No) Satisfaction by Rolling Stones',
  '19th Nervous Breakdown by Rolling Stones',
  'Ain\'t Too Proud to Beg by Rolling Stones',
  'Almost Hear You Sigh by Rolling Stones',
  'Angie by Rolling Stones',
  'Beast Of Burden by Rolling Stones',
  'Bitch by Rolling Stones',
  'Brown Sugar by Rolling Stones',
  'Can\'t You Hear Me Knocking by Rolling Stones',
  'CAROL by Rolling Stones',
  'Da Da Doo Ron Ron by Rolling Stones',
  'Dance Little Sister by Rolling Stones',
  'Doo Doo Doo Doo Doo (Heartbreaker) by Rolling Stones',
  'Doom And Gloom by Rolling Stones',
  'Emotional Rescue by Rolling Stones',
  'Fortune Teller by Rolling Stones',
  'Get Off My Cloud by Rolling Stones',
  'Get Off Of My Cloud by Rolling Stones',
  'Gimme Shelter by Rolling Stones',
  'Hand of Fate by Rolling Stones',
  'Hang Fire by Rolling Stones',
  'Happy by Rolling Stones',
  'Heartbreaker by Rolling Stones',
  'Honky Tonk Women by Rolling Stones',
  'IT\'S ALL OVER NOW by Rolling Stones',
  'It\'s Only Rock \'n Roll by Rolling Stones',
  'Jumpin\' Jack Flash by Rolling Stones',
  'Just My Imagination by Rolling Stones',
  'Let It Bleed by Rolling Stones',
  'Let\'s Spend the Night Together by Rolling Stones',
  'Like A Rolling Stone by Rolling Stones',
  'Little Queenie by Rolling Stones',
  'Midnight Rambler by Rolling Stones',
  'Miss You by Rolling Stones',
  'Monkey Man by Rolling Stones',
  'Mother\'s Little Helper by Rolling Stones',
  'Paint It Black by Rolling Stones',
  'Shattered by Rolling Stones',
  'She\'s a Rainbow by Rolling Stones',
  'She\'s So Cold by Rolling Stones',
  'Start Me Up by Rolling Stones',
  'Street Fighting Man by Rolling Stones',
  'Sympathy For The Devil by Rolling Stones',
  'THE LAST TIME by Rolling Stones',
  'THE SPIDER AND THE FLY by Rolling Stones',
  'TIME IS ON MY SIDE by Rolling Stones',
  'Time Waits for No One by Rolling Stones',
  'Tumbling Dice by Rolling Stones',
  'Under My Thumb by Rolling Stones',
  'UNDERCOVER OF THE NIGHT by Rolling Stones',
  'Waiting on a Friend by Rolling Stones',
  'Wild Horses by Rolling Stones',
  'You Can\'t Always Get What You Want by Rolling Stones',
  'YOU GOT THE SILVER by Rolling Stones',
  'YOU GOTTA MOVE by Rolling Stones',
  'Bullfrog Blues by Rory Gallagher',
  'Cry Sister by Royal Bliss',
  '2112: Overture / The Temples of Syrinx (Chronicles Version) by Rush',
  'Closer to the Heart by Rush',
  'Entre Nous by Rush',
  'Finding My Way by Rush',
  'Fly By Night by Rush',
  'Freewill by Rush',
  'In The Mood by Rush',
  'Limelight by Rush',
  'New World Man by Rush',
  'Red Barchetta by Rush',
  'Show Don\'t Tell by Rush',
  'Subdivisions by Rush',
  'Summertime Blues by Rush',
  'Test For Echo by Rush',
  'The Spirit of Radio by Rush',
  'The Trees by Rush',
  'Time Stand Still (live) by Rush',
  'Tom Sawyer by Rush',
  'Working Man by Rush',
  'YYZ by Rush',
  'Voices by Russ Ballard',
  'On The Loose by Saga',
  'SOUL MAN by Sam & Dave',
  'Can\'t Get Loose by Sammy Hagar',
  'Heavy Metal by Sammy Hagar',
  'I Can\'t Drive 55 by Sammy Hagar',
  'I\'ll Fall In Love Again by Sammy Hagar',
  'Plain Jane by Sammy Hagar',
  'Red by Sammy Hagar',
  'There\'s Only One Way to Rock by Sammy Hagar',
  'Three Lock Box by Sammy Hagar',
  'Trans Am (Highway Wonderland) by Sammy Hagar',
  'Turn Up The Music  1977 by Sammy Hagar',
  'Black Magic Woman by Santana',
  'Europa by Santana',
  'Evil Ways by Santana',
  'Jingo by Santana',
  'No One to Depend On by Santana',
  'Oye Como Va by Santana',
  'Put Your Lights On (feat. Everlast) by Santana',
  'Smooth by Santana',
  'Soul Sacrifice by Santana',
  'Well All Right by Santana',
  'Winning by Santana',
  'The Warrior by Scandal',
  '3 Strange Days by School Of Fish',
  'Big City Nights by Scorpions',
  'Blackout by Scorpions',
  'Don\'t Believe Her by Scorpions',
  'Holiday by Scorpions',
  'Loving You Sunday Morning by Scorpions',
  'No One Like You by Scorpions',
  'Rock You Like a Hurricane by Scorpions',
  'Still Loving You by Scorpions',
  'The Zoo by Scorpions',
  'Wind Of Change by Scorpions',
  'Remedy by Seether',
  'Words As Weapons by Seether',
  'God Save The Queen by Sex Pistols',
  'No Turning Back by Sherbs',
  '45 by Shinedown',
  'America by Simon & Garfunkel',
  'Cecilia by Simon & Garfunkel',
  'Mrs. Robinson by Simon & Garfunkel',
  'The Sounds Of Silence by Simon & Garfunkel',
  'Don\'t You by Simple Minds',
  '18 And Life by Skid Row',
  'I Remember You by Skid Row',
  'Youth Gone Wild by Skid Row',
  'Fly To The Angels by Slaughter',
  'All Star by Smash Mouth',
  '1979 by Smashing Pumpkins',
  'Bullet With Butterfly Wings by Smashing Pumpkins',
  'Landslide by Smashing Pumpkins',
  'Today by Smashing Pumpkins',
  'Driver\'s Seat by Sniff \'n\' the Tears',
  'Tainted Love by Soft Cell',
  'Black Hole Sun by Soundgarden',
  'Burden in My Hand by Soundgarden',
  'Fell On Black Days by Soundgarden',
  'Spoonman by Soundgarden',
  'Havin\' A Party by Southside Johnny',
  'The Fever by Southside Johnny',
  'GIMME SOME LOVIN\' by Spencer Davis Group',
  'Two Princes by Spin Doctors',
  'Black Coffee In Bed by Squeeze',
  'Pulling Mussels by Squeeze',
  'Tempted by Squeeze',
  'It\'s Been Awhile by Staind',
  'My Demons by Starset',
  'Stuck In the Middle With You by Stealers Wheel',
  'Black Cow by Steely Dan',
  'Deacon Blues by Steely Dan',
  'Dirty Work by Steely Dan',
  'Do It Again by Steely Dan',
  'Fm {no Static At All} by Steely Dan',
  'Hey Nineteen by Steely Dan',
  'Peg by Steely Dan',
  'Reelin\' in the Years by Steely Dan',
  'Rikki Don\'t Lose That Number by Steely Dan',
  'Love the One You\'re With by Stephen Stills',
  'Treetop Flyer by Stephen Stills',
  'Born to Be Wild by Steppenwolf',
  'Magic Carpet Ride by Steppenwolf',
  'Copperhead Road by Steve Earle',
  'Abracadabra by Steve Miller Band',
  'Fly Like an Eagle by Steve Miller Band',
  'Jet Airliner by Steve Miller Band',
  'Jungle Love by Steve Miller Band',
  'Living in the U.S.A. by Steve Miller Band',
  'Mercury Blues by Steve Miller Band',
  'Rock \'N Me by Steve Miller Band',
  'Space Cowboy by Steve Miller Band',
  'Swingtown by Steve Miller Band',
  'Take the Money and Run by Steve Miller Band',
  'The Joker by Steve Miller Band',
  'The Stake by Steve Miller Band',
  'Threshold/Jet Airliner by Steve Miller Band',
  'True Fine Love by Steve Miller Band',
  'Your Cash Ain\'t Nothin But Trash by Steve Miller Band',
  'Oh Sherrie by Steve Perry',
  'Back In the High Life Again by Steve Winwood',
  'Higher Love by Steve Winwood',
  'Roll With It by Steve Winwood',
  'While You See a Chance by Steve Winwood',
  'Love The One You\'Re With by Steven Stills',
  'Edge of Seventeen by Stevie Nicks',
  'Leather and Lace by Stevie Nicks',
  'Stand Back by Stevie Nicks',
  'Stop Draggin\' My Heart Around by Stevie Nicks',
  'Stop Draggin\' My Heart Around by Stevie Nicks w/ Tom Petty and the Heartbreakers',
  'Cold Shot by Stevie Ray Vaughan',
  'Couldn\'t Stand the Weather by Stevie Ray Vaughan',
  'Crossfire by Stevie Ray Vaughan',
  'Life by the Drop by Stevie Ray Vaughan',
  'Little Wing by Stevie Ray Vaughan',
  'Look At Little Sister by Stevie Ray Vaughan',
  'Pride And Joy by Stevie Ray Vaughan',
  'Scuttle Buttin\' by Stevie Ray Vaughan',
  'Superstition [Live] by Stevie Ray Vaughan',
  'Taxman by Stevie Ray Vaughan',
  'Texas Flood by Stevie Ray Vaughan',
  'The House Is Rockin\' by Stevie Ray Vaughan',
  'The Sky Is Crying by Stevie Ray Vaughan',
  'Tightrope by Stevie Ray Vaughan',
  'Voodoo Chile {slight Return} by Stevie Ray Vaughan',
  'Superstition by Stevie Wonder',
  'Fortress Around Your Heart by Sting',
  'If You Love Somebody Set Them Free by Sting',
  'Big Empty by Stone Temple Pilots',
  'Creep by Stone Temple Pilots',
  'Interstate Love Song by Stone Temple Pilots',
  'Lady Picture Show by Stone Temple Pilots',
  'Plush by Stone Temple Pilots',
  'Sex Type Thing by Stone Temple Pilots',
  'Trippin\' on a Hole in a Paper Heart by Stone Temple Pilots',
  'Vasoline by Stone Temple Pilots',
  'Rock This Town by Stray Cats',
  'Stray Cat Strut by Stray Cats',
  'To Hell With the Devil by Stryper',
  'The Isle Of Debris by Stu Nunnery',
  'Blue Collar Man by Styx',
  'Come Sail Away by Styx',
  'Crystal Ball by Styx',
  'Fooling Yourself by Styx',
  'Lady by Styx',
  'Light Up by Styx',
  'Lorelei by Styx',
  'Renegade by Styx',
  'Suite Madame Blue by Styx',
  'The Grand Illusion by Styx',
  'Too Much Time On My Hands by Styx',
  'What I Got by Sublime',
  'Wrong Way by Sublime',
  'Fly by Sugar Ray',
  'Green Eyed Lady by Sugarloaf',
  'Bloody Well Right by Supertramp',
  'Breakfast in America by Supertramp',
  'Dreamer by Supertramp',
  'Give a Little Bit by Supertramp',
  'Goodbye Stranger by Supertramp',
  'Take the Long Way Home by Supertramp',
  'The Logical Song by Supertramp',
  'Eye of the Tiger by Survivor',
  'I Can\'t Hold Back by Survivor',
  'Ballroom Blitz by Sweet',
  'Fox On The Run by Sweet',
  'Love Is Like Oxygen by Sweet',
  'Bang a Gong (Get It On) by T. Rex',
  'Jeepster by T. Rex',
  'And She Was by Talking Heads',
  'Burning Down the House by Talking Heads',
  'Life During Wartime by Talking Heads',
  'Once In A Lifetime by Talking Heads',
  'Psycho Killer by Talking Heads',
  'Road To Nowhere by Talking Heads',
  'Stay Up Late by Talking Heads',
  'Take Me To The River by Talking Heads',
  'Wild Wild Life by Talking Heads',
  'I\'m Leaving by Taxxi',
  'Everybody Wants to Rule the World by Tears for Fears',
  'Head Over Heels by Tears for Fears',
  'Shout by Tears for Fears',
  'Cat Scratch Fever by Ted Nugent',
  'Dog Eat Dog by Ted Nugent',
  'Free for All by Ted Nugent',
  'Great White Buffalo by Ted Nugent',
  'Stranglehold by Ted Nugent',
  'Wango Tango by Ted Nugent',
  'Hunger Strike by Temple of the Dog',
  'I\'d Love To Change The World by Ten Years After',
  'I\'m Goin\' Home by Ten Years After',
  'Little Suzi by Tesla',
  'Love Song by Tesla',
  'Modern Day Cowboy by Tesla',
  'Signs by Tesla',
  'Breakdown by The Alan Parsons Project',
  'Eye In the Sky by The Alan Parsons Project',
  'Games People Play by The Alan Parsons Project',
  'I Wouldn\'t Want to Be Like You by The Alan Parsons Project',
  'Rain In the Summertime by The Alarm (IRS)',
  'Journey to the Center of the Mind by The Amboy Dukes',
  'Don\'t Bring Me Down by The Animals',
  'House Of The Rising Sun by The Animals',
  'Monterey by The Animals',
  'San Franciscan Nights by The Animals',
  'Spill the Wine by The Animals',
  'Love Shack by The B-52\'s',
  'Roam by The B-52\'s',
  'Back On My Feet Again by The Babys',
  'Isn\'t It Time by The Babys',
  'Chest Fever by The Band',
  'The Night They Drove Old Dixie Down by The Band',
  'The Weight by The Band',
  'Up On Cripple Creek by The Band',
  'Good Vibrations by The Beach Boys',
  'A Day In The Life by The Beatles',
  'A Hard Day\'s Night by The Beatles',
  'A Saturday Club Xmas/Crimble Medley by The Beatles',
  'Across The Universe by The Beatles',
  'All My Loving by The Beatles',
  'All You Need Is Love by The Beatles',
  'And Your Bird Can Sing by The Beatles',
  'ANYTIME AT ALL by The Beatles',
  'Baby You\'re A Rich Man by The Beatles',
  'Back In the U.S.S.R. by The Beatles',
  'BAD BOY by The Beatles',
  'BALLAD OF JOHN AND YOKO by The Beatles',
  'Birthday by The Beatles',
  'Blackbird by The Beatles',
  'Can\'t Buy Me Love by The Beatles',
  'Come Together by The Beatles',
  'Cry For A Shadow by The Beatles',
  'Day Tripper by The Beatles',
  'Dear Prudence by The Beatles',
  'Don\'t Let Me Down by The Beatles',
  'Drive My Car by The Beatles',
  'Eight Days A Week by The Beatles',
  'Eleanor Rigby by The Beatles',
  'Everybody\'s Got Something To Hide Except Me And My Monk by The Beatles',
  'Fixing A Hole by The Beatles',
  'From Me To You by The Beatles',
  'Get Back by The Beatles',
  'Getting Better by The Beatles',
  'GIRL by The Beatles',
  'Golden Slumbers by The Beatles',
  'Good Day Sunshine by The Beatles',
  'Got To Get You Into My Life by The Beatles',
  'Hello Goodbye by The Beatles',
  'Help! by The Beatles',
  'Helter Skelter by The Beatles',
  'Here Comes The Sun by The Beatles',
  'Hey Jude by The Beatles',
  'I Am the Walrus by The Beatles',
  'I Feel Fine by The Beatles',
  'I Saw Her Standing There by The Beatles',
  'I Want To Hold Your Hand by The Beatles',
  'I Want You (She\'s So Heavy) by The Beatles',
  'I\'ll Follow The Sun by The Beatles',
  'I\'m A Loser by The Beatles',
  'I\'m Down by The Beatles',
  'I\'ve Got A Feeling by The Beatles',
  'I\'ve Just Seen A Face by The Beatles',
  'IN MY LIFE by The Beatles',
  'IT WON\'T BE LONG by The Beatles',
  'Lady Madonna by The Beatles',
  'Let It Be by The Beatles',
  'LITTLE CHILD by The Beatles',
  'Love Me Do by The Beatles',
  'Lovely Rita by The Beatles',
  'Lucy In The Sky With Diamonds by The Beatles',
  'Magical Mystery Tour by The Beatles',
  'Maxwell\'s Silver Hammer by The Beatles',
  'Norwegian Wood by The Beatles',
  'NOWHERE MAN by The Beatles',
  'Ob-la-di, Ob-la-da by The Beatles',
  'OH DARLING by The Beatles',
  'P.s. I Love You by The Beatles',
  'Paperback Writer by The Beatles',
  'Penny Lane by The Beatles',
  'Please Please Me by The Beatles',
  'Reprise / Day in the Life by The Beatles',
  'Revolution by The Beatles',
  'ROCK AND ROLL MUSIC by The Beatles',
  'Rocky Raccoon by The Beatles',
  'Roll Over Beethoven by The Beatles',
  'Sgt. Pepper Inner Groove by The Beatles',
  'Sgt. Pepper\'s Lonely Hearts Club Band by The Beatles',
  'Sgt. Pepper\'s Lonely Hearts Club Band (Reprise) by The Beatles',
  'Sgt. Pepper/a Day In The Life by The Beatles',
  'Sgt. Pepper/with A Little Help From My Friends by The Beatles',
  'She Loves You by The Beatles',
  'SHE\'S A WOMAN by The Beatles',
  'She\'s Leaving Home by The Beatles',
  'Something by The Beatles',
  'Strawberry Fields Forever by The Beatles',
  'Sun King by The Beatles',
  'The Ballad Of John And Yoko by The Beatles',
  'THE CONTINUING STORY OF BUNG by The Beatles',
  'The Fool On The Hill by The Beatles',
  'The Long And Winding Road by The Beatles',
  'The Word by The Beatles',
  'Things We Said Today by The Beatles',
  'Ticket to Ride by The Beatles',
  'Twist and Shout by The Beatles',
  'Two Of Us by The Beatles',
  'We Can Work It Out by The Beatles',
  'When I\'m 64 by The Beatles',
  'While My Guitar Gently Weeps by The Beatles',
  'Wild Honey Pie by The Beatles',
  'With a Little Help From My Friends by The Beatles',
  'Yellow Submarine by The Beatles',
  'Yesterday by The Beatles',
  'You Never Give Me Your Money by The Beatles',
  'You\'re Going To Lose That Girl by The Beatles',
  'YOUR MOTHER SHOULD KNOW by The Beatles',
  'A Conspiracy by The Black Crowes',
  'Gone by The Black Crowes',
  'Good Friday by The Black Crowes',
  'Goodbye Daughters of the Revolution by The Black Crowes',
  'Hard To Handle by The Black Crowes',
  'Hotel Illness by The Black Crowes',
  'Jealous Again by The Black Crowes',
  'Kickin\' My Heart Around by The Black Crowes',
  'Remedy by The Black Crowes',
  'She Talks To Angels by The Black Crowes',
  'Thorn In My Pride by The Black Crowes',
  'Twice As Hard by The Black Crowes',
  'Gold On The Ceiling by The Black Keys',
  'Lonely Boy by The Black Keys',
  'Soul Man by The Blues Brothers',
  'Eight Miles High by The Byrds',
  'Bye Bye Love by The Cars',
  'Candy-o by The Cars',
  'Dangerious Type by The Cars',
  'Drive by The Cars',
  'Good Times Roll by The Cars',
  'Hello Again by The Cars',
  'It\'s All I Can Do by The Cars',
  'Just What I Needed by The Cars',
  'Let\'s Go by The Cars',
  'Magic by The Cars',
  'Moving In Stereo by The Cars',
  'My Best Friend\'s Girl by The Cars',
  'Shake It Up by The Cars',
  'Since You\'re Gone by The Cars',
  'Stereo/All Mixed Up by The Cars',
  'Tonight She Comes by The Cars',
  'You Might Think by The Cars',
  'You\'re All I\'ve Got Tonight by The Cars',
  'Clampdown by The Clash',
  'I Fought The Law by The Clash',
  'London Calling by The Clash',
  'Rock The Casbah by The Clash',
  'Should I Stay Or Should by The Clash',
  'Train In Vain by The Clash',
  'Fire Woman by The Cult',
  'Another Park, Another Sunday by The Doobie Brothers',
  'Black Water by The Doobie Brothers',
  'China Grove by The Doobie Brothers',
  'It Keeps You Runnin\' by The Doobie Brothers',
  'Jesus Is Just Alright by The Doobie Brothers',
  'Listen To The Music by The Doobie Brothers',
  'Livin\' On the Fault Line by The Doobie Brothers',
  'Long Train Runnin\' by The Doobie Brothers',
  'Natural Thing by The Doobie Brothers',
  'Rockin\' Down The Highway by The Doobie Brothers',
  'South City Midnight Lady by The Doobie Brothers',
  'Take Me In Your Arms by The Doobie Brothers',
  'Takin\' It To The Streets by The Doobie Brothers',
  'UKIAH/THE CAPTAIN AND ME by The Doobie Brothers',
  'What a Fool Believes by The Doobie Brothers',
  'Wheels Of Fortune by The Doobie Brothers',
  'Back Door Man by The Doors',
  'Break On Through by The Doors',
  'Five To One by The Doors',
  'Gloria by The Doors',
  'Hello, I Love You by The Doors',
  'L.A. Woman by The Doors',
  'Light My Fire by The Doors',
  'Love Her Madly by The Doors',
  'Love Me Two Times by The Doors',
  'Moonlight Drive by The Doors',
  'Peace Frog by The Doors',
  'People Are Strange by The Doors',
  'Riders On The Storm by The Doors',
  'Roadhouse Blues by The Doors',
  'Soul Kitchen by The Doors',
  'The Changeling by The Doors',
  'The Crystal Ship by The Doors',
  'Touch Me by The Doors',
  'Twentieth Century Fox by The Doors',
  'Waiting For The Sun by The Doors',
  'When the Music\'s Over by The Doors',
  'Tuff Enuff by The Fabulous Thunderbirds',
  'Radioactive by The Firm',
  'One Thing Leads To Another by The Fixx',
  'Saved By Zero by The Fixx',
  'Iris by The Goo Goo Dolls',
  'Funk #49 by The James Gang',
  'This Beat Goes on/Switching to Glide by The Kings',
  'A Well Respected Man by The Kinks',
  'All Day And All Of The Night by The Kinks',
  'Apeman by The Kinks',
  'Come Dancing by The Kinks',
  'Destroyer by The Kinks',
  'Lola by The Kinks',
  'Sunny Afternoon by The Kinks',
  'Superman by The Kinks',
  'Tired of Waiting by The Kinks',
  'Victoria by The Kinks',
  'Waterloo Sunset by The Kinks',
  'You Really Got Me by The Kinks',
  'My Sharona by The Knack',
  'Mrs. Robinson by The Lemonheads',
  'Summer In the City by The Lovin\' Spoonful',
  'CALIFORNIA DREAMIN\' by The Mamas',
  'Can\'t You See by The Marshall Tucker Band',
  'HEARD IT IN A LOVE SONG by The Marshall Tucker Band',
  'Take The Highway by The Marshall Tucker Band',
  'Gypsy by The Moody Blues',
  'Question by The Moody Blues',
  'Ride My See Saw by The Moody Blues',
  'The Story In Your Eyes by The Moody Blues',
  'Your Wildest Dreams by The Moody Blues',
  'Life in the Fast Lane by The New Eagles',
  'Come Out and Play by The Offspring',
  'Self Esteem by The Offspring',
  'The Kids Aren\'t Alright by The Offspring',
  'Your Love by The Outfield',
  'Green Grass & High Tides by The Outlaws',
  'Can\'t Stand Losing You by The Police',
  'De Do Do Do, De Da Da Da by The Police',
  'Don\'t Stand So Close To Me by The Police',
  'Driven to Tears by The Police',
  'Every Breath You Take by The Police',
  'Every Little Thing She Does Is Magic by The Police',
  'Invisible Sun by The Police',
  'King Of Pain by The Police',
  'Message In A Bottle by The Police',
  'Roxanne by The Police',
  'So Lonely by The Police',
  'Spirits In The Material World by The Police',
  'Synchronicity II by The Police',
  'Walking On The Moon by The Police',
  'Wrapped Around Your Finger by The Police',
  'Some Like It Hot by The Power Station',
  'Back On The Chain Gang by The Pretenders',
  'Brass In Pocket by The Pretenders',
  'Don\'t Get Me Wrong by The Pretenders',
  'Message of Love by The Pretenders',
  'Middle Of The Road by The Pretenders',
  'My City Was Gone by The Pretenders',
  'Mystery Achievement by The Pretenders',
  'TALK OF THE TOWN by The Pretenders',
  'Blitzkrieg Bop by The Ramones',
  'Do You Remember Rock \'n\' Roll Radio by The Ramones',
  'I Wanna Be Sedated by The Ramones',
  'Rock \'n\' Roll High School by The Ramones',
  'Rockaway Beach by The Ramones',
  'Teenage Lobotomy by The Ramones',
  'TALKING IN YOUR SLEEP by The Romantics',
  'What I Like About You by The Romantics',
  'Itchycoo Park by The Small Faces',
  'A Girl Like You by The Smithereens',
  'I\'m A Man by The Spencer Davis Group',
  'Dirty Water by The Standells',
  'End of the Line by The Traveling Wilburys',
  'Handle with Care by The Traveling Wilburys',
  'Tweeter and the Monkey Man by The Traveling Wilburys',
  'She\'s a Beauty by The Tubes',
  'Talk To Ya Later by The Tubes',
  'One Headlight by The Wallflowers',
  'Seven Nation Army by The White Stripes',
  '0.21875 by The Who',
  'ANOTHER TRICKY DAY by The Who',
  'Athena by The Who',
  'Baba O\'Reilly by The Who',
  'Bargain by The Who',
  'Behind Blue Eyes by The Who',
  'Eminence Front by The Who',
  'Getting In Tune by The Who',
  'Going Mobile by The Who',
  'Happy Jack by The Who',
  'I Can See For Miles by The Who',
  'I CAN\'T EXPLAIN by The Who',
  'I\'m Free by The Who',
  'Join Together by The Who',
  'Long Live Rock by The Who',
  'Love Reign O\'er Me by The Who',
  'Magic Bus by The Who',
  'My Generation by The Who',
  'Pinball Wizard by The Who',
  'Shakin\' All Over by The Who',
  'Squeeze Box by The Who',
  'Substitute by The Who',
  'Summertime Blues by The Who',
  'The Kids Are Alright by The Who',
  'The Real Me by The Who',
  'THE SEEKER by The Who',
  'THE SONG IS OVER by The Who',
  'We\'re Not Gonna Take It by The Who',
  'Who Are You by The Who',
  'Won\'t Get Fooled Again by The Who',
  'You Better You Bet by The Who',
  'Get Together by The Youngbloods',
  'Jailbreak by Thin Lizzy',
  'The Boys Are Back In Town by Thin Lizzy',
  'The Cowboy Song by Thin Lizzy',
  'Semi-Charmed Life by Third Eye Blind',
  'Something In the Air by Thunderclap Newman',
  'Bang the Drum All Day by Todd Rundgren',
  'Hello It\'s Me by Todd Rundgren',
  'I Saw the Light by Todd Rundgren',
  'We Gotta Get You a Woman by Todd Rundgren',
  'Life Is a Highway by Tom Cochrane',
  'A Face In The Crowd by Tom Petty & The Heartbreakers',
  'A Woman In Love by Tom Petty & The Heartbreakers',
  'American Dream Plan B by Tom Petty & The Heartbreakers',
  'American Girl by Tom Petty & The Heartbreakers',
  'Breakdown by Tom Petty & The Heartbreakers',
  'Change of Heart by Tom Petty & The Heartbreakers',
  'Don\'t Come Around Here No More by Tom Petty & The Heartbreakers',
  'Don\'t Do Me Like That by Tom Petty & The Heartbreakers',
  'Even the Losers by Tom Petty & The Heartbreakers',
  'Fooled Again (I Don\'t Like It) by Tom Petty & The Heartbreakers',
  'Free Fallin\' by Tom Petty & The Heartbreakers',
  'Here Comes My Girl by Tom Petty & The Heartbreakers',
  'I Need to Know by Tom Petty & The Heartbreakers',
  'I Won\'t Back Down by Tom Petty & The Heartbreakers',
  'Into the Great Wide Open by Tom Petty & The Heartbreakers',
  'Jammin\' Me by Tom Petty & The Heartbreakers',
  'Learning To Fly by Tom Petty & The Heartbreakers',
  'Listen To Your Heart by Tom Petty & The Heartbreakers',
  'Mary Jane\'s Last Dance by Tom Petty & The Heartbreakers',
  'Refugee by Tom Petty & The Heartbreakers',
  'Runnin\' Down a Dream by Tom Petty & The Heartbreakers',
  'Stop Draggin\' My Heart Around by Tom Petty & The Heartbreakers',
  'The Waiting by Tom Petty & The Heartbreakers',
  'U Get Me High by Tom Petty & The Heartbreakers',
  'Yer So Bad by Tom Petty & The Heartbreakers',
  'You Don\'t Know How It Feels by Tom Petty & The Heartbreakers',
  'You Get Me High by Tom Petty & The Heartbreakers',
  'You Got Lucky by Tom Petty & The Heartbreakers',
  'You Wreck Me by Tom Petty & The Heartbreakers',
  '867-5309 / Jenny by Tommy Tutone',
  'If You Could Only See by Tonic',
  'AFRICA by Toto',
  'Hold The Line by Toto',
  'Dear Mr. Fantasy by Traffic',
  'Empty Pages by Traffic',
  'Medicated Goo by Traffic',
  'Medusa by Trapeze',
  'Fight The Good Fight by Triumph',
  'Hold On by Triumph',
  'I Can Survive by Triumph',
  'Lay It On the Line by Triumph',
  'Magic Power by Triumph',
  'Happy Together by Turtles',
  'I Wanna Rock by Twisted Sister',
  'We\'re Not Gonna Take It by Twisted Sister',
  'Angel Of Harlem by U2',
  'Bad by U2',
  'Beautiful Day by U2',
  'Bullet the Blue Sky by U2',
  'Desire by U2',
  'Even Better Than the Real Thing by U2',
  'I Still Haven\'t Found What I\'m Looking For by U2',
  'I Will Follow by U2',
  'MLK/Pride by U2',
  'Mysterious Ways by U2',
  'New Year\'s Day by U2',
  'One by U2',
  'Pride (In the Name of Love) by U2',
  'Sunday Bloody Sunday by U2',
  'Sweetest Thing by U2',
  'Vertigo by U2',
  'When Love Comes to Town by U2',
  'Where the Streets Have No Name by U2',
  'With Or Without You by U2',
  'Red Red Wine by UB40',
  'Lights Out (Live) by UFO',
  'Too Hot To Handle by UFO',
  'Easy Livin\' by Uriah Heep',
  'Stealin\' by Uriah Heep',
  'The Wizard by Uriah Heep',
  '(Oh) Pretty Woman by Van Halen',
  '1984/jump by Van Halen',
  'Ain\'t Talkin\' \'bout Love by Van Halen',
  'And the Cradle Will Rock... by Van Halen',
  'Atomic Punk by Van Halen',
  'Beautiful Girls by Van Halen',
  'Best Of Both Worlds by Van Halen',
  'Black And Blue by Van Halen',
  'Dance the Night Away by Van Halen',
  'Dancing In the Street by Van Halen',
  'Dreams by Van Halen',
  'Drop Dead Legs by Van Halen',
  'Eruption - You Really Got Me by Van Halen',
  'Everybody Wants Some!! by Van Halen',
  'Feel Your Love Tonight by Van Halen',
  'Feels So Good by Van Halen',
  'Finish What Ya Started by Van Halen',
  'Hot for Teacher by Van Halen',
  'I\'ll Wait by Van Halen',
  'I\'m the One by Van Halen',
  'Ice Cream Man by Van Halen',
  'Intruder/ Pretty Woman by Van Halen',
  'Jamie\'s Cryin\' by Van Halen',
  'Jump by Van Halen',
  'Little Dreamer by Van Halen',
  'Little Guitars by Van Halen',
  'Love Walks In by Van Halen',
  'Mean Street by Van Halen',
  'Panama by Van Halen',
  'Poundcake by Van Halen',
  'PRETTY WOMAN by Van Halen',
  'Right Now by Van Halen',
  'Runaround by Van Halen',
  'Runnin\' with the Devil by Van Halen',
  'Somebody Get Me A Doctor by Van Halen',
  'Summer Nights by Van Halen',
  'Take Your Whiskey Home by Van Halen',
  'Top Jimmy by Van Halen',
  'Top of the World by Van Halen',
  'Unchained by Van Halen',
  'When It\'s Love by Van Halen',
  'Where Have All the Good Times Gone! by Van Halen',
  'Why Can\'t This Be Love by Van Halen',
  'You Really Got Me by Van Halen',
  'And It Stoned Me by Van Morrison',
  'BLUE MONEY by Van Morrison',
  'Brown Eyed Girl by Van Morrison',
  'CRAZY LOVE by Van Morrison',
  'Domino by Van Morrison',
  'Gloria by Van Morrison',
  'Into The Mystic by Van Morrison',
  'Jackie Wilson Said by Van Morrison',
  'Moondance by Van Morrison',
  'Wild Night by Van Morrison',
  'Blister In the Sun by Violent Femmes',
  'Edge of a Broken Heart by Vixen',
  'Low Rider by War',
  'Spill the Wine by War',
  'The Cisco Kid by War',
  'Why Can\'t We Be Friends by War',
  'Cherry Pie by Warrant',
  'Uncle Tom\'s Cabin by Warrant',
  'Lawyers, Guns and Money by Warren Zevon',
  'Werewolves of London by Warren Zevon',
  'Buddy Holly by Weezer',
  'Street Corner Serenade by Wet Willie',
  'Wait by White Lion',
  'Fool for Your Loving by Whitesnake',
  'Here I Go Again by Whitesnake',
  'Is This Love by Whitesnake',
  'Slide It In by Whitesnake',
  'Slow An\' Easy by Whitesnake',
  'Still of the Night by Whitesnake',
  'Who Are You? by Why Not',
  'PLAY THAT FUNKY MUSIC by Wild Cherry',
  'Night Moves by Wildlife',
  'We\'ve Got Tonight by Wildlife',
  'Can\'t Get Enough by Winger',
  'Headed For A Heartbreak by Winger',
  'Seventeen by Winger',
  'Persephone by Wishbone Ash',
  'Summertime Girls by Y&T',
  'Changes by Yes',
  'I\'ve Seen All Good People by Yes',
  'It Can Happen by Yes',
  'Leave It by Yes',
  'Long Distance Runaround by Yes',
  'Owner of a Lonely Heart by Yes',
  'Roundabout by Yes',
  'Starship Trooper by Yes',
  'Wonderous Stories by Yes',
  'Yours Is No Disgrace by Yes',
  'Tell Me What You Want by Zebra',
  'Who\'s Behind The Door by Zebra',
  'Time of the Season by Zombies',
  'A Fool for Your Stockings by ZZ Top',
  'Arrested For Driving While Blind by ZZ Top',
  'Beer Drinkers & Hell Raisers by ZZ Top',
  'Cheap Sunglasses by ZZ Top',
  'Gimme All Your Lovin by ZZ Top',
  'Got Me Under Pressure by ZZ Top',
  'Heard It On the X by ZZ Top',
  'I Thank You by ZZ Top',
  'I\'m Bad, I\'m Nationwide by ZZ Top',
  'Jesus Just Left Chicago by ZZ Top',
  'Just Got Paid by ZZ Top',
  'La Grange by ZZ Top',
  'Legs by ZZ Top',
  'My Head\'s In Mississippi by ZZ Top',
  'Party On The Patio by ZZ Top',
  'Pearl Necklace by ZZ Top',
  'Sharp Dressed Man by ZZ Top',
  'She Loves My Automobile by ZZ Top',
  'Tube Snake Boogie by ZZ Top',
  'Tush by ZZ Top',
  'TV Dinners by ZZ Top',
  'WAITIN\' FOR THE BUS/JESUS JUST LEFT CHICAGO by ZZ Top',
];
