List<String> celui = [
  "Car tu as ton copain et tu tiens à lui, c'est net",
  'Devant ton charme exotique, je fonds comme Kim',
  "Le reste, j'te l'épargne, ouais j'te l'épargne",
  'Nul ne saura te comprendre mieux que moi',
  "Donc je cesse frime et t'exprime mon estime girl",
  "Faut que j'redescende sur terre",
  'À basses données en pagne, on pète le champagne',
  "Je n'ai même pas encore ton tél'",
  "Mais j'peux rien y faire, il faut que je l'exprime",
  "Non, le style fleur bleue, c'est vraiment pas moi",
  'Pourquoi cela tourne-t-il ainsi ? Why ?',
  'Tu seras ma Sylvia et moi ton Mesrine',
  "Copine, profiter de la vie c'est la doctrine",
  'Deux-trois bisous, un câlin sous la couette et pam (Wouh)',
  "Tu verras, tu verras, je s'rai celui-là, oh, non",
  'Passer quelques heures avec toi dans ce lit',
  'Je saurais prendre soin de toi',
  'Mais girl, écoute ça',
  'Laisse-moi ma chance, tu verras',
  'Un amour sincère dans un monde où le sexe prime',
  'Au pire celui, qui partage ta nuit (Celui, ta nuit)',
  "Mais t'imagines même pas c'que j'ressens pour toi",
  'Doc Reyel pas Gynéco',
  'Des problèmes de gals, ouais, je nnais-co',
  "Qu'on s'fasse des purs voyages, t'inquiètes, ce sera pas la campagne",
  "Docteur, à mes heures perdues selon l'timing",
  "J'aurais jamais pensé qu'un jour j'en arriverais là",
  "Celle des guadeloupéens d'la grande époque",
  "À Miami, le Brésil, le Maroc ou l'Espagne",
  'Aussitôt que le jour se lève, tu es dans ma tête',
  'Oui, celui qui brave tes interdits',
  'Sensuellement ultime, limite coquine',
  'Tu verras my girl, tu verras my girl, non',
  "J'te le dis, j'te le dis, je serai celui",
  "Te dire que je n'veux pas te détourner s'rait malhonnête",
  "J'te le dis, j'te le dis, je s'rai celui-ci",
  'Oui, celui à qui tu te confies',
  "J'ai étudié la chose à mon école",
  "J'veux être celui qui t'accompagne, que tu sois ma compagne",
  'Passer quelques heures avec toi me suffit',
  "Tu hantes mes pensées, je n'en sortirai pas inerte",
  'Au pire, celui qui partage ta nuit',
  "Un truc de dingue, j'peux même pas mettre de mots sur ça",
  'Donne-moi ma chance, tu verras',
  'Tellement tu contrôles mes réactions telle une marionnette',
  'Laisse-moi être celui qui partage ta vie'
];
List<String> aurelie = [
  'Et la galère commença',
  'Elle a dû construire très rapidement un foyer',
  "Le moins que l'on puisse dire c'est que ce ne fut pas le cas",
  'Trouver un travail coûte que coûte pour le payer',
  "Elle annonça qu'elle était enceinte de 3 mois",
  'Mettre un enfant au monde ne devrait pas être puni',
  "De ne pas lâcher l'affaire ça lui a enseigné, ooh",
  'Sort avec un mec de son quartier depuis peu',
  'Rejetée par ses amis mais surtout sa famille',
  "Pour trouver quelqu'un qui veuille bien la renseigner",
  'Une pour qui grossesse est synonyme de délit',
  "Celui-ci c'est pour toutes les Aurélie",
  'Faire face à ses responsabilités pour le loyer',
  "Aurélie n'a que 16 ans et elle attend un enfant",
  "Qui n'acceptent pas qu'elle souhaite donner la vie",
  "Comme on dit dans les quartiers, elle s'est saignée",
  "Elle l'a jamais fait elle attendait juste le bon gars",
  'Résultat : elle se retrouve seule dans cette histoire',
  "C'est que tu n'as rien compris",
  'La elle se dit "bingo" ils sont seuls dans la Twingo',
  'Elle aura tout essayé',
  'Pour toutes les Aurélie',
  'Je peux te dire que toute sa vie elle se rappellera',
  'Il réussi le ace comme Tsonga',
  'Oy, mère à tout prix',
  "Je crois qu'on n'est pas VIP comme Mathilde Seigner",
  'Oui mais voila, neuf mois plus tard',
  'Celles qui ont donné la vie',
  'Elle dit qu\'elle se sent prête pour qu\'on l\'appelle "Maman"',
  "Elle a découvert qu'en fait il est fêtard",
  "Elle n'est pas d'accord, elle voit les choses autrement",
  'Voila ce que je dirais si je devais donner mon avis',
  "C'est la plus belle chose qui soit et si tu le nies",
  "Où elle l'annonça à sa mère et son papa",
  "Elle ne s'attendait pas à ce qu'ils sautent de joie",
  "Mais elle espérait quand même qu'ils fassent preuve de bonne foi",
  "Il est comme elle aime, c'est-à-dire un peu plus vieux",
  'Il assume pas et se sauve comme un bâtard',
  "Il a l'air amoureux, ils ont tout pour être heureux",
  "Ses amis et ses parents lui conseillent l'avortement",
  "On a tous connu une fille dans le cas d'Aurélie",
  "Elle se rappellera le jour où elle l'annonça",
  'Donc ça va swinguer, elle enlève son tanga',
  'Elle est en seconde dans un lycée de banlieue'
];
List<String> tln = [
  'Toutes les nuits je pense à toi, tout près de moi',
  'Je nous vois tous les deux',
  "Je t'ai dans la tête et dans l'sang, my girl",
  "Je m'imagine à tes côtés, embrassant tes lèvres",
  "J'espère qu'on finira ensemble à la fin du livre",
  "J'ai trop d'fierté, ça m'agace",
  'Sois ma maîtresse, apprends-moi : je serai ton élève, girl',
  "Oh baby, my baby, pour toi j'viens chanter, girl",
  "J'ai pas l'courage de t'le dire en face",
  'Toutes les nuits je pense à toi',
  'Pas une nuit sans que je pense à toi...',
  'J\'aimerais être "celui", veux-tu être "celle" ? Ouh !',
  'Qui aurait pu dire que je connaîtrai ça un jour ?',
  "J'arrive pas à t'l'avouer mais j'suis tombé sous ton charme",
  "Je sais qu't'aurais jamais pensé",
  "J'ai trop lutté contre mes sentiments, j'dépose les armes",
  "T'es la seule et l'unique avec qui j'veux vivre",
  "Finalement peut-être que j'suis pas si coriace ! Faut qu'tu saches que...",
  "Ton parfum, ta chaleur : j'en ai jamais assez",
  "Qu'j't'avouerais que t'es dans mes pensées",
  "J'écoute pas ma timidité",
  "J'veux passer des heures à te caresser",
  "J'profite de cet instant pour briser la glace, oooh",
  "Tu illumines ma vie et tu m'inspires la joie...",
  'Dès que la nuit tombe, tu es dans mes rêves',
  "J'te promets que j'te dirai jamais rien de déplacé",
  'Chaque jour... Qui passe...',
  "Tu habites mes nuits, non ça ne change pas... Faut qu'tu saches que...",
  "Laisse-moi t'avouer c'que j'ressens",
  "C'est sans doute ce qu'on appelle l'amour",
  "Prêt à faire des efforts, je suis prêt à m'dépasser",
  'Toutes les nuits je rêve de nous deux'
];
List<String> ms = [
  "Rien d'autre n'a d'importance du moment que t'es là",
  'Tu es ma star...',
  "T'es ma star, mon étoile, éclaire ma galaxie",
  "C'est toi qui prie parmi toutes les étoiles du ciel",
  "Tu es ma star, toi seule me redonne dans l'espoir",
  'Je sais que je pourrais toujours venir frapper à ta porte',
  "Quelqu'un veut nous séparer, il va y rester",
  'Je suis ta star, moi seul te redonne espoir',
  'Coup de coeur',
  'Celle du Colonel Reyel',
  "J'ai su tout de suite qu'entre nous ce serait explicite",
  "Conscient de toute l'attention que tu me portes",
  'Pas de boule comme sur Materazzi',
  'Duo de choc',
  'Rien à faire de Beyoncé et de Shakira',
  'Oh oh, ma star ! Eh, eh, ma star.. ! (x2)',
  'Tu peux compter sur moi, je serai toujours là',
  "Et un jour, peut être que c'est toi qui me diras",
  'Tu es ma star, personnelle',
  "Rap'sun, Rihanna, et T'sun Umbrella",
  "Tu es la seule et l'unique, tu as été le déclic",
  'Toi et moi contre le monde, personne peut nous tester',
  'Meilleure équipe : the best team',
  "Toi et moi contre le monde : t'inquiètes, ça ira",
  "Je réalise la chance que j'ai que tu me supportes",
  "Merci d'être celle qui partage ma vie",
  "Que je suis ta star, je t'illumine dans le noir",
  "T'es ma star, je suis ton paparazzi",
  'Tu es ma star, ma star à moi',
  "Tu es ma star, tu m'illumines dans le noir",
  'Oh oh, ma star ! Eh, eh, ma star !',
  "Toi qui me guide et ravive en moi l'étincelle",
  "Tu sais que pour toi j'ai de l'estime",
  'Tu me feras toujours passer avant ta pote'
];

List<String> bde = [
  "J'ai rien dis",
  'On te donne ta chance',
  'Mama excuse mais',
  "J'ai meme menti",
  "Besoin d'évasion",
  'Avant que je dézele',
  'Sans calcul me tente',
  'A panam je sature',
  "Ne croie pas que quand t'es jeune",
  "D'un véritable exil",
  'Donc je chante:',
  'Pas ma famille, mes amis',
  "Et si tu te demande colonel esqu'il est sérieux",
  'Pourquoi faire?',
  'Partir sur un coup de téte',
  "Jte parle d'éxil",
  'Oh oh yeah',
  "Ici t'es mort d'avance",
  'Faut que je me décide',
  'Rester vivre a paris',
  'Oh oh yeah oh (bis)',
  "Voie le sourire je d'ésquisse",
  "Besoin d'aire pur",
  'Une seule vie',
  "A l'idée de partir",
  "En quéte de vérité j'ai chercher",
  'Mais au mépris des hommes',
  'Mais si tu prend pas sur toi',
  'Dans ma téte une prison',
  'Je me sens mal ici',
  'Retrouver la nature',
  "Ou sont passé l'amoure et l'harmonie?",
  "No body's",
  "Tout pour des biachs et l'harmonie",
  'Envie de faire mes valises pas que pour les vacances',
  'Une chose est sur',
  'Je me suis heurté',
  "Avec le mal j'ai flirté",
  'Plus le temmps passe et plus jme demande',
  'Ici tout est gris',
  'Cqui se passe hors de france',
  'Je dois me faire une raison',
  'Un vide si immense',
  'Faire les bons choix',
  'Lalalala'
];
