List<String> ld = [
  "Pas d'états d'âme, pas de tourments",
  'Libérée, délivrée',
  'La neige est reine à son tour',
  'Quand on prend de la hauteur',
  'Le bien, le mal, je dis tant pis',
  'Ma place est là, pour toujours',
  "La tristesse, l'angoisse et la peur",
  'De sentiments',
  'Non, je ne pleure pas',
  "Perdue dans l'hiver",
  'Un royaume de solitude',
  'Je ne mentirai plus jamais',
  "Je suis là, comme je l'ai rêvé",
  'Fais attention, le secret survivra',
  'Le vent qui hurle en moi ne pense plus à demain',
  "J'ai laissé mon enfance en été",
  "Mon âme s'exprime en dessinant et sculptant dans la glace",
  'Tant pis',
  'Plus de princesse parfaite',
  "Cache tes pouvoirs, n'en parle pas",
  'Je veux voir ce que je peux faire',
  'Les étoiles me tendent les bras',
  "J'ai lutté en vain",
  'Le passé est passé',
  'Je ne reviendrai pas',
  "Mon pouvoir vient du ciel et envahit l'espace",
  'Et mes pensées sont des fleurs de cristal gelées',
  'De cette magie pleine de mystère',
  "L'hiver s'installe doucement dans la nuit",
  'Il est bien trop fort',
  "Désormais plus rien ne m'arrête",
  "M'ont quittée depuis longtemps",
  'Tout semble insignifiant',
  'Le froid est pour moi le prix de la liberté',
  'Me voilà, oui, je suis là',
  "C'est décidé, je m'en vais"
];

List<String> slo = [
  "Toi t'aimerai bien vivre sur terre, bonjour la calamité",
  "Tu voit l'esturgeon et la raie, se sont lancés dans le reggae",
  "Sous l'océan",
  "Sous l'océan, sous l'océan, doudou c'est bien mieux",
  'Vas y souffle mon doudou (hahahaha)',
  'On fait carnaval tout les jours, mieux tu ne pourra pas trouver',
  "On a le rythme c'est la dynamite! sous l'océan",
  'Nous le jazzband et tout les copains',
  "Pendant qu'on plonge, comme des éponges!",
  "Sous l'océan (Choeur)",
  "Sous l'océannnnnnnnnnnnn",
  'On met des jingjag (?)',
  'Toubeau (?) au bongo (?)',
  "On est en trans faut qu'ca balance!",
  "Dans l'océan parfumé!",
  "Le lieu est le dieu d'la soooul (OUAIS)",
  'Les vagues sont un vrai régale',
  "Là-haut ils s'écaillent et ils flippent, a tourner dans leurs bocale",
  "Pas d'soupe de poisson, pas d'marmiton!",
  'Pour la tambouille on leur dit non',
  'Le thon garde le ton',
  'Esclavagés ou isolés',
  'Ca balance ca swing!',
  "Ils ont du sable ca c'est certain!",
  "La carpe joue d'la harpe",
  "Ariel, écoute moi, chez les humains, c'est la pagaille!",
  'Ouiiiiii',
  "On déambule, on fait des bulles! Sous l'océaaan. (Choeur)",
  'On a des cliclac',
  'Comme la sardine begin de begin (??)',
  'Chez leur copain cannibale',
  'Le bar et le sprate (?)',
  "Les soles rock n' roll",
  'Maqueraux aux saxos',
  'Et les bigorno vous donnent le tempo',
  'Gardon au violon',
  'Les limace dinnent',
  'Le thon au fluton',
  'La vie est super mieux que sur la terre je te le dit!',
  "C'est les rois du rap",
  "Se marre et s'eclate!",
  "Le roseau est toujours plus vert, dans le marais d'a coté",
  "Sous l'océan y'as pas d'hamecons",
  "Sous l'océan, sous l'océan",
  "Regarde bien le monde qui t'entoure",
  "Au rythme d'(?)",
  "Tout l'monde est heureux sous l'océan!",
  "Le bocale faut dire c'est l'extase",
  "C'est frénétique c'est fantastique",
  "Chez nous les poissons s'fendent la pipe",
  "Sous l'océan, sous l'océan, y'as pas d'courbouillon",
  "La vie sous la mer c'est bien mieux qu'la vie qu'ils ont la haut sur terre",
  "La rascasse d'la basse",
  'La raie au djembé',
  "Si (...) poisson n'est pas sage, il finira dans la poele (oh non!)",
  'Là haut ils bossent toute la journée',
  "Sous l'océan, hahahaha"
];

