List<String> loc = [
  'AA.VV.',
  'A bene placito',
  'A bove ante, ab asino retro, a stulto undique caveto',
  'A bove majore discit arare minor',
  'A cælo usque ad centrum',
  'A cane non magno sæpe tenetur aper',
  'A capite ad calcem',
  'A contrario',
  'A Deucalione',
  'A divinis',
  'A falsis principiis proficisci',
  'A fluctibus opes',
  'A fortiori',
  'A latere',
  'A majori ad minus',
  'A mari usque ad mare',
  'A minima',
  'A minori ad majus',
  'A mundo condito',
  'A parte',
  'A pedibus usque ad caput',
  'A posse ad esse non valet consequentia',
  'A posteriori',
  'A priori',
  'A quia',
  'A silentio',
  'A.E.I.O.U. = Austria Est Imperare Orbi Universo',
  'A.M.D.G. ː Pour la plus grande gloire de Dieu',
  'Ab absurdo',
  'Ab æterno',
  'Ab agendo',
  'Ab ante',
  'Ab antiquo',
  'Ab amicis honesta petamus',
  'Ab epistulis',
  'Ab esse ad posse valet, a posse ad esse non valet consequentia',
  'Ab extra',
  'Ab hinc',
  'Ab hoc et ab hac',
  'Ab igne ignem capere',
  'Ab imo pectore',
  'Ab inconvenienti',
  'Ab incunabulis',
  'Ab initio',
  'Ab intestat',
  'Ab irato',
  'Ab Jove principium',
  'Ab origine fidelis',
  'Ab ovo',
  'Ab ovo usque ad mala',
  'Ab uno disce omnes',
  'Ab urbe condita',
  'Aberatio ictus',
  'Abistis, dulces caricæ',
  'Abrogata lege abrogante non reviviscit lex abrogata',
  'Absens hæres non erit',
  'Absentem lædit, qui cum ebrio litigat',
  'Absit invidia (verbo)',
  'Absit omen',
  'Absit reverentia vero',
  'Absolutum dominium',
  'Abstulit qui dedit',
  'Absque argento omnia vana',
  'Abundans cautela non nocet',
  'Abusus non tollit usum',
  'Abyssus abyssum invocat',
  'Accessorium sequitur principale',
  'Accipe quam primum, brevis est occasio lucri',
  'Acta fabula est',
  'Acta sanctorum',
  'Actibus immensis urbs fulget massiliensis',
  'Actio personalis moritur cum persona',
  'Actore non probante, reus absolvitur',
  'Actori incumbit probatio',
  'Actum est de republica',
  'Actus dicatur bonus qui est conformis legi et rationi',
  'Ad arbitrium',
  'Ad astra',
  'Ad augusta per angusta',
  'Ad gloriam',
  'Ad hoc',
  'Ad hominem',
  'Ad honorem',
  'Ad honores',
  'Ad impossibilia nemo tenetur',
  'Ad infinitum',
  'Ad interim',
  'Ad kalendas græcas',
  'Ad libitum',
  'Ad litem',
  'Ad litteram',
  'Ad lucem',
  'Ad majorem Dei gloriam',
  'Ad multos annos !',
  'Ad nauseam',
  'Ad nutum',
  'Ad oculos',
  'Ad patres',
  'Ad pedem litteræ',
  'Ad perpetuam rei gloriam',
  'Ad rem',
  'Ad undas',
  'Ad unguem',
  'Ad usum Delphini',
  'Ad valorem',
  'Ad victoriam !',
  'Ad vitam æternam',
  'Adæquatio intellectus et rei',
  'Adæquatio intellectus nostri cum re',
  'Adde parvum parvo magnus acervus erit',
  'Addendum',
  'Adeo in teneris consuescere multum est',
  'Adhuc tua messis in herba est',
  'Adhuc sub judice lis est',
  'Adsum',
  'Adversus periculum naturalis ratio permittit se defendere',
  'Adversus solem ne loquitor',
  'Ægroto dum anima est, spes est',
  'Æquam memento servare mentem',
  'Æque principaliter',
  'Æquo pulsat pede',
  'Ære perennius exegi monumentum',
  'Æs triplex',
  'Ætatis suæ',
  'Æternum vale',
  'Ævo rarissima nostro simplicitas',
  'Affidavit',
  'Affirmanti incumbit probatio',
  'Age quod agis !',
  'Agenda',
  'Agere sequitur (esse)',
  'Agnosco veteris vestigia flammæ',
  'Agnus Dei',
  'Ait prætor : si non habebunt advocatum, ego dabo',
  'Albo lapillo diem notare',
  'Alea jacta est',
  'Aliam vitam, alio mores',
  'Alias',
  'Alibi',
  'Aliis si licet, tibi non licet',
  'Aliquid stat pro aliquo',
  'Aliquis non debet esse judex in propria causa',
  'Alis aquilæ',
  'Aliud est celare, aliud tacere',
  'Alius et idem',
  'Alma mater',
  'Alma parens',
  'Alpha et Omega',
  'Alta alatis patent',
  'Alter ego',
  'Alterius non sit, qui potest esse sui',
  'Alterum non lædere',
  'Alumnus, Alumni',
  'Ama et fac quod vis',
  'Ama nesciri',
  'Amant alterna camenæ',
  'Amare et sapere vix deo conceditur',
  'Ambitiosa recidet ornamenta',
  'Amici, diem perdidi',
  'Amicus certus in re incerta cernitur',
  'Amicus humani generis',
  'Amicus optima vitæ possessio',
  'Amicus Plato, sed magis amica veritas',
  'Amor et melle et felle fecundissimus es',
  'Amor fati',
  'Amor mundum fecit',
  'Amor omnibus idem',
  'Amor patitur moras',
  'Amor patriæ nostra lex',
  'Amor tussisque non celatur',
  'Amor vincit omnia',
  'Amore, more, ore, re',
  'An nescis, mi fili, quantilla prudentia mundus regatur',
  'Anguis in herba',
  'Anima sana in corpore sano',
  'Animo deliberato',
  'Animus furandi',
  'Animus imperat corpori',
  'Animus meminisse horret',
  'Annibal ad portas',
  'Anno Domini',
  'Annuit Cœptis',
  'Annus horribilis',
  'Annus mirabilis',
  'Ante cibum',
  'Ante litteram',
  'Ante domino',
  'Ante meridiem',
  'Ante mortem',
  'Ante prandium',
  'Aperietur vobis',
  'Aperto libro',
  'Aperit et nemo claudit',
  'Apparatus criticus',
  'Aqua et igne interdictus',
  'Aqua fortis',
  'Aqua regia',
  'Aqua vitæ',
  'Aquila non capit muscas',
  'Arbiter elegantiarum',
  'Arcades ambo',
  'Argentoratum locutum judicium finitum',
  'Arguendo',
  'Argumentum a silentio',
  'Argumentum ad antiquitatem',
  'Argumentum ad captandum',
  'Argumentum ad consequentiam',
  'Argumentum ad crumenam',
  'Argumentum ad feminam',
  'Argumentum ad hominem',
  'Argumentum ad ignorantiam',
  'Argumentum ad judicium',
  'Argumentum ad lazarum',
  'Argumentum ad logicam',
  'Argumentum ad metum',
  'Argumentum ad misericordiam',
  'Argumentum ad naturam',
  'Argumentum ad nauseam',
  'Argumentum ad novitatem',
  'Argumentum ad numerum',
  'Argumentum ad odium',
  'Argumentum ad personam',
  'Argumentum ad populum',
  'Argumentum ad temperantiam',
  'Argumentum ad verecundiam',
  'Argumentum baculinum',
  'Argumentum ex silentio',
  'Ars (est) celare artem',
  'Ars gratia artis',
  'Ars longa, vita brevis',
  'Ars similis casus',
  'Artem quævis alit terra',
  'Asinus ad lyram',
  'Asinus asinorum in sæcula sæculorum',
  'Asinus asinum fricat',
  'Asinus equum spectat',
  'Asinus in tegulis',
  'At spes non fracta',
  'Atqui, e lotio est',
  'Audaces fortuna juvat',
  'Audax Japeti genus',
  'Audere est facere',
  'Audi, vide, tace, si vis vivere',
  'Audi alteram partem',
  'Aura popularis',
  'Aurae mediocritas',
  'Auri sacra fames',
  'Auribus teneo lupum',
  'Aut agere aut mori',
  'Aut amat aut odit mulier, nil est tertium',
  'Aut bibat aut abeat',
  'Aut Cæsar, aut nihil',
  'Aut dedere aut punire',
  'Aut disce aut discede',
  'Aut dosce, aut disce, aut discede',
  'Aut nunc, aut numquam',
  'Aut omnia, aut nihil',
  'Aut pati aut mori',
  'Aut viam inveniam aut faciam',
  'Aut vincere, aut mori',
  'Autobi passebant completi',
  'Avaro omnia desunt, inopi pauca, sapienti nihil',
  'Avarus nisi cum moritur, nil recte facit',
  'Avaritia facit bardus',
  'Ave atque vale',
  'Ave Cæsar, morituri te salutant',
  'Ave Maria',
  'Ave Verum (Corpus)',
  'Barba tenus sapientes',
  'Barba non facit philosophum',
  'Beata Virgo Maria',
  'Beatæ memoriæ',
  'Beati hispani, quibus vivere bibere est',
  'Beati monoculi in terra cœcorum',
  'Beati pauperes in spiritu',
  'Beati possidentes',
  'Beatus homo qui invenit sapientiam',
  'Beatus ille qui procul negotiis',
  'Beatus qui prodest quibus potest',
  'Bella horrida bella',
  'Bella gerant alii',
  'Bella matribus detestata',
  'Bellum omnium contra omnes',
  'Bellum se ipsum alet',
  'Bene diagnoscitur, bene curatur',
  'Bertha rosas, Heotrud violas dat',
  'Bene qui latuit bene vixit',
  'Bis dat, qui cito dat',
  'Bis repetita placent',
  'Bis repetita non placent',
  'Bona fide',
  'Bona fides contraria est fraudi et dolo',
  'Bona valetudo melior est quam maximæ divitiæ',
  'Boni pastoris est tondere pecus, non deglubere',
  'Bonum ex malo non fit',
  'Bonum vinum lætificat cor hominis',
  'Brevitatis causa',
  'c.',
  'ca.',
  'Cacoethes scribendi',
  'Cadavera vero innumera',
  'Cædite eos. Novit enim Dominus qui sunt ejus',
  'Cælum non animum mutant qui trans mare currunt',
  'Cæsar non supra grammaticos',
  'Cætera desunt (latin médiéval)',
  'Camera obscura',
  'Canis pugnax',
  'Canis canem edit',
  'Canis sine dentibus vehementius latrat',
  'Cantabit vacuus coram latrone viator',
  'Canularium',
  'Capax Infiniti',
  'Captatus, bene judicatus',
  'Caput inter nubila',
  'Caput mortuum',
  'Caritas in veritate',
  'Carpe diem',
  'Carpent tua poma nepotes',
  'Carthago delenda est',
  'Castigat ridendo mores',
  'Casus belli',
  'Causa latet, vis est notissima',
  'Causa mortis',
  'Cave canem',
  'Cave ne cadas',
  'Cave nil vino',
  'Caveant consules ne quid detrimenti respublica capiat',
  'Caveat emptor',
  'Cedant arma togæ',
  'Celerius quam asparagi cocuntur',
  'Certamen bonum certavi',
  'Cessante causa legis, cessat lex',
  'Cetera desunt',
  'Ceteris paribus',
  'cf. cf.',
  'Christianos ad leones',
  'Christus nos liberavit',
  'Christus Rex',
  'Cibi condimentum est fames',
  'Circa',
  'Circulus in probando',
  'Circulus vitiosus',
  'Citius, altius, fortius',
  'Cito, longe, tarde',
  'Claves Sancti Petri',
  'Clavis aurea',
  'Clericus vagans',
  'Codex Juris Canonicis',
  'Cœtera desunt (latin médiéval)',
  'Cœteris paribus (latin médiéval)',
  'Cogitationis poenam nemo patitur',
  'Cogito ergo sum',
  'Coitus interruptus',
  'Coitus more ferarum',
  'Collige virgo rosas',
  'Combinatio nova',
  'Communibus locis',
  'Communicatio idiomatum',
  'Communis opinio',
  'Compos mentis',
  'Concordia civium murus urbium',
  'Condemnant quod non intellegunt',
  'Conditio sine qua non',
  'Confessio est regina probatio',
  'Confer',
  'Confœderatio Helvetica',
  'Conjunctis viribus',
  'Consuetudinis vis magna est',
  'Consuetudo altera natura est',
  'Consuetudo est jus quodam moribus institutum, quod pro lege usurpatur ubi deficit lex',
  'Consummatum est',
  'Contemptus sæculi',
  'Contemplata aliis tradere',
  'Contra bonos mores',
  'Contra factum non datur argumentum',
  'Contra legem',
  'Contra principia negantem non est disputandum',
  'Contra spem in spem credidit',
  'Contra vim mortis non est medicamen in hortis',
  'Contradictio in terminis',
  'Cor ad cor loquitur',
  'Cor unum',
  'Coram Deo',
  'Coram populo',
  'Corpus Christi',
  'Corpus delicti',
  'Corpus Juris Canonici',
  'Corpus Juris Civilis',
  'Corrigenda',
  'Corruptio optimi pessima',
  'Corruptissima re publica plurimæ leges',
  'Cras amet qui nunquam amavit ; quique amavit, cras amet',
  'Credat Judæus Apella',
  'Credo in Unum Deum',
  'Credo quia absurdum',
  'Crimen læsæ majestatis',
  'Cui bono ?',
  'Cui prodest',
  'Cuique suum reddere',
  'Cujus regio, ejus religio',
  'Cujusvis hominis est errare',
  'Culpa lata dolo æquiparatur',
  'Cum grano salis',
  'Cum hoc ergo propter hoc',
  'Cum laude',
  'Cum tacent, consentiunt',
  'Cupio dissolvi',
  'Cura ut valeas !',
  'Curriculum vitæ',
  'Custos morum',
  'Da mihi factum, dabo tibi jus',
  'Damnant quod non intelligunt',
  'Damnatio memoriæ',
  'Damnum absque injuria',
  'Dat veniam corvis, vexat censura columbas',
  'Data venia',
  'Davus sum, non Œdipus',
  'De commodo et incommodo',
  'De dicto',
  'De facto',
  'De gustibus coloribusque non disputandum',
  'De integro',
  'De internis non judicat prætor',
  'De jure.',
  'De jure uxoris',
  'De lege feranda',
  'De lege lata',
  'De minimis non curat lex',
  'De minimis non curat prætor',
  'De mortuis aut bene aut nihil',
  'De mortuis nihil nisi bonum',
  'De nilo nil',
  'De nobis fabula narratur',
  'De non vigilantibus non curat prætor',
  'De novo',
  'De omni re scibili',
  'De omnibus dubitandum',
  'De primis socialismi germanici lineamentis apud Lutherum, Kant, Fichte, Hegel et Marx',
  'De profundis clamavi',
  'De re',
  'De stercore Enii',
  'De te fabula narratur',
  'De viris',
  'De visu',
  'Debellare superbos',
  'Decet imperatorem stantem mori',
  'Decipimur specie recti',
  'Dei Gratia Regina',
  'Dei Gratia Rex',
  'Delectatio morosa',
  'Delenda Carthago',
  'Delicta juventutis meæ',
  'Deliriant isti Romani',
  'Dente superbo',
  'Deo gratias',
  'Deo juvante',
  'Deo Optimo Maximo (D.O.M.)',
  'Deo volente',
  'Desiderata',
  'Desinit in piscem mulier formosa superne',
  'Desipere est juris gentium',
  'Desipere in loco',
  'Deus dedit, deus abstulit, sit nomen domini benedictum',
  'Deus ex machina',
  'Deus caritas est',
  'Deus sive Natura',
  'Deus vult',
  'Di meliora piis',
  'Diem perdidi',
  'Dies iræ',
  'Difficiles nugæ',
  'Dignus est intrare',
  'Dilige et quod vis fac',
  'Dis aliter visum',
  'Dis manibus sacrum (D.M.S.)',
  'Disjecta membra',
  'Distinguo',
  'Divide et impera',
  'Dixi',
  'Dixit',
  'Do ut des',
  'Docendo discitur',
  'Doctus cum libro',
  'Doctus cum libro similis asino',
  'Dolus an virtus quis in hoste requirat ?',
  'Domine dirige nos',
  'Domine salvam fac reginam',
  'Domine salvum fac regem',
  'Dominus vobiscum',
  'Domus accipere debemus, non proprietatem domus, sed domicilium',
  'Dona nobis pacem',
  'Donec eris felix, multos numerabis amicos',
  'Dramatis personæ',
  'Ducunt volentem fata, nolentem trahunt',
  'Dulce bellum inexperti',
  'Dulce et decorum est pro patria mori',
  'Dulce et utile',
  'Dum Roma deliberat Saguntum perit',
  'Dum spiro, spero',
  'Dum vita est, spes est',
  'Dum vitant stulti vitia in contraria currunt',
  'Duos habet et bene pendentes !',
  'Duplex legum incertudino ; altera ubi lex nulla præscribitur, altera ubi ambigua et obscura',
  'Dura lex, sed lex',
  'Dura mater',
  'Dura necessitas',
  'Dux bellorum',
  'E fructu arbor cognoscitur',
  'E Pluribus Unum',
  'Ecce panis angelorum',
  'Ecce Homo',
  'Ecclesia abhorret sanguinem ou Ecclesia abhorret a sanguine',
  'Editio princeps',
  'Ego non',
  'Ego sum qui sum',
  'Ego te absolvo',
  'Eheu fugaces labuntur anni',
  'Ejusdem generis',
  'Ejusdem farinæ',
  'Ejusdem furfuris',
  'Ens causa sui',
  'Entitas ipsa involvit aptitudinem ad extorquendum certum assensum',
  'Eo ipso',
  'Epicuri de grege porcum',
  'Equo ne credite',
  'Erga omnes',
  'Ergo',
  'Ergo glu capiuntur aves',
  'Eritis sicut dii',
  'Errata',
  'Erratum',
  'Errare humanum est, perseverare diabolicum',
  'Error communis facit jus',
  'Esse quam videri',
  'Esto laborator, et erit Deus auxiliator',
  'Et alibi',
  'Et alii',
  'Et campos ubi Troja fuit',
  'Et cetera',
  'Et cum spiritu tuo',
  'Et cætera Voir',
  'Et cœtera Voir',
  'Et facta est lux',
  'Et in Arcadia ego',
  'Et lux in tenebris lucet',
  'Et nunc reges, intelligite… erudimini, qui judicatis terram',
  'Et sequentes',
  'Et seq. Abréviation de Et sequentes',
  'Et suppositio nil ponit in esse',
  'Et tu Brute',
  'etc. Abréviation de Et cetera',
  'Etiam innocentes cogit mentiri dolor',
  'Etiam periere ruinæ',
  'Etiamsi omnes, ego non',
  'Ex abrupto',
  'Ex abstracto',
  'Ex æquo',
  'Ex Africa semper aliquid novi',
  'Ex animo',
  'Ex-ante',
  'Ex cathedra',
  'Ex dolo malo',
  'Ex dono',
  'Ex falso sequitur quod libet',
  'Ex gratia',
  'Ex hypothesi',
  'Ex infra',
  'Ex libris',
  'Ex malo bonum',
  'Ex mea sententia',
  'Ex nihilo nihil',
  'Ex nihilo nihil fit',
  'Ex novo',
  'Ex nudo pacto Abréviation de Ex nudo pacto oritur actio nudum a solemnitate sed non nudum a causa',
  'Ex officio',
  'Ex opere operantis',
  'Ex opere operato',
  'Ex pede Hercule',
  'Ex-post',
  'Ex silentio',
  'Ex situ',
  'Ex supra',
  'Ex tempore',
  'Ex tenebris lux',
  'Ex ungue leonem',
  'Ex vi termini',
  'Ex vulgus scientia',
  'Ex vivo',
  'Ex voto',
  'Ex-voto',
  'Exceptio est strictissimæ interpretationis',
  'Exceptio firmat regulam in casibus non exceptis',
  'Exceptio plurium concumbentium',
  'Excusatio non petita accusatio manifesta',
  'Exeat',
  'Exegi monumentum ære perennius',
  'Exempli gratia',
  'Exemplum est argumentatio in qua ex uno singulari infertur, quod fieri potest a pari, vel a contrario, vel a fortiori',
  'Exeunt',
  'Exit',
  'Exoriare aliquis nostris ex ossibus ultor',
  'Experimentum crucis',
  'Extra ecclesiam nulla salus',
  'Extra omnes',
  'Fabricando fit faber',
  'Fac simile',
  'Fama volat',
  'Felix culpa',
  'Felix qui potuit rerum cognoscere causas',
  'Fere libenter homines id quod volunt credunt',
  'Festina lente',
  'Fex urbis, lex orbis',
  'Fiat justicia pereat mundus',
  'Fiat Lux',
  'Fiat voluntas tua',
  'Fide, sed cui vide',
  'Fidei Defensor',
  'Finis coronat opus',
  'Flagellum Dei',
  'Flagrante delicto',
  'Florebo quocumque ferar',
  'Fluctuat nec mergitur',
  'Forsan et hæc olim meminisse juvabit',
  'Fontes aquarum',
  'Fortes fortuna juvat',
  'Fortissimi sunt belgæ',
  'Fortuna cæca est',
  'Fragrans feminæ',
  'Fraus omnia corrumpit',
  'Fugit irreparabile tempus',
  'Furor arma ministrat',
  'Gaudeamus hodie',
  'Gaudeamus igitur',
  'Gaudium in veritate',
  'Generalia specialibus non derogant',
  'Generis virtus nobilitas !',
  'Genius loci',
  'Gens humana ruit per vetitum',
  'Genus irritabile vatum',
  'Gesta non verba',
  'Gladius legis custos',
  'Gloria in Excelsis Deo',
  'Gloria Patri',
  'Gloria Patri et Filio et Spiritui Sancto',
  'Gloria victis',
  'Græcia capta ferum victorem cepit',
  'Græcum est, non legitur',
  'Grammatici certant',
  'Gratis pro deo',
  'Graviora manent',
  'Grosso modo',
  'Gutta cavat lapidem (non vi sed sæpe cadendo)',
  'habeas corpus',
  'Habemus papam',
  'Habent sua fata libelli',
  'Hannibal ad portas',
  'Hic et nunc',
  'Hic et ubique terrarum',
  'Hic jacet lepus',
  'Hic Rhodus, hic salta',
  'Hic sunt dracones',
  'Hic terminus hæret',
  'Hoc signo vinces',
  'Hodie mihi, cras tibi',
  'Homines quod volunt credunt',
  'Homo homini lupus est',
  'Homo sum, humani nil a me alienum puto',
  'Honoris causa',
  'Hora fugit, stat jus',
  'Horas non numero nisi serenas',
  'Horum omnium fortissimi sunt Belgæ',
  'Horresco referens',
  'Horribile dictu',
  'Hostis humani generis',
  'I tego arcana dei',
  'i.e. Abréviation de id est',
  'Ibi deficit orbis',
  'Ibid. Abréviation de Ibidem',
  'Ibidem',
  'Id est',
  'Idem',
  'Idus Martiæ',
  'Jesus Nazarenus Rex Judæorum (INRI)',
  'Ignorantia juris nocet (Ignorantia juris nocet)',
  'Ignorantia juris non excusat',
  'Ignorantia juris neminem excusat (Ignorantia juris neminem excusat)',
  'Ignorantia legis non excusat',
  'Ignoti nulla cupido',
  'Ignotum per ignotius',
  'Imitatio dei',
  'Imperium in imperio',
  'Imperium sine fine',
  'Impossibilia nulla tenetur',
  'Imprimatur',
  'In',
  'In absentia',
  'In actu',
  'In articulo mortis',
  'In cauda venenum',
  'In dubio contra fiscum',
  'In dubio pro reo',
  'In dubiis abstine',
  'In duplo',
  'In extenso',
  'In extremis',
  'In fine',
  'In girum imus nocte et consumimur igni',
  'In hoc senso ou In sensu hoc',
  'In hoc signo vinces',
  'In hunc effectum',
  'In illo tempore',
  'In loco',
  'In manus tuas commendo spiritum meum',
  'In medias res',
  'In medio stat virtus',
  'In memoriam',
  'In naturalibus',
  'In nocte consilium',
  'In nuce',
  'In omnia paratus',
  'In pari causa turpitudinis cessat repetitio',
  'In partibus infidelium',
  'In pectore',
  'In personam',
  'In principio erat Verbum',
  'In rerum natura',
  'In silico',
  'In situ',
  'In toto',
  'In utero',
  'In utroque jure',
  'In vacuo',
  'In varietate concordia',
  'In vino veritas',
  'In vitam æternam',
  'In vitro',
  'In vivo',
  'Incredibile dictu',
  'Index Librorum Prohibitorum',
  'Infandum, regina, jubes renovare dolorem',
  'INRI Abréviation de (INRI)',
  'Intelligenti pauca',
  'Inter alia',
  'Inter arma silent leges',
  'Inter fæces et urinam nascimur',
  'Into Vinceres',
  'Intra muros',
  'Intuitu personæ',
  'Interpretatio cessat in claris',
  'Ipsa scientia potestas est',
  'Ipse dixit',
  'Ipso facto',
  'Ira furor brevis est',
  'Irritare crabrones',
  'Is fecit, cui prodest',
  'Is pater est quem nuptiæ demonstrant',
  'Is qui tacet non fatetur, sed nec utique negare videtur',
  'Ita diis placuit !',
  'Ite missa est1',
  'Item',
  'Jesus Nazarenus Rex Judæorum Jésus de Nazareth, Roi des Juifs. Voir aussi INRI',
  'Jovis erepto fulmine per inferna vehitur Promethei genus',
  'Junctis viribus',
  'Jurare in verba magistri',
  'Jure uxoris',
  'Juris præcepta sunt hæc : honeste vivere, alterum non lædere, suum cuique tribuere',
  'Jus est ars boni et æqui',
  'Jus gentium',
  'Jus in bello',
  'Jus primæ noctis',
  'Jus sanguinis',
  'Jus soli',
  'Justicia omnibus',
  'Juventus stultorum magister',
  'Labor omnia vincit improbus',
  'Laborare est orare',
  'Lacrimis struit insidias cum femina plorat',
  'Lapsus',
  'Lapsus calami',
  'Lapsus linguæ',
  'Lassata sed non satiata',
  'Lata sententia judex desinit esse judex',
  'Lato sensu',
  'Laudator temporis acti',
  'Laus Deo',
  'Leges instituuntur dum promulgantur',
  'Lex cessat, si finis adæquatus cessat, non vero si particulari',
  'Lex est quod notamus',
  'Lex moneat priusquam feriat',
  'Lex naturalis non scribitur, sed profluit quodam naturali fonte in singulis exprimititur',
  'Lex non promulgata non obligat',
  'Lex non scripta',
  'Lex parsimoniæ',
  'Lex ratio perfecta a rerum natura',
  'Lex talionis',
  'Libera nos a malo',
  'Libera te tutemet ex inferis',
  'Liberate me ex inferis',
  'Libidini nihil inhonestum',
  'Libido imperandi',
  'Libido sciendi',
  'Loc. cit. Abréviation de Loco citato',
  'Loc. laud. Abréviation de Loco laudato',
  'Loco citato',
  'Loco laudato',
  'Locus regit actum',
  'Loqui cum grano salis',
  'Lux in tenebris',
  'Macte animo, generose puer ! sic itur ad astra',
  'Magister dixit',
  'Magna cum laude',
  'Magna est vis consuetudinis',
  'Magno cum gaudio',
  'Magnum opus',
  'Major e longinquo reverentia',
  'Major pœna minorem absorbat',
  'Majores pennas nido',
  'Mala malus mala mala dat',
  'Malitiis non est indulgendum',
  'Malum discordiæ',
  'Manu militari',
  'Manus dei',
  'Manus manum lava',
  'Mare nostrum',
  'Margaritas ante porcos',
  'Mater Dei',
  'Maxima debetur puero reverentia',
  'Mea culpa',
  'Medicus curat, natura sanat',
  'Medice, cura te ipsum',
  'Memento mori',
  'Memento audere semper',
  'Memento quia pulvis es',
  'Mens sana in corpore sano',
  'Mihi cura futuri',
  'Minima de malis',
  'Minimum minimorum',
  'Miserere nobis',
  'Missi dominici',
  'Moderatio in omnibus',
  'Modus operandi',
  'Modus vivendi',
  'Moneat lex priusquam feriat',
  'More ferarum',
  'Mors, ubi est victoria tua',
  'Morituri te salutant',
  'Motu proprio',
  'Multa paucis',
  'Multa remittuntur ei peccata quia dilexit multum',
  'Multi sunt vocati, pauci vero electi',
  'Mutatis mutandis',
  'N.B. Abréviation de Nota bene',
  'Nam et ipsa scienta potestas est',
  'Natare piscem doces',
  'Natura abhorret a vacuo',
  'Natura naturans',
  'Natura naturata',
  'Natura nihil frustra facit',
  'Natura non contristatur',
  'Natura non facit saltus',
  'Naturam expelles furca, tamen usque recurret',
  'Ne bis in idem',
  'Ne quid nimis',
  'Ne varietur',
  'Nec Hercules contra plures',
  'Nec plus ultra',
  'Nec pluribus impar',
  'Nec spe, nec metu',
  'Nec ut emat melius, nec ut vendat, quidquam simulabit aut dissimulabit vir bonus',
  'Necessitas reducit ad moerum jus naturæ',
  'Neminem lædit qui suo jure utitur',
  'Nemo admittitur sibi nocere',
  'Nemo auditur propriam turpitudinem allegans',
  'Nemo damnatus sine judicio',
  'Nemo est supra legis',
  'Nemo judex in causa sua',
  'Nemo judex sine lege',
  'Nemo legem ignorare censetur',
  'Nemo me impune lacessit',
  'Nemo plus juris ad quiam transfere potest quam ipse habet',
  'Nemo tenetur se ipsum accusar',
  'Neque ignorare medicum oportet quæ sit ægri natura',
  'Nigro notanda lapillo',
  'Nihil conveniens decretis ejus !',
  'Nihil est in intellectu quod non sit prius in sensu',
  'Nihil est sine ratione',
  'Nihil lacrima citius arescit',
  'Nihil novi sub sole',
  'Nihil obstat',
  'Nihil sine Deo',
  'Nil desperandum',
  'Nil mortalibus ardui est',
  'Nil nisi bonum',
  'Nil sine numine',
  'Nil volentibus arduum',
  'Nolens, volens',
  'Noli me tangere',
  'Noli turbare circulos meos',
  'Nolite mittere margaritas ante porcos',
  'Nomen est omen',
  'Nomina si nescis, perit et cognitio rerum',
  'Non ædificandi',
  'Non æs sed fides',
  'Non bene olet qui semper bene olet',
  'Non bis in idem',
  'Non canimus surdis',
  'Non fui, fui, non sum, non curo',
  'Non idem est si duo dicunt idem',
  'Non licet omnibus adire Corinthum',
  'Non liquet',
  'Non nisi parendo vincitur',
  'Non nobis, Domine, non nobis, sed Nomini Tuo da gloriam',
  'Non omne quod licet honestum est',
  'Non omnia possumus omnes',
  'Non possumus',
  'Non scholæ, sed vitæ discimus',
  'Non serviam',
  'Non una cum',
  'Non ut edam vivo, sed ut vivam edo',
  'Non vestimentum virum ornat, sed vir vestimentum',
  'Non vini vi no, sed vi no aquæ',
  'Nondum amabam, et amare amabam',
  'Nosce te ipsum',
  'Nota bene',
  'Nove sed non nova',
  'Nulla dies sine linea',
  'Nulla est medicina sine lingua latina',
  'Nullum crimen, nulla pœna sine lege',
  'Nulla pœna sine lege',
  'Nulla regula sine exceptione',
  'Nulla res tam necessaria est quam medicina',
  'Nulla tenaci invia est via',
  'Nullum crimen, nulla pœna, nullum judicium sine lege',
  'Nullus idoneus testis in re sua intelligitur',
  'Nunc est bibendum',
  'Nunc scio veritatem',
  'Numero deus impare gaudet',
  'Numerus clausus',
  'Nunquam plura delicta concurrentia faciunt ut illius impunitas datur',
  'Nutrisco et extinguo',
  'O altitudo',
  'O Crux ave, spes unica',
  'O et præsidium et dulce decus meum !',
  'O fortunatos nimium, sua si bona norint, agricolas',
  'O homines ad servitutem paratos',
  'O tempora, o mores',
  'O tempus edax !',
  'O ubi campi !',
  'Obiit',
  'Oculi plus vident quam oculus',
  'Oculos habent et non videbunt',
  'Oderint dum metuant',
  'Odi et amo',
  'Odit verus amor nec patitur moras',
  'Oleum camino',
  'Oleum perdidisti',
  'Omne ignotum pro magnifico',
  'Omne ignotum pro terribili',
  'Omne tulit punctum qui miscuit utile dulci',
  'Omnes enim qui acceperint gladium, gladio peribunt',
  'Omnes vulnerant, ultima necat',
  'Omnia dicta fortiora si dicta Latina',
  'Omnia mea mecum porto',
  'Omnia mutantur, nihil interit',
  'Omnia vincit amor',
  'Omnibus viis Romam pervenitur',
  'Omnis homo mendax',
  'Omnium artium medicina nobilissima est',
  'Onus probandi incumbit actori',
  'op. cit.',
  'Opera omnia',
  'Opera posthuma',
  'Opere citato',
  'Optimum medicamentum quies es',
  'Ora et labora',
  'Ora pro nobis',
  'Ordo ab chao',
  'Oremus pro invicem',
  'Otium cum dignitate',
  'Pacta sunt servanda',
  'Panem et circenses',
  'Par in parem non habet jurisdictionem',
  'Para bellum',
  'Parcere subjectis et debellare superbos',
  'Pari passu',
  'Passim',
  'Pater familias',
  'Pater incertus, mater semper certissima',
  'Pater omnipotens',
  'Pater Patriae',
  'Pater peccavi',
  'Patere aut abstine',
  'Patere legem quam ipse fecisti',
  'Pauca sed bona',
  'Pauca sed matura',
  'Pax æterna',
  'Pax Christi',
  'Pax Deorum',
  'Pax in terra hominibus bonae voluntatis',
  'Pax Romana',
  'Pax melior est quam iustissimum bellum',
  'Pax tecum',
  'Pax vobiscum',
  'Pecunia non olet',
  'Pede pœna claudo',
  'Per aspera ad astra',
  'Per capita',
  'Per contra',
  'Per fas et nefas',
  'Per inania regna',
  'Per os',
  'Per scientiam ad salutem ægroti',
  'Per se',
  'Perinde ac cadaver',
  'Perpetuum mobile',
  'Persona non grata',
  'Petitio principii',
  'Pia mater',
  'Pinxit',
  'Piscis primum a capite fœtet',
  'Plaudite, cives !',
  'Placere et docere',
  'Plenus venter non studet libenter',
  'Plures crapula quam gladius perdidit',
  'Plurimae leges pessima respublica',
  'Plus ultra',
  'Pœna est malum passionis propter malum actionis',
  'Pons asinorum',
  'Post aut propter',
  'Post cenam non stare sed mille passus meare',
  'Post cibum',
  'Post coitum',
  'Post hoc ergo propter hoc',
  'Post hoc non est propter hoc',
  'Post meridiem',
  'Post mortem',
  'Post mortem nihil est',
  'Post mortem nihil est ipsaque mors nihil',
  'Post prandium',
  'Post tenebras lux',
  'Potius mori quam fœdari',
  'Praemonitus praemunitus',
  'Præsente medico nihil nocet',
  'Praesumptio sumitur de eo quod plerumque fit',
  'Prævenire melius est quam præveniri',
  'Premimur non opprimimur',
  'Prima luce',
  'Primo occupanti',
  'Primum movens',
  'Primum non nocere',
  'Primum vivere deinde philosophari',
  'Primus inter pares',
  'Pro bono',
  'Pro forma',
  'Pro parte',
  'Pro tempore',
  'Probis pateo',
  'Propria manu',
  'Prorata temporis',
  'Punctum saliens',
  'Quæ sunt cæsaris, cæsari',
  'Qualis artifex pereo !',
  'Qualis pater, talis filius',
  'Quandoque bonus dormitat Homerus',
  'Quantum libet',
  'Quantum satis',
  'Quantum sufficit',
  'Quaque hora',
  'Quaque die',
  'Quaque mane',
  'Quaque nocte',
  'Quasimodo',
  'Quater in die',
  'Quem di diligunt adulescens moritur',
  'Qui bene amat, bene castigat',
  'Qui bene cantat bis orat',
  'Qui cupit aut metuit liber non erit unquam',
  'Qui dicit de omnibus dicit de singulis ; qui dicit de singulis non dicit de omnibus',
  'Qui dicit de uno negat de altero',
  'Qui est sine peccato, primum in illam lapidem mitat',
  'Qui futuri sunt moliti',
  'Qui habet aures audiendi audiat',
  'Qui nescit dissimulare nescit regnare',
  'Qui pro quo',
  'Qui rogat non errat',
  'Qui scribit bis legit',
  'Qui tacet consentire videtur',
  'Quia ego nominor leo',
  'Quia nominor leo',
  'Quia pulvis es et in pulverem reverteris',
  'Quia suam uxorem etiam suspiciore vacare vellet',
  'Quieta non movere',
  'Quid agis ?',
  'Quid est veritas ?',
  'Quid novi ?',
  'Quid novi sub sole ?',
  'Quid pro quo',
  'Quidquid agis, prudenter agas et respice finem !',
  'Quidquid discis, tibi discis',
  'Quidquid latine dictum sit, altum sonatur',
  'Quidquid recipitur, ad modum recipientis recipitur',
  'Quis, quid, ubi, quibus auxiliis, cur, quomodo, quando ?',
  'Quis separabit ?',
  'Quod ad jus naturale attinet, omnes homines æquale sunt',
  'Quod gratis asseritur gratis negatur',
  'Quo fata ferunt',
  'Quo vadis ?',
  'Quocunque jeceris stabit',
  'Quod ab omnibus, quod ubique, quod semper',
  'Quod erat demonstrandum (Q.E.D.)',
  'Quod medicina aliis aliis est acre venenum',
  'Quod omnes tangit, ab omnibus probari debet',
  'Quod scripsi, scripsi',
  'Quomodo vales ?',
  'Quorum',
  'Quot capita, tot sententiæ',
  'Quot homines tot sententiæ',
  'Quot linguas calles, tot homines vales',
  'Quousque tandem abutere, Catilina, patientia nostra ?',
  'Rara avis in terris',
  'Re',
  'Ratio legis',
  'Rebus sic stantibus',
  'Recto tono (en),',
  'Redde Cæsari quæ sunt Cæsaris, et quæ sunt Dei Deo',
  'Reductio ad absurdum',
  'Reductio ad infinitum',
  'Regina Dei gratia',
  'Regis ad exemplar totus componitur orbis',
  'Rem acu tetigisti',
  'Repetita juvant',
  'Repetitio est mater studiorum',
  'Requiescat in pace',
  'Res impura omnia impura',
  'Res ipsa loquitur',
  'Res judicata pro veritate habetur',
  'Res, non verba',
  'Res publica',
  'Res nullius',
  'Respice finem',
  'Reus in excipiendo fit actor',
  'Rex Dei gratia',
  'Rex regnat sed non gubernat',
  'Ridendo dicere verum quid vetat',
  'Rigor mortis',
  'Roma invicta',
  'Roma locuta, causa finita est',
  's.v.',
  'Sæpe morborum gravium exitus incerti sunt',
  'Saltus in demonstrando',
  'Salus ægroti suprema lex',
  'Salus populi suprema lex esto',
  'Salvator Mundi',
  'Sancta Sedes',
  'Sancta simplicitas',
  'Sanctus sanctorum',
  'Sapere aude !',
  'Sapientia est potentia',
  'Satius esse impunitum relinqui facinus nocentis quam innocentem damnare',
  'Satius est supervacua scire quam nihil',
  'Scienta potestas est',
  'Scio me nihil scire',
  'Sed satis est jam posse mori',
  'Sedes apostolica',
  'Semel in anno licet insanire',
  'Semper fidelis',
  'Semper paratus',
  'Senatus Populusque Romanus : (S.P.Q.R.)',
  'Sensu amplio',
  'Sensu lato',
  'Sensu stricto',
  'Sero sed serio',
  'Sequela Christi',
  'Si augur augurem…',
  'Si napo leo viveret, hominem non esset',
  'Si tacuisses, philosophus mansisses',
  'Si vales valeo (SVV)',
  'Si vis pacem, para bellum',
  'Si vis pacem, para justitiam',
  'Sic',
  'Sic in se sua per vestigia voluitur annus',
  'Sic itur ad astra',
  'Sic parvis magna ;',
  'Sic transit gloria mundi',
  'Sic vita est',
  'Similia similibus curantur',
  'Simplex sigillum veri',
  'Sine anno',
  'Sine die',
  'Sine ira et studio',
  'Sine labore non erit panis in ore',
  'Sine loco',
  'Sine nomine',
  'Sine nomine vulgus',
  'Sine pœna nulla lex',
  'Sine prole',
  'Sine qua non',
  'Sinite parvulos venire ad me',
  'Sint ut sunt aut non sint',
  'Sit tibi terra levis',
  'Sol lucet omnibus',
  'Sola cogitatio furti faciendi non facit furem',
  'Sola scriptura',
  'Solem lucerna non ostenderent',
  'Soli sol soli',
  'Spes contra spem',
  'Spes messis in semine',
  'Spes salutis',
  'Spiritus promptus est, caro autem infirma',
  'Spoliatis arma supersunt',
  'sqq.',
  'Stat crux dum volvitur orbis',
  'Statim',
  'Statu quo',
  'Statu quo ante bellum',
  'Stricto sensu',
  'Stultorum numerus est infinitus',
  'Stude, non ut plus aliquid scias, sed ut melius',
  'Sub judice',
  'Sub rosa',
  'Sub specie æternitatis',
  'Sub voce',
  'Sublata causa, tollitur effectus',
  'Sufficit cuique diei malitia sua',
  'Sui generis',
  'Sum quod eris',
  'Summa cum laude',
  'Summa potestas',
  'Summum bonum',
  'Summum jus, summa injuria',
  'Surge et ambula',
  'Sursum corda',
  'Sutor, ne supra crepidam',
  'Tabula rasa',
  'Talis qualis',
  'Tarde venientibus ossa',
  'Temet nosce',
  'Tempora heroica',
  'Tempora mutantur et nos mutamur in illis',
  'Tempora si fuerint nubila, solus eris',
  'Tempori servire',
  'Tempus edax, homo edacior',
  'Tempus edax rerum',
  'Tempus fugit',
  'Tempus fugit, hora volant',
  'Tempus rerum imperator',
  'Teneo lupum auribus',
  'Teneo te Africa',
  'Terminus a quo',
  'Terminus ad quem',
  'Terminus ante quem',
  'Terminus post quem',
  'Terra australis incognita',
  'Terra incognita',
  'Terra nullius',
  'Terrae marique fidelis',
  'Terribilis est locus iste',
  'Tertium non datur',
  'Testis unus, testis nullus',
  'Timeo Danaos et dona ferentes',
  'Timeo hominem unius libri',
  'Trahit sua quemque voluptas',
  'Tres faciunt collegium',
  'Treuga Dei',
  'Tu quoque mi fili',
  'Tu fui ego eris',
];