List<String> ft = [
  "Abel",
  "Acnologia",
  "Ajil Lamur",
  "Aldron Mokushin",
  "Alios",
  "Alya",
  "Animus",
  "Apothicaire",
  "Arcadios",
  "Archevêque de Zentopia",
  "Arlock",
  "Arzak (Edolas)",
  "Arzak Connel",
  "August",
  "Azuma",
  "Bacchus Glow",
  "Baislogia",
  "Bakr",
  "Ban",
  "Banaboster",
  "Bappy",
  "Bayro",
  "Belserion",
  "Berick",
  "Biby",
  "Bielness Kinjin",
  "Bill",
  "Billard",
  "Bixrow",
  "Bloodman",
  "Bluenote Stinger",
  "Bob",
  "Bobo",
  "Bomb Sentense",
  "Bora de Prominens",
  "Bora de Prominens (Fairy Tail City Hero)",
  "Bozo",
  "Brain",
  "Brianna",
  "Byro Cracy",
  "Cancer",
  "Cancer/Forme Éclipse",
  "Cannon",
  "Capitaine Blue",
  "Caprico",
  "Caprico/Forme Éclipse",
  "Capuccino",
  "Chapati Lola",
  "Chase",
  "Clap",
  "Cloupsy",
  "Comte Balsamico",
  "Cream",
  "Crowford Sheem",
  "Crunch",
  "D-6",
  "Daichi Shinagawa",
  "Dallas",
  "Dan Straight",
  "Daume",
  "De Cybele",
  "Deneb",
  "Derton",
  "Devon",
  "Diseur de Bonne Fortune",
  "Dobengal",
  "Doronbo",
  "Draculos Hyberion",
  "Drierte",
  "Drop Brothers",
  "Droy",
  "Droy (Edolas)",
  "Drum Bee",
  "Dublin",
  "Duc de Saouard",
  "Dyst",
  "Eave Tilm",
  "Ebar",
  "Ebar (Fairy Tail City Hero)",
  "Ed",
  "Eizi & Pandô",
  "Elbiman",
  "Elefseria",
  "Elfman (Edolas)",
  "Elfman Strauss",
  "Eligoal",
  "Erick",
  "Erick (Fairy Tail City Hero)",
  "Ezer",
  "Fabrizio",
  "Faust",
  "Fingers",
  "Forgeron de Magnoria",
  "Franmars",
  "Fried Justin",
  "Ga Maille",
  "Gajel",
  "Gajil (Edolas)",
  "Gajil Redfox",
  "Gaku Izumi",
  "Gatman Kubrick",
  "Gatow",
  "Geese",
  "Geoffrey",
  "Georg Risen",
  "Gerald Fernandez",
  "Gildarts Clive",
  "God Serena",
  "Gogotora",
  "Golmine",
  "Gran Doma",
  "Gren",
  "Grey Fullbuster",
  "Grey Soluge",
  "Griffon Kato",
  "Grog Fot",
  "Guy Aleus",
  "Gémini",
  "Gômon",
  "Hades",
  "Hammer Lala",
  "Hamélio Musica",
  "Happy",
  "Happy (Fairy Tail City Hero)",
  "Haru Glory",
  "Hawk",
  "Hibiki Leithis",
  "Hog",
  "Horologium",
  "Hughes",
  "Ichiya Vandalei Kotobuki",
  "Ignia",
  "Ignir",
  "Ikusatsunagi",
  "Inbel Yura",
  "Iwan Draer",
  "Jackal",
  "Jacob Lessio",
  "Jason",
  "Java Let Dahaka",
  "Jean-Luc Neville",
  "Jera Nekis",
  "Jerome",
  "Jett",
  "Jett (Edolas)",
  "Jienma Orlando",
  "Jilkonis",
  "Jiself",
  "José Pora",
  "Joy Fullbone",
  "Jude Heartfilia",
  "Jäger",
  "Kaby Melon",
  "Kafuchi Marmalade",
  "Kageyama",
  "Kain Hikaru",
  "Kalard",
  "Kama",
  "Karakka",
  "Karim",
  "Kashima",
  "Kawazu",
  "Keith",
  "King",
  "Kriserk",
  "Krof",
  "Kross",
  "Kurodoa",
  "Kurohebi",
  "Lapointe",
  "Lecter",
  "Leon Bastia",
  "Lowbawl",
  "Lucky (Exceed)",
  "Luis",
  "Luxris",
  "Luxus Draer",
  "Léo",
  "Léo/Forme Éclipse",
  "Macao (Edolas)",
  "Macao Combolto",
  "Macbeth",
  "Mace Orlando",
  "Madmall",
  "Maire de Magnoria",
  "Makarof Draer",
  "Makarof Draer (Fairy Tail City Hero)",
  "Maki",
  "Mald Gheel Tartaros",
  "Marin Hollow",
  "Martum",
  "Mashumâ",
  "Mato",
  "Matthew Redfox",
  "Max (Edolas)",
  "Max Alose",
  "Meliodas",
  "Merkphobia",
  "Mest Glider",
  "Metalicana",
  "Mezyl",
  "Michelo",
  "Migi",
  "Mikuni Shin",
  "Milk Boy",
  "Mink",
  "Mistgun",
  "Moka",
  "Momon",
  "Monmo",
  "Mugant",
  "Mysderoy",
  "Nab (Edolas)",
  "Nab Lasaro",
  "Nadar",
  "Nady",
  "Nady (Fairy Tail City Hero)",
  "Nakajima",
  "Nakku",
  "Nalpuding",
  "Natsu Dragnir",
  "Natsu Dragnir (Fairy Tail City Hero)",
  "Natsu Draguion",
  "Nebaru",
  "Nepper",
  "Nez Booms",
  "Nichiya",
  "Nichiya (Fairy Tail City Hero)",
  "Nigee",
  "Nikola",
  "Ninehart",
  "Nobarly",
  "Orga Nanagia",
  "Owl",
  "Panther Lily",
  "Pauze Lightless",
  "Perot",
  "Phénix",
  "Pâtissier",
  "Père Brock",
  "Père de Yoshino",
  "Rabian",
  "Rahal",
  "Rahkeid Dragnir",
  "Rayure",
  "Readers (Edolas)",
  "Readers Johnner",
  "Reiji",
  "Reis",
  "Ren Akatsuki",
  "Ribon",
  "Richard Buchanan",
  "Richard Buchanan (Fairy Tail City Hero)",
  "Risia",
  "Rivaia",
  "Rob",
  "Rocker",
  "Rog Chenny",
  "Rog du Futur",
  "Roi des Esprits",
  "Roi des Esprits/Forme Éclipse",
  "Roil",
  "Rokki",
  "Roméo Combolto",
  "Roméo du Futur",
  "Ruby",
  "Rufus Roy",
  "Rustyrose",
  "Sagittarius",
  "Sagittarius/Forme Éclipse",
  "Samagui",
  "Samuel",
  "San Jiao Shin",
  "Sanrô Pepper",
  "Sardean",
  "Sarval",
  "Sawyer",
  "Sawyer (Fairy Tail City Hero)",
  "Scissor Runner",
  "Scorpio",
  "Scorpio/Forme Éclipse",
  "Seiya Chiba",
  "Semus",
  "Shaw",
  "Shiki Granbell",
  "Shinra",
  "Shitou Yajima",
  "Shiyû",
  "Silver Fullbuster",
  "Simon Mikazuchi",
  "Skiadram",
  "Skullion Raider",
  "Sniper Drake",
  "Sol",
  "Sting Youclif",
  "Sugar Boy",
  "Sugar Boy (Earthland)",
  "Sunny",
  "Suzaku",
  "Sword Hiroshi",
  "Taurus",
  "Taurus/Forme Éclipse",
  "Tavernier de Blue Skull",
  "Taï",
  "Tempester",
  "Thann",
  "Thibo",
  "Thuncrow",
  "Toby Ololta",
  "Toma E. Fiore",
  "Tono Rabbits",
  "Torch Endebar",
  "Totomaru",
  "Trafzer",
  "Triton",
  "Velveno",
  "Vendeur d'Harujion",
  "Vidaldus Taka",
  "Visitor Echo",
  "Vodka Killer",
  "Volen (Edolas)",
  "Volen Rackow",
  "Wahl Icht",
  "Wakaba (Edolas)",
  "Wakaba Mine",
  "Wan Chan-Ji",
  "Warcry",
  "Will Neville",
  "Wise Steiner",
  "Wolfheim",
  "Wolly Buchanan",
  "Worlod Seaken",
  "Yaje",
  "Yajil",
  "Yomazu",
  "Yûka Suzuki",
  "Yûri",
  "Yûri Draer",
  "Zatow",
  "Zekua Melon",
  "Zeleph Dragnir",
  "Zoldio",
  "Aceto",
  "Alanya Web",
  "Amélie",
  "Angelica",
  "Anna Heartfilia",
  "Aquarius",
  "Aquarius/Forme Éclipse",
  "Aries",
  "Aries/Forme Éclipse",
  "Aska (Edolas)",
  "Aska Connel",
  "Aska du Futur",
  "Bellétocat",
  "Belno",
  "Bernicka Rilafille",
  "Beth Vanderhood",
  "Biska (Edolas)",
  "Biska Connel",
  "Braiya",
  "Brandish Myuh",
  "Capricia",
  "Carla",
  "Carla (Fairy Tail City Hero)",
  "Carlotti",
  "Carol",
  "Chagot",
  "Cherry Brendy",
  "Cherrya Brendy",
  "Chica C.Hermit",
  "Chloé",
  "Chronos",
  "Coordinateur",
  "Cornelia Alperona",
  "Cosmos",
  "Daisy",
  "Daiya",
  "Daphné",
  "DeZille Horae",
  "Diane",
  "Dimaria Iesta",
  "E.M.Pino",
  "Eileen Belserion",
  "Elena Alteria",
  "Elie",
  "Elizabeth",
  "Emery",
  "Enno Combolto",
  "Erkis",
  "Erza Knightwalker",
  "Erza Scarlett",
  "Erza Scarlett (Fairy Tail City Hero)",
  "Ever Green",
  "Frea Corona",
  "Ginger Mattan",
  "Grammy",
  "Grandiné",
  "Hana Adachi",
  "Heine Lunasea",
  "Hilda",
  "Homura Kôgetsu",
  "Ikaruga",
  "Imitatia",
  "Jade E. Fiore",
  "Jenny Rearlight",
  "Jubia (Edolas)",
  "Jubia Lokser",
  "Jubina",
  "Julia Line Dragoon",
  "Juliet Sun",
  "Kagura Mikazuchi",
  "Kamika",
  "Kanna (Edolas)",
  "Kanna Alperona",
  "Kanna Alperona (Fairy Tail City Hero)",
  "Kara",
  "Karamiila",
  "Karen Lilica",
  "Katja",
  "Kinana",
  "Kiria",
  "Koko",
  "Koko (Earthland)",
  "Kyôka",
  "Lamy",
  "Layla Heartfilia",
  "Lead",
  "Libra",
  "Libra/Forme Éclipse",
  "Lisana Strauss",
  "Lucia",
  "Lucky Olietta",
  "Lucy Ashley",
  "Lucy du Futur",
  "Lucy Heartfilia",
  "Lucy Heartfilia (Fairy Tail City Hero)",
  "Lulu",
  "Lusha",
  "Lyra",
  "Mako",
  "Mary (Avatar)",
  "Mary (Ice Trail)",
  "Mary Hughes",
  "Mavis Vermillion",
  "Meldy",
  "Mia",
  "Michelia",
  "Michelle Lobster",
  "Micky Chickentiger",
  "Mika Fullbuster",
  "Miko",
  "Miliana",
  "Millgana Mine",
  "Minajane",
  "Minerva Orlando",
  "Mio",
  "Mirajane (Edolas)",
  "Mirajane Strauss",
  "Mother Grea",
  "Mâr",
  "Nalshe Mikagura",
  "Nano Leaf",
  "Ohba Baba",
  "Ophiuchus/Forme Éclipse",
  "Oul Milkovich",
  "Polyussica",
  "Propriétaire",
  "Rebecca",
  "Reby (Edolas)",
  "Reby du Futur",
  "Reby MacGarden",
  "Reisha Whiteday",
  "Riko Applico",
  "Rinka Himeji",
  "Ripenille",
  "Risaala",
  "Risley Law",
  "Rita Draer",
  "Rizy",
  "Roen",
  "Roka",
  "Sakiha",
  "Sameko",
  "Samemi",
  "Sarah",
  "Seila",
  "Sonnetto",
  "Sorano Agria",
  "Sorano Agria (Fairy Tail City Hero)",
  "Sovia",
  "Spet",
  "Stola",
  "Sue",
  "Swan",
  "Séléné Gesshin",
  "Tomeko",
  "Touka",
  "Ultia Milkovich",
  "Ururu",
  "Vaize",
  "Viola",
  "Virgo",
  "Virgo (Fairy Tail City Hero)",
  "Virgo/Forme Éclipse",
  "Wendil",
  "Wendy (Edolas)",
  "Wendy Marvel",
  "Wendy Marvel (Fairy Tail City Hero)",
  "Yoshino",
  "Yukino Agria",
  "Zera (Mage)",
  "Éclair",
  "Aera",
  "Age Seal",
  "Aiguilles Magiques",
  "Amaterasu",
  "Animal Soul",
  "Arche de la Création",
  "Arche des Arbres",
  "Arche du Temps",
  "Ars Magia",
  "Beast Soul",
  "Briseur Abyssal",
  "Cercle Magique d'Auto-Destruction",
  "Changement de Masse",
  "Contrôle des Souvenirs",
  "Copie Instantanée",
  "Crush",
  "Disparition Totale",
  "Dog Whistle Magic",
  "Dragon Soul",
  "Drainage Magique",
  "Drill Rock For You",
  "Déflecteur",
  "Earkype",
  "Effet Topographique",
  "Egg Knock",
  "Enchantement",
  "Espace Aérien",
  "Flammes Arc-en-Ciel",
  "Flammes Rougeoyantes",
  "Foudre Naissante",
  "Gigantisme",
  "God Soul",
  "Hermes",
  "Historia",
  "Illusion Magique",
  "Invocation Sacrificielle",
  "Iron Dog",
  "Larmes Magiques",
  "Law",
  "Le Chevalier",
  "Le Danseur",
  "Légende Urbaine",
  "Machina Soul",
  "Magie Arc-en-Ciel",
  "Magie Blanche",
  "Magie Constructrice des Souvenirs",
  "Magie Créatrice de Saison",
  "Magie d'Absorption",
  "Magie d'Annulation",
  "Magie d'Aplatissement",
  "Magie d'Entrave",
  "Magie d'Esclavage",
  "Magie d'Espace",
  "Magie d'Écriture",
  "Magie d'Érosion",
  "Magie de Construction",
  "Magie de Copie",
  "Magie de Dissimulation",
  "Magie de Dissipation",
  "Magie de Division",
  "Magie de Désassemblage",
  "Magie de Glace Constructive",
  "Magie de Gravité",
  "Magie de l'Acide",
  "Magie de l'Air",
  "Magie de l'Eau",
  "Magie de l'Humiliation",
  "Magie de l'Ombre",
  "Magie de la Brume",
  "Magie de la Foudre",
  "Magie de la Glace",
  "Magie de la Laine",
  "Magie de la Lumière",
  "Magie de la Nature",
  "Magie de la Neige",
  "Magie de la Terre",
  "Magie de la Toupie",
  "Magie de la Vie",
  "Magie de Manipulation de l'Énergie Vitale",
  "Magie de Manipulation Dragonique",
  "Magie de Modelage de l'Acier",
  "Magie de Modelage du Bois",
  "Magie de Possession",
  "Magie de Ralentissement du Temps",
  "Magie de Revêtement",
  "Magie de Soumission Humaine",
  "Magie de Suppression",
  "Magie de Téléportation",
  "Magie de Vampirisation Indirecte",
  "Magie des Bombes",
  "Magie des Chaînes",
  "Magie des Cheveux",
  "Magie des Docteurs",
  "Magie des Explosions",
  "Magie des Fées",
  "Magie des Instruments de Torture",
  "Magie des Légumes",
  "Magie des Marionnettes",
  "Magie des Ondes",
  "Magie des Papiers",
  "Magie des Plantes",
  "Magie des Runes",
  "Magie des Ténèbres",
  "Magie des Œufs",
  "Magie du Chasseur de Dieu",
  "Magie du Chasseur de Dieu Céleste",
  "Magie du Chasseur de Dieu du Feu",
  "Magie du Chasseur de Dieu Foudroyant",
  "Magie du Chasseur de Dragon",
  "Magie du Chasseur de Dragon Blanc",
  "Magie du Chasseur de Dragon Collant",
  "Magie du Chasseur de Dragon Cuirassé",
  "Magie du Chasseur de Dragon Céleste",
  "Magie du Chasseur de Dragon d'Acier",
  "Magie du Chasseur de Dragon de Feu",
  "Magie du Chasseur de Dragon de l'Ombre",
  "Magie du Chasseur de Dragon de Neptune",
  "Magie du Chasseur de Dragon des Cavernes",
  "Magie du Chasseur de Dragon des Tempêtes",
  "Magie du Chasseur de Dragon du Purgatoire",
  "Magie du Chasseur de Dragon Fantôme",
  "Magie du Chasseur de Dragon Foudroyant",
  "Magie du Chasseur de Dragon Lame",
  "Magie du Chasseur de Dragon Venimeux",
  "Magie du Chasseur de Démon de Glace",
  "Magie du Corps Céleste",
  "Magie du Feu",
  "Magie du Fil",
  "Magie du Ré-équipement",
  "Magie du Sable",
  "Magie du Sommeil",
  "Magie du Vent",
  "Magie Défensive",
  "Magie Féerique",
  "Magie Gravitationnelle",
  "Magie Noire",
  "Magie Oculaire",
  "Magie Sonore",
  "Maguilty Sens",
  "Mimic",
  "Miroir Magique",
  "Muscles Peak",
  "Néo Éclipse",
  "Ongles Paralysants : Méga Méduse",
  "Papillon de Nuit",
  "Passe-Muraille",
  "Picto Magie",
  "Pistolera",
  "Plaisir",
  "Poing Souple",
  "Polygone Magique",
  "Possession Animale",
  "Possession Humaine",
  "Possession Magique",
  "Projection de pensée",
  "Purple Flame",
  "Pyrokinésie",
  "Regulus Noir",
  "Restriction des Mouvements",
  "Robe Stellaire",
  "Règle de l'Espace",
  "Satan Soul",
  "Shikigami Magique",
  "Snake Snake Charms",
  "Solid Script",
  "Solid Script Oriental",
  "Sorts de Lien Vivant",
  "Stone Eyes",
  "Super Earkype",
  "Take Over",
  "Territoire",
  "Transformation",
  "Transformation Animale",
  "Télékinésie",
  "Télépathie",
  "Unison Raid",
  "Universe One",
  "Virus",
  "Water Make",
  "Weakness",
  "Épées Magiques",
  "Œil du Démon",
  "Aetherion",
  "Anima",
  "Anti-Link",
  "Bague Magique",
  "Baguette de Commandement Magique",
  "Barrière Magique",
  "Buster Ma'am",
  "Bâtons Magiques",
  "Canons Magiques",
  "Changeling",
  "Charme Magique",
  "Christina",
  "Droma Anim",
  "Face",
  "Faux Magiques",
  "Guitare Magique",
  "Harpon Dragon",
  "Jet Magique",
  "L'Heure du Bœuf",
  "Lance Tornade",
  "Magie Athlétique",
  "Magie Climatique",
  "Magie d'Attraction",
  "Magie d'Espace",
  "Magie de Commandement",
  "Magie de l'Ange",
  "Magie de la Fumée",
  "Magie de Prédiction de l'Avenir",
  "Magie des Cartes",
  "Magie des Constellations",
  "Magie des Feuilles de Papier",
  "Magie des Parfums",
  "Magie du Sommeil",
  "Magie à Sous",
  "Objets Magiques d'Edolas",
  "Oiseau Magique",
  "Pistolet Magique",
  "Regulus",
  "Sceptre d'Absorption",
  "Serpent de Contention",
  "Sylpharion (Dix Commandements)",
  "Urumi",
  "Vaisseau de Grimoire Heart",
  "Végétation",
  "Épée de Feu (Edolas)",
  "Épée Musica",
  "Épées Magiques",
  "Guilde Blue Pegasus",
  "Guilde Carbuncle",
  "Guilde des Mercenaires du Loup du Sud",
  "Guilde Diabolos",
  "Guilde Dullahan Head",
  "Guilde Dwarf Gear",
  "Guilde Fairy Nail",
  "Guilde Fairy Tail",
  "Guilde Gramlush",
  "Guilde Hound Holy",
  "Guilde Lamia Scale",
  "Guilde Magia Dragon",
  "Guilde Mermaid Heel",
  "Guilde Orochi's Fin",
  "Guilde Phoenix Grave",
  "Guilde Quattro Cerberos",
  "Guilde Red Princess",
  "Guilde Saber Tooth",
  "Guilde Scarmiglione",
  "Guilde Titan Nose",
  "Guilde Twilight Ogre",
  "Love & Lucky",
  "Guilde Abyss Horn",
  "Guilde Blue Skull",
  "Guilde Chrono Noise",
  "Guilde d'Assassins des Skulls",
  "Guilde Dark Mirror",
  "Guilde Fairy Tail (Edolas)",
  "Guilde Five Bridge Familia",
  "Guilde Ghoul Spirits",
  "Guilde Grimoire Heart",
  "Guilde Naked Mummy",
  "Guilde Raven Goblin",
  "Guilde Succubus Eye",
  "Guilde Tartaros",
  "Guilde de la Sorcière Criminelle",
  "Guilde Fisherman's Prize",
  "Guilde Sylph Labyrinth",
  "Guilde Eisen Wald",
  "Guilde Ghoul Spirits",
  "Guilde Harpuia",
  "Guilde Raven Tail",
  "Nouvelle Oracion Seis",
  "Guilde Oracion Seis",
  "Guilde Cait Shelter",
  "Guilde Circus Night",
  "Guilde Raven Tail",
  "Guilde Red Lizard",
  "Guilde Phantom Lord",
  "7 Frères du Purgatoire",
  "Alliance de Lumière",
  "Armée des Chasseurs de Dragon",
  "Armée Quartum",
  "Avatar",
  "Bande de Voleurs du Papillon de Nuit",
  "Celestial Sisters",
  "Chasseur de Dieu",
  "Chasseur de Dragon",
  "Chasseur de Démon",
  "Chasseur de Trésors",
  "Chevaliers des Runes",
  "Chevaliers Sacrés des Cerisiers du Royaume de Fiore",
  "Conglomérat Heartfilia",
  "Conseil Magique",
  "Division Dragons Volants",
  "Division Eileen",
  "Division Orfraie",
  "Dix Mages Sacrés",
  "Dragons Divins",
  "Dragons Jumeaux",
  "Fairy Girls (Équipe)",
  "Gang des Fesses Dodues",
  "Gang des Poitrines Dodues",
  "Gang Oracion Seis",
  "Groupe de Tenrô",
  "Jumeaux d'Eisen Wald",
  "Luxris et les Rois de la Foudre",
  "Orques Ailées",
  "Porte des Neuf Démons",
  "Quartet des Jeunes Filles",
  "Quatre Grands Chevaliers",
  "Quatre Rois Célestes d'Ishgar",
  "Quatre Éléments",
  "Shadow Gear",
  "Société d'Archéologie",
  "Soeurs Chercheuses",
  "Spriggan Twelve",
  "Team Blue Pegasus",
  "Team Fairy Tail",
  "Team Fairy Tail A",
  "Team Fairy Tail B",
  "Team Lamia Scale",
  "Team Leon",
  "Team Makarof",
  "Team Mermaid Heel",
  "Team Quattro Cerberos",
  "Team Raven Tail",
  "Team Saber Tooth",
  "Trimens",
  "Trinity Raven",
  "Troupe des Loups Affamés",
  "Trymens (Fairy Tail City Hero)",
  "Unité Ajil",
  "Unité Brandish",
  "Unité de Ninehart",
  "Unité de Raijin",
  "Unité des Légions",
  "Vanish Brothers",
  "Young Megadeath",
  "Église de Zentopia",
  "Équipe de Natsu",
];
