import 'package:english_words/english_words.dart';

List<List<String>> lilist = [
  hp,
  hpsorts,
  nct,
  vd,
  countries,
  capitales,
  disneyHV,
  disneyMovies,
  hercule,
  aristochats,
  nouns,
  adjectives,
  all,
  orelsan,
  beatles,
  ptitbac,
  departements,
  usStates,
  math,
  fonctions,
  mimes,
];

List<String> liliste = [
  'Harry Potter',
  'Harry Potter (sorts)',
  'NCT',
  'Vampire Diaries',
  'Pays',
  'Capitales',
  'Disney (Héros et Méchants)',
  'Disney (Films)',
  'Hercule',
  'Les Aristochats',
  'Nouns',
  'Adjectives',
  'Words',
  'Orel/Gringe/Casseurs Flowteurs',
  'The Beatles',
  'P\'tit Bac',
  'Départements',
  'US States',
  'Maths',
  'Fonctions',
  'Mimes',
];

List<String> hp = [
  'Les Contes de Beedle le Barde',
  'L\'école des sorciers',
  'La Chambre des Secrets',
  'Le prisonnier d\'Azkaban',
  'La Coupe de Feu',
  'L\'Ordre du Phénix',
  'Le Prince de Sang-Mêlé',
  'Les Reliques de la Mort',
  'Les Animaux fantastiques',
  'Les Crimes de Grindelwald',
  'Harry Potter',
  'Hermione Granger',
  'Ronald Weasley',
  'Neville Londubat',
  'Luna Lovegood',
  'Drago Malefoy',
  'Albus Dumbledore',
  'Minerva McGonagall',
  'Severus Rogue',
  'Filius Fitwick',
  'Pomona Chourave',
  'Rubeus Hagrid',
  'Sibylle Trelawney',
  'Gilderoy Lockhart',
  'Horace Slughorn',
  'Tom Jedusor',
  'Bellatrix Lestrange',
  'Peter Pettigrow',
  'Barty Croupton Jr.',
  'Fenrir Greyback',
  'Mangemort',
  'Sirius Black',
  'Alastor Maugrey',
  'Remus Lupin',
  'Fleur Delacour',
  'Kingsley Shacklebolt',
  'Nymphadora Tonks',
  'Ordre du Phénix',
  'Cornelius Fudge',
  'Rufus Scrimgeour',
  'Dolores Ombrage',
  'Arthur Weasley',
  'Molly Weasley',
  'Sang-pur',
  'Sang-mêlé',
  'Moldu',
  'Terrier',
  'Département des Mystères',
  'Armée de Dumbledore',
  'Ginny Weasley',
  'Gabrielle Delacour',
  'Vélane',
  'Narcissa Malefoy',
  'Lucius Malefoy',
  'Poudlard',
  'Azkaban',
  'Serpentard',
  'Gryffondor',
  'Serdaigle',
  'Poufsouffle',
  'Choixpeau magique',
  'Godric Gryffondor',
  'Salazar Serpentard',
  'Rowena Serdaigle',
  'Helga Poufsouffle',
  'Ministère de la Magie',
  'Vernon Dursley',
  'Pétunia Dursley',
  'Dudley Dursley',
  'Quirinus Quirrell',
  'Firenze',
  'Gilderoy Lockhart',
  'Cédric Diggory',
  'Tournoi des Trois Sorciers',
  'La Gazette du sorcier',
  'Mondingus Fletcher',
  'Frank Londubat',
  'Alice Londubat',
  'Cho Chang',
  'James Potter',
  'Lily Potter',
  'George Weasley',
  'Fred Weasley',
  'Charlie Weasley',
  'Fumseck',
  'Nagini',
  'Abelforth Dumbledore',
  'Horcruxe',
  'Cartes de Chocogrenouille',
  'Mimi Geignarde',
  'Basilic',
  'Aragog',
  'Épée de Gryffondor',
  'Baguette de Sureau',
  'Regulus Black',
  'Dobby',
  'Kreattur',
  'Cape d\'Invisibilité',
  'Pierre de Résurrection',
  'Vif d\'or',
  'Pierre philosophale',
  'Nicolas Flamel',
  'Beauxbâtons',
  'Allée des Embrumes',
  'Chemin de Traverse',
  'Miroir du Riséd',
  'Détraqueur',
  'Cracmol',
  'Argus Rusard',
  'Miss Teigne',
  'Olympe Maxime',
  'Viktor Krum',
  'Durmstrang',
  'Forêt de Dean',
  'Gringotts',
  'Gobelins',
  'Gripsec',
  'Salle sur Demande',
  'Éclair de Feu',
  'Gare de King\'s Cross',
  'Pré-au-Lard',
  'Feudeymon',
  'Forêt interdite',
  'Sombrals',
  'Obscurus',
  'Croyance Bellebosse',
  'Norbert Dragonneau',
  'Bathilda Tourdesac',
  'Godric\'s Hollow',
  'Igor Karkaroff',
  'Norbert',
  'Pattenrond',
  'Crockdur',
  'Trevor',
  'Voie 9¾',
  'Pompom Pomfresh',
  'Polynectar',
  'Poudlard Express',
  'Ford Anglia',
  'Carte du Maraudeur',
  'Touffu',
  'Hedwige',
  'Croûtard',
  'Buck',
  'Le Chaudron Baveur',
  'Ollivander',
  '4, Privet Drive',
  'Beuglante',
  'Auror',
  'Baguette magique',
  'Gallions',
  'Weasley, Farces pour sorciers facétieux',
  'Zonko',
  'Mornilles',
  'Noises',
  'Coupe de Feu',
  'Coupe de Helga Poufsouffle',
  'Médaillon de Salazar Serpentard',
  'Impero',
  'Endoloris',
  'Avada Kedavra',
  'Expelliarmus',
  'Stupéfix',
  'Wingardium Leviosa',
  'Collier d\'opale',
  'Barjow et Beurk',
  'Déluminateur',
  'Glace à l\'Ennemi',
  'Pensine',
  'Oubliettes',
  'Plume à Papote',
  'Rita Skeeter',
  'Rapeltout',
  'Retourneur de Temps',
  'Sac en perles d\'Hermione',
  'Enervatum',
  'Accio',
  'Aguamenti',
  'Alohomora',
  'Amplificatum',
  'Anapneo',
  'Anteoculatia',
  'Aparecium',
  'Aqua Eructo',
  'Arania Exumai',
  'Aresto Momentum',
  'Assurdiato',
  'Avis',
  'Bloclang',
  'Bombarda',
  'Bombarda Maxima',
  'Brackium Emendo',
  'Calvorio',
  'Carpe Retractum',
  'Cave inimicum',
  'Collaporta',
  'Colovaria',
  'Confringo',
  'Confundo',
  'Cracbadabum',
  'Dentesaugmento',
  'Deprimo',
  'Descendo',
  'Destructum',
  'Diffindo',
  'Dissendium',
  'Draconifors',
  'Duro',
  'Elasticus',
  'Engorgio Cranius',
  'Entomorphis',
  'Episkey',
  'Erigo',
  'Evanesco',
  'Expecto Patronum',
  'Expulso',
  'Failamalle',
  'Ferula',
  'Finite',
  'Finite Incantatem',
  'Flambios',
  'Flipendo',
  'Furunculus',
  'Gemino',
  'Glacius',
  'Glisseo',
  'Harmonia Nectere Passus',
  'Herbivicus',
  'Herbifors',
  'Hominum revelio',
  'Immobulus',
  'Impedimenta',
  'Impervius',
  'Incarcerem',
  'Incarcifors',
  'Incendio',
  'Lacarnum Inflamarae',
  'Lapifors',
  'Lashlabask',
  'Legilimens',
  'Levicorpus',
  'Liberacorpus',
  'Limacius Eructo',
  'Locomotor',
  'Locomotor Mortis',
  'Lumos',
  'Lumos Maxima',
  'Lumos Solem',
  'Magicus Extremos',
  'Meteorribilis recanto',
  'Mobiliarbus',
  'Mobilicorpus',
  'Morsmordre',
  'Multicorfors',
  'Mutinlutin Malinpesti',
  'Nox',
  'Obscuro',
  'Oculus Reparo',
  'Oppugno',
  'Orbis',
  'Orchideus',
  'Oubliettes',
  'Partis Temporus',
  'Periculum',
  'Petrificus Totalus',
  'Piertotum locomotor',
  'Pointe au nord',
  'Portus',
  'Prior Incanto',
  'Priori Incantatum',
  'Protego',
  'Protego horribilis',
  'Protego totalum',
  'Récurvite',
  'Redactum Cranius',
  'Reducto',
  'Reparo',
  'Repello Moldum',
  'Repulso',
  'Rictusempra',
  'Riddikulus',
  'Salveo maleficia',
  'Sectumsempra',
  'Serpensortia',
  'Silencio',
  'Sonorus',
  'Sourdinam',
  'Specialis revelio',
  'Stupéfix',
  'Tarentallegra',
  'Tergeo',
  'Volatilors',
  'Vulnera Sanentur',
  'Waddiwasi',
  'Peeves',
  'Attrapeur',
  'Batteur',
  'Poursuiveur',
  'Gardien',
  'Capitaine',
  'Balai volant',
  'Cognard',
  'Souafle',
  'Préfèt',
  'Professeur',
  'Renée Bibine',
];

List<String> hpsorts = [
  'Accio',
  'Aguamenti',
  'Alohomora',
  'Amplificatum',
  'Anapneo',
  'Anteoculatia',
  'Aparecium',
  'Aqua Eructo',
  'Arania Exumai',
  'Aresto Momentum',
  'Assurdiato',
  'Avis',
  'Bloclang',
  'Bombarda',
  'Bombarda Maxima',
  'Brackium Emendo',
  'Calvorio',
  'Carpe Retractum',
  'Cave inimicum',
  'Collaporta',
  'Colovaria',
  'Confringo',
  'Confundo',
  'Cracbadabum',
  'Dentesaugmento',
  'Deprimo',
  'Descendo',
  'Destructum',
  'Diffindo',
  'Dissendium',
  'Draconifors',
  'Duro',
  'Elasticus',
  'Enervatum',
  'Engorgio Cranius',
  'Entomorphis',
  'Episkey',
  'Erigo',
  'Evanesco',
  'Expecto Patronum',
  'Expulso',
  'Expelliarmus',
  'Failamalle',
  'Ferula',
  'Finite',
  'Finite Incantatem',
  'Flambios',
  'Flipendo',
  'Furunculus',
  'Gemino',
  'Glacius',
  'Glisseo',
  'Harmonia Nectere Passus',
  'Herbivicus',
  'Herbifors',
  'Hominum revelio',
  'Immobulus',
  'Impedimenta',
  'Impervius',
  'Incarcerem',
  'Incarcifors',
  'Incendio',
  'Lacarnum Inflamarae',
  'Lapifors',
  'Lashlabask',
  'Legilimens',
  'Levicorpus',
  'Liberacorpus',
  'Limacius Eructo',
  'Locomotor',
  'Locomotor Mortis',
  'Lumos',
  'Lumos Maxima',
  'Lumos Solem',
  'Magicus Extremos',
  'Meteorribilis recanto',
  'Mobiliarbus',
  'Mobilicorpus',
  'Morsmordre',
  'Multicorfors',
  'Mutinlutin Malinpesti',
  'Nox',
  'Obscuro',
  'Oculus Reparo',
  'Oppugno',
  'Orbis',
  'Orchideus',
  'Oubliettes',
  'Partis Temporus',
  'Periculum',
  'Petrificus Totalus',
  'Piertotum locomotor',
  'Pointe au nord',
  'Portus',
  'Prior Incanto',
  'Priori Incantatum',
  'Protego',
  'Protego horribilis',
  'Protego totalum',
  'Récurvite',
  'Redactum Cranius',
  'Reparo',
  'Repello Moldum',
  'Repulso',
  'Revigor',
  'Rictusempra',
  'Riddikulus',
  'Salveo maleficia',
  'Sectumsempra',
  'Serpensortia',
  'Silencio',
  'Sonorus',
  'Sourdinam',
  'Specialis revelio',
  'Spero Patronum',
  'Stupéfix',
  'Tarentallegra',
  'Tergeo',
  'Volatilors',
  'Vulnera Sanentur',
  'Waddiwasi',
  'Wingardium Leviosa',
];

List<String> nct = [
  'Taeil',
  'Johnny',
  'Taeyong',
  'Yuta',
  'Kun',
  'Doyong',
  'Ten',
  'Jaehyun',
  'Winwin',
  'Jungwoo',
  'Lucas',
  'Mark',
  'Xiaojun',
  'Hendery',
  'Renjun',
  'Jeno',
  'Haechan',
  'Jaemin',
  'Yangyang',
  'Shotaro',
  'Sungchan',
  'Chenle',
  'Jisung',
  'NCT 127',
  'NCT',
  'NCT Dream',
  'WayV',
  '0 Mile',
  '1, 2, 3',
  '100',
  '119',
  '7 Days',
  '90\'s Love',
  'After Midnight',
  'Angel',
  'Another World',
  'Baby Don\'t Like It',
  'Baby Don\'t Stop',
  'Back 2 U (AM 01:27)',
  'Bad Alive',
  'Beautiful Time',
  'Best Friend',
  'Black on Black',
  'Blow My Mind',
  'BOOM',
  'Boom',
  'BOSS',
  'Bye My First…',
  'Candle Light',
  'Chain',
  'Cherry Bomb',
  'Chewing Gum',
  'City 127',
  'Come Back',
  'Come Back (WayV)',
  'Coming Home',
  'Dancing In The Rain',
  'Day Dream',
  'Dear DREAM',
  'Domino',
  'Don\'t Need Your Love',
  'Dream Launch',
  'Dream Run',
  'Dreaming',
  'Dreams Come True',
  'Drippin',
  'Dunk Shot',
  'Déjà Vu',
  'Electric Hearts',
  'Elevator (127F)',
  'End to Start',
  'Face to Face',
  'Faded In My Last Song',
  'Fire Truck',
  'Fly Away With Me',
  'FOOL',
  'From Home',
  'Go',
  'Good Thing',
  'Heartbreaker',
  'Highway to Heaven',
  'Interlude: Awaken The World',
  'Interlude: Neo Zone',
  'Interlude: Past to Present',
  'Interlude: Regular to Irregular',
  'INTRO: Neo Got My Back',
  'Jet Lag',
  'Joy',
  'Kick It',
  'King of Hearts',
  'Kitchen Beat',
  'Knock On',
  'La La Love',
  'Let me love u',
  'Light Bulb',
  'Limitless',
  'Long Flight',
  'Long Slow Distance',
  'Love Again',
  'Love Me Now',
  'Love Song',
  'Love Talk',
  'Mad City',
  'Mad Dog',
  'Make A Wish',
  'Make Your Day',
  'Misfit',
  'Moonwalk',
  'Music, Dance',
  'My First and Last',
  'My Page',
  'My Van',
  'Nectar',
  'No Longer',
  'Non Stop',
  'Not Alone',
  'Once Again',
  'Only Human',
  'OUTRO: VISION',
  'OUTRO: WE ARE 127',
  'Pandora\'s Box',
  'Paper Plane',
  'Paradise',
  'Prelude',
  'Punch',
  'Puzzle Piece',
  'Quiet Down',
  'Regular',
  'Regular (WayV)',
  'Replay (PM 01:27)',
  'Ridin',
  'Run Back 2 U',
  'Running 2 U',
  'Say It',
  'Simon Says',
  'Sit Down!',
  'Stand By Me',
  'STRONGER',
  'Summer 127',
  'Sun & Moon',
  'Superhuman',
  'Switch',
  'Take Off',
  'The 7th Sense',
  'Timeless',
  'Touch',
  'Trigger The Fever',
  'Turn Back Time',
  'Unbreakable',
  'Up From Here',
  'Volcano',
  'Wake Up',
  'Wakey-Wakey',
  'Walk You Home',
  'We go nanana',
  'We Go Up',
  'We Young',
  'Welcome To My Playground',
  'Whiplash',
  'White Night',
  'Without You',
  'Work It',
  'Yeah Yeah Yeah',
  'Yestoday',
  'Empathy',
  'Regular-Irregular',
  'Awaken',
  'Neo Zone',
  'Awaken the World',
  'Resonance Part. 1',
];

List<String> vd = [];

List<String> capitales = [
  'Tokyo',
  'Mexico',
  'Séoul',
  'Jakarta',
  'New Delhi',
  'Le Caire',
  'Moscou',
  'Buenos Aires',
  'Manille',
  'Londres',
  'Dhâkâ',
  'Paris',
  'Pékin',
  'Bangkok',
  'Lima',
  'Lisbonne',
  'Téhéran',
  'Kinshasa',
  'Santiago',
  'Madrid',
  'Naypyidaw',
  'Damas',
  'Singapour',
  'Ankara',
  'Luanda',
  'Bagdad',
  'Riyad',
  'Caracas',
  'Athènes',
  'Berlin',
  'Accra',
  'Hanoï',
  'Kiev',
  'Rome',
  'Addis-Abeba',
  'Guatemala',
  'Pyongyang',
  'Tachkent',
  'Saint-Domingue',
  'Brasilia',
  'Nairobi',
  'San José',
  'Tunis',
  'Alger',
  'Bucarest',
  'Budapest',
  'Conakry',
  'La Havane',
  'Port-au-Prince',
  'Dakar',
  'Amman',
  'Bogota',
  'Stockholm',
  'Kaboul',
  'Bakou',
  'San Salvador',
  'Minsk',
  'Varsovie',
  'Vienne',
  'Astana',
  'Harare',
  'Katmandou',
  'Khartoum',
  'Montevideo',
  'Quito',
  'Tananarive',
  'Colombo',
  'Kuala Lumpur',
  'Erevan',
  'Tripoli',
  'Phnom Penh',
  'Sofia et bruxelles',
  'Belgrade',
  'Mogadiscio',
  'Prague',
  'Tegucigalpa',
  'Yaoundé',
  'Maputo',
  'Tbilissi',
  'Pretoria',
  'Kampala',
  'Ottawa',
  'Abou Dabi',
  'Bamako',
  'Beyrouth',
  'Lusaka',
  'Managua',
  'Ndjamena',
  'Ouagadougou',
  'Sanaa',
  'Mascate',
  'Lomé',
  'Panama',
  'Brazzaville',
  'Islamabad',
  'Kigali',
  'Zagreb',
  'Jerusalem',
  'Monrovia',
  'Rīga',
  'Amsterdam',
  'Niamey',
  'Tirana',
  'Oulan-Bator',
  'Bangui',
  'Libreville',
  'Chişinău',
  'Rabat',
  'Vientiane',
  'Kingston',
  'Bichkek',
  'Achgabat',
  'Skopje',
  'Washington',
  'Helsinki',
  'Nouakchott',
  'Vilnius',
  'Freetown',
  'Asuncion',
  'Oslo',
  'Douchanbé',
  'Copenhague',
  'Dublin',
  'Asmara',
  'Bratislava',
  'Koweït',
  'Lilongwe',
  'Tallinn',
  'Sarajevo',
  'Djibouti',
  'Doha',
  'Wellington',
  'Canberra',
  'Port Moresby',
  'Bujumbura',
  'Port-d\'Espagne',
  'Porto-Novo',
  'Sucre (Bolivie)',
  'Bissau',
  'Ljubljana',
  'Georgetown',
  'Paramaribo',
  'Windhoek',
  'Nassau',
  'Nicosie',
  'Dodoma',
  'Gaborone',
  'Maseru',
  'Suva',
  'Manama',
  'Port-Louis',
  'Podgorica',
  'Berne',
  'Reykjavik',
  'Yamoussoukro',
  'Praia',
  'Abuja',
  'Bandar Seri Begawan',
  'Luxembourg',
  'Malé',
  'Castries',
  'Dili',
  'Moroni',
  'Mbabane',
  'Thimphou',
  'Malabo',
  'São Tomé',
  'Banjul',
  'Apia',
  'Nuku\'alofa',
  'Saint-Georges',
  'Monaco',
  'Honiara',
  'Port-Vila',
  'Saint John\'s',
  'Tarawa',
  'Victoria',
  'Delap-Uliga-Darrit',
  'Andorre-la-Vieille',
  'Kingstown',
  'Roseau',
  'Basseterre',
  'Palikir',
  'Belmopan',
  'La Valette',
  'Bridgetown',
  'Vaduz',
  'Funafuti',
  'Ville de Saint-Marin',
  'Cité du Vatican',
  'Melekeok',
  'Hargeisha',
  'Taipei',
  'Pristina',
  'Soukhoumi',
  'Stepanakert',
  'Tiraspol',
  'Tskhinvali',
];

List<String> countries = [
  'Japon',
  'Mexique',
  'Corée du Sud',
  'Indonésie',
  'Inde',
  'Égypte',
  'Russie',
  'Argentine',
  'Philippines',
  'Royaume-Uni',
  'Bangladesh',
  'France',
  'Chine',
  'Thaïlande',
  'Pérou',
  'Portugal',
  'Iran',
  'République démocratique du Congo',
  'Chili',
  'Espagne',
  'Birmanie',
  'Syrie',
  'Singapour',
  'Turquie',
  'Angola',
  'Irak',
  'Arabie saoudite',
  'Venezuela',
  'Grèce',
  'Allemagne',
  'Ghana',
  'Viêt Nam',
  'Ukraine',
  'Italie',
  'Éthiopie',
  'Guatemala',
  'Corée du Nord',
  'Ouzbékistan',
  'République dominicaine',
  'Brésil',
  'Kenya',
  'Costa Rica',
  'Tunisie',
  'Algérie',
  'Roumanie',
  'Hongrie',
  'Guinée',
  'Cuba',
  'Haïti',
  'Sénégal',
  'Jordanie',
  'Colombie',
  'Suède',
  'Afghanistan',
  'Azerbaïdjan',
  'Salvador',
  'Biélorussie',
  'Pologne',
  'Autriche',
  'Kazakhstan',
  'Zimbabwe',
  'Népal',
  'Soudan',
  'Uruguay',
  'Équateur',
  'Madagascar',
  'Sri Lanka',
  'Malaisie',
  'Arménie',
  'Libye',
  'Cambodge',
  'Bulgarie et belgique',
  'Serbie',
  'Somalie',
  'République tchèque',
  'Honduras',
  'Cameroun',
  'Mozambique',
  'Géorgie',
  'Afrique du Sud',
  'Ouganda',
  'Canada',
  'Émirats arabes unis',
  'Mali',
  'Liban',
  'Zambie',
  'Nicaragua',
  'Tchad',
  'Burkina Faso',
  'Yémen',
  'Oman',
  'Togo',
  'Panama',
  'République du Congo',
  'Pakistan',
  'Rwanda',
  'Croatie',
  'Israël',
  'Libéria',
  'Lettonie',
  'Pays-Bas',
  'Niger',
  'Albanie',
  'Mongolie',
  'République centrafricaine',
  'Gabon',
  'Moldavie',
  'Maroc',
  'Laos',
  'Jamaïque',
  'Kirghizistan',
  'Turkménistan',
  'Macédoine',
  'États-Unis',
  'Finlande',
  'Mauritanie',
  'Lituanie',
  'Sierra Leone',
  'Paraguay',
  'Norvège',
  'Tadjikistan',
  'Danemark',
  'Irlande',
  'Érythrée',
  'Slovaquie',
  'Koweït',
  'Malawi',
  'Estonie',
  'Bosnie-Herzégovine',
  'Djibouti',
  'Qatar',
  'Nouvelle-Zélande',
  'Australie',
  'Papouasie-Nouvelle-Guinée',
  'Burundi',
  'Trinité-et-Tobago',
  'Bénin',
  'Bolivie',
  'Guinée-Bissau',
  'Slovénie',
  'Guyana',
  'Suriname',
  'Namibie',
  'Bahamas',
  'Chypre',
  'Tanzanie',
  'Botswana',
  'Lesotho',
  'Fidji',
  'Bahreïn',
  'Maurice',
  'Monténégro',
  'Suisse',
  'Islande',
  'Côte d\'Ivoire',
  'Cap-Vert',
  'Nigeria',
  'Brunei',
  'Luxembourg',
  'Maldives',
  'Sainte-Lucie',
  'Timor oriental',
  'Comores',
  'Swaziland',
  'Bhoutan',
  'Guinée équatoriale',
  'Sao Tomé-et-Principe',
  'Gambie',
  'Samoa',
  'Tonga',
  'Grenade',
  'Monaco',
  'Salomon',
  'Vanuatu',
  'Antigua-et-Barbuda',
  'Kiribati',
  'Seychelles',
  'Marshall',
  'Andorre',
  'Saint-Vincent-et-les Grenadines',
  'Dominique',
  'Saint-Christophe-et-Niévès',
  'Micronésie',
  'Belize',
  'Malte',
  'Barbade',
  'Liechtenstein',
  'Tuvalu',
  'Saint-Marin',
  'Saint-Siège',
  'Palaos',
  'Somaliland',
  'Taïwan',
  'Chypre du Nord',
  'Kosovo',
  'Abkhazie',
  'Haut-Karabagh',
  'Transnistrie',
  'Ossétie du Sud',
];

List<String> disneyHV = [
  'Blanche-Neige',
  'Cendrillon',
  'Aurore',
  'Ariel',
  'Belle',
  'Jasmine',
  'Pocahontas',
  'Mulan',
  'Tiana',
  'Raiponce',
  'Mérida',
  'Vaiana',
  'Éloïse',
  'Mélodie',
  'Kida Nedakh',
  'Ting-Ting, Su, et Mei',
  'Kilala Reno',
  'Kairi',
  'Princesse de Gentlehaven',
  'Vanellope von Schweetz',
  'Sofia',
  'Elena',
  'Anna',
  'Elsa',
  'Alice',
  'Wendy Darling',
  'Clochette',
  'Esméralda',
  'Marianne',
  'Mégara',
  'Nala',
  'Jane Porter',
  'Raya',
  'La Reine',
  'Chernabog',
  'Reine de Cœur',
  'Capitaine Crochet',
  'Maléfique',
  'Cruella d\'Enfer',
  'Ursula',
  'Jafar',
  'Scar',
  'Hadès',
  'Docteur Facilier',
  'Grand Méchant Loup',
  'Pat Hibulaire',
  'Cavalier Sans Tête',
  'Mortimer Mouse',
  'Frère Renard',
  'Frère Ours',
  'Grand Coquin',
  'Gédéon',
  'Stromboli',
  'Le Cocher',
  'Monstro',
  'Monsieur Loyal',
  'Éléphants roses',
  'Diablo',
  'Fantômes auto-stoppeur',
  'Les Revenants Solitaires',
  'Madame de Trémaine',
  'Anastasie de Trémaine',
  'Javotte de Trémaine',
  'Lucifer',
  'Monsieur Mouche',
  'Si et Am',
  'Jasper etHorace',
  'Madame Mim',
  'Kaa',
  'Shere Khan',
  'Edgar Balthazar',
  'Prince Jean',
  'Triste Sire',
  'Shérif de Nottingham',
  'Madame Médusa',
  'Amos Slade',
  'Seigneur des Ténèbres',
  'Ratigan',
  'Félicia',
  'Bill Sykes',
  'Efélants',
  'Nouifs',
  'Flotsam et Jetsam',
  'Percival McLeach',
  'Gaston',
  'Iago',
  'Shenzi, Banzai et Ed',
  'Oogie Boogie',
  'Gouverneur Ratcliffe',
  'Claude Frollo',
  'Peine et Panique',
  'Moires',
  'Shan Yu',
  'Clayton',
  'Yzma',
  'Kronk',
  'Capitaine Gantu',
  'Docteur Hämsterviel',
  'DOR-15',
  'Michael "Goob" Yagoobian',
  'Reine Narissa',
  'Lawrence',
  'Mère Gothel',
  'Les Frères Stabbington',
  'Sa Sucrerie',
  'Aigre Bill',
  'Hans',
  'Yokai',
  'Tamatoa',
  'Sid Phillips',
  'Le Borgne',
  'Empereur Zurg',
  'Papi Pépite',
  'Léon "Le Caméléon"',
  'Henry J. Waternoose III',
  'Syndrome',
  'Chick Hicks',
  'AUTO',
  'Charles Muntz',
  'Lotso',
  'Professeur Zündapp',
  'Mor\'du',
  'Coup de Tonnerre',
  'Miss Fritter',
  'Ernesto de la Cruz',
  'Evelyn Deavor',
  'l\'Hypnotiseur',
  'Sarah Sanderson',
  'Winifred Sanderson',
  'Mary Sanderson',
  'Florian',
  'Henry',
  'Philippe',
  'Éric',
  'La Bête',
  'Aladdin',
  'John Smith',
  'Li Shang',
  'Naveen',
  'Flynn Rider',
  'Bambi',
  'Arthur Pendragon',
  'Prince Edward',
  'Rei',
  'Simba',
  'Hercule',
  'Milo Thatch',
  'Kovu',
  'Empereur Kuzco',
  'Harris, Hubert, et Hamish',
  'Mickey Mouse',
  'Donald Duck',
  'Dingo',
  'Tilt',
  'Peter Pan',
  'Mowgli',
  'Jack Skellington',
  'Quasimodo',
  'Tarzan',
  'John Rolfe',
  'Taram',
  'Phœbus',
  'Sora',
  'Ralph-la-casse',
  'Jim Hawkins',
  'Kristoff',
  'Yao, Ling et Chien Po',
  'Robin des Bois',
];

List<String> disneyMovies = [
  'Blanche-Neige et les Sept Nains',
  'Pinocchio',
  'Fantasia',
  'Dumbo',
  'Bambi',
  'Saludos Amigos',
  'Les Trois Caballeros',
  'La Boîte à musique',
  'Coquin de Printemps',
  'Mélodie Cocktail',
  'Le Crapaud et le Maître d\'École',
  'Cendrillon',
  'Alice au Pays des Merveilles',
  'Peter Pan',
  'La Belle et le Clochard',
  'La Belle au Bois Dormant',
  'Les 101 Dalmatiens',
  'Merlin l\'Enchanteur',
  'Le Livre de la Jungle',
  'Les Aristochats',
  'Robin des Bois',
  'Les Aventures de Winnie l\'Ourson',
  'Les Aventures de Bernard et Bianca',
  'Rox et Rouky',
  'Taram et le Chaudron magique',
  'Basil, détective privé',
  'Oliver et Compagnie',
  'La Petite Sirène',
  'Bernard et Bianca au pays des kangourous',
  'La Belle et la Bête',
  'Aladdin',
  'Le Roi Lion',
  'Pocahontas : une légende indienne',
  'Le Bossu de Notre-Dame',
  'Hercule',
  'Mulan',
  'Tarzan',
  'Fantasia 2000',
  'Dinosaure',
  'Kuzco, l\'empereur mégalo',
  'Atlantide, l\'empire perdu',
  'Lilo et Stitch',
  'La Planète au trésor, un nouvel univers',
  'Frère des Ours',
  'La Ferme se rebelle',
  'Chicken Little',
  'Bienvenue chez les Robinson',
  'Volt, star malgré lui',
  'La Princesse et la Grenouille',
  'Raiponce',
  'Winnie l\'Ourson',
  'Les Mondes de Ralph',
  'La Reine des Neiges',
  'Les Nouveaux Héros',
  'Zootopie',
  'Vaiana, la légende du bout du monde',
  'Les Mondes de Ralph 2',
  'La Reine des Neiges 2',
  'Raya et le Dernier Dragon',
  'Toy Story',
  '1001 pattes',
  'Toy Story 2',
  'Monstres et Cie',
  'Le Monde de Nemo',
  'Les Indestructibles',
  'Cars : Quatre Roues',
  'Ratatouille',
  'WALL·E',
  'Là-haut',
  'Toy Story 3',
  'Cars 2',
  'Rebelle',
  'Monstres Academy',
  'Vice-Versa',
  'Le Voyage d\'Arlo',
  'Le Monde de Dory',
  'Cars 3',
  'Coco',
  'Les Indestructibles 2',
  'Toy Story 4',
  'En avant',
  'Soul',
  'La Bande à Picsou, le Film : Le Trésor de la Lampe Perdue',
  'Le Retour de Jafar',
  'Dingo et Max',
  'Aladdin et le Roi des Voleurs',
  'Winnie l\'Ourson 2 : Le Grand Voyage',
  'La Belle et la Bête 2 : Le Noël Enchanté',
  'Le Monde Magique de la Belle et la Bête',
  'Pocahontas 2 : Un Monde Nouveau',
  'Le Roi Lion 2 : L\'Honneur de la Tribu',
  'Mickey, il était une fois Noël',
  'Winnie l\'Ourson : Joyeux Noël',
  'Les Aventures de Tigrou',
  'Dingo et Max 2 : Les Sportifs de l\'Extrême',
  'La Petite Sirène 2 : Retour à l\'Océan',
  'La Belle et le Clochard 2 : L\'Appel de la Rue',
  'Peter Pan 2 : Retour au Pays Imaginaire',
  'Cendrillon 2 : une vie de princesse',
  'Le Bossu de Notre-Dame 2 : Le Secret de Quasimodo',
  'Winnie l\'Ourson : Bonne Année',
  'Les 101 Dalmatiens 2 : Sur la Trace des Héros',
  'Le Livre de la Jungle 2',
  'Les Aventures de Porcinet',
  'Les Énigmes de l\'Atlantide',
  'Le Roi Lion 3 : Hakuna Matata',
  'Les Aventures de Petit Gourou',
  'Mickey, Donald, Dingo : Les Trois Mousquetaires',
  'Mickey, il était deux fois Noël',
  'Mulan 2 : La mission de l\'Empereur',
  'Winnie l\'Ourson et l\'Éfélant',
  'Tarzan 2 : L\'Enfance d\'un Héros',
  'Lilo et Stitch 2 : Hawaï, Nous avons un Problème!',
  'Winnie l\'Ourson : Lumpy fête Halloween',
  'Kuzco 2 : King Kronk',
  'Bambi 2',
  'Frère des Ours 2',
  'Rox et Rouky 2',
  'Le Sortilège de Cendrillon',
  'Les Histoires Merveilleuses - Vis tes Rêves',
  'Le Secret de la Petite Sirène',
  'La Fée Clochette',
  'Clochette et la Pierre de Lune',
  'Clochette et l\'Expédition Féerique',
  'Clochette et le Secret des Fées',
  'Planes',
  'Clochette et la Fée Pirate',
  'Planes 2',
  'Clochette et la Créature Légendaire',
];

List<String> hercule = [
  'Gospel Pur',
  'Le monde qui est le mien',
  'Il me reste un espoir',
  'De Zéro en Héros',
  'Jamais je n\'avouerai',
  'Une Étoile est née',
  'Hercule',
  'Hadès',
  'Pégase',
  'Philoctète',
  'Mégara',
  'Peine et Panique',
  'les Moires',
  'les Muses',
  'Zeus',
  'Héra',
  'Hermès',
  'Hestia',
  'Héphaïstos',
  'Athéna',
  'Arès',
  'Poséidon',
  'Aphrodite',
  'Artémis',
  'Apollon',
  'les Thébains',
  'Dionysos',
  'Titans',
  'Cerbère',
  'l\'Hydre de Lerne',
  'le Minotaure',
  'Sthéno',
  'Lion de Némée',
  'Nessus',
  'les Furies',
  'les Nymphes',
  'Amphitryon',
  'Alcmène',
  'Dieux de l\'Olympe',
  'Lythos',
  'Hydros',
  'Pyros',
  'Stratos',
  'Cyclope',
  'Calliope',
  'Clio',
  'Thalie',
  'Terpsichore',
  'Melpomène',
  'Lachesis',
  'Clotho',
  'Atropos',
  'Déméter',
  'Amphitrite',
  'Boreas',
  'Cupidon',
  'Morphée',
  'Phantasos',
  'Trivia',
  'Triton',
  'Circée',
  'Narcisse',
  'Erato',
  'Polyhymnia',
  'Euterpe',
  'Urania',
  'Grèce antique',
  'Mont Olympe',
  'Enfers',
  'Île de Philoctète',
  'Thèbes',
  'Académie Prométhée',
  'Atlantide',
  'Eclairs de Zeus',
  'Fiole Mortel',
  'Trident',
];

List<String> aristochats = [
  'Duchesse',
  'Thomas O\'Malley',
  'Toulouse',
  'Marie',
  'Berlioz',
  'Roquefort',
  'Frou-Frou',
  'Edgar Balthazar',
  'Adélaïde de Bonnefamille',
  'Georges Hautecourt',
  'le Laitier',
  'Napoléon',
  'Lafayette',
  'Amélie et Amelia Jacasse',
  'Waldo',
  'Scat Cat',
  'France',
  'Paris',
  'Manoir de Bonnefamille',
  'Ferme',
  'Repaire des Chats de Gouttière',
  '	Les Aristocats',
  'Gammes et Arpèges',
  'Thomas O\'Malley (chanson)',
  'Tout le monde veut devenir un Cat',
  'La Donna è mobile',
];

List<String> beatles = [
  'John Lennon',
  'Paul McCartney',
  'George Harrisson',
  'Ringo Starr',
  'I Saw Her Standing There',
  'Misery',
  'Anna (Go To Him)',
  'Chains',
  'Boys',
  'Ask Me Why',
  'Please Please Me',
  'Love Me Do',
  'P.S. I Love You',
  'Baby It\'s You',
  'Do You Want To Know A Secret',
  'A Taste Of Honey',
  'There\'s A Place',
  'Twist And Shout',
  'It Won\'t Be Long',
  'All I\'ve Got To Do',
  'All My Loving',
  'Don\'t Bother Me',
  'Little Child',
  'Till There Was You',
  'Please Mister Postman',
  'Roll Over Beethoven',
  'Hold Me Tight',
  'You Really Got A Hold On Me',
  'I Wanna Be Your Man',
  'Devil In Her Heart',
  'Not A Second Time',
  'Money',
  'A Hard Day\'s Night',
  'I Should Have Known Better',
  'If I Fell',
  'I\'m Happy Just To Dance With You',
  'And I Love Her',
  'Tell Me Why',
  'Can\'t Buy Me Love',
  'Any Time At All',
  'I\'ll Cry Instead',
  'Things We Said Today',
  'When I Get Home',
  'You Can\'t Do That',
  'I\'ll Be Back',
  'No Reply',
  'I\'m A Loser',
  'Baby\'s In Black',
  'Rock And Roll Music',
  'I\'ll Follow The Sun',
  'Mr Moonlight',
  'Medley',
  'Eight Days A Week',
  'Words Of Love',
  'Honey Don\'t',
  'Every Little Thing',
  'I Don\'t Want To Spoil The Party',
  'What You\'re Doing',
  'Everybody\'s Trying To Be My Baby',
  'Help !',
  'The Night Before',
  'You\'ve Got To Hide Your Love Away',
  'I Need You',
  'Another Girl',
  'You\'re Going To Lose That Girl',
  'Ticket To Ride',
  'Act Naturally',
  'It\'s Only Love',
  'You Like Me Too Much',
  'I\'ve Just Seen A Face',
  'Tell Me What You See',
  'Yesterday',
  'Dizzy Miss Lizzy',
  'Drive My Car',
  'Norvegian Wood (This Bird Has Flown)',
  'You Won\'t See Me',
  'Nowhere Man',
  'Think For Yourself',
  'The Word',
  'Michelle',
  'What Goes On',
  'Girl',
  'I\'m Looking Through You',
  'In My Life',
  'Wait',
  'If I Needed Someone',
  'Run For Your Life',
  'Taxman',
  'Eleanor Rigby',
  'I\'m Only Sleeping',
  'Love You To',
  'Here, There and Everywhere',
  'Yellow Submarine',
  'She Said She Said',
  'Good Day Sunshine',
  'And Your Bird Can Sing',
  'For No One',
  'Doctor Robert',
  'I Want To Tell You',
  'Got To Get You Into My Life',
  'Tomorrow Never Knows',
  'Sgt. Pepper\'s Lonely Hearts Club Band',
  'With A Little Help From My Friends',
  'Lucy In The Sky With Diamonds',
  'Getting Better',
  'Fixing A Hole',
  'She\'s Leaving Home',
  'Being For The Benefit Of Mr. Kite !',
  'Within You Without You',
  'When I\'m Sixty-Four',
  'Lovely Rita',
  'Good Morning Good Morning',
  'Sgt. Pepper\'s Lonely Hearts Club Band (Reprise)',
  'A Day In The Life',
  'Magical Mystery Tour',
  'The Fool On The Hill',
  'Flying',
  'Blue Jay Way',
  'Your Mother Should Know',
  'I Am The Walrus',
  'Hello Goodbye',
  'Strawberry Fields For Ever',
  'Penny Lane',
  'Baby You\'re a Rich Man',
  'All You Need Is Love',
  'Back in the U.S.S.R.',
  'Dear Prudence',
  'Glass Onion',
  'Ob-la-di, Ob-la-da',
  'Wild Honey Pie',
  'The Continuing Story of Bungalow Bill',
  'While My Guitar Gently Weeps',
  'Happiness is a Warm Gun',
  'Martha My Dear',
  'I\'m so tired',
  'Blackbird',
  'Piggies',
  'Rocky Raccoon',
  'Don\'t Pass Me By',
  'Why don\'t we do it in the road ?',
  'I Will',
  'Julia',
  'Birthday',
  'Yer Blues',
  'Mother Nature\'s Son',
  'Everybody\'s Got Something to Hide Except Me and My Monkey',
  'Sexy Sadie',
  'Helter Skelter',
  'Long, Long, Long',
  'Revolution 1',
  'Honey Pie',
  'Savoy Truffle',
  'Cry Baby Cry',
  'Revolution 9',
  'Good Night',
  'Yellow Submarine',
  'Only a Northern Song',
  'All together Now',
  'Hey Bulldog',
  'It\'s all too much',
  'All you need is Love',
  'Pepperland',
  'Sea of Time',
  'Sea of Holes',
  'Sea of Monsters',
  'March of The Meanies',
  'Pepperland laid waste',
  'Yellow Submarine in Pepperland',
  'Two Of Us',
  'Dig A Pony',
  'Across the Universe',
  'I Me Mine',
  'Dig It',
  'Let It Be',
  'Maggie Mae',
  'I\'ve Got A Feeling',
  'One After 909',
  'The Long And Winding Road',
  'For You Blue',
  'Get Back',
  'Paperback Writer',
  'Rain',
  'Lady Madonna',
  'Revolution',
  'Hey Jude',
  'Old Brown Shoe',
  'Don\'t Let Me Down',
  'The Ballad of John and Yoko',
];

List<String> orelsan = [
  'Orelsan',
  'Gringe',
  'Skread',
  'Ablaye',
  'Diamond 2klo',
  'Etoiles invisibles',
  'Changement',
  'Soirée ratée',
  'Différent',
  'No life',
  'Pour le pire',
  'Perdu d\'avance',
  'Gros poissons dans une petite mare',
  'Logo dans le ciel',
  '50 pourcents',
  'Jimmy Punchline',
  'Entre bien et mal',
  'Courez courez',
  'Peur de l\'échec',
  'Raelsan',
  'Le chant des sirènes',
  'Plus rien ne m\'étonne',
  'Mauvaise idée',
  'Double vie',
  'Finir mal',
  'Si seul',
  'Des trous dans la tête',
  'La petite marchande de portes-clefs',
  'La terre est ronde',
  '1990',
  '2010',
  'La morale',
  'Ils sont cools',
  'Suicide social',
  'Elle viendra quand même',
  '14h58 - Casseurs Flowters Opening',
  '15h02 - Regarde comme il fait beau (dehors)',
  '15h45 - Stupide stupide stupide',
  '16h00 - tu m\'dois d\'loseille',
  '16h22 - Deux connards dans un abribus',
  '17h04 - Prends des pièces',
  '18h30 - Bloqué',
  '19h26 - La mort du disque',
  '20h08 - Dans la place pour être',
  '20h13 - La nouvelle paire',
  '22h31 - Fais les backs',
  '01h14 - Couplet de claude (interlude)',
  '01h16 - Les putes et moi',
  '01h25 - Johnny Galoche',
  '01h47 - Change de pote',
  '03h53 - Manger c\'est tricher',
  '04h41 - Greenje et orselane',
  '06h16 - Des histoires à raconter',
  'Nouvelle Journée',
  'Au bout du compte',
  'A l\'heure où je me couche',
  'Quand ton père t\'engueule',
  'En boucle',
  'Faut qu\'on rentre bosser',
  'Freestyle radio Phoenix',
  'Le mal est fait',
  'C\'est toujours 2 connards dans un abribus',
  'Pas n\'importe quel toon',
  'J\'essaye, j\'essaye',
  'Promenade imprévue',
  'Xavier',
  'Wondercash',
  'On est resté à l\'hôtel',
  'Si facile',
  'Inachevés',
  'Quand on descend vers le centre',
  'Mémo',
  'Paradis noir',
  'Je la laisse faire',
  'On danse pas',
  'Qui dit mieux (feat. Orelsan, Vald & Suikon Blaz AD)',
  'Konnichiwa',
  'Jusqu\'où elle m\'aime (feat. Nemir)',
  'Déchiré (feat. Orelsan)',
  'Retourne d\'où tu viens',
  'Pour la nuit',
  'Pièces détachées',
  'Scanner (feat. Léa Castel)',
  'LMP',
  'Karma (feat. 2klo)',
  'Enfant Lune',
  'San',
  'La fête est finie',
  'Basique',
  'Tout va bien',
  'Défaite de famille',
  'La lumière',
  'Bonne meuf',
  'Quand est-ce que ça s\'arrête',
  'Christophe (feat. Maître Gims)',
  'Zone (feat. Nekfeu & Dizzee Rascal)',
  'Dans ma ville, on traîne',
  'La pluie (feat. Stromae)',
  'Notes pour trop tard (feat. Ibeyi)',
  'Fantômes',
  'Tout ce que je sais feat. YBN Cordae',
  'La famille, la famille',
  'Mes grands-parents',
  'Tout va bien remix feat. Eugy & Kojo Funds',
  'Discipline',
  'Adieu les filles',
  'Excuses ou mensonges',
  'Dis-moi',
  'Rêves bizarres feat. Damso',
  'Epilogue',
];

List<String> orelHard = [
  'Intro Diamond 2klo',
  'Les petites notes',
  'j\'vais baiser ta femme',
  'Calage feat Diamond 2klo',
  'Perdu d\'avance',
  'Sans m\'justifier',
  'Bounce',
  'Dors dans le métro',
  'Venu pour flowter',
  'Sauf si c\'est pas une métaphore',
  'Drogues feat Diamond 2klo',
];

List<String> ptitbac = [
  'Prénom',
  'Pays/Capitale',
  'Objet',
  'Insecte/Animal',
  'Fruit/Légume/Fleur',
  'Sport/Métier',
  'Célébrité (réelle)',
  'Personnage fictif',
  'Partie du corps',
  'Marque',
  'Aliment/Plat/Gourmandise',
  'Couleur',
  'Instruments de musique',
  'Série/Film',
  'Mot de plus de 8 lettre',
  'Cadeau de Noël',
  'Mot en anglais',
  'Région/Ville',
  'Qui sent mauvais',
  'Nom que l\'on donne à un doudou',
  'Qui fait plaisir',
  'Vêtement/Accessoire de mode',
];

List<String> alphabet = [
  'A',
  'B',
  'C',
  'D',
  'E',
  'F',
  'G',
  'H',
  'I',
  'J',
  'K',
  'L',
  'M',
  'N',
  'O',
  'P',
  'Q',
  'R',
  'S',
  'T',
  'U',
  'V',
  'W',
  'X',
  'Y',
  'Z',
];

List<String> departements = [
  '01	Ain',
  '02	Aisne',
  '03	Allier',
  '04	Alpes-de-Haute-Provence',
  '05	Hautes-Alpes',
  '06	Alpes-Maritimes',
  '07	Ardèche',
  '08	Ardennes',
  '09	Ariège',
  '10	Aube',
  '11	Aude',
  '12	Aveyron',
  '13	Bouches-du-Rhône',
  '14	Calvados',
  '15	Cantal',
  '16	Charente',
  '17	Charente-Maritime',
  '18	Cher',
  '19	Corrèze',
  '2A	Corse-du-Sud',
  '2B	Haute-Corse',
  '21	Côte-d\'Or',
  '22	Côtes d\'Armor',
  '23	Creuse',
  '24	Dordogne',
  '25	Doubs',
  '26	Drôme',
  '27	Eure',
  '28	Eure-et-Loir',
  '29	Finistère',
  '30	Gard',
  '31	Haute-Garonne',
  '32	Gers',
  '33	Gironde',
  '34	Hérault',
  '35	Ille-et-Vilaine',
  '36	Indre',
  '37	Indre-et-Loire',
  '38	Isère',
  '39	Jura',
  '40	Landes',
  '41	Loir-et-Cher',
  '42	Loire',
  '43	Haute-Loire',
  '44	Loire-Atlantique',
  '45	Loiret',
  '46	Lot',
  '47	Lot-et-Garonne',
  '48	Lozère',
  '49	Maine-et-Loire',
  '50	Manche',
  '51	Marne',
  '52	Haute-Marne',
  '53	Mayenne',
  '54	Meurthe-et-Moselle',
  '55	Meuse',
  '56	Morbihan',
  '57	Moselle',
  '58	Nièvre',
  '59	Nord',
  '60	Oise',
  '61	Orne',
  '62	Pas-de-Calais',
  '63	Puy-de-Dôme',
  '64	Pyrénées-Atlantiques',
  '65	Hautes-Pyrénées',
  '66	Pyrénées-Orientales',
  '67	Bas-Rhin',
  '68	Haut-Rhin',
  '69	Rhône',
  '70	Haute-Saône',
  '71	Saône-et-Loire',
  '72	Sarthe',
  '73	Savoie',
  '74	Haute-Savoie',
  '75	Paris',
  '76	Seine-Maritime',
  '77	Seine-et-Marne',
  '78	Yvelines',
  '79	Deux-Sèvres',
  '80	Somme',
  '81	Tarn',
  '82	Tarn-et-Garonne',
  '83	Var',
  '84	Vaucluse',
  '85	Vendée',
  '86	Vienne',
  '87	Haute-Vienne',
  '88	Vosges',
  '89	Yonne',
  '90	Territoire de Belfort',
  '91	Essonne',
  '92	Hauts-de-Seine',
  '93	Seine-St-Denis',
  '94	Val-de-Marne',
  '95	Val-D\'Oise',
  '971  Guadeloupe',
  '972	Martinique',
  '973	Guyane',
  '974	La Réunion',
  '976	Mayotte',
];

List<String> usStates = [
  'Alabama',
  'Alaska',
  'American Samoa',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'District of Columbia',
  'Florida',
  'Georgia',
  'Guam',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Maryland',
  'Massachusetts',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'New York',
  'North Carolina',
  'North Dakota',
  'Northern Mariana Islands',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Pennsylvania',
  'Puerto Rico',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Tennessee',
  'Texas',
  'Utah',
  'Vermont',
  'Virgin Islands',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming',
];

List<String> math = [
  'Équation',
  'Inconnue',
  'Solution',
  'Système d\'équations',
  'Opération',
  'Développement',
  'Factorisation',
  'Théorème fondamental de l\'algèbre',
  'Structure algébrique',
  'Monoïde',
  'Groupe',
  'Anneau',
  'Corps',
  'Corps commutatif',
  'Corps gauche',
  'Espace vectoriel',
  'Algèbre',
  'Théorie des ensembles',
  'Théorie des anneaux',
  'Théorie des groupes',
  'Théorie des catégories',
  'fonction',
  'expression',
  'variable',
  'valeur',
  'ensemble de départ',
  'ensemble d\'arrivée',
  'graphe',
  'domaine de définition',
  'image',
  'antécédent',
  'préimage',
  'restriction',
  'composition',
  'réciproque',
  'Étude de fonction',
  'domaine de définition',
  'périodicité',
  'parité',
  'continuité',
  'dérivabilité',
  'dérivée',
  'variations',
  'extremum',
  'zéros',
  'signe',
  'limites',
  'comparaison asymptotique',
  'Courbe représentative',
  'tangentes',
  'asymptotes',
  'branches paraboliques',
  'concavité',
  'points d\'inflexion',
  'position relative',
  'quadrant',
  'pente',
  'Dérivation',
  'règle du produit',
  'fonctions composées',
  'dérivation itérée (formule de Faà di Bruno)',
  'théorème de Glaeser',
  'Calcul de limites',
  'opérations (forme indéterminée)',
  'composition',
  'théorème des gendarmes',
  'théorème de la limite monotone',
  'développement asymptotique',
  'équivalent',
  'négligeable',
  'règle de L\'Hôpital',
  'Intégration',
  'primitive',
  'intégrabilité',
  'intégrale',
  'théorème fondamental de l\'analyse',
  'intégration par parties',
  'changement de variables (règles de Bioche)',
  'théorème des valeurs intermédiaires',
  'théorème de la bijection',
  'théorème de la moyenne',
  'théorème des bornes',
  'théorème de Rolle',
  'théorème des accroissements finis',
  'théorème de Darboux',
  'théorème de la moyenne de Cauchy',
  'Approximation locale',
  'approximation linéaire',
  'théorème de Taylor',
  'développement limité',
  'Régularité par morceaux',
  'Lipschitz',
  'condition de Hölder',
  'absolue continuité',
  'continuité uniforme',
  'variation bornée',
  'semi-continuité',
  'suite',
  'terme',
  'rang',
  'sous-suite',
  'relation de récurrence',
  'raison',
  'suites arithmétiques',
  'suites géométriques',
  'suites arithmético-géométriques',
  'suites récurrentes linéaires',
  'suite de Fibonacci',
  'suite de Tribonacci',
  'suite de Perrin',
  'suite de Padovan',
  'suite de Pell',
  'suite de Lucas',
  'suites logistiques',
  'suites adjacentes',
  'moyenne arithmético-géométrique',
  'suites équivalentes',
  'formule de Stirling',
  'suite bornée',
  'suite de Cauchy',
  'suite périodique',
  'Convergence',
  'limite',
  'limite inférieure',
  'limite supérieure',
  'lemme de Cesàro',
  'théorème de Stolz-Cesàro',
  'lemme de l\'escalier',
  'valeur d\'adhérence',
  'théorème de Bolzano-Weierstrass',
  'développement décimal',
  'fraction continue',
  'produit infini',
  'produit infini de Cantor',
  'convergence linéaire',
  'convergence quadratique',
  'séries géométriques',
  'harmonique',
  'série des inverses des nombres premiers',
  'séries de Riemann',
  'Bertrand',
  'Grandi',
  'série alternée des entiers',
  'série double',
  'série alternée',
  '(critère de convergence)',
  'série télescopique',
  'convergence absolue',
  'convergence inconditionnelle',
  'règle de Cauchy',
  'règle de d\'Alembert',
  'règle de Raabe-Duhamel',
  'inégalité de Carleman',
  'théorème de réarrangement de Riemann',
  'lemme de Kronecker',
  'produit de Cauchy',
  'sommation par parties',
  'sommation de Borel',
  'série d\'Eisenstein',
  'Engel',
  'Lambert',
  'zêta rationnelle',
  'dérivée partielle',
  'dérivée directionnelle',
  'différentielle',
  'point critique (point col)',
  'matrice hessienne',
  'gradient',
  'ligne de niveau',
  'multiplicateur de Lagrange',
  'théorème de Sard',
  'Monge',
  'Schwarz',
  'Rademacher',
  'lemme de Hadamard',
  'théorème d\'Euler',
  'fonction homogène',
  'laplacien',
  'fonction harmonique',
  'fonction harmonique sphérique',
  'fonction harmonique ellipsoïdale',
  'intégrale curviligne',
  'lemme d\'estimation',
  'intégrale multiple',
  'intégrale de surface',
  'théorème de Green',
  'divergence',
  'théorème de flux-divergence',
  'rotationnel',
  'théorème du gradient',
  'théorème du rotationnel',
  'inégalité des accroissements finis',
  'Nabla',
  'matrice jacobienne',
  'champ de vecteurs (conservatif',
  'solénoïdal',
  'irrotationnel)',
  'champ scalaire',
  'théorème de Helmholtz-Hodge',
  'jet',
  'singularité',
  'théorème de Stokes',
  'théorème du redressement',
  'courant',
  'flot',
  'flot géodésique',
  'théorème d\'inversion locale',
  'théorème des fonctions implicites',
  'difféomorphisme',
  'forme différentielle',
  'théorème de Poincaré',
  'problème de Dirichlet',
  'Analyse vectorielle',
  'Géométrie différentielle',
  'Suite numérique',
  'Série numérique',
  'Suite de fonction',
  'convergence simple',
  'convergence uniforme',
  'convergence en moyenne',
  'convergence en moyenne quadratique',
  'théorème de la limite simple de Baire',
  'équicontinuité',
  'théorèmes de Dini',
  'théorème d\'approximation de Stone-Weierstrass',
  'approximation de Bernstein',
  'théorème de Müntz',
  'théorème de Chudnovsky',
  'théorème de Bernstein',
  'Série de fonctions',
  'convergence normale',
  'série de Taylor',
  'série de Fourier',
  'série trigonométrique',
  'inégalité de Bernstein',
  'Série entière',
  'rayon de convergence',
  'fonction analytique',
  'théorème d\'Abel',
  'série hypergéométrique',
  'série lacunaire',
  'calcul intégral',
  'famille sommable',
  'fonction localement intégrable',
  'fonction simple',
  'théorème de convergence dominée',
  'lemme de Fatou',
  'carré sommable',
  'somme de Riemann',
  'intégrale impropre',
  'intégrale de chemin',
  'lemme de Cousin',
  'point de Lebesgue',
  'intégrale de Riemann',
  'intégrale de Lebesgue',
  'intégrale de Kurzweil-Henstock',
  'intégrale de Stieltjes',
  'intégrale impropre',
  'intégrale paramétrique',
  'produit de convolution',
  'valeur principale de Cauchy',
  'comparaison série-intégrale'
      'inégalité de Jensen',
  'théorème d\'interversion série-intégrale',
  'inégalité de Wirtinger',
  'inégalité de Tchebychev pour les sommes',
  'inégalité de réarrangement',
  'inégalité de Young',
  'inégalité de Nesbitt',
  'fonction maximale de Hardy-Littlewood',
  'formule d\'Euler-Maclaurin',
  'formule de Cauchy pour l\'intégration successive',
  'lemme de Grönwall',
  'théorème de Fubini',
  'théorème de convergence dominée',
  'théorème de convergence monotone',
  'théorème de différentiation de Lebesgue',
  'intégrales de Wallis',
  'intégrale de Gauss',
  'intégrale d\'Euler',
  'intégrale de Dirichlet',
  'intégrale de Fresnel',
  'Théorie de la mesure',
  'tribu',
  'sigma-anneau',
  'mesure',
  'espace mesurable',
  'espace mesuré',
  'partie mesurable',
  'fonction mesurable',
  'support de mesure',
  'mesure de comptage',
  'mesure de Dirac',
  'mesure de Hausdorff',
  'mesure de Lebesgue',
  'mesure finie',
  'mesure sigma-finie',
  'mesure complète',
  'régularité extérieure',
  'complétion d\'une mesure',
  'mesure produit',
  'mesure secondaire',
  'mesure signée',
  'mesure spectrale',
  'transformée de Stieltjes',
  'ensemble standard',
  'infiniment petit',
  'Abraham Robinson',
  'Edward Nelson',
  'nombre hyperréel',
  'principe d\'idéalisation',
  'principe de standardisation',
  'lissage',
  'méthode de la phase stationnaire',
  'méthode du point col',
  'technique de relaxation (dynamique',
  'continue)',
  'delta-2',
  'méthode de Monte-Carlo',
  'optimisation',
  'optimisation linéaire',
  'optimisation quadratique',
  'méthode des éléments finis',
  'méthode de Galerkin',
  'calcul numérique',
  'critères de Wolfe',
  'descente de gradient',
  'différence finie',
  'différences divisées',
  'séparation et évaluation',
  'extrapolation de Richardson',
  'BFGS',
  'méthode de Newmark',
  'méthode des caractéristiques',
  'intégration de Verlet',
  'problème bien posé',
  'théorème de Lax',
  'théorème de Lax-Wendroff',
  'stabilité d\'un schéma numérique',
  'théorème de Sturm',
  'théorème de Laguerre',
  'recherche linéaire',
  'conditions de Kuhn-Tucker',
  'ondelette',
  'ondelette de Haar',
  'sous-différentiel',
  'problème de l\'obstacle',
  'phénomène de Runge',
  'linéarisation équivalente',
  'théorème de Mahler',
  'théorème des nombres premiers',
  'théorème de Mertens',
  'problème de Bâle',
  'produit eulérien',
  'théorie de Galois différentielle',
  'théorie du potentiel',
  'théorie du transport',
  'Axiomes',
  'Point',
  'Droite',
  'Plan',
  'Polygones',
  'Triangle',
  'Carré',
  'Rectangle',
  'Losange',
  'Parallélogramme',
  'Trapèze',
  'Courbes',
  'Cercle',
  'Ellipse',
  'Cycloïde',
  'Parabole',
  'Hyperbole',
  'Conique',
  'Polyèdres',
  'Tétraèdre régulier',
  'Cube',
  'Octaèdre',
  'Dodécaèdre',
  'Icosaèdre',
  'Solides de révolutions',
  'Boule',
  'Cône de révolution',
  'Cylindre de révolution',
  'Tore',
  'Symétrie axiale',
  'Symétrie centrale',
  'Géométrie affine',
  'Coplanaire',
  'Convexité',
  'Espace affine',
  'Repère affine',
  'Orthocentre',
  'Barycentre',
  'Centre du cercle circonscrit',
  'Géométrie projective',
  'Application projective',
  'Conique',
  'Coordonnées homogènes',
  'Espace projectif',
  'Point à l\'infini',
  'Théorème de Pascal',
  'Géométrie euclidienne',
  'Espace euclidien',
  'Inégalité de Ptolémée',
  'Isométrie',
  'Plan euclidien',
  'Axiomes de Hilbert',
  'Géométrie différentielle',
  'Champ de vecteurs',
  'Coordonnées locales',
  'Fibré vectoriel',
  'Forme différentielle',
  'Variété différentielle',
  'Géométrie riemannienne',
  'Métrique riemannienne',
  'Variété riemannienne',
  'Géodésique',
  'Courbure',
  'Géométrie symplectique',
  'Dynamique hamiltonnienne',
  'Forme symplectique',
  'Théorème de Darboux (géométrie)',
  'Variété cotangente',
  'Groupe de Lie',
  'Transformation géométrique',
  'Programme d\'Erlangen',
  'Géométrie algébrique',
  'Courbe algébrique',
  'Faisceau',
  'Schéma',
  'Spectre d\'anneau',
  'Variété algébrique',
  'Géométrie discrète',
  'Lemme de Sperner',
  'Pavage',
  'Polytope',
  'Géométrie hyperbolique',
  'Demi-plan de Poincaré',
  'Disque de Poincaré',
  'Henri Poincaré',
  'Nicolaï Lobatchevsky',
  'Géométrie descriptive',
  'Gaspard Monge',
  'Projections orthogonales',
  'Dessin industriel',
  'Automate fini',
  'Automate sur les mots infinis',
  'Transducteur fini',
  'Automate à pile',
  'Automate linéairement borné',
  'Automate cellulaire',
  'Machine de Turing',
  'Lambda-calcul',
  'Fonction récursive',
  'Random access machine',
  'Parallel random access machine',
  'Recherche locale',
  'Recherche tabou',
  'Recuit simulé',
  'Algorithme génétique',
  'Programmation génétique',
  'Réseau de neurones artificiel',
  'Reconnaissance de formes',
  'Apprentissage non-supervisé',
  'Apprentissage supervisé',
  'Classification automatique',
  'Reconnaissance optique de caractères',
  'Algorithme de colonies de fourmis',
  'Système multi-agents',
  'Optimisation par essaims particulaires',
  'Calcul des propositions',
  'Calcul des prédicats',
  'Logique d\'ordre supérieur',
  'Skolémisation',
  'Théorie des modèles',
  'Théorie des types',
  'Théorème d\'incomplétude de Gödel',
  'Correspondance de Curry-Howard',
  'Thèse de Church',
  'Décidabilité',
  'Problème de l\'arrêt',
  'Ensemble récursif',
  'Ensemble récursivement énumérable',
  'Graphe',
  'Arbre',
  'Arête',
  'Clique',
  'Degré',
  'Graphe planaire',
  'Graphe complet',
  'Graphe biparti',
  'Graphe expanseur',
  'Coloration de graphe',
  'Coloration équitable',
  'Problème du voyageur de commerce',
  'Triangulation de graphe',
  'Recherche de chemin',
  'Problème d\'affectation',
  'Codes identifiants dans les graphes',
  'Problème de couverture de sommets',
  'Problème SAT',
  'Théorème de Robertson-Seymou',
  'Algorithme minimax',
  'Élagage alpha-bêta',
  'Dilemme du prisonnier',
  'Théorie des jeux',
  'Retour sur trace (ou backtrack)',
  'Séparation et évaluation (ou Branch & Bound)',
  'Algorithme A*',
  'Programmation par contraintes',
  'Optimisation linéaire',
  'Algorithme du simplexe',
  'Branch and cut',
  'Théorie des graphes',
  'Algorithme de Dijkstra',
  'Algorithme de Kruskal',
  'Algorithme de Prim',
  'Théorie de l\'information',
  'Combinatoire des mots',
  'Codage de l\'information',
  'Compression de données',
  'Cryptologie',
  'Cryptographie',
  'Cryptanalyse',
  'Cryptage',
  'Calcul séquentiel',
  'Calcul parallèle',
  'Ordinateur à ADN',
  'Calculateur quantique',
  'Théorie des langages',
  'Compilation',
  'Expression rationnelle',
  'Théorème de Kleene',
  'Grammaire formelle',
  'Langage rationnel',
  'Langage algébrique',
  'Langage contextuel',
  'Transduction rationnelle',
  'Théorème de Cook',
  'Réduction polynomiale',
  'Problèmes NP-complet',
  'Diviser pour régner',
  'Algorithme glouton',
  'Programmation dynamique',
  'Algorithme probabiliste',
  'Algorithme génétique',
  'Heuristique',
  'Théorie des graphes',
  'Géométrie algorithmique',
  'Structure de données',
  'Optimisation',
  'Liste de nombres',
  'Nombre rationnel',
  'Entier relatif',
  'Nombre parfait',
  'Nombre algébrique',
  'Nombre transcendant',
  'Nombre hypercomplexe',
  'Nombre transfini',
  'Nombre premier',
  'Legendre',
  'Conjecture de Legendre',
  'Théorème des nombres premiers',
  'Conjecture de Mertens',
  'Dernier théorème de Fermat-Théorème de Wiles',
  'Nombre de Bernoulli',
  'Nombre de Stirling',
  'Formule sommatoire de Poisson',
  'Formule sommatoire d\'Abel',
  'Pafnouti Tchebychev',
  'Mertens',
  'Gauss',
  'Théorème des quatre carrés',
  'Conjecture de Goldbach',
  'Problème de Waring',
  'Pierre de Fermat',
  'Fonction zêta de Riemann',
  'Histoire de la fonction zêta de Riemann',
  'Hardy',
  'Littlewood',
  'Térence Tao',
  'Wiles',
  'Joseph Bertrand',
  'Postulat de Bertrand',
  'Problème de Mengoli',
  'Crible d\'Ératosthène',
  'Théorème de Brun',
  'Hermite',
  'Nombre transcendant',
  'Liouville',
  'Axiomes des probabilités',
  'Probabilité',
  'Événement',
  'Tribu',
  'Espace probabilisé',
  'Indépendance',
  'Moment',
  'Espérance',
  'Variance',
  'Écart type',
  'Médiane',
  'Quartile',
  'Variable aléatoire',
  'Variables iid',
  'Loi de Bernoulli',
  'Loi de Poisson',
  'Loi uniforme',
  'Loi normale',
  'Théorème central limite',
  'Loi des grands nombres',
  'Théorème de Borel-Cantelli',
  'Marche aléatoire',
  'Chaîne de Markov',
  'Processus stochastique',
  'Processus de Markov',
  'Mouvement brownien',
  'Martingale',
  'Équation différentielle stochastique',
  'Statistique descriptive',
  'Échantillon',
  'Moyenne',
  'Quantile',
  'Erreur type',
  'Intervalle de confiance',
  'Représentations de données',
  'Histogramme',
  'Régression linéaire',
  'Méthode des moindres carrés',
  'Analyse des données',
  'Statistique mathématique',
  'Une statistique',
  'Fonction de répartition empirique',
  'Théorème de Glivenko-Cantelli',
  'Inférence bayésienne',
  'Maîtrise statistique des procédés',
  'Tests statistiques',
  'Test d\'hypothèse',
  'Hypothèse statistique (Hypothèse nulle)',
  'Estimateur',
  'Test du χ²',
  'Test de Student',
  'Test de Fisher',
  'Signification statistique',
  'Valeur p',
  'La mécanique quantique',
  'La théorie de l\'information',
  'La physique statistique',
  'la science actuarielle',
  'Science des données',
];

List<String> fonctions = [
  'nulle (x ↦ 0)',
  'constantes (x ↦ C)',
  'affines (x ↦ ax+b)',
  'identité (x ↦ x)',
  'linéaires (x ↦ ax)',
  'carré (x ↦ x2)',
  'second degré (x ↦ ax2+bx+c)',
  'polynomiales (x ↦ P(x))',
  'cube (x ↦ x3)',
  'puissances (x ↦ xn)',
  'inverse (x ↦ 1/x)',
  'homographiques (x ↦ ax+b/cx+d)',
  'rationnelles (x ↦ P(x)/Q(x))',
  'lorentziennes',
  'racine carrée (x ↦ √x)',
  'racine cubique (x ↦ 3√x)',
  'valeur absolue (x ↦ |x|)',
  'signe (sgn)',
  'partie entière (E : x ↦ [x])',
  'partie fractionnaire (x ↦ {x})',
  'porte (Π)',
  'rampe',
  'fonction de Heaviside (H)',
  'fonctions de Walsh (Wj)',
  'ondelettes de Haar (hk)',
  'compte des nombres premiers (π)',
  'fonctions de Tchebychev (ϑ, ψ)',
  'sinus (sin)',
  'cosinus (cos)',
  'tangente (tan)',
  'cotangente (cot)',
  'sécante (sec)',
  'cosécante (csc)',
  'arc sinus (arcsin)',
  'arc cosinus (arccos)',
  'arc tangente (arctan)',
  'arc cotangente (arccot)',
  'arc sécante (arcsec)',
  'arc cosécante (arccsc)',
  'involute (inv)',
  'noyau de Dirichlet (Dn)',
  'noyau de Fejér (Fn)',
  'sinus cardinal (sinc)',
  'Carotid–Kundalini (CKn)',
  'fonction de phase de Henyey-Greenstein (P)',
  'exponentielle (exp)',
  'exponentielle de base a (expa)',
  'exponentielle double',
  'exponentielle étirée',
  'logarithme décimal (log)',
  'logarithme népérien (ln)',
  'logarithme complexe (Log)',
  'gaussienne',
  'fonction W de Lambert',
  'cosinus hyperbolique (cosh)',
  'argument cosinus hyperbolique (arcosh)',
  'sinus hyperbolique (sinh)',
  'argument sinus hyperbolique (arsinh)',
  'tangente hyperbolique (tanh)',
  'argument tangente hyperbolique (artanh)',
  'sigmoïde',
  'logit',
  'fonctions de Brillouin (BJ)',
  'Langevin (L)',
  'Stumpff (cn)',
  'fonction de Brillouin (BJ)',
  'fonction de Langevin (L)',
  'fonction de Stumpff (cn)',
  'gamma (Γ)',
  'digamma (Ψ)',
  'polygamma',
  'gamma incomplète',
  'multidimensionnelle',
  'bêta (Β)',
  'bêta incomplète',
  'G-fonction de Barnes',
  'K-fonction',
  'fonction de Bose (gσ)',
  'Legendre (Pλμ, Qλμ)– Mittag-Leffler (Eαβ)',
  'logarithme intégral (Li)',
  'exponentielle intégrale (Ei)',
  'sinus intégral (Si)',
  'cosinus intégral (Ci)',
  'fonction d\'erreur (erf)',
  'fonctions de Dawson (D+, D−)',
  'fonctions de Voigt (V)',
  'fonctions de Pearson',
  'fonction de Gudermann (gd)',
  'Owen (T)',
  'Bickley-Naylor (Kin)',
  'fonction elliptique de Jacobi (sn, cn, dn)',
  'fonction elliptique de Weierstrass (℘)',
  'zêta (ζ) de Weierstrass',
  'thêta (ϑ)',
  'modulaire (λ)',
  'fonctions de Bessel (Jn)',
  'modifiées (In, Kn)',
  'sphériques (jn, yn)',
  'Neumann (Yn)',
  'Hankel (Hα)',
  'Kelvin-Bessel (berν, beiν, kerν, keiν)',
  'fonctions d\'Airy (Ai, Bi)',
  'Scorer (Gi, Hi)',
  'Q de Marcum',
  'harmoniques sphériques (Yl,m)',
  'ellipsoïdales',
  'fonctions de Mathieu',
  'fonctions cylindro-paraboliques',
  'fonctions zêta (ζ) de Riemann',
  'Dedekind',
  'Hasse-Weil',
  'Hurwitz',
  'Lerch',
  'fonction zêta (ζ) de Selberg',
  'fonction êta (η) de Dedekind',
  'fonction êta (η) de Dirichlet',
  'fonction bêta (β) de Dirichlet',
  'fonction chi (χ) de Legendre',
  'hypergéométrique confluente',
  'polylogarithme (Lin)',
  'fonction de Kummer (Λn)',
  'fonction de Clausen (Cls)',
  'fonction R de Riemann',
  'xi de Riemann (ξ)',
  'φ d\'Euler',
  'factorielle (!)',
  'indicatrice d\'Euler (φ)',
  'fonction diviseur (σa)',
  'partition d\'un entier (p)',
  'totient de Jordan (Jk)',
  'grand omega (Ω)',
  'fonction de Möbius (μ)',
  'Landau (g)',
  'Liouville (λ)',
  'von Mangoldt (Λ)',
  'Mertens (M)',
  'fonction 91 de McCarthy',
  'fonction d\'Ackermann (A)',
  'Carmichael (λ)',
  'castor affairé (Σ)',
  'Collatz',
  'comète de Goldbach (g)',
  'fonction de Sudan',
  'Takeuchi (τ)',
  'symbole de Kronecker (δ)',
  'symbole de Levi-Civita (ε)',
];

List<String> mimes = [
  'Architecte',
  'Traducteur',
  'Archéologue',
  'Bûcheron',
  'Boulanger',
  'Ébéniste',
  'Scientifique',
  'Policier',
  'Réparateur automobile',
  'Styliste',
  'Pédiatre',
  'Géologue',
  'Toiletteur',
  'Professeur',
  'Plombier',
  'Coiffeur',
  'Médecin',
  'Maréchal ferrant',
  'Berger',
  'Infirmière',
  'Agriculteur',
  'Peintre',
  'Caissière',
  'Grutier',
  'Avocat',
  'Acteur',
  'Footballeur',
  'Reporter',
  'Président',
  'Éleveur de chiens',
  'Informaticien',
  'Cuisinier',
  'Détective',
  'Publiciste',
  'Fleuriste',
  'Océanologue',
  'Dentiste',
  'Nageur',
  'Serrurier',
  'Pharmacien',
  'Garde forestier',
  'Maître-nageur',
  'Généticien',
  'Livreur de pizza',
  'Comptable',
  'Moniteur de ski',
  'Psychiatre',
  'Journaliste',
  'Vétérinaire',
  'Boucher',
  'Serveur ,Webmaster',
  'Orthophoniste',
  'Libraire',
  'Réalisateur',
  'Sapeur-pompier',
  'Chanteur',
  'Marionnettiste',
  'Designer',
  'Danseuse de ballet',
  'Magicien',
  'Photographe',
  'Pêcheur',
  'Barman',
  'Dompteur',
  'Éboueur',
  'Chanteur d\'opéra',
  'Chirurgien',
  'Président de la république',
  'Pilote d\'avion',
  'Clown',
  'Pick Pocket',
  'Danseuse du ventre',
  'Professeur de sport',
  'Garagiste',
  'Pingouin',
  'Héron',
  'Girafe',
  'Panda',
  'Babouin',
  'Marmotte',
  'Dauphin',
  'Bernard l\'ermite',
  'Boa',
  'Chameau',
  'Autruche',
  'Papillon',
  'Écureuil',
  'Lion',
  'Hibou',
  'Scarabée',
  'Lama',
  'Zèbre',
  'Koala',
  'Fourmi',
  'Souris',
  'Taupe',
  'Raton-laveur',
  'Grenouille',
  'Biche',
  'Escargot',
  'Phoque',
  'Tortue',
  'Chien de traineau',
  'Étoile de mer',
  'Caméléon',
  'Loutre',
  'Paon',
  'Kangourou',
  'Mouton',
  'Canard',
  'Bison',
  'Dinosaure',
  'Tatou',
  'Poule',
  'Hyène',
  'Faucon',
  'Anaconda',
  'Scorpion',
  'Coccinelle',
  'Têtard',
  'Saumon',
  'Mille-pattes',
  'Hippocampe',
  'Libellule',
  'Tapir',
  'Poisson clown',
  'Raton laveur',
  'Pic vert',
  'Chauve-souris',
  'Poulpe',
  'Lapin',
  'Dindon',
  'Paresseux',
  'Éléphant',
  'Moustique',
  'Crabe',
  'Papillon',
  'Chauve souris',
  'Piranha',
  'Poisson-chat',
  'Limace',
  'Pieuvre',
  'Pigeon',
  'Araignée',
  'Chat',
  'Tigre',
  'Singe',
  'Regarder la télé',
  'Mâcher un chewing-gum',
  'Faire du surf',
  'Fêter son anniversaire',
  'Rencontrer un martien',
  'Faire sauter une crêpe',
  'Presser une orange',
  'Faire la vaisselle',
  'Courir un Marathon',
  'Faire de la corde à sauter',
  'Couper un gâteau',
  'Marcher avec des échasses',
  'Faire ses devoirs',
  'Étendre du linge',
  'Sauter à la corde',
  'Tuer une araignée avec une bombe insecticide',
  'Être lunatique',
  'Faire la racaille',
  'Jouer à Pokemon',
  'Faire le clown',
  'Tirer à l\'arc',
  'Aller dans le train fantôme',
  'Chercher ses clés',
  'Courir après le bus',
  'Sortir les poubelles',
  'Faire des claquettes',
  'Allumer le barbecue',
  'Regarder la télé',
  'Mâcher un chewing-gum',
  'Traire une vache',
  'Escalader une montagne',
  'Se battre à l\'épée',
  'Avoir la grippe',
  'Téléphoner à mamie',
  'Planter un arbre',
  'Éplucher des patates',
  'Aller à la piscine',
  'Promener le chien',
  'Jongler avec des pommes',
  'Prendre l\'ascenseur',
  'Se transformer en loup-garou',
  'Lire du braille',
  'Faire du patin à glace',
  'Être malade en bateau',
  'Explorer une grotte',
  'Jouer du banjo',
  'Faire un tour en montgolfière',
  'Nouer sa cravate',
  'Se faire cuire un œuf',
  'Prendre l\'escalator',
  'Faire sauter une crêpe',
  'Presser une orange',
  'Jouer avec un yoyo',
  'Recevoir une médaille',
  'Être blonde',
  'Emballer une momie',
  'Arriver en retard',
  'Se préparer un café',
  'Changer le bébé',
  'Prendre un bain',
  'Aller à la pêche',
  'Faire de la trotinette',
  'Prendre un médicament (de votre choix…)',
  'Faire une course de haies',
  'Prendre le train',
  'Allumer un feu',
  'Vendre un tapis',
  'Manger une glace',
  'Faire de la moto',
  'Faire un câlin',
  'Marcher sur des braise',
  'Faire une galipette',
  'Manger des spaghettis',
  'Marcher dans le désert',
  'Faire des crêpes',
  'Danser la valse',
  'Changer une couche',
  'Faire de la boxe',
  'Jouer au curling',
  'Astérix le gaulois',
  'Bill Gates',
  'Lancelot',
  'Nanouk l’esquimau',
  'Superman',
  'Barack Obama',
  'Tintin',
  'Rayman',
  'Einstein',
  'Alice au pays des merveilles',
  'Jack Sparrow',
  'Louis Vuitton',
  'Alphonse Daudet',
  'Casimir',
  'Napoléon',
  'Bugs Bunny',
  'Johnny Halliday',
  'Lucky Luke',
  'Charlie Chaplin',
  'La Joconde',
  'Dark Vador',
  'Le génie de la lampe',
  'Haroun Tazieff',
  'Schreck',
  'La reine d’Angleterre',
  'Claude François',
  'Gaston Lagaffe',
  'Cindy Sanders',
  'Zavatta',
  'Lionel Messi',
  'Agatha Christie',
  'Hubert Reeves',
  'Picasso',
  'Steve Job',
  'Louis de Funès',
  'Mickey',
  'Chantal Goya',
  'Cousteau',
  'Galilée',
  'Un shadock',
  'Chef indien',
  'Harry Potter',
  'Cyril Lignac',
  'Archimède',
  'L’Abbé Pierre',
  'Louis XIV',
  'Céline Dion',
  'Les frères Grimm',
  'Cléopâtre',
  'Mr Bean',
  'Yannick Noah',
  'Isaac Newton',
  'Le Dalaï lama',
  'Bisounours',
  'Homer Simpson',
  'Jean-Pierre Pernaut',
  'Jules Verne',
  'Gad Elmaleh',
  'Dorothée',
  'Mac Gyver',
  'Mimi Mathy',
  'Zinedine Zidane',
  'Michael Jackson',
  'Mime Marceau',
  'Marilyn Monroe',
  'Anguille sous roche',
  'Tomber dans les pommes',
  'Mettre son grain de sel',
  'Être un ours mal léché',
  'Un froid de canard',
  'Jeter le bébé avec l’eau du bain',
  'Faut pas pousser mémé dans les orties',
  'Poser un lapin',
  'Filer à l’anglaise',
  'Fier comme un pou',
  'Avoir une araignée au plafond',
  'Rouler des yeux de merlan frit',
  'La poule aux oeufs d’or',
  'Bailler aux corneilles',
  'Pousser comme un champignon',
  'Toucher du bois',
  'Tirer les vers du nez',
  'Revenir bredouille',
  'Raconter des salades',
  'Vouloir le beurre et l’argent du beurre',
  'Être au bout du rouleau',
  'Devoir une fière chandelle',
  'Avoir un poil dans la main',
  'Comme on fait son lit',
  'on se couche',
  'Être au pied du mur',
  'Dire ses 4 vérités',
  'Être sage comme une image',
  'Passer comme un lettre à la poste',
  'Péter plus haut que son cul',
  'Rouler à tombeau ouvert',
  'La goutte d’eau qui fait déborder le vase',
  'Ronfler comme un loir',
  'Avoir les yeux plus gros que le ventre',
  'S’ennuyer comme un rat mort',
  'Copains comme cochons',
  'Donner sa langue au chat',
  'Remettre les pendules à l’heure',
  'L’habit ne fait pas le moine',
  'Mettre la main à la pâte',
  'Se mettre en 4',
  'Tête de linotte',
  'Épée de Damoclès',
  'Avoir le cafard',
  'Tirer le diable par la queue',
  'Avoir l’estomac dans les talons',
  'Donner de la confiture à un cochon',
  'Courir sur le haricot',
  'Tuer le temps',
  'Avoir la moutarde qui monte au nez',
  'Être sourd comme un pot',
  'Pleurer comme une madeleine',
  'Rire jaune',
  'N’avoir pas froid aux yeux',
  'La bave du crapaud n’atteint pas la blanche colombe',
  'Mentir comme un arracheur de dents',
  'Un moulin à paroles',
  'Être muet comme une carpe',
  'Avoir les crocs',
  'Se faire un sang d’encre',
  'Avoir plusieurs cordes à son arc',
  'Remuer le couteau dans la plaie',
  'Se prendre un râteau',
  'Pisser dans un violon',
  'Planche à voile',
  'Rugby',
  'Boxe anglaise',
  'Tennis de table',
  'Lancer de disque',
  'Parachutisme',
  'Gymnastique',
  'Plongée sous marine',
  'Curling',
  'Badminton',
  'Aviron',
  'Triathlon',
  'Spéléologie',
  'Foot',
  'Basket',
  'Natation',
  'Taikwendo',
  'Volley Ball',
  'Lancer du marteau',
  'Saut en longueur',
  'saut en hauteur',
  '110 mètres haies',
];
