List<String> naruto = [
  'Byakugan',
  'Izanagi',
  'Jôgan',
  'Kekkei Genkai de Ranmaru',
  'Ketsuryûgan',
  'Mangekyô Sharingan',
  'Mode Chakra du Tenseigan',
  'Rinne Sharingan',
  'Rinnegan',
  'Sharingan',
  'Susanô',
  'Susanô - Boule de Feu Suprême',
  'Susanô - Écrasement',
  'Tenseigan',
  '11 de Konoha',
  'Akatsuki',
  'Alliance Shinobi',
  'Anbu de la Feuille',
  'Armée des Zetsu Blanc',
  'Armée Fantôme',
  'Bande Anrai',
  'Bandits Mujina',
  'Brigade de Protection des Daimyô',
  'Brigade des Marionnettistes',
  'Brigade Kinkaku',
  'Chevaliers de Haido',
  'Cinquième Division',
  'Compagnie Gatô',
  'Compagnie Kaminarimon',
  'Conseil d\'Iwa',
  'Conseil de Konoha',
  'Conseil de Kumo',
  'Conseil de Suna',
  'Deux Grands Crapauds Ermites',
  'Deuxième Division',
  'Douze Ninjas Gardiens',
  'Duo A&B',
  'Département de Police de Konoha',
  'Détachement d\'Infiltration et de Reconnaissance',
  'Escouade de Huit Hommes',
  'Famille Akagi',
  'Famille Kurosuki',
  'Force Alliée des Mères',
  'Fratrie du Sable',
  'Frères Criminels',
  'Frères d\'Or et d\'Argent',
  'Frères Démons',
  'Gang de Jako',
  'Gang de la Route du Silence',
  'Gang de Quatre',
  'Garde de la Barrière de Konoha',
  'Garde de la Barrière de Kumo',
  'Gardes du corps du Raikage',
  'Groupe d\'Exploration de Suna',
  'Groupe Prajñâ',
  'Honorable Fratrie',
  'Idiots Légendaires',
  'Ino-Saku-Saï',
  'Ino-Shika-Chô (15e)',
  'Kara',
  'Lutteurs Sumo',
  'Nijû Shôtai',
  'Ninja Cuisinier',
  'Ninja Watari',
  'Nokizaru',
  'Nouveaux Sept Épéistes de la Brume',
  'Nuits Blanches',
  'Orphelins d\'Ame',
  'Peloton de Garde du Hokage',
  'Première Division',
  'Quadruplés de la Brume',
  'Quartet du Son',
  'Quatre Guerriers Ninjas Animaux',
  'Racine',
  'Raikô',
  'Révolutionnaires',
  'Sannin',
  'Section des Interrogatoires',
  'Sept Épéistes de la Brume',
  'Shin Uchiwa (Clones)',
  'Shinobazu',
  'Shitenshônin',
  'Taka',
  'Trio Moya',
  'Trois Frères Haimaru',
  'Trois Frères Ryûdôin',
  'Trois Frères Senka',
  'Trois Ninjas Errants',
  'Union Shinobi',
  'Unité d\'Assistance Médicale',
  'Unité d\'Attaque-Surprise',
  'Unité d\'Escorte',
  'Unité de Dynamitage',
  'Unité de Décryptage',
  'Unité de Décryptage (Kiri)',
  'Unité de Renseignement',
  'Unité de Scellage',
  'Unité des Traqueurs',
  'Unité Minato',
  'Équipe 2',
  'Équipe 40',
  'Équipe Ajisaï',
  'Équipe Ameno',
  'Équipe Asuma',
  'Équipe Bandô',
  'Équipe Chôza',
  'Équipe d\'Analyse',
  'Équipe d\'Arrestation du Kaima',
  'Équipe d\'Embuscade et de Distraction',
  'Équipe d\'Escorte du Marchand',
  'Équipe d\'Outils Scientifiques Ninjas',
  'Équipe de Missions Spéciales de Konoha',
  'Équipe de Protection de l\'Étoile',
  'Équipe de Recherche des Insectes Flaireurs',
  'Équipe de Récupération de Sasuke',
  'Équipe de sauvetage de Hanabi',
  'Équipe de Sauvetage du Kazekage',
  'Équipe de Scellement',
  'Équipe Dosu',
  'Équipe Doton',
  'Équipe Ebisu',
  'Équipe Furido',
  'Équipe Fû',
  'Équipe Fûton',
  'Équipe Ganryû',
  'Équipe Gaï',
  'Équipe Guren',
  'Équipe Hanabi',
  'Équipe Hiruko',
  'Équipe Jiraya',
  'Équipe Kabuto',
  'Équipe Kakashi',
  'Équipe Katon',
  'Équipe Kazami',
  'Équipe Komugi',
  'Équipe Konohamaru',
  'Équipe Kurenaï',
  'Équipe Magaki',
  'Équipe Matsuri',
  'Équipe Minato',
  'Équipe Moegi',
  'Équipe Médicale',
  'Équipe Oboro',
  'Équipe Orochimaru',
  'Équipe Ro',
  'Équipe Samui',
  'Équipe Saya',
  'Équipe Saï',
  'Équipe Shibire',
  'Équipe Shigeri',
  'Équipe Shigure',
  'Équipe Shinki',
  'Équipe Shiore',
  'Équipe Shira',
  'Équipe Shisui',
  'Équipe Suien',
  'Équipe Suiton',
  'Équipe Tobirama',
  'Équipe Udon',
  'Équipe Yurui',
  'Anbu',
  'Chasseur de Déserteur',
  'Chef de Village',
  'Chef Ninja',
  'Chûnin',
  'Commandant Jônin',
  'Daimyô',
  'Étudiant à l\'Académie',
  'Femme au foyer',
  'Genin',
  'Hokage',
  'Hoshikage',
  'Jônin',
  'Kage',
  'Kazekage',
  'Missions',
  'Mizukage',
  'Mode Ermite',
  'Ninja Médecin',
  'Nukenin',
  'Raikage',
  'Rang A',
  'Rang B',
  'Rang C',
  'Rang d',
  'Rang E',
  'Rang S',
  'Sannin',
  'Tokubetsu Jônin',
  'Tsuchikage',
  '10 Phalanges Perforantes',
  '1000 Ans de Souffrances',
  '128 Poings du Hakke',
  '16 Poings du Hakke',
  '32 Poings du Hakke',
  '64 Poings du Hakke',
  '64 Poings du Hakke Protecteurs',
  'Absorption de l\'Âme',
  'Absorption de Vapeur',
  'Absorption des Corps',
  'Adresse du Paon',
  'Affect Sournois de l\'Esprit',
  'Affection par Sons Perçants',
  'Aiguille Aqueuse',
  'Aiguille de Chakra',
  'Aiguille de Chevelure de Lapin',
  'Aiguille Silencieuse',
  'Aiguille Torpedo',
  'Aiguilles des Mille Oiseaux',
  'Aiguilles Infernales',
  'Akuta',
  'Altération du Corps',
  'Amaterasu',
  'Amenomihashira',
  'Amenominaka',
  'Amenotejikara',
  'Anatta',
  'Anneau de Carbone',
  'Anneau Tourbillonnant',
  'Apposition des Sceaux Maléfiques',
  'Arbre Muqueux',
  'Arc de Guerre de l\'Araignée - Scission Terrible',
  'Arc de Susanô',
  'Arcanes Blancs - Dix Pantins de Chikamatsu',
  'Arcanes du Hokage – Six Décennies – Rempart du Retour à la Source',
  'Arcanes Maudites - Contrôle du Corps par le Sang',
  'Arcanes Maudites - Hémo-Manipulation',
  'Arcanes Maudites - Pouvoir sur la Mort par le Sang',
  'Arcanes Noirs - Double Chambre Noire',
  'Arcanes Noirs - Fer Noir',
  'Arcanes Noirs - Salamandre',
  'Arcanes Rouges - Théâtre des 100 Pantins',
  'Arcanes Rouges - Triangle Mécanique',
  'Argile Explosive',
  'Armure de Cristal',
  'Armure de Frappe de Foudre',
  'Armure de Pierre',
  'Armure de Sable',
  'Arsenal de Limaille de Fer',
  'Art de l\'Épée Ninja - Crucifixion Filaire',
  'Art Ninja de l\'Aimant - Météorites Infinies',
  'Art Ninja de l\'Aimant - Particules Électromagnétiques',
  'Art Ninja de l\'Aimantation',
  'Artefact de la Barrière - Formation du Triangle Inversé',
  'Ascension du Dragon de Sang',
  'Assaut de Rassemblement de Limaille de Fer',
  'Assimilation - Boulet de Pierre',
  'Assimilation - Sarcophage de Sable',
  'Assimilation - Tempête de Pierre',
  'Assimilation - Tombeau du Désert',
  'Assimilation de l\'Univers',
  'Astre de Rikudô',
  'Attaquant Inattendu Reflété',
  'Attaque Blanche de la Marionnette',
  'Attaque d\'Âge Moyen',
  'Attaque de Bataille Circulaire',
  'Attaque de Grande Griffe de Chat',
  'Attaque de la Catapulte',
  'Attaque de Lance de Corne',
  'Attaque de Plumes',
  'Attaque de Vide des Quatre-Vingt Dieux',
  'Attaque des Abeilles Explosives',
  'Attaque des Démons Jumeaux',
  'Attaque des Mille Dards',
  'Attaque Destructrice des Lions Jumeaux du Hakke',
  'Attaque du Petit Orteil',
  'Attaque du Poing de Kurama',
  'Attaque Ultime - Lance de Shukaku',
  'Baiser d\'Exécution',
  'Baiser du Genjutsu',
  'Bakuton - Paume Explosive',
  'Bakuton - Poing Explosif',
  'Banbutsu Sôzô',
  'Banshô Ten\'in',
  'Barrage Déchaîné',
  'Barrière - Formation Canopy',
  'Barrière Auto-Régénérante',
  'Barrière de Blocage de Perception à Longue Portée',
  'Barrière de Scellement Quadrilatérale',
  'Barrière des Cinq Sceaux',
  'Barrière Labyrinthe',
  'Barrière Magique - Prison-Gourde du Crapaud',
  'Barrière Sensorielle',
  'Bataille des Enfers',
  'Bille de Sable',
  'Blizzard de Sakura',
  'Bois de Transmission',
  'Bombes Œufs Verts',
  'Boruto Stream',
  'Bouclier d\'Amaterasu',
  'Bouclier de Chakra',
  'Bouclier de Poussière d\'Or',
  'Bouclier de Sable',
  'Boue Acide',
  'Boule de Foudre',
  'Boulet Humain',
  'Boulet Humain Aqueux',
  'Boulet Humain Hérissé',
  'Bourrasque de Konoha',
  'Bourrasque Déchaînée',
  'Bras de Chakra de Bijû',
  'Bras Maléfiques',
  'Briseur de Roc du Hakke',
  'Brouillage par Insectes',
  'Brouillard Empoisonné - Destruction à l\'Aveugle',
  'Bruine de Limaille de Fer',
  'Bruine de Sable',
  'Bruine de Sable Perpétuelle',
  'Brume Illusoire',
  'Brumes du Tyran',
  'Bulle d\'Occultation d\'Odeur',
  'Bulle de Savon Visqueuse',
  'Bulle Explosive',
  'C0',
  'C1',
  'C2',
  'C3',
  'C4',
  'Cage aux Murs Indestructibles',
  'Cage de Fils',
  'Camouflage',
  'Camouflage dans la Brume',
  'Camouflage dans le Gel',
  'Camouflage en Surface',
  'Canon Naruto',
  'Canon à Grenadine',
  'Capacité de Régénération',
  'Carapace Dorée',
  'Cartouche Katon - Lance-Flamme',
  'Cartouche Raiton - Grand Souffle',
  'Cartouche Suiton - Orque',
  'Cercle Lumino-Filaire',
  'Chakra Noir',
  'Chakram de Papier',
  'Chaîne',
  'Chaîne de Foudre',
  'Chaînes d\'Adamantine d\'Attaque',
  'Chaînes d\'Adamantine de Scellement',
  'Chaînes de la Statue du Grand Démon',
  'Cheveux de Camouflage',
  'Chibaku Tensei',
  'Chikushôdô',
  'Chute de Feuille de Konoha',
  'Chute du Faucon',
  'Châtiment Divin',
  'Clonage Aqueux',
  'Clonage de Bô',
  'Clone d\'Argile',
  'Clone d\'Attentat Suicide',
  'Clone d\'Encre',
  'Clone d\'Image Rémanente',
  'Clone d\'Insectes',
  'Clone d\'Ombre Explosif',
  'Clone de Brume',
  'Clone de Cire d\'Abeille',
  'Clone de Corbeau',
  'Clone de Croquettes de Chat',
  'Clone de Fumée',
  'Clone de Limaille de Fer',
  'Clone de Papier',
  'Clone de Pierre',
  'Clone de Sable',
  'Clone de Tentacule de Poulpe',
  'Clone Ligneux',
  'Clone Parasite',
  'Clone Serpent',
  'Cocon d\'Araignée',
  'Combo de Konoha',
  'Contre-Attaque du Pantin',
  'Contrôle de Chauve-Souris',
  'Contrôle de Chauve-Souris - Vagues Ultrasoniques Télépathiques',
  'Contrôle des Calories',
  'Contrôle du Chakra - Vie et Mort',
  'Contrôle du Chakra de Ryûmyaku',
  'Corps de Sable',
  'Coup de Pied de la Lance Céleste',
  'Coup de Pied Plongeant',
  'Coup de Pied Éruptif',
  'Coup de Piston',
  'Coup de Piston - Style Un',
  'Coup de Sabre Arrière de l\'École de Kumo',
  'Coup de Sabre Expéditif',
  'Coup de Talon Légendaire',
  'Coup de Talon Retourné du Clone',
  'Coup de Tonnerre d\'Ouragan',
  'Coup de Tranchoir de Yosaku',
  'Coup de Tête',
  'Coups de Bandages',
  'Courant d\'Encre',
  'Course d\'Ombre',
  'Crainte de la Rancœur de la Terre',
  'Crinière Hirsute du Lion',
  'Crocs d\'insectes',
  'Crocs de la Foudre',
  'Crocs de Terre du Seigneur Légendaire',
  'Crocs Lacérants',
  'Crocs Scieurs',
  'Crocs Spirales',
  'Croissant de Lune Pourfendeur de l\'École de Kumo',
  'Création d\'Encre',
  'Création de Chakra Comestible',
  'Création de Griffe',
  'Création et Renouveau',
  'Création et Renouveau Suprêmes',
  'Cube aux Faces Écarlates',
  'Cube de Flammes Pourpres',
  'Daikokuten',
  'Danger des Lames Dansantes',
  'Danse de Faucille - Chute',
  'Danse de l\'Ancien Shuriken',
  'Danse de la Clématite à Grandes Fleurs',
  'Danse de la Transposition',
  'Danse des Jeunes Fougères Arborescentes',
  'Danse des Sept Sabres',
  'Danse du Camélia',
  'Danse du Chien',
  'Danse du Genji',
  'Danse du Mélèze',
  'Danse du Requin en Prison Aqueuse',
  'Danse du Saule',
  'Danse du Shikigami',
  'Danse du Shikigami - Punition',
  'Danse Sauvage du Feu Surgissant',
  'Danse sous la Nouvelle Lune',
  'Deiton - Bourbier Sans Fond',
  'Deiton - Fondations de Boue',
  'Deiton - Poupée de Boue',
  'Deiton - Sables Mouvants Boueux',
  'Destruction du Sceau des Cinq Éléments',
  'Deuxième Mouvement',
  'Dieu Dragon de Konoha',
  'Dieu du Tonnerre Volant',
  'Dieu du Tonnerre Volant - Seconde Étape',
  'Dieu du Tonnerre Volant - Tonnerre Guidant',
  'Dispersion en Origami',
  'Disque de Glace',
  'Doton - Abri sous la Roche',
  'Doton - Barrière de Terre',
  'Doton - Bâton de Roche',
  'Doton - Camouflage dans la Roche',
  'Doton - Canon Rocheux',
  'Doton - Cercueil de Pierre',
  'Doton - Corps de Boue',
  'Doton - Corps de Fer',
  'Doton - Coulée de Boue',
  'Doton - Croc de Forage Perçant',
  'Doton - Danse du Sable',
  'Doton - Drone',
  'Doton - Fouet du Dragon de Terre',
  'Doton - Fracture Tectonique',
  'Doton - Frappe Sismique',
  'Doton - Garde de Pierre',
  'Doton - Geôle de Terre',
  'Doton - Glissement de Terrain',
  'Doton - Golem de Pierre',
  'Doton - Grand Couvercle',
  'Doton - Grand Noyau Sismique',
  'Doton - Grande Muraille de Terre',
  'Doton - Hyper-Croissance Minérale',
  'Doton - Loups de Boue',
  'Doton - Marteau de Roche',
  'Doton - Marécage des Limbes',
  'Doton - Moine de Boue',
  'Doton - Montagne de Terre',
  'Doton - Motte de Terre',
  'Doton - Multi Clonage',
  'Doton - Mur de Terre',
  'Doton - Mur de Terre Multiple',
  'Doton - Noyau de Rotation Terrestre',
  'Doton - Pierres Volantes',
  'Doton - Pieu de Roche',
  'Doton - Pieux de Roche',
  'Doton - Poing de Granite',
  'Doton - Pression Lithique',
  'Doton - Prison aux Barreaux de Pierre',
  'Doton - Prison de Fer',
  'Doton - Projection Souterraine de Poissons',
  'Doton - Rempart de Terre',
  'Doton - Rempart de Terre Mouvant',
  'Doton - Roches Lourdes et Roches Légères',
  'Doton - Sables Mouvants',
  'Doton - Souffle du Dragon de Terre',
  'Doton - Technique de la Décapitation Fatale',
  'Doton - Technique de la Taupe Furtive',
  'Doton - Technique de la Tranchée',
  'Doton - Termitière de Boue',
  'Doton - Terre Dévorante',
  'Doton - Tourments de la Terre',
  'Doton - Tunnel',
  'Doton - Vague de Flux de Terre',
  'Doton - Vague de Terre',
  'Doton - Voyage Souterrain',
  'Doton - Écroulement des Roches',
  'Doton - Épines de Roche',
  'Doton - Éruption Volcanique',
  'Doton - Étreinte Tectonique',
  'Double Boulet Humain',
  'Double Coup Chargé',
  'Double Griffe Céleste',
  'Double Irruption Fracassante',
  'Double Mort des Serpents',
  'Double Panthère Noire',
  'Dragon Aqueux Électrique',
  'Dragon de Fumée',
  'Dragons Jumeaux',
  'Dynamic Action',
  'Décuplement Partiel',
  'Défense Absolue - Bouclier du Shukaku',
  'Défense de Sable - Lions Gardiens',
  'Déferlante de Sables Mouvants',
  'Déflagration Fulgurante',
  'Déguisement de Chakra',
  'Démoniaques Miroirs de Glace',
  'Déplacement Instantané',
  'Déplacement Éphémère',
  'Déploiement Aqueux Fatal',
  'Déploiement de la Toile',
  'Détection d\'Émotions Négatives',
  'Détection par la Pluie',
  'Détection par le Sable',
  'Dôjutsu d\'Espace-Temps de Sasuke',
  'Dôjutsu d\'Espace-Temps de Shin Uchiwa',
  'Dôme de Bulle',
  'Dôme de Tissu de Protection',
  'Dôme du Hakke',
  'Elbow',
  'Emprisonnement des Morts',
  'Emprisonnement des Morts - Rupture',
  'Emprisonnement du Feu',
  'Enchevêtrement Scalaire des Parchemins',
  'Enfer de Sable',
  'Enregistrement d\'Événement',
  'Ensorcellement des Cent Marionnettes',
  'Ensorcellement Scriptural',
  'Entaille de Flammes',
  'Entaille de Langue de Combat',
  'Enterrement du Désert',
  'Enton - Auxiliaires de Feu Noir',
  'Enton - Flammes Foudroyantes',
  'Enton - Projectiles Magiques de Yasaka',
  'Enton - Susanô Kagutsuchi',
  'Entrailles du Serpent Géant',
  'Entraînement de Concentration de la Feuille',
  'Entrelacement des Ombres',
  'Escalade des Arbres',
  'Estocade de l\'Enfer',
  'Estocade des Cornes',
  'Estocade du Dieu de la Foudre',
  'Excrétion de Fluide Corporel',
  'Exercice de Marche sur la Surface de l\'Eau',
  'Explosion de Bulle d\'Encre',
  'Explosion du Sasumata',
  'Explosion Météore Autruche',
  'Faisan Chasseur',
  'Faisceau de Kyûbi',
  'Faisceau de Lance Céleste de Kyûbi',
  'Feu du Dragon',
  'Filet de Sable',
  'Fils d\'Araignée',
  'Fils de Chakra (Fûma)',
  'Fission de Jûbi',
  'Flamme Rugissante du Chat de Feu',
  'Flash',
  'Flash Rouge',
  'Fleur de Lotus Recto',
  'Fleur de Lotus Recto Solo',
  'Fleur de Lotus Verso',
  'Fleur du Lotus Recto - Tourbillon Divin du Hakke',
  'Floraison de Toile d\'Araignée',
  'Flux de Chakra',
  'Flux des Mille Oiseaux',
  'Flèche d\'Indra',
  'Flèche de Papier',
  'Flèche Flamboyante d\'une Incroyable Capacité',
  'Flèche Lumineuse',
  'Flûte Démoniaque - Dissonance Hallucinatoire',
  'Flûte Démoniaque - Mélodie de Manipulation des Guerriers Illusoires',
  'For Intérieur de Sakura',
  'Force Améliorée au Chakra',
  'Formation Aile de Grue',
  'Formation Circulaire',
  'Formation de Barrière Destructive',
  'Formation de Combat - Myriades de Serpents',
  'Formation de Flammes Violettes',
  'Formation de la Barrière',
  'Formation de la Flamme des Uchiwa',
  'Formation de Sable Aveuglant - Confusion',
  'Formation de Sable Magnétique - Camouflage de Sable Brûlant',
  'Formation des Huit Portes',
  'Formation du Dieu du Tonnerre Volant',
  'Formation du Hakke Mécanique',
  'Formation Ino-Shika-Chô',
  'Formation Manji',
  'Formation Mur de Chien',
  'Formation Paon Tourbillonnant',
  'Foudre Noire',
  'Foudre Perçante de la Main du Sage',
  'Fouet d\'Amour',
  'Fouet de Carbone',
  'Fouet de la Conque',
  'Fracture Terrestre',
  'Frappe des Crapauds',
  'Frappes de Blocage des Tenketsu',
  'Fulgurance Ascensionnelle Rocheuse',
  'Funérailles Célestes - Frappe de la Foudre',
  'Funérailles Impériales du Désert',
  'Fureur Divine',
  'Fureur du Lion',
  'Furie des Orbes Géants',
  'Futton - Brume Acide',
  'Futton - Force Inégalée',
  'Fûinjutsu - Cellule Tétraédrique',
  'Fûinjutsu - Étreinte de la Pieuvre',
  'Fûton - Balles d\'Air',
  'Fûton - Bourrasque de Montagne Verdoyante',
  'Fûton - Bâtons d\'Étincelles',
  'Fûton - Canon du Crapaud',
  'Fûton - Danse des Pétales',
  'Fûton - Distorsion de l\'Air',
  'Fûton - Déferlante de Sable',
  'Fûton - Déferlantes de Vide',
  'Fûton - Embrasement de l\'Huile',
  'Fûton - Filet de Vent',
  'Fûton - Grand Filet de Vent',
  'Fûton - Grande Coupe du Dragon',
  'Fûton - Grande Lame du Vent',
  'Fûton - Grande Percée',
  'Fûton - Huile de Crapaud',
  'Fûton - Lame de Vide',
  'Fûton - Nuée de Dards de Sable',
  'Fûton - Orbe Shuriken',
  'Fûton - Orbe Shuriken Géant',
  'Fûton - Orbe Shuriken Répété',
  'Fûton - Orbe Tourbillonnant',
  'Fûton - Paume de la Bourrasque',
  'Fûton - Percée',
  'Fûton - Poing Tourbillon',
  'Fûton - Poussière de Vent',
  'Fûton - Pression Ravageuse',
  'Fûton - Sphère de Vide',
  'Fûton - Sphère de Vide Majeure',
  'Fûton - Spirale de Vent',
  'Fûton - Tornade de Shakujô',
  'Fûton - Trancheuse de Vent',
  'Fûton - Typhon Suprême',
  'Fûton - Vague de Vide',
  'Fûton - Valse d\'Air',
  'Gakidô',
  'Gardien d\'Aiguilles',
  'Gaz Corrosif',
  'Gaï de la Nuit',
  'Gedô',
  'Genjutsu - Flûte Paralysante',
  'Genjutsu - Ketsuryûgan',
  'Genjutsu - Poison de Papillon',
  'Genjutsu - Sharingan',
  'Genjutsu - Évasion en Pétale de Fleur',
  'Genjutsu d\'Interrogatoire',
  'Genjutsu d\'Éboulement',
  'Genjutsu de Communication',
  'Genjutsu du Cactus',
  'Genjutsu du Chat',
  'Genjutsu du Tintement de Grelot',
  'Genjutsu Mirage',
  'Genjutsu Suiton - Prison de Brouillard Fantôme Démoniaque',
  'Geôle de Paille',
  'Globe Visqueux',
  'Glycines Acides',
  'Gozu Tennô',
  'Grand Anneau Tourbillonnant',
  'Grand Brasier Foudroyant',
  'Grand Canon à Vide',
  'Grand Combo des Cinq Éléments',
  'Grand Éclair de Konoha',
  'Grande Claque',
  'Grande Confusion',
  'Grande Division de la Limace',
  'Grande Lame du Vent',
  'Grande Poigne du Serpent Spectral',
  'Grande Tornade de Konoha',
  'Gravure Manuelle du Sceau',
  'Griffes de Chakra du Chat',
  'Griffes du Félin',
  'Grêle d\'Orbes',
  'Grêle de Coups de Pied',
  'Grêle de Poings',
  'Grêle de Sable',
  'Guillotine Drop',
  'Gôken',
  'Habit de Sable',
  'Hexaèdre aux Faces Écarlates',
  'Hinokagutsuchi',
  'Hirondelle Volante',
  'Hitori Omote Renge',
  'Hommes-Bêtes Enragés',
  'Horizon de Tortures',
  'Horizon de Tortures - Danse Millénaire',
  'Huile de Crapaud',
  'Huit Portes',
  'Huit Tourbillons du Démon',
  'Hyôton - Avalanche de Loups',
  'Hyôton - Baleine Blanche Cornue',
  'Hyôton - Blizzard des Dragons Jumeaux',
  'Hyôton - Blizzard du Dragon Noir',
  'Hyôton - Chaîne Tellurique de Glace',
  'Hyôton - Dix Mille Pétales de Glace',
  'Hyôton - Dragon de Glace',
  'Hyôton - Dôme de Glace',
  'Hyôton - Hirondelles de Glace',
  'Hyôton - Marteau Brise Glace',
  'Hyôton - Mur de Cristal',
  'Hyôton - Tourbillon',
  'Hyôton - Zone de Capture Glaciale',
  'Iaidô',
  'Illusion des Chaînes de Haricots',
  'Illusion Démoniaque - Cajolerie de Charme',
  'Illusion Démoniaque - Chant de Confrontation du Crapaud',
  'Illusion Démoniaque - Corbeau Mirage',
  'Illusion Démoniaque - Descente aux Enfers',
  'Illusion Démoniaque - Destruction par Étreinte d\'Arbre',
  'Illusion Démoniaque - Double Environnement Trompeur',
  'Illusion Démoniaque - Entrave par les Pieux',
  'Illusion Démoniaque - Environnement Trompeur',
  'Illusion Démoniaque - Illusion de Mort',
  'Illusion Démoniaque - Puissante Illusion Distordante',
  'Illusion Mystique - Retournement du Miroir du Ciel et de la Terre',
  'Impact de la Fleur de Cerisier',
  'Insectes Parasites Géants - Morsure d\'Insecte',
  'Intervalle de la Sangsue',
  'Invocation',
  'Invocation - Concassage de l\'Estomac du Crapaud',
  'Invocation - Création d\'Armes en un Éclair',
  'Invocation - Danse du Faucheur',
  'Invocation - Destruction des Échoppes',
  'Invocation - Doton - Crocs Traqueurs',
  'Invocation - Estomac du Crapaud',
  'Invocation - Quintuple Rempart',
  'Invocation - Rempart',
  'Invocation - Réincarnation des Âmes',
  'Invocation - Statue du Grand Démon Hérésiarque',
  'Invocation - Triple Rempart',
  'Invocation - Vierge de Fer',
  'Invocation - Échoppe-Crapaud',
  'Invocation Combinée',
  'Invocation de Mandala',
  'Invocation des Cinq Portes Protectrices - Fermeture des Huit Portes',
  'Invocation des Ombres',
  'Invocation Expansive',
  'Invocation Inversée',
  'Invocation Spontanée d\'Arbre',
  'Irruption Fracassante',
  'Izanami',
  'Jarre de Poison',
  'Jigokudô',
  'Jinton - Détachement du Monde Primitif',
  'Jinton - Vol des Ténèbres',
  'Jiton - Funérailles Impériales de Poussière d\'Or',
  'Jiton - Shuriken Magnétique',
  'Jiton - Tonnerre sur Soi',
  'Juinjutsu de Danzô',
  'Juinjutsu de la Branche Principale du Clan Hyûga',
  'Jumbo Décuplement',
  'Jûken',
  'Kamui',
  'Kamui Shuriken',
  'Kata des Crapauds',
  'Katon - Araignée Écarlate',
  'Katon - Balsamine',
  'Katon - Balsamine Pourpre',
  'Katon - Bond de la Griffe du Corbeau Pourpre',
  'Katon - Boule de Feu',
  'Katon - Boule de Feu Suprême',
  'Katon - Bûcher Suprême',
  'Katon - Cantique de Libération du Feu du Dragon',
  'Katon - Corde de Feu',
  'Katon - Course de Feu',
  'Katon - Danse du Brouillard',
  'Katon - Déflagrations Vorticelles',
  'Katon - Embrasement de l\'Huile',
  'Katon - Embrasement Infernal du Dragon',
  'Katon - Embrasement Suprême',
  'Katon - Entrave Céleste',
  'Katon - Entrave du Feu',
  'Katon - Extermination par l\'Embrasement',
  'Katon - Face Intrépide',
  'Katon - Feu du Dragon',
  'Katon - Feu du Dragon Suprême',
  'Katon - Feu du Renard',
  'Katon - Flamme Suprême',
  'Katon - Garuda',
  'Katon - Grand Brasier',
  'Katon - Grande Boule de Feu',
  'Katon - Grande Fournaise',
  'Katon - Lanternes Démoniaques',
  'Katon - Météores de Feu',
  'Katon - Nuées Ardentes',
  'Katon - Nuées de Cendres',
  'Katon - Pluie de Boules de Feu',
  'Katon - Silex du Yagura',
  'Katon - Souffle du Dragon de Feu',
  'Katon - Tornade de Flammes',
  'Katon - Épée du Feu de l\'Entrave Céleste',
  'Katsuyu - Immense Réseau de Guérison',
  'Kekkei Genkai de Ryûzetsu',
  'Kekkei Genkai de Sakon et Ukon',
  'Kekkei Genkai du Clan de Jûgo',
  'Kekkei Genkai du Clan Iburi',
  'Kekkei Genkai du Clan Kurama',
  'Kekkei Genkai du Clan Rinha',
  'Kinjutsu d\'Iwa',
  'Kirin',
  'Kotoamatsukami',
  'Kurohigi : Arcanes Noirs',
  'Kâma',
  'Kôton - Bouclier d\'Acier',
  'Kôton - Corps d\'Acier',
  'Kôton - Projectile d\'Acier',
  'Lacération',
  'Lame de Chakra - Ligne Droite',
  'Lame des Conjurés - Os et Cendre',
  'Lame Dissimulée dans le Charme',
  'Lame du Vent',
  'Lame Meurtrière du Crapaud',
  'Lames Raiton à Haute Fréquence',
  'Lance Acérée du Chidori',
  'Lance de Coquillage',
  'Lance de Sable',
  'Lance Flamme Explosif',
  'Lance Pointue de Cheveux - Puissance',
  'Lancer du Clone',
  'Lances de la Conque',
  'Lariat du Démon à Queues',
  'Larmes Célestes',
  'Lecture de l\'Esprit',
  'Lecture du Temps',
  'Lettres Aqueuses',
  'Libération des Quatre Bombes Scellées',
  'Libération du Pouvoir de Sanbi',
  'Libération du Sceau Maléfique',
  'Ligotage de Fils',
  'Limaille de Fer - Ailes de Fer Noir',
  'Limelight',
  'Liquide de Chakra',
  'Lycoris Noir',
  'Main de Sable Monstrueuse',
  'Main du Désert',
  'Malédiction des Marionnettes',
  'Malédiction des Pantins de Sable',
  'Mangeur d\'Armure',
  'Manipulation de Chewing-Gum',
  'Manipulation de Lames d\'Attaque',
  'Manipulation des Mannequins de Bois',
  'Manipulation des Mille Mains',
  'Manipulation des Ombres',
  'Manipulation des Ombres de Gama Daïra',
  'Manipulation du Climat',
  'Manipulation du Moulin à Trois Lames',
  'Manipulation et Entrelacement des Ombres',
  'Marionnettes - Attaque de Rotation',
  'Marionnettisme',
  'Marquage de Limaille de Fer',
  'Marquage du Territoire',
  'Marque Maudite',
  'Marque Maudite de la Terre',
  'Marque Maudite du Ciel',
  'Marque Maudite du Félin',
  'Marques Maudites du Quartet du Son',
  'Masse d\'Eau Visqueuse',
  'Matérialisation de la Volonté',
  'Meiton - Jugement',
  'Meiton - Succion Abyssale',
  'Mille Aiguilles',
  'Mille Oiseaux',
  'Mines Explosives',
  'Mini Clone de Sanbi',
  'Mini Orbe Shuriken',
  'Mini Orbe Tourbillonnant',
  'Minions d\'Argile Explosive',
  'Miroir de Yata',
  'Missile',
  'Mode Baryon',
  'Mode Chakra de Kyûbi',
  'Mode Chakra Raiton',
  'Mode Chakra Yôton',
  'Mode Ermite',
  'Mode Ermite de Rikudô',
  'Mode Papillon',
  'Mode Rampement du Serpent',
  'Modification Physique Souple',
  'Mokunin - Possession Psychique',
  'Mokuton - Anneau de Pointes de Bois',
  'Mokuton - Carcan',
  'Mokuton - Colosse Sylvestre',
  'Mokuton - Coup d\'Adamantine',
  'Mokuton - Dragon Ligneux',
  'Mokuton - Enceinte de Bois',
  'Mokuton - Forêt des Essences Marines',
  'Mokuton - Gangue de Bois',
  'Mokuton - Grande Forêt',
  'Mokuton - Grande Lance d\'Arbre',
  'Mokuton - Maillet de Bois',
  'Mokuton - Maison des Quatre Piliers',
  'Mokuton - Manipulation d\'Outil Manuel',
  'Mokuton - Palais aux Mille Piliers',
  'Mokuton - Prison aux Quatre Piliers',
  'Mokuton - Révolte de l\'Enfer',
  'Mokuton - Sépulture de Bois',
  'Mokuton - Technique de la Lance Rhizomique',
  'Mokuton - Technique des Racines Souterraines',
  'Mokuton - Technique du Mur de Bois',
  'Mokuton - Technique Secrète - Croissance Luxuriante de la Forêt',
  'Mokuton - Transformation',
  'Mokuton - Têtes de Lions Gardiens',
  'Mokuton - Émergence Arborée',
  'Mokuton - Étreinte du Bouddha',
  'Mokuton - Étreinte Silencieuse',
  'Monde de Limaille de Fer',
  'Montée de Foudre',
  'Morsure de l\'Homme-Bête',
  'Morsure de Soin',
  'Morsure du Loup',
  'Mort Silencieuse',
  'Mouchard de Bois',
  'Moulin à Triple Tranchant',
  'Mucus Acide',
  'Mue de la Cigale',
  'Multi Clonage',
  'Multi Clonage de Fumée',
  'Multi Clonage Supra',
  'Multi-Shuriken Fantôme',
  'Multiclonage Mokuton Supra',
  'Multiple Cercle Lumino-Filaire',
  'Multiples Canons Lotus Connectés Non-Autonomes',
  'Mur Aérien de Sable',
  'Mur d\'Acier Scellé',
  'Mur de Boue',
  'Mur de Limaille de Fer',
  'Mur de Paume du Hakke',
  'Mur de Quarantaine',
  'Mur de Vent Rapide',
  'Muraille de Brume Rouge',
  'Musique d\'Amélioration de Chakra',
  'Musique de Compensation',
  'Méga Orbe Tourbillonnant',
  'Métamorphose Combinée',
  'Métempsychose de la Marionnette',
  'Métempsychose Explosive de l\'Anneau d\'Argent',
  'Métempsychose Explosive de l\'Anneau d\'Or',
  'Métempsychose Explosive Localisée',
  'Méthode de Changement du Corps par un Miroir d\'Ombre',
  'Méthode de Libération du Démon',
  'Météore Mortel de l\'Outil Précieux',
  'Naissance Divine d\'un Monde d\'Arbres',
  'Naruto Ultime Furie',
  'Narutornade des 2000 Poings',
  'Ningendô',
  'Ninjutsu d\'Espace-Temps de Jigen',
  'Ninjutsu des Bulles de Savon',
  'Ninpô - Poisson Éclair',
  'Ninpô - Reflet du Miroir aux Fleurs',
  'Ninpô Canin - Danse du Nuage de Poussière',
  'Ninpô des Fleurs',
  'Ninpô des Fleurs - Ouverture des Cent Corolles',
  'Ninpô des Fleurs - Étreinte Fatale des Cent Fleurs',
  'Ninpô Kagerô - Évanescence',
  'Nintaijutsu',
  'Nouveau Sexy Jutsu',
  'Nuage de Poison',
  'Nuit de Lune Voilée',
  'Ombre de la Feuille Morte',
  'Onde Bestiale',
  'Onde de Choc de Chakra Coupant',
  'Onde de Choc du Démon à Queues',
  'Onde Violente Bestiale',
  'Ondes Cinglantes',
  'Ondes Cinglantes Puissance Ultime',
  'Ongle Brumeux Essorant Volant',
  'Orbe des Démons à Queues',
  'Orbe Furie',
  'Orbe Pourpre',
  'Orbe Shuriken Démoniaque',
  'Orbe Shuriken Géant',
  'Orbe Tourbillonnant',
  'Orbe Tourbillonnant - Flash',
  'Orbe Tourbillonnant - « Unisson »',
  'Orbe Tourbillonnant Absolu',
  'Orbe Tourbillonnant Absorbant',
  'Orbe Tourbillonnant aux Sept Couleurs',
  'Orbe Tourbillonnant Comprimé',
  'Orbe Tourbillonnant de Guelel',
  'Orbe Tourbillonnant des Démons à Queues',
  'Orbe Tourbillonnant Disparaissant',
  'Orbe Tourbillonnant du Croissant de Lune',
  'Orbe Tourbillonnant Géant',
  'Orbe Tourbillonnant Hyper Comprimé',
  'Orbe Tourbillonnant Parent et Enfant',
  'Orbe Tourbillonnant Planétaire',
  'Orbe Tourbillonnant Tornade',
  'Orbe Tourbillonnant/Brouillon',
  'Orbes de Lumière',
  'Ouragan Autruche',
  'Ouragan de Konoha',
  'Ouragan Herculéen de Konoha',
  'Outil de Ninja - Boule de Fer Géante',
  'Outils de Manipulation - Météore de Confinement',
  'Pacte Sigillaire',
  'Pain Rikudô',
  'Pantin - Huit Salves d\'Aiguilles',
  'Pantin - Père et Mère',
  'Paon Matinal',
  'Paon Tourbillonnant',
  'Papillon Écrasant',
  'Parasite Démoniaque',
  'Parchemin Occultant',
  'Parfum de Fleur Mirifique',
  'Paume du Hakke',
  'Paume Mystique',
  'Paumes Jumelles des Lions Agiles',
  'Paumes Jumelles des Lions Agiles Tourbillonnants',
  'Perturbation des Impulsions du Corps',
  'Pilier de Sable',
  'Piques de Glace',
  'Piqûre d\'Insecte',
  'Pistolet à Eau',
  'Pistolet à Eau - Double Gun',
  'Piège Clonique',
  'Piège de Destruction de Repaire',
  'Piège de la Roche Cachée',
  'Piège de Miel',
  'Piège de shuriken',
  'Piège des Cheveux de Chakra',
  'Plaquage de la Montagne',
  'Pleine Charge de Démon à Queues',
  'Plongée dans les Limbes',
  'Plongée dans les Ténèbres',
  'Pluie d\'Araignées',
  'Pluie de la Rancune',
  'Pluie de Sang',
  'Pluie des Mille Aiguilles',
  'Plumes Explosives',
  'Pléiades du Cosmos',
  'Pléiades du Cosmos - Alioth',
  'Pléiades du Cosmos - Palais du Dragon',
  'Poigne du Serpent Spectral',
  'Poing Activé',
  'Poing Brise-Glace',
  'Poing d\'Arhat',
  'Poing de Corail',
  'Poing de Grès',
  'Poing Silencieux',
  'Poing Souple - Aiguille de Tenketsu',
  'Poing Souple - Soufflage de Corps',
  'Poing Ultra Activé',
  'Poing-Hache Destructeur',
  'Poings de Fer',
  'Possession du Serpent Blanc',
  'Pouding Pouding Jutsu',
  'Poussière Toxique',
  'Pouvoir du Sceau Sacré',
  'Pouvoir du Sceau Sacré - Silhouette',
  'Pouvoir Yang de Rikudô',
  'Pouvoir Yin de Rikudô',
  'Pratique de l\'Escalade de Falaise',
  'Prison d\'Incendie Criminel de Chaleur en Cage',
  'Prison de Fumée',
  'Prison de Fumée Destructrice d\'Odeur',
  'Prison de Sable',
  'Projectile Chakra de Kyûbi',
  'Projectiles Magiques de Yasaka',
  'Protection Genjutsu',
  'Puissance de la Main Divine - Mille Oiseaux',
  'Pétrification',
  'Quartet du Son - Invocation - Encerclement des Quatre Monstres',
  'Quatre Brouillards Noirs',
  'Quatre Serpents Noirs',
  'Raconter l\'Avenir',
  'Rafale d\'Orbes Tourbillonnants',
  'Rafale de Chakra de la Statue du Grand Démon',
  'Rafale de Konoha',
  'Rafale de Pic',
  'Rafales de Bruine de Limaille de Fer',
  'Raigô - Assassinat aux Mille Bras',
  'Raisen',
  'Raiton - Course de l\'Éclair',
  'Raiton - Crocs Traqueurs de la Bête de Foudre',
  'Raiton - Double Lariat',
  'Raiton - Flamboyance de la Foudre Illusoire',
  'Raiton - Flash Violet',
  'Raiton - Foudre',
  'Raiton - Foudre Serpentine',
  'Raiton - Lariat',
  'Raiton - Multi Clonage',
  'Raiton - Obscurité Factice',
  'Raiton - Overdrive',
  'Raiton - Panthère Noire',
  'Raiton - Paratonnerre',
  'Raiton - Porte du Tonnerre',
  'Raiton - Prison Électrique',
  'Raiton - Toile d\'Araignée',
  'Raiton - Vague d\'Émotions',
  'Raiton - Éclair du Loup',
  'Raiton - Éclairs Foudroyants',
  'Raiton - Électrocution par les Aiguilles Électriques',
  'Raiton - Étreinte des Quatre Piliers',
  'Raiton - Étreinte des Seize Piliers',
  'Ranton - Lame Azur de l\'Aigle',
  'Ranton - Laser Circus',
  'Ranton - Turbulences',
  'Ranton - Vague de Brouillard Électrique',
  'Rassemblement des Serpents',
  'Rayon Naruto',
  'Recouvrement du Corps',
  'Remontée Temporelle',
  'Remplacement d\'Eau',
  'Restreinte par le Sable',
  'Retournement de Vent',
  'Rikudô - Hurlement Légendaire',
  'Rikudô - Kunitsukami',
  'Rikudô - Main d\'Extinction de Flamme',
  'Rikudô - Orbe Shuriken Géant',
  'Rituel d\'Espace-Temps - Voyage pour l\'Enfer',
  'Rocher du Singe',
  'Roi Lotus Kanzeon',
  'Rotation Féroce de Vent',
  'Ruche en Pierre',
  'Rupture du Sceau',
  'Ruse des Insectes',
  'Ryûmyaku - Grand Feu du Dragon',
  'Ryûmyaku - Super Grande Technique du Feu du Dragon',
  'Récepteur de Chakra',
  'Réincarnation Mort-Vivante',
  'Répulsion Céleste',
  'Rétribution de l\'Éventail',
  'Rôen-Kodon',
  'Sabre Secret - Ombre Lunaire',
  'Saisie Meurtrière',
  'Salive Coulante de l\'Araignée',
  'Salve d\'Orbes Démoniaques',
  'Sanctuaire du Saule',
  'Sarcophage de Sable',
  'Saut Rapide Accéléré',
  'Scalpel de Chakra',
  'Sceau Auto Maléfique',
  'Sceau d\'Absorption de Chakra',
  'Sceau d\'Effacement de Mémoire',
  'Sceau de Confinement de Jûbi de Rikudô',
  'Sceau de Création et Renouveau Suprêmes',
  'Sceau de Drain de Chakra',
  'Sceau de Transcription - Amaterasu',
  'Sceau de Téléportation',
  'Sceau des Cinq Éléments',
  'Sceau des Neuf Dragons Illusoires',
  'Sceau des Quatre Anti-Éléments',
  'Sceau des Quatre Symboles',
  'Sceau du Grand Mausolée de Sable',
  'Sceau du Hakke',
  'Sceau du Torii',
  'Sceau Endigue le Mal',
  'Sceau Maudit Mortel',
  'Scellement de Bijû',
  'Scellement de Chakra du Bijû',
  'Senbon d\'Écaille',
  'Senjutsu de Rikudô',
  'Senpô - Amphibien',
  'Senpô - Chant des Grenouilles',
  'Senpô - Déchaînement de Foudre Inton',
  'Senpô - Fulgurance du Grand Serpent',
  'Senpô - Goemon',
  'Senpô - Jiton Orbe Tourbillonnant',
  'Senpô - Mokuton - Mille Mains Véritables',
  'Senpô - Méga Déchaînement d\'Orbes',
  'Senpô - Méga Orbe Shuriken Démoniaque',
  'Senpô - Porte du Dieu de Lumière',
  'Senpô - Rage Blanche',
  'Senpô - Ranton Crocs Incandescents',
  'Senpô - Shuriken de Magma',
  'Senpô - Transmigration Inorganique',
  'Senpô - Vent du Désert',
  'Sept Respirations Célestes',
  'Serpents Clones',
  'Serpents Clones - Technique du Dragon',
  'Serpents Maléfiques',
  'Serviteur de Brume',
  'Sexy Jutsu - Pole Dance et Corps de Rêve',
  'Sexy-Méta',
  'Shakuton - Grand Souffle de Fumée Explosive',
  'Shakuton - Halo Éolien de la Flèche Céleste de Flammes Noires',
  'Shakuton - Mort par Étuvage',
  'Sharingan de Coercition',
  'Shikotsumyaku',
  'Shin - Chibaku Tensei',
  'Shining Kick Autruche',
  'Shinraiju no Jutsu',
  'Shuradô',
  'Shuriken de Fleurs - Pluie de Pétales',
  'Shuriken de Manipulation des Ombres',
  'Shuriken de Papier',
  'Shuriken de Puce',
  'Shuriken de Sable',
  'Shuriken des Tuiles',
  'Shuriken Furtif',
  'Shuriken Multi Clonage',
  'Shôton - Aiguilles de Cristal',
  'Shôton - Clone de Cristal',
  'Shôton - Danse des Shuriken à Six Lames',
  'Shôton - Danse Sauvage des Shuriken de Cristal',
  'Shôton - Dragon de Cristal',
  'Shôton - Flèche de Lumière',
  'Shôton - Fruit Pourpre',
  'Shôton - Geôle de Cristal aux Cinq Parois',
  'Shôton - Labyrinthe de Cristal',
  'Shôton - Lame de Cristal',
  'Shôton - Lance de Cristal',
  'Shôton - Miroir de Cristal',
  'Shôton - Mur de Campement de Cristal',
  'Shôton - Mur de Huitième Formation',
  'Shôton - Pilier de Cristal à Six Faces',
  'Shôton - Pont de Cristal',
  'Shôton - Prison de Cristal',
  'Shôton - Roue de Cristal',
  'Shôton - Shuriken Géant de Cristal',
  'Shôton - Vague d\'Emprisonnement de Cristal',
  'Shôton - Épines de Croissance de Cristaux',
  'Singe Pyromane',
  'Smash Aérien Autruche',
  'Sommeil du Tanuki',
  'Sort d\'Entrave - Regard du Serpent',
  'Souffle Dévastateur des Trois Trésors',
  'Sphère d\'Eau Sensorielle',
  'Sphère d\'Odeur',
  'Sphère de Lumière Protectrice',
  'Sphère de Pelage',
  'Sphère de Sable Sensorielle',
  'Sphère de Vérité',
  'Sphère de Vérité Géante',
  'Sphère Géante',
  'Statue de l\'Hérétique - Cycle Éternel des Réincarnations',
  'Style de Taki - Lame Trancheuse d\'Eau',
  'Style Kumo',
  'Suiton - Armée de l\'Eau',
  'Suiton - Attaque d\'Eau du Ciel Glaciale',
  'Suiton - Attaque du Mégalodon Suprême',
  'Suiton - Balle de Croc d\'Eau',
  'Suiton - Barrière d\'Eau',
  'Suiton - Bassin de la Cascade',
  'Suiton - Bombe Aqueuse',
  'Suiton - Bouclier Aqueux',
  'Suiton - Bouclier d\'eau',
  'Suiton - Camouflage dans l\'Eau',
  'Suiton - Camouflage dans la Bruine',
  'Suiton - Camouflage dans la Pluie',
  'Suiton - Canon Aqueux',
  'Suiton - Canon Hypnique',
  'Suiton - Cinq Requins Dévoreurs',
  'Suiton - Cône du Déluge',
  'Suiton - Cônes du Déluge',
  'Suiton - Dragon Aqueux',
  'Suiton - Dragon Aqueux Explosif',
  'Suiton - Déferlante Brûlante',
  'Suiton - Encerclement des Piliers d\'Eau',
  'Suiton - Forge Aqueuse',
  'Suiton - Fouet Aqueux',
  'Suiton - Funérailles Explosives d\'Hydrification',
  'Suiton - Grand Bras Aqueux',
  'Suiton - Grand Typhon',
  'Suiton - Grande Cataracte',
  'Suiton - Grande Masse d\'Eau',
  'Suiton - Grande Vague Explosive',
  'Suiton - Gueule du Serpent',
  'Suiton - Large Projectile',
  'Suiton - Mare de Mucus',
  'Suiton - Mille Requins Dévoreurs',
  'Suiton - Miroir d\'Eau',
  'Suiton - Mitraillage d\'Eau',
  'Suiton - Méduse Médical',
  'Suiton - Paume du Dragon Azur',
  'Suiton - Piliers d\'Eau',
  'Suiton - Pluie de Colère et de Souffrance',
  'Suiton - Pluie Noire',
  'Suiton - Poisson du Démon',
  'Suiton - Prison Aqueuse',
  'Suiton - Rafale d\'Eau',
  'Suiton - Raz de Marée',
  'Suiton - Requin Élémentaire Aqueux',
  'Suiton - Rupture de la Lumière du Lotus',
  'Suiton - Technique de l\'Horizon entre Ciel et Mer',
  'Suiton - Technique de Sphère Sauvage de Requin d\'Eau',
  'Suiton - Technique des Bulles d\'Eau',
  'Suiton - Torrent Destructeur',
  'Suiton - Tranchant d\'Eau',
  'Suiton - Tranchant d\'Eau Montant',
  'Suiton - Trompette d\'Eau',
  'Suiton - Vague de Bulle Chaotique',
  'Suiton - Vague du Chaos',
  'Suiton - Vague Explosive',
  'Suiton - Vagues Déferlantes',
  'Suiton - Évanescence Explosive',
  'Suiton des Pantins - Danse de la Pluie',
  'Suiton Médical - Mante Religieuse Aqueuse',
  'Suiton Médical - Moustiques d\'Eau',
  'Sukunahikona',
  'Super Excellente Hyper Attaque',
  'Super Grand Orbe Shuriken Démoniaque',
  'Super Mini Orbe de Bijû',
  'Susanô - Chidori',
  'Susanô - Lacération Captive',
  'Susanô - Poing',
  'Susanô - Tsukumo',
  'Suspension du Désert',
  'Suture de l\'Araignée',
  'Sécrétion Arachnéenne Dorée',
  'Taiton - Furie du Cyclone',
  'Taiton - Tempête du Cauchemar',
  'Takamimusubinokami',
  'Talisman Maléfique Interdit Individuel',
  'Technique Chimère',
  'Technique d\'Accès au Temple Naka',
  'Technique d\'Activation de Cellule',
  'Technique d\'Assassinat',
  'Technique d\'Effacement de Mémoire',
  'Technique d\'Effacement et Copie du Visage',
  'Technique d\'Espionnage du Dragon',
  'Technique d\'Espionnage par les Insectes',
  'Technique d\'Evasion',
  'Technique d\'Extraction d\'Objet',
  'Technique d\'Extraction du Bijû',
  'Technique d\'Extraction du Poison',
  'Technique d\'Incorporation',
  'Technique d\'Insecte Parasite Destructeur',
  'Technique d\'Invisibilité',
  'Technique d\'Invocation Interdite - Comète des Feux des Rats',
  'Technique d\'Ouverture de la Barrière des Cinq Sceaux',
  'Technique d\'Ouverture de la Barrière Sensorielle',
  'Technique d\'Oxydation du Corps',
  'Technique d\'Évasion Transparente',
  'Technique de Bijû',
  'Technique de Blocage de la Mémoire',
  'Technique de Bulle d\'Eau Noyante',
  'Technique de Clone',
  'Technique de Copie du Visage',
  'Technique de Croisement',
  'Technique de Création d\'Outil',
  'Technique de Descellement',
  'Technique de Dispersion des Mille Corbeaux',
  'Technique de Dissimulation du Crapaud',
  'Technique de Division',
  'Technique de Décuplement',
  'Technique de Déplacement du Corps',
  'Technique de Guérison',
  'Technique de Guérison Réanimation Régénération',
  'Technique de l\'Alliance Shinobi',
  'Technique de l\'Avalanche',
  'Technique de l\'Homme Explosif',
  'Technique de l\'Homme Ivre',
  'Technique de l\'Âme Morte',
  'Technique de la barrière du Gunbai',
  'Technique de la Boule de Lumière',
  'Technique de la Brise Barrière',
  'Technique de la Bulle de Noyade',
  'Technique de la Cape d\'Invisibilité',
  'Technique de la Chambre Noire',
  'Technique de la Corde Fantôme',
  'Technique de la Coupe de Vent',
  'Technique de la Lanterne Magique du Corps',
  'Technique de la Météorite',
  'Technique de la Porte Cachée',
  'Technique de la Prison Glacée',
  'Technique de la Taupe Giflée',
  'Technique de la Vague de Son',
  'Technique de Lance-Boue',
  'Technique de Libération de Scellage',
  'Technique de Liquéfaction',
  'Technique de Manipulation d\'Objet',
  'Technique de Manipulation de Courrier',
  'Technique de Manipulation de la Taille',
  'Technique de Manipulation de Shuriken',
  'Technique de Marionnette - Aiguilles du Bras Prothétique',
  'Technique de Marionnette - Réalisation avec un Corps Humain',
  'Technique de Marionnettiste - Châtiment de l\'Attaque Printanière',
  'Technique de Modification du Relief',
  'Technique de Métamorphose',
  'Technique de Paralysie Temporaire',
  'Technique de Perception',
  'Technique de Permutation',
  'Technique de Permutation d\'Orochimaru',
  'Technique de Projection',
  'Technique de Pétrification',
  'Technique de Recréation de Corps',
  'Technique de Rikudô',
  'Technique de Réflexion Spirituelle',
  'Technique de Régénération Secrète',
  'Technique de Régénération Ultra-Rapide',
  'Technique de Rétrécissement',
  'Technique de Sabre du Samouraï',
  'Technique de Sceau - Assaut du Tigre aux Aguets',
  'Technique de Scellement - Rugissement de Fermeture du Lion',
  'Technique de Scellement des Uzumaki',
  'Technique de Spiritualisation',
  'Technique de Substitution',
  'Technique de Suppression de Chakra',
  'Technique de Séparation des Corps',
  'Technique des Bulles Aveuglantes',
  'Technique des Pantins Cadavériques',
  'Technique des Spores',
  'Technique des Tsuchigumo - Technique Interdite de Libération de Vie - Création du Ciel et de la Terre',
  'Technique Doton de Résurrection - Sol de Cadavres',
  'Technique du Brouillard d\'Encre',
  'Technique du Brouillard de Sang - Désossement',
  'Technique du Chakra Fantôme',
  'Technique du Clone de Bulle',
  'Technique du Cocon Humain',
  'Technique du Harem',
  'Technique du Harem - Sexy Inversé',
  'Technique du Livre de Dieu',
  'Technique du Miel',
  'Technique du Mur d\'Insectes',
  'Technique du Parchemin de Communication',
  'Technique du Sable - Manipulation de la Mémoire',
  'Technique du Télescope',
  'Technique pour Dénouer les Liens',
  'Technique Secrète - Aiguilles de Pierres',
  'Technique Secrète - Brouillard Étincelant',
  'Technique Secrète - Cocon d\'Insecte',
  'Technique Secrète - Invocation d\'Insectes',
  'Technique Secrète - Sphère d\'Insectes',
  'Technique Secrète - Tornade d\'Insectes',
  'Technique Secrète - Verse Acérée',
  'Technique Secrète - Vol de la Voix',
  'Technique Secrète Improvisée - Shuriken Fulguro-Sphères',
  'Technique à Retardement',
  'Temple du Nirvana',
  'Tempête de Poussière',
  'Tempête de Sable',
  'Tendô',
  'Tenpenchii',
  'Tenue Majestueuse - Susanô',
  'Terre Cramoisie',
  'Tigre du Zénith',
  'Tir d\'Aiguilles Chargées',
  'Toile aux Monstres Fantomatiques',
  'Toile d\'Araignée',
  'Tombeau du Désert',
  'Tonnerre Enragé',
  'Toppû de Konoha',
  'Tornade Céleste de Konoha',
  'Tornade d\'Éclairs et Danse des Hurlements',
  'Tornade de Konoha',
  'Tornade de Kyûbi',
  'Tornade de Pieds',
  'Tornade du Dragon de Foudre',
  'Tornade Herculéenne de Konoha',
  'Tornade Igno-Aqueuse',
  'Tornade Noire',
  'Tourbillon de Shuriken des Quatre Points Cardinaux',
  'Tourbillon Divin du Hakke',
  'Tourbillon Divin Géant du Hakke',
  'Tout est Souffrance',
  'Transfert de Cellules de Régénération',
  'Transfert de Chakra',
  'Transfert de Forme',
  'Transfert de volonté',
  'Transfert du Démon à Queues',
  'Transfert du Sceau - Izanagi',
  'Transfert Instantané',
  'Transfiguration Suprême',
  'Transformation - Bâton de la Vérité Bouddhique Indestructible',
  'Transformation Batracienne',
  'Transformation du Sang',
  'Transformation en Kaima',
  'Transformation en Loup Bicéphale',
  'Transformation en Loup Tricéphale',
  'Transformation Ermite',
  'Transmigration de sa Propre Vie',
  'Transmigration du Dragon',
  'Transmission Sensitive',
  'Transmission Tigre et Loup',
  'Transmission Étrange de l\'Ombre Distante',
  'Transposition',
  'Transposition Multiple',
  'Triple Coup de Lame du Crapaud',
  'Triple Foudre',
  'Troisième Œil',
  'Troisième Œil de Kagura',
  'Tsukuyomi',
  'Tsukuyomi Infini',
  'Tsukuyomi Restraint',
  'Télépathie',
  'Ultime Rasengan de Shion et de Naruto',
  'Uppercut Dragon de l\'Autruche',
  'Uzumaki Formation',
  'Uzumaki Naruto Furie',
  'Vague de Limaille de Fer',
  'Vague de Sable',
  'Vague Ténébreuse',
  'Vagues de Vent',
  'Valse de Perturbation Maléfique',
  'Volte-Face du Corps Démoniaque',
  'Volute de Fumée',
  'Vérification Sensorielle',
  'Véritable Feu de Samadhi',
  'Yamata',
  'Yo-Yo de Chair',
  'Yomotsu Hirasaka',
  'Yôton - Boule de Caoutchouc',
  'Yôton - Boules de Feu Flamboyantes',
  'Yôton - Chaux Pétrifiante',
  'Yôton - Corde Élastique',
  'Yôton - Destruction de Planète',
  'Yôton - Dissolution Monstrueuse',
  'Yôton - Défense Élastique',
  'Yôton - Expansion d\'Anneaux de Flamme',
  'Yôton - Mur de Caoutchouc',
  'Yôton - Poing Blindé Brûlant',
  'Yôton - Scellement en Pierre de Cendres',
  'Zone de Fils d\'Araignée',
  'Zone de Manipulation des Ombres',
  'Échange du Dieu de la Foudre',
  'Éclair Perçant',
  'Éclair Pourfendeur',
  'Éclair Pourfendeur Divin',
  'Éclair Rose',
  'Éclosion',
  'Éclosion Totale - Impact de la Fleur de Cerisier',
  'École de Konoha - Technique du Saule',
  'École de Nadeshiko - Coup de Pied Rugissant',
  'École de Nadeshiko - Danse Aérienne',
  'École de Nadeshiko - Poing de la Tornade Rugissant',
  'École des Herbes - Poings Destructeurs',
  'Écrasement de Vapeur',
  'Éléphant du Soir',
  'Éphémère',
  'Épée de Glace',
  'Épée de Kusanagi - Katana du Chidori',
  'Épée de Kusanagi - Katana Volant',
  'Épée de l\'Ombre',
  'Épée de Sable',
  'Épée du Vent',
  'Épée Flamboyante d\'Uchiwa - Possession de Feu',
  'Épée Volante Tournoyante',
  'Éro-Technique - Ébats Féminins',
  'Éro-Technique - Ébats Masculins',
  'Éruption de Fleurs',
  'Éternel Rival',
  'Étreinte de Cheveux',
  'Étreinte de l\'Infini',
  'Étreinte de l\'Infini Multiple',
  'Étreinte de Langue de Combat',
  'Étreinte de Tissu',
  'Étreinte du Vent',
  'Étreinte Mortelle de l\'Ombre',
  'Évangile de l\'Ange',
  'Éventail du Bananier - Rouleau de Feu',
  'Éventail du Bananier - Rouleau de Vent',
  'Œil de Lecture d\'Esprit',
  'A (Deuxième Raikage)',
  'A (Premier Raikage)',
  'A (Quatrième Raikage)',
  'A (Troisième Raikage)',
  'Abiru',
  'Agari',
  'Agari Kaisen',
  'Ageha',
  'Agira Ryûdôin',
  'Ahiko',
  'Ajisaï',
  'Akaboshi',
  'Akahoshi',
  'Akamaru',
  'Akane',
  'Akatsuchi',
  'Akemaru',
  'Akino',
  'Akio',
  'Akita Inuzuka',
  'Akkun',
  'Amachi',
  'Amado',
  'Amaru',
  'Amayo',
  'Amaï',
  'Ame (étudiant)',
  'Ameno',
  'Ameyuki',
  'Ameyuri Ringo',
  'Ami',
  'Amino',
  'Anbu au Masque d\'Aigle',
  'Anbu au Masque d\'Oiseau',
  'Anbu au Masque de Renard',
  'Anbu au Masque de Sanglier',
  'Anbu au Masque de Tigre',
  'Ancien des Hyûga',
  'Ancienne Cheffe du Village de Nadeshiko',
  'Aniki',
  'Anko Mitarashi',
  'Ao',
  'Aoba Yamashiro',
  'Aoda',
  'Aoï Rokushô',
  'Arai',
  'Arashi',
  'Araya',
  'Armadiko',
  'Asaka',
  'Asami',
  'Ashimaru',
  'Ashina',
  'Ashina Uzumaki',
  'Ashitaba',
  'Assistant du Sculpteur sur Pierre',
  'Asuma Sarutobi',
  'Asura Ôtsutsuki',
  'Atsui',
  'Ayame',
  'Ayato',
  'Azami',
  'Baiu',
  'Baji',
  'Baki',
  'Baku',
  'Baku (Anbu)',
  'Bakuto',
  'Bando',
  'Bandô',
  'Banna',
  'Bansai',
  'Baraki',
  'Baru Uchiwa',
  'Bekkô',
  'Benga',
  'Benten',
  'Bisuke',
  'Biwako Sarutobi',
  'Blue B',
  'Boro',
  'Boruto Uzumaki',
  'Bull',
  'Buna',
  'Bunpuku',
  'Buntan Kurosuki',
  'Bunzô',
  'Burami',
  'Butsuma Senju',
  'Byakuren',
  'Bête Ultime d\'Invocation',
  'C',
  'Calmar Géant',
  'Caméléon Géant à Queue de Serpent',
  'Capitaine des Assassins de Suna',
  'Capitaine des Ninjas du Ciel',
  'Capitaine du Vaisseau Fantôme',
  'Capitaine Ninja du Ciel',
  'Chamaru',
  'Chamû',
  'Chef des Tsuchigumo',
  'Chef du Clan Kaguya',
  'Chef du Village de Tonika',
  'Chen',
  'Chen (étudiant)',
  'Chibi',
  'Chichiatsu',
  'Chien Multicéphale Géant',
  'Chikara',
  'Chino',
  'Chiriku',
  'Chishima',
  'Chiyo',
  'Chiyo (princesse)',
  'Chogo',
  'Chôchô Akimichi',
  'Chôhan',
  'Chôji Akimichi',
  'Chôjûrô',
  'Chômei',
  'Chôseki',
  'Chôza Akimichi',
  'Chûji',
  'Chûkaku',
  'Chûkichi',
  'Chûshin',
  'Clone de Naruto à Neuf Queues',
  'Code',
  'Commandant de l\'Anbu',
  'Condor',
  'Corbeau d\'Itachi',
  'Crustacé Géant',
  'Créature d\'Espionnage au Sharingan',
  'Daen Nara',
  'Daibutsu',
  'Daichi',
  'Daikoku Funeno',
  'Daimaru',
  'Daimyô de Ci',
  'Daimyô de l\'Eau',
  'Daimyô de la Foudre',
  'Daimyô de la Terre',
  'Daimyô des Crocs',
  'Daimyô des Griffes',
  'Daimyô des Sources Chaudes',
  'Daimyô du Feu',
  'Daimyô du Gel',
  'Daimyô du Son',
  'Daimyô du Thé',
  'Daimyô du Vent (Partie I)',
  'Daimyô du Vent (Partie II)',
  'Dajimu',
  'Dan Katô',
  'Dango',
  'Dango Mitsuki',
  'Dangô',
  'Danzô Shimura',
  'Darui',
  'Daï Maito',
  'Deepa',
  'Deidara',
  'Delta',
  'Dengaku',
  'Denka',
  'Denki Kaminarimon',
  'Disonasu',
  'Dodaï',
  'Dokan',
  'Doki',
  'Dokku',
  'Don',
  'Doragu',
  'Dosu Kinuta',
  'Dotô Kazahana',
  'Dôshin',
  'Dôshu Goetsu',
  'Dôtô Akimichi',
  'Ebisu',
  'Ebizô',
  'Ehô Norimaki',
  'Emi',
  'Emina',
  'Emiru',
  'En',
  'En no Gyôja',
  'En Oyashiro',
  'Enchû Nara',
  'Enko Onikuma',
  'Enma',
  'Enra',
  'Ensui Nara',
  'Ereki Kaminarimon',
  'Erimaki Sharo',
  'F',
  'Faz',
  'Femme de Kisuke',
  'Fille de Sâra',
  'Fils de Gennô',
  'Fourmilier Géant',
  'Fubuki Kakuyoku',
  'Fudô',
  'Fuen',
  'Fugaku Uchiwa',
  'Fugaï',
  'Fugi',
  'Fuguki Suikazan',
  'Fukasaku',
  'Fuki',
  'Fuki (Pays du Son)',
  'Fuku',
  'Fukusuke Hikyakuya',
  'Fukuyokana',
  'Funari',
  'Furofuki',
  'Furui',
  'Fusô',
  'Futaba',
  'Futsu',
  'Fuyô',
  'Fû',
  'Fû Yamanaka',
  'Fûjin',
  'Fûka',
  'Fûta Kagetsu',
  'Gaara',
  'Gakidô (personnage)',
  'Gaku Inuzuka',
  'Gama',
  'Gamabunta',
  'Gamaden',
  'Gamagorô',
  'Gamahiro',
  'Gamaken',
  'Gamakichi',
  'Gamamaru',
  'Gamariki',
  'Gamatama',
  'Gamatatsu',
  'Gameru',
  'Gandô',
  'Ganryû',
  'Gantetsu (Iwa)',
  'Gantetsu (Shinobazu)',
  'Garaga',
  'Garde du Corps de Tenzen',
  'Gari',
  'Garuda',
  'Garô',
  'Gataro',
  'Gatsu',
  'Gatô',
  'Gaï Maito',
  'Gekkô',
  'Gekomatsu',
  'Gen\'yûmaru',
  'Genba',
  'Genbu',
  'Gengetsu Hôzuki',
  'Gengo',
  'Genji',
  'Genma Shiranui',
  'Gennaï',
  'Gennô',
  'Genshô Ryûdôin',
  'Gensui Amagiri',
  'Genzô',
  'Gerotora',
  'Gigi',
  'Giichi',
  'Ginji',
  'Ginkaku',
  'Gitai',
  'Golem de la Prison de Pierre',
  'Gonbee',
  'Gongorô Kamakura',
  'Gonta',
  'Goshiki',
  'Gosunkugi',
  'Gotta',
  'Gozu',
  'Gozu (Racine)',
  'Grand Chef Ninja de Kumo',
  'Grand-Mère d\'Obito',
  'Guerrier Maudit',
  'Guren',
  'Guruko',
  'Gyûki',
  'Gôshô Tôjin',
  'Gôza',
  'Gôzu',
  'Hachidai',
  'Hagiri',
  'Hagoromo Ôtsutsuki',
  'Haguruma',
  'Haido',
  'Haie',
  'Hajiki',
  'Hakkaku',
  'Hako Kuroi',
  'Haku',
  'Hakubi Shin',
  'Hakuhyô',
  'Hakui',
  'Hamaki Mimura',
  'Hamura Ôtsutsuki',
  'Han',
  'Hana Inuzuka',
  'Hanabi Hyûga',
  'Hanare',
  'Hanzaki',
  'Hanzô',
  'Haori',
  'Harine',
  'Haruna',
  'Harusame',
  'Hashirama Senju',
  'Hassaku Onomichi',
  'Hayama Shirakumo',
  'Hayase',
  'Hayate Gekkô',
  'Hazuki Uchiwa',
  'Hebiichigo',
  'Heiji',
  'Heki',
  'Hiashi Hyûga',
  'Hibachi',
  'Hibari',
  'Hidan',
  'Hidari',
  'Hikaku Uchiwa',
  'Hikaru',
  'Hikaru Tsuki',
  'Himawari Uzumaki',
  'Himuka Suzukaze',
  'Himushi',
  'Hina',
  'Hinata Hyûga',
  'Hino',
  'Hinoe',
  'Hinoko',
  'Hippo Boss',
  'Hiruga',
  'Hiruko (nukenin)',
  'Hiruzen Sarutobi',
  'Hisame',
  'Hisen',
  'Hishaku',
  'Hitode',
  'Hizashi Hyûga',
  'Hoheto Hyûga',
  'Hohozuki',
  'Hokushin',
  'Hokuto',
  'Homura Mitokado',
  'Honoka',
  'Hotaru',
  'Hotarubi',
  'Hyô',
  'Hâto',
  'Hôichi',
  'Hôki (Taki)',
  'Hôki (Takumi)',
  'Hôki (Watari)',
  'Hôki Taketori',
  'Hôsei',
  'Hôshô',
  'Ibara',
  'Ibiki Morino',
  'Ibuse',
  'Ibushi',
  'Ichi',
  'Ichigen',
  'Ichikishimahime',
  'Ichirôta Oniyuzu',
  'Idate Morino',
  'Iggy',
  'Ikkaku Umino',
  'Ikkyû Madoka',
  'Inabi Uchiwa',
  'Inaho',
  'Inari',
  'Indra Ôtsutsuki',
  'Ino Yamanaka',
  'Inoichi Yamanaka',
  'Inojin Yamanaka',
  'Inomatsu',
  'Insecte Géant',
  'Iori',
  'Iroha (Genin)',
  'Iroha Hyûga',
  'Iruka Umino',
  'Isago',
  'Isaribi',
  'Ise',
  'Ishidate',
  'Ishikawa',
  'Isobu',
  'Isono',
  'Isshiki Ôtsutsuki',
  'Itachi Uchiwa',
  'Itama Senju',
  'Ittan',
  'Ittetsu',
  'Iwabee Yuino',
  'Iwana Akame',
  'Iwashi Tatami',
  'Iyashi',
  'Izumi Uchiwa',
  'Izumo Kamizuki',
  'Izuna Uchiwa',
  'Iô',
  'Iô (ninja médecin)',
  'Iô (Village des Bambous)',
  'J',
  'Jako',
  'Jakô Ryûdôin',
  'Jantô',
  'Jibachi',
  'Jiga',
  'Jigen',
  'Jigokudô (personnage)',
  'Jigumo',
  'Jimei',
  'Jin',
  'Jinin Akebino',
  'Jinpachi Munashi',
  'Jiraya',
  'Jiryû Sendô',
  'Jirô',
  'Jirôbô',
  'Jirôchô Wasabi',
  'Junsai',
  'Jôseki',
  'Jûbi',
  'Jûbi de Jigen',
  'Jûgo',
  'Jûzô Biwa',
  'K',
  'Kabuto Yakushi',
  'Kaede Yoshino',
  'Kagami Uchiwa',
  'Kagari',
  'Kage (Anbu)',
  'Kageki',
  'Kagen Uchiwa',
  'Kagerô',
  'Kagura Karatachi',
  'Kaguya Ôtsutsuki',
  'Kahiko',
  'Kahyô',
  'Kaiza',
  'Kaji',
  'Kajika',
  'Kajûra',
  'Kakashi Hatake',
  'Kakeru Tsuki',
  'Kakkô',
  'Kakoi',
  'Kakuzu',
  'Kakô',
  'Kamata',
  'Kamatari',
  'Kamikiri',
  'Kamira',
  'Kandachi',
  'Kangourous Boxeurs',
  'Kankitsu Akitsuki',
  'Kankurô',
  'Kanna',
  'Kanna (Charpentier)',
  'Kannyû',
  'Kanoe',
  'Kanoto',
  'Kanpô',
  'Kaori',
  'Karashi',
  'Karasuki',
  'Karenbana',
  'Karin',
  'Karui',
  'Karura',
  'Karyû',
  'Kashike',
  'Kasuga Nara',
  'Kasumi',
  'Katasuke Tôno',
  'Katazu',
  'Katsura',
  'Katsuyu',
  'Kawaki',
  'Kawarama Senju',
  'Kaya',
  'Kayo',
  'Kazabune',
  'Kazami',
  'Kazan',
  'Kazuma',
  'Kedama',
  'Kegon',
  'Kiba Inuzuka',
  'Kido Tsumiki',
  'Kidômaru',
  'Kie',
  'Kigiri',
  'Kihô',
  'Kiiro',
  'Kiki',
  'Kikunojô',
  'Killer B',
  'Kimimaro',
  'Kin Tsuchi',
  'Kina Kodon',
  'King',
  'Kinkaku',
  'Kinoto',
  'Kinshiki Ôtsutsuki',
  'Kintoki',
  'Kirara',
  'Kiri (ninja)',
  'Kiri (villageoise)',
  'Kirisaki',
  'Kirisame',
  'Kiruru',
  'Kisame Hoshigaki',
  'Kisuke Maboroshi',
  'Kitane',
  'Kitsuchi',
  'Kitô',
  'Kiyoi Yotsuki',
  'Kiyomu Fukuda',
  'Kiyoyasu Kagetsu',
  'Kizashi Haruno',
  'Kodaka',
  'Kohada',
  'Kohan Yamanaka',
  'Kohari Umino',
  'Koharu Utatane',
  'Koji Kashin',
  'Kokage Yanagikage',
  'Kokuri',
  'Kokuyô',
  'Kokuyô (marionnettiste)',
  'Kokuô',
  'Komachi',
  'Komame',
  'Komaza',
  'Komichi',
  'Komitsu',
  'Komugi',
  'Komushi',
  'Kona',
  'Konan',
  'Kongô',
  'Konohamaru Sarutobi',
  'Kontsuchi',
  'Korega',
  'Korobi',
  'Kosuke',
  'Kosuke Maruboshi',
  'Kotetsu Hagane',
  'Kotohime',
  'Koyuki Kazahana',
  'Kozuchi',
  'Kujaku',
  'Kumade Toriichi',
  'Kumadori',
  'Kunihisa',
  'Kunijirô',
  'Kunoichi d\'Iwa',
  'Kunugi Mokume',
  'Kurama',
  'Kurenaï Yûhi',
  'Kurobachi',
  'Kuromaru',
  'Kurotsuchi',
  'Kurozuka',
  'Kusabi',
  'Kushimaru Kuriarare',
  'Kushina Uzumaki',
  'Kusuma',
  'Kusuna',
  'Kusune',
  'Kusushi',
  'Kyodaigumo',
  'Kyohô Fuefuki',
  'Kyôya',
  'Kyûroku Wagarashi',
  'Kyûsuke',
  'Kô (Anbu)',
  'Kô Hyûga',
  'Kôji',
  'Kôji (Suna)',
  'Kômei',
  'Kôsuke',
  'Kôsuke (Scientifique)',
  'Kôta',
  'Kôtarô Fûma',
  'Kôza Kubisaki',
  'Kû',
  'Lando',
  'Leh',
  'Lemon Yoimura',
  'Liste des Moines Ninjas',
  'Liste des Personnages de Kumo',
  'Liste des Personnages de Suna',
  'Log',
  'Léo',
  'Lézard Messager',
  'Mabui',
  'Madame Shijimi',
  'Madara Uchiwa',
  'Maen Nara',
  'Magire',
  'Magire Kakuremino',
  'Mahiru',
  'Mai Kagetsu',
  'Makaro Akimichi',
  'Maki',
  'Makinami Senka',
  'Makino',
  'Malice',
  'Mamushi',
  'Manabu Akado',
  'Manari',
  'Manda',
  'Manda II',
  'Mangetsu Hôzuki',
  'Margo',
  'Mari',
  'Maroï',
  'Maruten Akimichi',
  'Masako',
  'Mashô',
  'Matatabi',
  'Matsu',
  'Matsuba',
  'Matsuri',
  'Matsuri (Konoha)',
  'Mawashi Dokuraku',
  'Mebuki Haruno',
  'Meizu',
  'Membre inconnu du clan Hyûga',
  'Menma',
  'Menma Namikaze',
  'Menma Uzumaki',
  'Menô',
  'Menô (dragon)',
  'Metal Lee',
  'Metoro Konjiki',
  'Mezu',
  'Meï Terumî',
  'Mia',
  'Michiru Tsuki',
  'Michizô Manaka',
  'Midare',
  'Midori',
  'Mifune',
  'Migaki',
  'Miina',
  'Mikazuki',
  'Mikoshi',
  'Mikoto Uchiwa',
  'Mille Pattes Géant',
  'Minato Namikaze',
  'Ministre Corrompu du Daimyô du Thé',
  'Minoji',
  'Mirai Sarutobi',
  'Miroku',
  'Miru',
  'Misumi Tsurugi',
  'Misuno',
  'Mitate',
  'Mito Uzumaki',
  'Mitoku',
  'Mitsuki',
  'Mizore Fuyukuma',
  'Mizuki',
  'Mizunoe',
  'Mizura',
  'Mo',
  'Moegi Kazamatsuri',
  'Mogusa',
  'Momiji',
  'Momiji (Tanzaku)',
  'Momo',
  'Momoshiki Ôtsutsuki',
  'Mondai',
  'Monga',
  'Monju',
  'Monzaemon Chikamatsu',
  'Motoï',
  'Mozuku',
  'Mubi',
  'Mugino',
  'Mui',
  'Mujô',
  'Mukade',
  'Mukade (film)',
  'Mukai Kohinata',
  'Muku',
  'Murakumo Kurama',
  'Murasame',
  'Musaï',
  'Muta Aburame',
  'Muyami',
  'Mère d\'Ino',
  'Mère de Chôji',
  'Mère de Haku',
  'Mère de Hinata et Hanabi',
  'Mère de Karin',
  'Mère de Sasori',
  'Mère de Yûkimaru',
  'Mécha-Naruto',
  'Môryô',
  'Mû',
  'Nadare Rôga',
  'Nae',
  'Nagare',
  'Nagato',
  'Naho',
  'Naka Uchiwa',
  'Namida Suzumeno',
  'Nan',
  'Nanafushi',
  'Nanara',
  'Nangô',
  'Naori Uchiwa',
  'Naruto Uzumaki',
  'Natori',
  'Natsu',
  'Natsu Hyûga',
  'Natsuhi',
  'Nauma',
  'Nawaki',
  'Neji Hyûga',
  'Nejiri',
  'Nekobaa',
  'Nekomata',
  'Nemui',
  'Nerugui',
  'Nezumi Kaitô',
  'Ni',
  'Ningame',
  'Ningendô (personnage)',
  'Nishi',
  'Nobori',
  'Nonota',
  'Nonô Yakushi',
  'Nowaki',
  'Nue',
  'Nurari',
  'Obito Uchiwa',
  'Oboro',
  'Oiseau Ahô',
  'Oiseau Géant au Bec Perforant',
  'Oiseau Ninja Géant',
  'Okami',
  'Okisuke',
  'Oko',
  'Okyô',
  'Ombre Noire',
  'Omoï',
  'Onbu',
  'Orochimaru',
  'Orphelins d\'Ame',
  'Osoï',
  'Otoha',
  'Otokaze',
  'Oyone',
  'Pakkun',
  'Pakura',
  'Palourde Géante',
  'Partenaire de Kakuzu',
  'Patriarche du Clan Ôtsutsuki',
  'Ponta',
  'Potcha',
  'Premier Chikushôdô (personnage)',
  'Premier Hoshikage',
  'Premier Ministre',
  'Père d\'Akane',
  'Père de Haku',
  'Père de Sasori',
  'Père de Yûsuke',
  'Rai Uchiwa',
  'Raidô Namiashi',
  'Raijin',
  'Ran',
  'Ran (kunoichi)',
  'Ranka',
  'Ranke',
  'Ranmaru',
  'Rasa',
  'Rashii',
  'Raïga Kurosuki',
  'Reibi',
  'Reine des Abeilles',
  'Reishi Kodon',
  'Reki',
  'Renga',
  'Renga Kokubô',
  'Reto',
  'Riichi',
  'Riichi (ninja)',
  'Rikumaru',
  'Rin Nohara',
  'Rinji',
  'Rock Lee',
  'Roi Conque',
  'Roi des Enfers',
  'Rokkaku Ryûdôin',
  'Rokusuke',
  'Ruiga',
  'Ruka',
  'Ryôgi',
  'Ryôkan',
  'Ryûgan',
  'Ryûki',
  'Ryûsa',
  'Ryûsui',
  'Ryûzetsu',
  'Rô',
  'Rôen',
  'Rôshi',
  'Sabiru',
  'Sabu',
  'Sadaï',
  'Sagan',
  'Sagi',
  'Sagiri',
  'Saiken',
  'Saisu Kamano',
  'Sajin',
  'Sajô',
  'Sakon et Ukon',
  'Sakumo Hatake',
  'Sakura Haruno',
  'Sakuya',
  'Samidare Amaashi',
  'Samo',
  'Samui',
  'San',
  'Sana',
  'Sandayû Asama',
  'Sangorô',
  'Sanshô',
  'Santa Yamanaka',
  'Sarada Uchiwa',
  'Saraï',
  'Sari',
  'Sasame',
  'Sasori',
  'Sasuke Sarutobi',
  'Sasuke Uchiwa',
  'Satetsu',
  'Satori',
  'Saya',
  'Sazanami',
  'Sazanami Senka',
  'Saï',
  'Saô',
  'Sculpteur sur Pierre',
  'Seimei',
  'Seito',
  'Sekiei',
  'Sekiei (spectateur)',
  'Sekka',
  'Sekki',
  'Sen',
  'Senji',
  'Sensei de Kabuto',
  'Senta',
  'Sentoki',
  'Serpent Blanc Ermite',
  'Setsuna',
  'Setsuna Uchiwa',
  'Shabadaba',
  'Shamon',
  'Shiba',
  'Shiba (Kusa)',
  'Shibi Aburame',
  'Shibire',
  'Shibito Azuma',
  'Shibuki',
  'Shigure',
  'Shiho',
  'Shiin',
  'Shikadai Nara',
  'Shikaku Nara',
  'Shikamaru Nara',
  'Shikazo',
  'Shikuro Aburame',
  'Shima',
  'Shimeji',
  'Shimon Hijiri',
  'Shin',
  'Shin Uchiwa',
  'Shin\'emon',
  'Shinayakana',
  'Shinigami',
  'Shinki',
  'Shinko Inari',
  'Shinku Yûhi',
  'Shinnô',
  'Shino Aburame',
  'Shinobu Mibu',
  'Shinta',
  'Shion',
  'Shiore',
  'Shira',
  'Shiranami',
  'Shiro',
  'Shiromari',
  'Shiseru',
  'Shishio',
  'Shisui Uchiwa',
  'Shisô',
  'Shitô Akimichi',
  'Shizuka',
  'Shizuku',
  'Shizuma Hoshigaki',
  'Shizune',
  'Shojoji',
  'Shukaku',
  'Shun',
  'Shura',
  'Shuradô (personnage)',
  'Shôseki',
  'Shû',
  'Shû (seigneur)',
  'Son Gokû',
  'Sora',
  'Sora (orpheline)',
  'Statue du Grand Démon Hérésiarque',
  'Suguro',
  'Suien',
  'Suigetsu Hôzuki',
  'Suika',
  'Suika Kannonji',
  'Suiko',
  'Suiren',
  'Suiren (Kiri)',
  'Sukeza',
  'Sukima',
  'Sukui',
  'Sukune',
  'Sumaru',
  'Sumashi',
  'Sumire (citoyenne)',
  'Sumire Kakei',
  'Suname',
  'Susuki',
  'Susuki (Pays des Démons)',
  'Suzaku Nara',
  'Suzume',
  'Suzumebachi',
  'Sâra',
  'Sêramu',
  'Sôma',
  'Sôsetsu Kazahana',
  'Sôta',
  'Sôzu',
  'Tadaichi',
  'Taiko Uchiwa',
  'Taiseki',
  'Taji',
  'Tajiki',
  'Tajima Uchiwa',
  'Takajô Torikai',
  'Takamaru',
  'Takanami Senka',
  'Takemaru',
  'Taku',
  'Tamaki',
  'Tango',
  'Tanishi',
  'Tanuki Shigaraki',
  'Tanzô',
  'Taruho',
  'Tarui',
  'Tatewaki',
  'Tatsuji',
  'Tatsuma Aburame',
  'Tatsumi',
  'Tayori Kuroyagi',
  'Tayuya',
  'Tazuna',
  'Teguse',
  'Tekka Uchiwa',
  'Tekuno Kanden',
  'Temari',
  'Temui',
  'Temujin',
  'Tenga',
  'Tenji',
  'Tenma Izumo',
  'Tenma Kodon',
  'Tenten',
  'Tentô Madoka',
  'Tenzen',
  'Tera',
  'Terai',
  'Terubô',
  'Tessen Togeito',
  'Tetsu',
  'Teuchi',
  'Teyaki Uchiwa',
  'Tezuna',
  'Tobi',
  'Tobi (Zetsu)',
  'Tobimaru',
  'Tobio',
  'Tobirama Senju',
  'Todoroki',
  'Tofu',
  'Tokara',
  'Tokara Aburame',
  'Toki',
  'Toki (Shinobazu)',
  'Tokiwa',
  'Tokuma Hyûga',
  'Tomari',
  'Tomaru',
  'Tomaru Minakura',
  'Tonbee',
  'Tonbo Tobitake',
  'Toneri Ôtsutsuki',
  'Tonton',
  'Tora',
  'Tora (Anbu)',
  'Torifu Akimichi',
  'Toroï',
  'Toroï (Genin)',
  'Tortue-Lion',
  'Torune Aburame',
  'Toutou',
  'Towa',
  'Toyosa',
  'Trois Frères Haimaru',
  'Trois Serpents Géants',
  'Troisième Hoshikage',
  'Troisième Kazekage',
  'Troisième Mizukage',
  'Tsubaki (anime)',
  'Tsubaki (parent)',
  'Tsubaki Kurogane',
  'Tsubusa',
  'Tsuchino',
  'Tsuchinoe',
  'Tsuchinoto',
  'Tsukiko Kagetsu',
  'Tsukino',
  'Tsukiyo',
  'Tsukune',
  'Tsume Inuzuka',
  'Tsunade',
  'Tsunami',
  'Tsuru Itoi',
  'Tsurugi',
  'Tsurushi Hachiya',
  'Tsuzumi',
  'Tsuzumi Sarugaku',
  'Tôbei Kagetsu',
  'Tôfu',
  'Tôka Senju',
  'Tôu',
  'Ubau',
  'Udon Ise',
  'Ugatsu',
  'Ugaï',
  'Umibôzu',
  'Unagi',
  'Unkai Kurama',
  'Unmo Samidare',
  'Urakaku',
  'Urashiki Ôtsutsuki',
  'Uroko Kurama',
  'Uruchi Uchiwa',
  'Urushi',
  'Urushi (invocation)',
  'Ushi',
  'Utakata',
  'Utilisateurs du Bakuton',
  'Utilisateurs du Fûton',
  'Utilisateurs du Raiton',
  'Utilisateurs du Suiton',
  'Uô',
  'Vent Furieux',
  'Victor',
  'Waraji',
  'Wasabi Izuno',
  'Watase',
  'Ya',
  'Yagura (anime)',
  'Yagura Karatachi',
  'Yahiko',
  'Yajirobee',
  'Yakku',
  'Yakumi Uchiwa',
  'Yakumo Kurama',
  'Yamame',
  'Yamaoka',
  'Yamato',
  'Yaoki',
  'Yashamaru',
  'Yashiro Uchiwa',
  'Yatogo Ryûgen',
  'Yodo',
  'Yokaze',
  'Yokozuna',
  'Yome',
  'Yomi',
  'Yomito Hirasaka',
  'Yone',
  'Yoroï Akadô',
  'Yoruga',
  'Yoshino Nara',
  'Yoshiteru',
  'Yota',
  'Yotaka',
  'Yubina',
  'Yugito Nii',
  'Yui',
  'Yuina Itomaki',
  'Yukata',
  'Yukimi',
  'Yurika',
  'Yurinojô',
  'Yurito',
  'Yurui',
  'Yôji Aburame',
  'Yôrô',
  'Yûdachi',
  'Yûga',
  'Yûgao Uzuki',
  'Yûki Minazuki',
  'Yûkimaru',
  'Yûra',
  'Yûsuke',
  'Zabuza Momochi',
  'Zaji',
  'Zaku Abumi',
  'Zangei',
  'Zenza',
  'Zetsu',
  'Zetsu Blanc',
  'Zetsu Noir',
  'Zô',
  'Zôri',
  'Zôsui',
  'Ôkei',
  'Ômitsu',
  'Ônoki',
  'Ôtora',
  'Ôwashi',
  'Ûhei',
  'Ame',
  'Getsu',
  'Grotte Ryûchi',
  'Hoshi',
  'Hôzukijô',
  'Ishi',
  'Iwa',
  'Jômae',
  'Kagerô (village)',
  'Katabami Kinzan',
  'Kiri',
  'Konoha',
  'Kumo',
  'Kusa',
  'Nadeshiko',
  'Oto',
  'Paradis',
  'Port de Degarashi',
  'Quartiers de Tanzaku',
  'Shimo',
  'Shukuba',
  'Sora-ku',
  'Suna',
  'Taki',
  'Takumi',
  'Tani',
  'Tsuki',
  'Uzushio',
  'Village de Daidai',
  'Village de Hachô',
  'Village de la Céramique',
  'Village de la forêt du Genjutsu',
  'Village de Motoyoshi',
  'Village de Rôkoku',
  'Village de Tonika',
  'Village des Arbres Morts',
  'Village des Bambous',
  'Village Tsuchigumo',
  'Yu',
  'Yuki',
  'Yume',
  'Clan Aburame',
  'Clan Akimichi',
  'Clan Chinoike',
  'Clan de Jûgo',
  'Clan de Yota',
  'Clan du Kazekage',
  'Clan Fûma',
  'Clan Fûma (Pays du Son)',
  'Clan Hagoromo',
  'Clan Hatake',
  'Clan Hoshigaki',
  'Clan Hyûga',
  'Clan Hôzuki',
  'Clan Iburi',
  'Clan Inuzuka',
  'Clan Kaguya',
  'Clan Kamizuru',
  'Clan Kedôin',
  'Clan Kodon',
  'Clan Kohaku',
  'Clan Kumanoi',
  'Clan Kurama',
  'Clan Lee',
  'Clan Nara',
  'Clan Onikuma',
  'Clan Rinha',
  'Clan Sarutobi',
  'Clan Sendô',
  'Clan Senju',
  'Clan Shiin',
  'Clan Shimura',
  'Clan Shirogane',
  'Clan Tsuchigumo',
  'Clan Uchiwa',
  'Clan Uzumaki',
  'Clan Yamanaka',
  'Clan Yotsuki',
  'Clan Yuki',
  'Clan Ôtsutsuki',
  'Famille Kagetsu',
  'Famille Karatachi',
  'Famille Wagarashi',
  'Famille Wasabi',
];
