List<String> desole = [
  'J\'ai préféré partir et m\'isoler',
  'Maman, comment te dire, j\'suis désolé',
  'La conseillère m\'a clairement négligé',
  'Et moi comme un teu-bé j\'ai dit O.K',
  'Et tous les jours je pense à arrêter',
  'Les gens veulent faire de moi une entité',
  'J\'vais tout plaquer',
  'Je ne suis qu\'un homme, j\'vais finir par clamser',
  'Et j\'ai dû côtoyer l\'pavé',
  'Pas à pas, j\'me dis c\'est pas vrai',
  'Papa, Maman, les gars, désolé',
  'J\'ressens comme une envie d\'m\'isoler',
  'Et j\'ai dû côtoyer l\'pavé',
  'Pas à pas, j\'me dis c\'est pas vrai',
  'Papa, Maman, les gars, désolé',
  'J\'ressens comme une envie d\'m\'isoler',
  'Moi aussi, les frères, j\'vais m\'barrer',
  'Rejoindre tous les miens, les dingaris',
  'Paris c\'est Alcatraz',
  'Marre des amendes et d\'tous ces tas d\'paperasse',
  'Leur cœur est noir et fin comme un Sénégalais',
  'À les entendre, on croirait que saigner il fallait',
  'Moi j\'veux ma femme, mon Dîn, mes gosses',
  'Pour ça, crois-moi, j\'emploierai bien toutes mes forces',
  'Et j\'ai dû côtoyer l\'pavé',
  'Pas à pas, j\'me dis c\'est pas vrai',
  'Papa, Maman, les gars, désolé',
  'J\'ressens comme une envie d\'m\'isoler',
  'Et j\'ai dû côtoyer l\'pavé',
  'Pas à pas, j\'me dis c\'est pas vrai',
  'Papa, Maman, les gars, désolé',
  'J\'ressens comme une envie d\'m\'isoler',
  'Pardonne-moi, grand mère, s\'il-te-plaît',
  'J\'serais revenu t\'voir si j\'avais plus de blé',
  'Mais t\'sais ici non plus c\'est pas facile',
  'En France, la hass nous met des baffes aussi',
  'Désolé aux profs de maths, d\'anglais et d\'français',
  'Vous inquiétez pas, mon père m\'a bien défoncé',
  'Désolé monsieur l\'banquier',
  'Mais si j\'m\'arrache, vous allez pas m\'manquer',
  'Et j\'ai dû côtoyer l\'pavé',
  'Pas à pas, j\'me dis c\'est pas vrai',
  'Papa, Maman, les gars, désolé',
  'J\'ressens comme une envie d\'m\'isoler',
  'Et j\'ai dû côtoyer l\'pavé',
  'Pas à pas, j\'me dis c\'est pas vrai',
  'Papa, Maman, les gars, désolé',
  'J\'ressens comme une envie d\'m\'isoler',
  'Maman, Papa, j\'vous dis "on diarama"',
  'Je sais qu\'dans votre tête vous êtes déjà là-bas',
  'J\'ai beau dire que j\'l\'ai mais j\'ai pas la foi',
  'J\'ai fait l\'con, j\'ai commencé par la fin',
  'J\'aurais pas dû m\'lancer dans la musique étant petit',
  'J\'aurais dû t\'écouter, Papa, étant petit',
  'J\'me sens coupable',
  'Quand j\'vois ce que vous a fait c\'pays d\'kouffar',
  'Et j\'ai dû côtoyer l\'pavé',
  'Pas à pas, j\'me dis c\'est pas vrai',
  'Papa, Maman, les gars, désolé',
  'J\'ressens comme une envie d\'m\'isoler',
  'Et j\'ai dû côtoyer l\'pavé',
  'Pas à pas, j\'me dis c\'est pas vrai',
  'Papa, Maman, les gars, désolé',
  'J\'ressens comme une envie d\'m\'isoler',
  'J\'ai préféré partir et m\'isoler',
  'Maman, comment te dire, j\'suis désolé',
  'La conseillère m\'a clairement négligé',
  'Et moi comme un teu-bé j\'ai dit O.K'
];

List<String> direction = [
  'On prétend pas être des modèles pour les gosses',
  'Ni pour personne d\'autre',
  'On tient juste à dire que... le pont qui mène au succès',
  'Est un pont fragile',
  'J\'ai demandé pardon sans qu\'on puisse me l\'accorder',
  'J\'ai demandé ma route sans qu\'on puisse me l\'indiquer',
  'J\'ai troqué mes études contre un disque de platine',
  'Tout en sachant qu\'tôt ou tard ton public te piétines',
  'J\'ai vu les choses en grand, j\'ai du cran, j\'ai du talent',
  'Je reste sur mes gardes, je n\'suis qu\'un homme',
  'Ça capture mon image dans des 7D Canon',
  'Tout ça j\'le fais pour moi, ceux qui doutent et la daronne',
  'J\'ai pété les plombs! (J\'ai pété les plombs)',
  'J\'ai quitté l\'école! (J\'ai quitté l\'école)',
  'Si seulement tu savais (Si seulement tu savais)',
  'Tout le mal que je garde (Tout le mal que je garde)',
  'C\'est ma direction!',
  'J\'ai pété les plombs, sans abandonner ni baisser les bras',
  'Plus d\'nouvelles, batterie faible, malédiction',
  'Dorénavant, je vais de l\'avant, c\'est ma direction',
  'Ma direction',
  'J\'ai fui les sonneries, les bruits d\'chaises',
  'Moi j\'cherchais d\'autre style (yeah) de richesses',
  'Du journal d\'Anne Frank à c\'lui d\'Bridget (Bridget)',
  'J\'ai jamais kiffé lire depuis qu\'jai 12 piges',
  'Malgré les ratures j\'gratte le papier',
  'C\'est ma direction, j\'me suis pas éparpillé',
  'Plaqué plus d\'une fois, dos au re-mu',
  'Trop fier pour demander d\'l\'aide au RMI',
  'Les srabs en guise de mif\', l\'estrade en guise de but',
  'Freiné par les fils de (chut)',
  'J\'me souviens qu\'à la base on voulait même pas toucher d\'blé',
  'Ça rappait sale quand on s\'entassait tous chez l\'Blanc (yeah)',
  'Tu connais BatiPro, Crit, Selpro',
  'J\'écrivais dans l\'trom avant d\'aller m\'casser l\'dos (yeah)',
  'Aujourd\'hui tout ça n\'aurais pas d\'sens',
  'Sans tous ces sacrifices, sans toute cette patience',
  'C\'est ma direction',
  'J\'ai pété les plombs, sans abandonner ni baisser les bras',
  'Plus d\'nouvelles, batterie faible, malédiction',
  'Dorénavant je vais de l\'avant c\'est ma direction',
  'Ma direction',
  'J\'me remémore les clashs, les concours de rap, la hess',
  'Dans la rue ça rap en masse ça zappe même d\'aller nehess',
  'Pour un 16 mes gars t\'agressent seul le kickage nous apaise',
  'Nos voix, nos mains s\'élèvent quand les flics salent nous rabaissent',
  'Le rêve est à nos pieds donc on dort tête bêche',
  'On baigne dans les richesses mais nos lèvres restent sèches',
  'J\'veux vivre de ma passion car tous mes taffs me déplaisent',
  'On cherchait qu\'la reconnaissance on voulait pas parler d\'espèces',
  'Maintenant on fout dehors la hess même si nos passés l\'heberge',
  'Ca veut acheter des caisses, attaquer l\'marché des States',
  'Si on a autant ramé, c\'est pour être stock à l\'arrivée',
  'Pour bien steaker les stre-mon qui voulaient nous faire chavirer',
  'Mais ça taf, j\'ai quitté pour mieux déplacer des montagnes',
  'Résultat, ma foi baisse, mes fautes sont indénombrables',
  'Cherche pas trop la lumière, le soleil brûle ta peau',
  'Oui le succès te fume, à peine tu l\'crapotes',
  'C\'est ma direction!',
  'J\'ai pété les plombs sans abandonner ni baisser les bras',
  'Plus d\'nouvelles, batterie faible, malédiction',
  'Dorénavant je vais de l\'avant c\'est ma direction',
  'Ma direction',
  'Fuck le taff... un bac pro ça paye pas',
  'Avec les srabs, pour le rap bah on veille tard',
  'Malgrè les découverts, les sales patrons',
  'J\'ai tout plaqué à la conquête des salles, partons',
  'Un projet suicidaire, ça passe ou on s\'casse',
  'Et tu nous suis si t\'aimes (akhi)',
  'Déterminés, on part au front sans armure',
  'Et les plus terre-à-terre disent qu\'on foncent dans un mur (Aah!)',
  'Les darons savent pas c\'que j\'fais, ils disent que j\'dors',
  'Ils pensent que leur fiston ne vit que dehors',
  'Sans savoir qu\'ce p\'tit con prépare des disques d\'or',
  'Et qu\'tout ceux qui le négligent bah on plus que tort',
  'J\'sais où j\'vais, sans savoir si j\'s\'rais le bienvenu',
  'J\'suis pas invité et j\'suis accompagné d\'OVNIs',
  'J\'me dirige vers la gloire et les blèmes-pro',
  'La musique est une femme à problèmes mais putain j\'l\'aime trop',
  'C\'est ma direction',
  'J\'ai pété les plombs, sans abandonner ni baisser les bras',
  'Plus d\'nouvelles, batterie faible, malédiction',
  'Dorénavant, je vais de l\'avant c\'est ma direction',
  'Ma direction',
  'T\'es foutu si tu échoues, dans ta situation',
  'Foutu si tu échoues, dans ta situation',
];

List<String> wbn = [
  'Le soir s’approche ça se tape des barres',
  'Ça fume des sbars comme si c’était légal',
  'Les gars veulent serrer des meufs, les meufs serrer des gars',
  'Et ça toute la night',
  'Les soirées de samedi soir',
  'Quelquefois ça me déçoit',
  'Pour quelques billets de cent',
  'Ça part en giclée de sang',
  'Hey Ho',
  'Hey Ho',
  'Hey Ho',
  'Hey Ho',
  'Au parking de la boite, toutes sortes de plaques',
  '9.1 9.2 9.3 9.4',
  'Tout Bériz est à-l, Kofton sous Hasch',
  'Sauvageons sous flash, et au platine ya HCue',
  "Hey mais y'a même les gens du 7.7",
  'Wati bronx wesh Hamed quand tu veux on remet ça',
  'Des go se tapent, un tissage vole',
  'Pendant que mon gars Jeryzoos se met bien sous alcool',
  'Moi je danse le Mia dès que ca sonne un peu funky',
  'Si elle me demande si j’ai le mi-per je lui réponds cash fuck you',
  'Et c’est souvent sur un bête de son',
  'Que souvent dans la te-boi y a une grosse flaque de sang',
  'J’ai vu une tate-pa partir au ralenti',
  'Ça s’insulte ça se bouscule ça zappe la galanterie',
  "Et mon gars sûr s'en tape lui est dans ses bails",
  'Attends , non je crois que Dry est die',
  'Moi j’ai un bête de style que des balles me filent',
  'Téma la bête de file où les boules défilent',
  'Ici les samedis soirs se jouent à face ou pile',
  'Embrouilles histoires si t’as pas trop de sex appeal',
  "Putain je suis khabat, j'sais plus où j'me trouve",
  'C’est la loge, les chiottes, la cour ou la douche ?',
  "Des cheveux longs des cheveux courts, j’l'accoste ou je cours",
  'Elle est grosse ! Oh my god, pas moyen de lui faire la cour',
  'Le soir s’approche ça se tape des barres',
  'Ça fume des sbars comme si c’était légal',
  'Les gars veulent serrer des meufs, les meufs serrer des gars',
  'Et ça toute la night',
  'Les soirées de samedi soir',
  'Quelquefois ça me déçoit',
  'Pour quelques billets de cent',
  'Ça part en giclée de sang',
  'Souvent les samedi soir c’est coup de tête et gauche',
  "Que ce soit le tieks ou la tec' c'est lass'dégue, c'est moche",
  "Tous ces gars prennent de l'âge mais restent des mioches",
  'Putain, tu vois pourquoi je préfère le cinoche',
  'Souvent les samedi soir c’est coup de tête et gauche',
  "Que ce soit le tieks ou la tec' c'est lass'dégue, c'est moche",
  "Tous ces gars prennent de l'âge mais restent des mioches",
  'Putain, tu vois pourquoi je préfère le cinoche',
  "Hello sista, je t'demande pas ton numéro",
  "On t’a déjà dit que t'étais une beauté numérique",
  "Tu comprends le lingala ? M'boté ma chérie",
  'Je fais du real hip hop comme les mecs en Amérique',
  "Je suis dans la boite, j'aperçois mon gars Wisla",
  'Casquette Wati-B veste moncler putain ça se pé-sa',
  "Il y a Yaya du Havre à coté y'a mon gars Lefa",
  "Et on se rend compte qu'on est super loin du Jannah",
  'Un petit pas de breakdance, je bouscule une top modèle',
  'Je me dis c’est dead elle ressemble a mon ex Anna',
  'Et oui je suis faible, et je suis qu’un homme',
  'Qui boit des litres, pour noyer sa haine',
  'Le soir s’approche ca se tape des barres',
  'Ça fume des sbars comme si c’était légal',
  'Les gars veulent serrer des meufs, les meufs serrer des gars',
  'Et ça toute la night',
  'Les soirées de samedi soir',
  'Quelquefois ça me déçoit',
  'Pour quelques billets de cent',
  'Ça part en giclée de sang',
  'Ça fait les 100 pas, tous à la recherche de créatures',
  'En solo ou pas, belles ou pas, guette les filatures',
  'Au début, ça trinque, ça sert et ça frappe des mains',
  'Sous rapta bien vi-ser ça frappe des poings',
  '- Wesh, D.R., mon gars sur, bien ou quoi poto, tranquille',
  '- Bien ou bien',
  '- Si-si, lourd la soirée, hein',
  '- Ah, franchement lourd, lourd',
  'Hé gros, mais putain, mais ça danse sec là-bas la gros',
  "-  Ah j'avoue, wesh Glee lui, mon frère",
  'T’arrives sur la piste genre moonwalk',
  'Mais wesh il est pas un peu trop lé-mou ton haut ?',
  "Y'en qui goutent aux go, y'en a qui goutent aux coups",
  'Putain je sens que ça va partir en soirée coup de teau-cou',
  'Le soir s’approche ca se tape des barres',
  'Ça fume des sbars comme si c’était légal',
  'Les gars veulent serrer des meufs, les meufs serrer des gars',
  'Et ça toute la night',
  'Les soirées de samedi soir',
  'Quelquefois ça me déçoit',
  'Pour quelques billets de cent',
  'Ça part en giclée de sang',
  "Merci, j'me sens invincible",
  "Merci, j'me sens invincible"
];

List<String> balader = [
  'On veut plus taffer pour un homme ni toujours jouer les ien-ch',
  "Non, il y a plus d'illicite, je pense qu'on a retenu la leçon",
  'Nouveaux textes, donc nouvelle casquette imbibée de sueur',
  'Musique à fond Boulevard Haussman ça bombarde à Rue de la Paix',
  "On est plus malsains, t'as l'seum, tu vis mal ça",
  '"Break ya neck", au lieu de mal parler sur nous',
  "Tu-tu te demandes, si c'est Black M ou Black Shady qui parle (Hu)",
  "Si on fait le cristal, c'est cool pour la baraque il faut des sous",
  "(Moi j'vais m'sé-po) Hmmm Gims on s'capte",
  "Ensuite, on m'a chuchoté que je pouvais devenir numéro uno",
  "J'aime pas trop le caviar, laissez-moi mon assiette de pennes",
  'Nous sommes des bolides, vous êtes des luges',
  "Tu n'es que mon tit-pe, je suis comme ton père",
  "100% gros yeux, 75, ça vient pas d'Harlem",
  "Sur l'instrumentale je m'balade avec trop de swag",
  "P'tit bout de me-eus, toujours dans la che-po",
  'Vous êtes les sinistrés qui se réfugient',
  'Au début, je faisais du son pour épater les collégiennes',
  "Dans la ville des jolies bolides dominent sans faire d'action",
  "(Moi j'vais m'sé-po) L'insomniaque on s'capte",
  "Sachez que les amis de mes amis, t'inquiète j'les rince",
  "C'est le titi parisien, t'a reconnu l'accent",
  "J'suis faya, je déboule avec l'équipe et le poto Zied",
  "J'suis bouillant, y a de la f-meu et du de-mon vers la Fayette",
  'Ensuite, je le faisais pour épater les lycéennes',
  "(Moi j'vais m'sé-po) T'inquiète Black M on s'capte",
  "J'vais me balader dans les rues de Paname en Cayenne",
  "Y en a même qui disait qu'on s'pourrait faire des une-deux",
  "Donc j'vais me balader, aller me balader (yeah)",
  "À part ça, nous on t'mets ien-b",
  "Nous la flamble, la mala, va leur dire qu'on vit ap' sans",
  "J'vais me balader aux Champs Elysées",
  "(Moi j'vais m'sé-po) JR on s'capte",
  "Fini l'époque où ça marchait sans liquide dans l'errance akhi",
  'On fait sortir le gent-ar des poches mêmes aux plus grosses pinces donc',
  "(Moi j'vais m'sé-po) Petrodollars on s'capte",
  "(Moi j'vais m'sé-po) Wesh les mecs on s'capte",
  "J'ai dit, je vais me balader aux Champs Elysées",
  "Tout d'abord, 1 pour les nôtres, je fuck tous les autres, je bosse tous les jours",
  'Attend y a, Chico, les Maréga rue des Coquillères',
  "(Moi j'vais m'sé-po) Maska on s'capte",
  "Imbécile, j'dirais même que t'es con",
  "Je suis sous hach, j'kick sale, dis-le t'as pas le choix",
  'Masta na nga, Masta na nga, Masta',
  "Je suis passé de l'anonymat aux petites soirées mondaines",
  'Me manque pas de respect quand je kick mec',
  "J'vais me balader, aller me balader",
  "2 secondes, vas-y miss s'te plaît, c'est quoi le 06 j’t'appelle",
  "Séné-Sénégal, je veux l'Porsche et les poches pleines",
  'Wati B, nouveaux t-shirts, nouveaux vêt-sur',
  "Je voulais m'balader, m'balader",
  'Nous sommes comparables au déluge',
  'Mon équipe des niggas portent atteinte au corps, donc porte tes couilles',
  "Je veux pas que t'écoutes et que tu portes plainte",
  "À vouloir nous faire des croches-pattes, t'as gâté tes pompes",
  "(Moi j'vais m'sé-po) T'inquiète Barack on s'capte",
  'Balader, aller me balader (yeah)',
  "Moi j'étais l'petit con qu'les keufs aimaient contrôler",
  "Mais celui qui me les cassait, j'étais chaud pour le balafrer",
  "Que des textes insolites, j'suis solide, je suis plus le même",
  "Parce que c'est fini, on se massacre plus mince !",
  "Nous c'est du solide, vous c'est du lèg'",
  "Roule un spliff, si y a les keufs, on mets la poudre d'escampette",
  'On m\'disait "Joue pas trop avec la ue-r ou elle va te mettre une che-gau"',
  'Sortez nous le tapis rouge, on ira se prosterner dessus ouais',
  'Je veux me balader sur les Champs sans flics aux pattes',
  'Masta, Masta, Masta na nga',
  'Change rien, fuck les gadgets électroniques',
  "Moi j'vais m'sé-po dans les coins chics, t'inquiète",
  'Après nous y a plus de groupes, y a que des pom-pom girls',
  'En plus on veut faire des sous, et devenir des princes',
  'Toujours le petit sourire moqueur quand ils me disaient contre le mur',
  'Wesh le boss, double roro sur les Chroniques',
  'Paranoïaque, psychopathe',
  "J'arrive en bolide, impoli, j'attise la haine cousin"
];

List<String> qad = [
  "Qui a dit qu'les blondes étaient toutes des connes",
  'Toutes des connes, tou-tou-toutes des connes ?',
  "Qui t'a dit qu'j'serais clodo si j'quittais l'école",
  "Quittais l'école, qui-qui-quittais l'école ?",
  "C'est l'Wati-B ça sent la diff'",
  "Inconsciemment ça sent le biff'",
  "Tu sens la diff', ça sent le biff'",
  "Mais qui t'a dit qu't'étais d'la mif ?",
  "Qui c'est qui veut du Real Hip Hop, ça vient d'Paname",
  "Jetez moi des groupies comme Zahia, ça vient d'Paname",
  "Excuse, je n'voulais pas dire ça, ça vient d'Paname",
  "Demande à Black M, everybody let's go, come on, say :",
  'Naa, Na na na na, Na na na na',
  'Na na na, na na na',
  'Na na na naaaa...',
  'Okay Okay Okay Okay',
  "Hello Wendy, quoi d'neuf depuis Wati Bon Son ?",
  'Toujours devant ton PC ou devant ton écran Thomson ?',
  'Wesh boy tu veux du flow ? Demande aux bonnes personnes',
  "Donne pas tes fesses, ou tu vas t'faire dom'-so",
  '"T\'inquiète Gims, y\'en a aucun qui t\'baise"',
  "J'm'inquiète ap', j'ressens aucun suspens",
  "Y'a des scores lourds, guette comme j'suis vif",
  "J'l'ai déjà dit, moi je smash ou je switch",
  "Hé les mômes, il faut y aller mollo, c'monde",
  "Te met des baffes avec le bras d'Mauresmo",
  "Paris la nuit, trop d'têtes se droguent",
  "Que ce soit le tieks ou la tec' c'est 'lasse-dégue, c'est mort",
  "Maitre Gimso, Gringo, j'crois qu'j'ai l'single",
  "J'suis pas Sean Paul ni Kingston j'viens du Congo",
  "Là j'y go, pas l'temps d'papoter d'go",
  "J'suis qu'à 30 pour cent mais y'a pas d'problèmes",
  "C'est l'Wati-B ça sent la diff'",
  "Inconsciemment ça sent le biff'",
  "Tu sens la diff', ça sent le biff'",
  "Mais qui t'a dit qu't'étais d'la mif ?",
  "Qui c'est qui veut du Real Hip Hop, ça vient d'Paname",
  "Jetez moi des groupies comme Zahia, ça vient d'Paname",
  "Excuse, je n'voulais pas dire ça, ça vient d'Paname",
  "Demande à Black M, everybody let's go, come on, say :",
  'Naa, Na na na na, Na na na na',
  'Na na na, na na na',
  'Na na na naaaa...',
  "Quelques Watt sé-po sur le tec', (NAN)",
  "En quête mon flow, ma tech', (Dis wAllah)",
  "Handeck, (NO) Sans déc'",
  "J'ai mon assurance flow la famille t'inquiète",
  "Quelques Watt sé-po sur le tec', (Arrête)",
  "En quête mon flow, ma tech', (Tu Mens)",
  "Handeck, (Eh Ouais) Sans dec'",
  "J'ai mon assurance flow la famille t'inquiète",
  "Qui a dit qu'les blondes étaient toutes des connes",
  'Toutes des connes, tou-tou-toutes des connes ?',
  "Qui t'a dit qu'j'serais clodo si j'quittais l'école",
  "Quittais l'école, qui-qui-quittais l'école ?",
  "Wesh mon suisse, quoi d'neuf depuis l'Wati Bonhomme ?",
  "Rien d'space, ah si, on est sur le podium",
  "Aie c'est du bon job, personne peut l'nier",
  "Grosse casse-déd' à Dawa' tant qu'on y est",
  "Ok, qui t'a dit qu'on était en bout d'course ?",
  "Sûrement des pouf' qui bouffent des bouts d'bourses",
  "Si on cane c'est qu'on s'est dé-suici",
  "Vous n'aimez pas nos sons pourtant vous écoutez celui-ci",
  "Mais qui t'a dit qu'au placard y'avait qu'beurs et blacks ?",
  "Akhi qui t'a dit que les Bakaris sont bons qu'à s'bagarrer ?",
  "Qui t'a dit qu'y a qu'des Portuguais au Rez-de-chaussée ?",
  "Le mec dont tous les gardiens ont peur est Guesh on l'sait",
  "Mais qui t'a dit qu'tous les épiciers font des taros d'bâtard",
  "Qu'les paquets de LU coûtent plus chers que les baraques au Qatar ?",
  "Qui t'a dit que tous les Japonais maîtrisaient les ordi' ?",
  "Qu'tous les Chinois font du kung-fu quel est le con qui l'a sorti ?",
  "Akhi, qui t'a dit de boire leur Alcool",
  "Sous rap dense, t'as traité l'agent de sale conne",
  "Maintenant tout ce que tu vois c'est lavabo, carreaux, barreaux",
  "Qui t'a dit qu'tout ça n'allait pas rendre la mif' et l'daron paro ?",
  "C'est l'Wati-B ça sent la diff'",
  "Inconsciemment ça sent le biff'",
  "Tu sens la diff', ça sent le biff'",
  "Mais qui t'a dit qu't'étais d'la mif ?",
  "Qui c'est qui veut du Real Hip Hop, ça vient d'Paname",
  "Jetez moi des groupies comme Zahia, ça vient d'Paname",
  "Excuse, je n'voulais pas dire ça, ça vient d'Paname",
  "Demande à Black M, everybody let's go, come on, say :",
  'Naa, Na na na na, Na na na na',
  'Na na na, na na na',
  'Na na na naaaa...',
  "Wesh boy quoi d'neuf depuis Wati By Night ?",
  "Fais pas d'gestes brusques, sur ma droite y'a Bajnight",
  "Oui y'a du on-s, y'a des petits tah sa race night",
  "Oui je suis présent et chaud bouillant si mes gars s'fight",
  '(HO) Joue pas piano, (HO) je suis un Diallo',
  '(HO) Comme le dit Allo (HO), cette année est à nous',
  "Wesh qui t'a dit qu'on était rassasiés ?",
  "Demande à R si ça ce n'est que pas sa ra-za ce-ze, (Ouh)",
  "Mais qui t'a dit qu'y en avait des comme Black M ?",
  "Qui est l'rageux qui t'a dit qu'il fallait surtout pas m'backer ?",
  "Qui t'a dit qu'on roulait en gros gamos ?",
  "Ici c'est la hass, qui pilote et si t'es aud-ch vamos ?",
  'C\'est lequel d\'entre eux qui t\'a dit : "Quoi la Sexion',
  'En concert dans l\'tiekson ? Ça hors de question !" ?',
  "Résultat j'suis à-l et j'kicke ça",
  "Mais qui t'a dit de te mettre tout au fond d'cette p'tite salle ? (HO)",
  "Mais qui t'a dit de négliger le Wati-B ?",
  'Triple disques de platine dans ton cavu akhi, breh',
  "Mais qui t'a dit que le Wati B n'allait pas tout niquer",
  'Tout niquer, tou-tou-tout niquer ?',
  'Rambouima yété Diallo alla projet',
  'Ha ha ha',
  "Mais qui t'a dit que Sarkozy était français ?!",
  "Qui t'as dit que les noirs ne savaient pas nager ?!",
  'Hein ?!',
  "Adama, mais qui t'a dit que les guinéens n'étaient pas des vrais Diallo ?!",
  "T'es Bête Ou Quoi ?!",
  "Qui t'a dit qu'on était au cimetière ?! Akhi",
  'Dj Hcue, sisisi',
  "Et qui t'a dit qu'les zaico n'savaient pas se saper ?!",
  'Imbécile, on est là on est là, 75',
  "Et qui t'a dit que les arabes étaient tous des voleurs ?!",
  '"Hé le Rebeu, Ramène la Porsche Carrera enfoiré ramène la"',
  '"Tu devais passer demain, passe hein ?!"',
  "In your motherfuckin' face",
  "Tu m'avais négligé enfoiré ?!",
  'Les Chroniques du 75 Volume 2',
  'Kinshasa, Brazzaville, Mwana mwana mwanananana mayi Soldiers',
  "Qui t'a dit d'redire tout c'qu'on t'a dit",
  "Maintenant retire c'que t'as dit ou c'qu'on t'a fait dire",
  "Qui t'a dit d'redire tout c'qu'on t'a dit",
  "Maintenant retire c'que t'as dit ou c'qu'on t'a fait dire",
  "Qui t'a dit d'redire tout c'qu'on t'a dit",
  "Maintenant retire c'que t'as dit ou c'qu'on t'a fait dire",
];
