List<String> desole = [
  "J'ressens comme une envie d'm'isoler",
  "Paris c'est Alcatraz",
  "Moi j'veux ma femme, mon Dîn, mes gosses",
  "Mais si j'm'arrache, vous allez pas m'manquer",
  "J'ai préféré partir et m'isoler",
  "Pour ça, crois-moi, j'emploierai bien toutes mes forces",
  "Et moi comme un teu-bé j'ai dit O.K",
  'Leur cœur est noir et fin comme un Sénégalais',
  "Désolé monsieur l'banquier",
  'Rejoindre tous les miens, les dingaris',
  "Vous inquiétez pas, mon père m'a bien défoncé",
  "J'aurais pas dû m'lancer dans la musique étant petit",
  "J'aurais dû t'écouter, Papa, étant petit",
  'Papa, Maman, les gars, désolé',
  "J'me sens coupable",
  "Quand j'vois ce que vous a fait c'pays d'kouffar",
  "Je ne suis qu'un homme, j'vais finir par clamser",
  "Marre des amendes et d'tous ces tas d'paperasse",
  "Pas à pas, j'me dis c'est pas vrai",
  'En France, la hass nous met des baffes aussi',
  "Désolé aux profs de maths, d'anglais et d'français",
  "J'ai beau dire que j'l'ai mais j'ai pas la foi",
  "La conseillère m'a clairement négligé",
  "J'serais revenu t'voir si j'avais plus de blé",
  "Mais t'sais ici non plus c'est pas facile",
  "J'ai fait l'con, j'ai commencé par la fin",
  "J'vais tout plaquer",
  'Et tous les jours je pense à arrêter',
  'Les gens veulent faire de moi une entité',
  "Maman, comment te dire, j'suis désolé",
  "Moi aussi, les frères, j'vais m'barrer",
  "Pardonne-moi, grand mère, s'il-te-plaît",
  "Je sais qu'dans votre tête vous êtes déjà là-bas",
  "Et j'ai dû côtoyer l'pavé",
  'À les entendre, on croirait que saigner il fallait',
  'Maman, Papa, j\'vous dis "on diarama"'
];

List<String> direction = [
  "Les srabs en guise de mif', l'estrade en guise de but",
  'On baigne dans les richesses mais nos lèvres restent sèches',
  "Aujourd'hui tout ça n'aurais pas d'sens",
  "J'veux vivre de ma passion car tous mes taffs me déplaisent",
  "Un projet suicidaire, ça passe ou on s'casse",
  'Freiné par les fils de (chut)',
  "J'ai demandé ma route sans qu'on puisse me l'indiquer",
  "Tout en sachant qu'tôt ou tard ton public te piétines",
  "J'ai pété les plombs sans abandonner ni baisser les bras",
  'Foutu si tu échoues, dans ta situation',
  "J'ai vu les choses en grand, j'ai du cran, j'ai du talent",
  "Du journal d'Anne Frank à c'lui d'Bridget (Bridget)",
  "La musique est une femme à problèmes mais putain j'l'aime trop",
  "Dorénavant, je vais de l'avant, c'est ma direction",
  "J'me souviens qu'à la base on voulait même pas toucher d'blé",
  "J'écrivais dans l'trom avant d'aller m'casser l'dos (yeah)",
  "C'est ma direction, j'me suis pas éparpillé",
  "J'ai pété les plombs! (J'ai pété les plombs)",
  "Malgré les ratures j'gratte le papier",
  'Déterminés, on part au front sans armure',
  "T'es foutu si tu échoues, dans ta situation",
  "Pour un 16 mes gars t'agressent seul le kickage nous apaise",
  "J'ai demandé pardon sans qu'on puisse me l'accorder",
  "Maintenant on fout dehors la hess même si nos passés l'heberge",
  "J'ai jamais kiffé lire depuis qu'jai 12 piges",
  "J'me remémore les clashs, les concours de rap, la hess",
  "J'ai quitté l'école! (J'ai quitté l'école)",
  "Dorénavant, je vais de l'avant c'est ma direction",
  'Si seulement tu savais (Si seulement tu savais)',
  'Fuck le taff... un bac pro ça paye pas',
  "J'ai troqué mes études contre un disque de platine",
  "Et tu nous suis si t'aimes (akhi)",
  'Malgrè les découverts, les sales patrons',
  "J'ai fui les sonneries, les bruits d'chaises",
  'Ils pensent que leur fiston ne vit que dehors',
  "J'sais où j'vais, sans savoir si j's'rais le bienvenu",
  "Dorénavant je vais de l'avant c'est ma direction",
  'Avec les srabs, pour le rap bah on veille tard',
  "Et qu'tout ceux qui le négligent bah on plus que tort",
  "Dans la rue ça rap en masse ça zappe même d'aller nehess",
  'Pour bien steaker les stre-mon qui voulaient nous faire chavirer',
  "J'ai pété les plombs, sans abandonner ni baisser les bras",
  "Je reste sur mes gardes, je n'suis qu'un homme",
  'Tout le mal que je garde (Tout le mal que je garde)',
  "J'ai tout plaqué à la conquête des salles, partons",
  "Tout ça j'le fais pour moi, ceux qui doutent et la daronne",
  "Plaqué plus d'une fois, dos au re-mu",
  "Les darons savent pas c'que j'fais, ils disent que j'dors",
  "C'est ma direction",
  "Mais ça taf, j'ai quitté pour mieux déplacer des montagnes",
  "Moi j'cherchais d'autre style (yeah) de richesses",
  'Est un pont fragile',
  "Plus d'nouvelles, batterie faible, malédiction",
  'Le rêve est à nos pieds donc on dort tête bêche',
  "J'suis pas invité et j'suis accompagné d'OVNIs",
  "Trop fier pour demander d'l'aide au RMI",
  "Et les plus terre-à-terre disent qu'on foncent dans un mur (Aah!)",
  'On tient juste à dire que... le pont qui mène au succès',
  'Ma direction',
  "Ni pour personne d'autre",
  "Ça rappait sale quand on s'entassait tous chez l'Blanc (yeah)",
  'Tu connais BatiPro, Crit, Selpro',
  "Oui le succès te fume, à peine tu l'crapotes",
  "Sans savoir qu'ce p'tit con prépare des disques d'or",
  'Résultat, ma foi baisse, mes fautes sont indénombrables',
  'Sans tous ces sacrifices, sans toute cette patience',
  'Ça capture mon image dans des 7D Canon',
  "J'me dirige vers la gloire et les blèmes-pro",
  "Nos voix, nos mains s'élèvent quand les flics salent nous rabaissent",
  "Si on a autant ramé, c'est pour être stock à l'arrivée",
  "On cherchait qu'la reconnaissance on voulait pas parler d'espèces",
  'Cherche pas trop la lumière, le soleil brûle ta peau',
  'On prétend pas être des modèles pour les gosses',
  "C'est ma direction!",
  "Ca veut acheter des caisses, attaquer l'marché des States"
];

List<String> wbn = [
  'Qui boit des litres, pour noyer sa haine',
  '- Wesh, D.R., mon gars sur, bien ou quoi poto, tranquille',
  'Moi j’ai un bête de style que des balles me filent',
  'Ici les samedis soirs se jouent à face ou pile',
  'Le soir s’approche ça se tape des barres',
  'Ça fume des sbars comme si c’était légal',
  "Tous ces gars prennent de l'âge mais restent des mioches",
  'Au début, ça trinque, ça sert et ça frappe des mains',
  'Si elle me demande si j’ai le mi-per je lui réponds cash fuck you',
  'Hey Ho',
  'Tout Bériz est à-l, Kofton sous Hasch',
  'Quelquefois ça me déçoit',
  "Putain je suis khabat, j'sais plus où j'me trouve",
  'Sauvageons sous flash, et au platine ya HCue',
  "Hello sista, je t'demande pas ton numéro",
  "On t’a déjà dit que t'étais une beauté numérique",
  "-  Ah j'avoue, wesh Glee lui, mon frère",
  'T’arrives sur la piste genre moonwalk',
  'Le soir s’approche ca se tape des barres',
  'Les gars veulent serrer des meufs, les meufs serrer des gars',
  "Tu comprends le lingala ? M'boté ma chérie",
  'Pour quelques billets de cent',
  'En solo ou pas, belles ou pas, guette les filatures',
  'Téma la bête de file où les boules défilent',
  'Putain je sens que ça va partir en soirée coup de teau-cou',
  'Et ça toute la night',
  '- Ah, franchement lourd, lourd',
  'Les soirées de samedi soir',
  'Putain, tu vois pourquoi je préfère le cinoche',
  '9.1 9.2 9.3 9.4',
  'Ça s’insulte ça se bouscule ça zappe la galanterie',
  "Il y a Yaya du Havre à coté y'a mon gars Lefa",
  "Y'en qui goutent aux go, y'en a qui goutent aux coups",
  "Que ce soit le tieks ou la tec' c'est lass'dégue, c'est moche",
  '- Si-si, lourd la soirée, hein',
  "Des cheveux longs des cheveux courts, j’l'accoste ou je cours",
  'Souvent les samedi soir c’est coup de tête et gauche',
  'Je fais du real hip hop comme les mecs en Amérique',
  "Et on se rend compte qu'on est super loin du Jannah",
  'Un petit pas de breakdance, je bouscule une top modèle',
  'Des go se tapent, un tissage vole',
  'C’est la loge, les chiottes, la cour ou la douche ?',
  "Hey mais y'a même les gens du 7.7",
  '- Bien ou bien',
  'J’ai vu une tate-pa partir au ralenti',
  "Merci, j'me sens invincible",
  'Au parking de la boite, toutes sortes de plaques',
  "Je suis dans la boite, j'aperçois mon gars Wisla",
  'Pendant que mon gars Jeryzoos se met bien sous alcool',
  'Embrouilles histoires si t’as pas trop de sex appeal',
  'Ça fait les 100 pas, tous à la recherche de créatures',
  'Je me dis c’est dead elle ressemble a mon ex Anna',
  'Et c’est souvent sur un bête de son',
  'Attends , non je crois que Dry est die',
  'Elle est grosse ! Oh my god, pas moyen de lui faire la cour',
  'Casquette Wati-B veste moncler putain ça se pé-sa',
  'Sous rapta bien vi-ser ça frappe des poings',
  'Hé gros, mais putain, mais ça danse sec là-bas la gros',
  'Wati bronx wesh Hamed quand tu veux on remet ça',
  "Et mon gars sûr s'en tape lui est dans ses bails",
  'Que souvent dans la te-boi y a une grosse flaque de sang',
  'Et oui je suis faible, et je suis qu’un homme',
  'Moi je danse le Mia dès que ca sonne un peu funky',
  'Ça part en giclée de sang',
  'Mais wesh il est pas un peu trop lé-mou ton haut ?'
];

List<String> balader = [
  'On veut plus taffer pour un homme ni toujours jouer les ien-ch',
  "Non, il y a plus d'illicite, je pense qu'on a retenu la leçon",
  'Nouveaux textes, donc nouvelle casquette imbibée de sueur',
  'Musique à fond Boulevard Haussman ça bombarde à Rue de la Paix',
  "On est plus malsains, t'as l'seum, tu vis mal ça",
  '"Break ya neck", au lieu de mal parler sur nous',
  "Tu-tu te demandes, si c'est Black M ou Black Shady qui parle (Hu)",
  "Si on fait le cristal, c'est cool pour la baraque il faut des sous",
  "(Moi j'vais m'sé-po) Hmmm Gims on s'capte",
  "Ensuite, on m'a chuchoté que je pouvais devenir numéro uno",
  "J'aime pas trop le caviar, laissez-moi mon assiette de pennes",
  'Nous sommes des bolides, vous êtes des luges',
  "Tu n'es que mon tit-pe, je suis comme ton père",
  "100% gros yeux, 75, ça vient pas d'Harlem",
  "Sur l'instrumentale je m'balade avec trop de swag",
  "P'tit bout de me-eus, toujours dans la che-po",
  'Vous êtes les sinistrés qui se réfugient',
  'Au début, je faisais du son pour épater les collégiennes',
  "Dans la ville des jolies bolides dominent sans faire d'action",
  "(Moi j'vais m'sé-po) L'insomniaque on s'capte",
  "Sachez que les amis de mes amis, t'inquiète j'les rince",
  "C'est le titi parisien, t'a reconnu l'accent",
  "J'suis faya, je déboule avec l'équipe et le poto Zied",
  "J'suis bouillant, y a de la f-meu et du de-mon vers la Fayette",
  'Ensuite, je le faisais pour épater les lycéennes',
  "(Moi j'vais m'sé-po) T'inquiète Black M on s'capte",
  "J'vais me balader dans les rues de Paname en Cayenne",
  "Y en a même qui disait qu'on s'pourrait faire des une-deux",
  "Donc j'vais me balader, aller me balader (yeah)",
  "À part ça, nous on t'mets ien-b",
  "Nous la flamble, la mala, va leur dire qu'on vit ap' sans",
  "J'vais me balader aux Champs Elysées",
  "(Moi j'vais m'sé-po) JR on s'capte",
  "Fini l'époque où ça marchait sans liquide dans l'errance akhi",
  'On fait sortir le gent-ar des poches mêmes aux plus grosses pinces donc',
  "(Moi j'vais m'sé-po) Petrodollars on s'capte",
  "(Moi j'vais m'sé-po) Wesh les mecs on s'capte",
  "J'ai dit, je vais me balader aux Champs Elysées",
  "Tout d'abord, 1 pour les nôtres, je fuck tous les autres, je bosse tous les jours",
  'Attend y a, Chico, les Maréga rue des Coquillères',
  "(Moi j'vais m'sé-po) Maska on s'capte",
  "Imbécile, j'dirais même que t'es con",
  "Je suis sous hach, j'kick sale, dis-le t'as pas le choix",
  'Masta na nga, Masta na nga, Masta',
  "Je suis passé de l'anonymat aux petites soirées mondaines",
  'Me manque pas de respect quand je kick mec',
  "J'vais me balader, aller me balader",
  "2 secondes, vas-y miss s'te plaît, c'est quoi le 06 j’t'appelle",
  "Séné-Sénégal, je veux l'Porsche et les poches pleines",
  'Wati B, nouveaux t-shirts, nouveaux vêt-sur',
  "Je voulais m'balader, m'balader",
  'Nous sommes comparables au déluge',
  'Mon équipe des niggas portent atteinte au corps, donc porte tes couilles',
  "Je veux pas que t'écoutes et que tu portes plainte",
  "À vouloir nous faire des croches-pattes, t'as gâté tes pompes",
  "(Moi j'vais m'sé-po) T'inquiète Barack on s'capte",
  'Balader, aller me balader (yeah)',
  "Moi j'étais l'petit con qu'les keufs aimaient contrôler",
  "Mais celui qui me les cassait, j'étais chaud pour le balafrer",
  "Que des textes insolites, j'suis solide, je suis plus le même",
  "Parce que c'est fini, on se massacre plus mince !",
  "Nous c'est du solide, vous c'est du lèg'",
  "Roule un spliff, si y a les keufs, on mets la poudre d'escampette",
  'On m\'disait "Joue pas trop avec la ue-r ou elle va te mettre une che-gau"',
  'Sortez nous le tapis rouge, on ira se prosterner dessus ouais',
  'Je veux me balader sur les Champs sans flics aux pattes',
  'Masta, Masta, Masta na nga',
  'Change rien, fuck les gadgets électroniques',
  "Moi j'vais m'sé-po dans les coins chics, t'inquiète",
  'Après nous y a plus de groupes, y a que des pom-pom girls',
  'En plus on veut faire des sous, et devenir des princes',
  'Toujours le petit sourire moqueur quand ils me disaient contre le mur',
  'Wesh le boss, double roro sur les Chroniques',
  'Paranoïaque, psychopathe',
  "J'arrive en bolide, impoli, j'attise la haine cousin"
];

List<String> qad = [
  'C\'est lequel d\'entre eux qui t\'a dit : "Quoi la Sexion',
  "Grosse casse-déd' à Dawa' tant qu'on y est",
  '"T\'inquiète Gims, y\'en a aucun qui t\'baise"',
  "Demande à Black M, everybody let's go, come on, say :",
  "Qui t'a dit qu'y a qu'des Portuguais au Rez-de-chaussée ?",
  "Là j'y go, pas l'temps d'papoter d'go",
  "Qui t'a dit qu'on était au cimetière ?! Akhi",
  "J'l'ai déjà dit, moi je smash ou je switch",
  "Maintenant retire c'que t'as dit ou c'qu'on t'a fait dire",
  "Qu'tous les Chinois font du kung-fu quel est le con qui l'a sorti ?",
  "In your motherfuckin' face",
  'Ha ha ha',
  'Okay Okay Okay Okay',
  'Kinshasa, Brazzaville, Mwana mwana mwanananana mayi Soldiers',
  "Le mec dont tous les gardiens ont peur est Guesh on l'sait",
  '(HO) Joue pas piano, (HO) je suis un Diallo',
  "Demande à R si ça ce n'est que pas sa ra-za ce-ze, (Ouh)",
  "Mais qui t'a dit que Sarkozy était français ?!",
  "Oui je suis présent et chaud bouillant si mes gars s'fight",
  "Qui t'a dit que tous les Japonais maîtrisaient les ordi' ?",
  "Maitre Gimso, Gringo, j'crois qu'j'ai l'single",
  'Tout niquer, tou-tou-tout niquer ?',
  "Qui t'a dit qu'tout ça n'allait pas rendre la mif' et l'daron paro ?",
  "Handeck, (Eh Ouais) Sans dec'",
  "Et qui t'a dit que les arabes étaient tous des voleurs ?!",
  "Hé les mômes, il faut y aller mollo, c'monde",
  "C'est l'Wati-B ça sent la diff'",
  "J'suis pas Sean Paul ni Kingston j'viens du Congo",
  'En concert dans l\'tiekson ? Ça hors de question !" ?',
  "Sous rap dense, t'as traité l'agent de sale conne",
  "Handeck, (NO) Sans déc'",
  "Tu m'avais négligé enfoiré ?!",
  "Qui c'est qui veut du Real Hip Hop, ça vient d'Paname",
  "Qui t'a dit d'redire tout c'qu'on t'a dit",
  "Qu'les paquets de LU coûtent plus chers que les baraques au Qatar ?",
  "Mais qui t'a dit qu'tous les épiciers font des taros d'bâtard",
  "Mais qui t'a dit qu't'étais d'la mif ?",
  "Qui t'a dit qu'on roulait en gros gamos ?",
  "Qui t'a dit qu'j'serais clodo si j'quittais l'école",
  "Akhi qui t'a dit que les Bakaris sont bons qu'à s'bagarrer ?",
  'Triple disques de platine dans ton cavu akhi, breh',
  "Mais qui t'a dit que le Wati B n'allait pas tout niquer",
  'Rambouima yété Diallo alla projet',
  "Maintenant tout ce que tu vois c'est lavabo, carreaux, barreaux",
  "Paris la nuit, trop d'têtes se droguent",
  "Wesh qui t'a dit qu'on était rassasiés ?",
  'Na na na, na na na',
  "Akhi, qui t'a dit de boire leur Alcool",
  "Wesh mon suisse, quoi d'neuf depuis l'Wati Bonhomme ?",
  "Aie c'est du bon job, personne peut l'nier",
  'Toujours devant ton PC ou devant ton écran Thomson ?',
  "Te met des baffes avec le bras d'Mauresmo",
  "J'ai mon assurance flow la famille t'inquiète",
  "Quelques Watt sé-po sur le tec', (NAN)",
  "Qui a dit qu'les blondes étaient toutes des connes",
  '"Tu devais passer demain, passe hein ?!"',
  '"Hé le Rebeu, Ramène la Porsche Carrera enfoiré ramène la"',
  'Na na na naaaa...',
  "Et qui t'a dit qu'les zaico n'savaient pas se saper ?!",
  "Adama, mais qui t'a dit que les guinéens n'étaient pas des vrais Diallo ?!",
  "Mais qui t'a dit qu'y en avait des comme Black M ?",
  "Mais qui t'a dit de négliger le Wati-B ?",
  'Imbécile, on est là on est là, 75',
  "Ici c'est la hass, qui pilote et si t'es aud-ch vamos ?",
  "Inconsciemment ça sent le biff'",
  "Excuse, je n'voulais pas dire ça, ça vient d'Paname",
  'Hein ?!',
  'Naa, Na na na na, Na na na na',
  "En quête mon flow, ma tech', (Dis wAllah)",
  'Dj Hcue, sisisi',
  "J'm'inquiète ap', j'ressens aucun suspens",
  'Les Chroniques du 75 Volume 2',
  "Oui y'a du on-s, y'a des petits tah sa race night",
  "Qui t'as dit que les noirs ne savaient pas nager ?!",
  "Fais pas d'gestes brusques, sur ma droite y'a Bajnight",
  "Qui est l'rageux qui t'a dit qu'il fallait surtout pas m'backer ?",
  "Hello Wendy, quoi d'neuf depuis Wati Bon Son ?",
  'Wesh boy tu veux du flow ? Demande aux bonnes personnes',
  "Tu sens la diff', ça sent le biff'",
  "Wesh boy quoi d'neuf depuis Wati By Night ?",
  "Quelques Watt sé-po sur le tec', (Arrête)",
  "Ok, qui t'a dit qu'on était en bout d'course ?",
  "T'es Bête Ou Quoi ?!",
  "Rien d'space, ah si, on est sur le podium",
  "Mais qui t'a dit de te mettre tout au fond d'cette p'tite salle ? (HO)",
  "En quête mon flow, ma tech', (Tu Mens)",
  '(HO) Comme le dit Allo (HO), cette année est à nous',
  "Quittais l'école, qui-qui-quittais l'école ?",
  "Jetez moi des groupies comme Zahia, ça vient d'Paname",
  "Vous n'aimez pas nos sons pourtant vous écoutez celui-ci",
  "J'suis qu'à 30 pour cent mais y'a pas d'problèmes",
  "Si on cane c'est qu'on s'est dé-suici",
  'Toutes des connes, tou-tou-toutes des connes ?',
  "Que ce soit le tieks ou la tec' c'est 'lasse-dégue, c'est mort",
  "Sûrement des pouf' qui bouffent des bouts d'bourses",
  "Résultat j'suis à-l et j'kicke ça",
  "Donne pas tes fesses, ou tu vas t'faire dom'-so",
  "Y'a des scores lourds, guette comme j'suis vif",
  "Mais qui t'a dit qu'au placard y'avait qu'beurs et blacks ?"
];
