List<String> hp = [
  'Les Contes de Beedle le Barde',
  'L\'école des sorciers',
  'La Chambre des Secrets',
  'Le prisonnier d\'Azkaban',
  'La Coupe de Feu',
  'L\'Ordre du Phénix',
  'Le Prince de Sang-Mêlé',
  'Les Reliques de la Mort',
  'Les Animaux fantastiques',
  'Les Crimes de Grindelwald',
  'Harry Potter',
  'Hermione Granger',
  'Ronald Weasley',
  'Neville Londubat',
  'Luna Lovegood',
  'Drago Malefoy',
  'Albus Dumbledore',
  'Minerva McGonagall',
  'Severus Rogue',
  'Filius Fitwick',
  'Pomona Chourave',
  'Rubeus Hagrid',
  'Sibylle Trelawney',
  'Gilderoy Lockhart',
  'Horace Slughorn',
  'Tom Jedusor',
  'Bellatrix Lestrange',
  'Peter Pettigrow',
  'Barty Croupton Jr.',
  'Fenrir Greyback',
  'Mangemort',
  'Sirius Black',
  'Alastor Maugrey',
  'Remus Lupin',
  'Fleur Delacour',
  'Kingsley Shacklebolt',
  'Nymphadora Tonks',
  'Ordre du Phénix',
  'Cornelius Fudge',
  'Rufus Scrimgeour',
  'Dolores Ombrage',
  'Arthur Weasley',
  'Molly Weasley',
  'Sang-pur',
  'Sang-mêlé',
  'Moldu',
  'Terrier',
  'Département des Mystères',
  'Armée de Dumbledore',
  'Ginny Weasley',
  'Gabrielle Delacour',
  'Vélane',
  'Narcissa Malefoy',
  'Lucius Malefoy',
  'Poudlard',
  'Azkaban',
  'Serpentard',
  'Gryffondor',
  'Serdaigle',
  'Poufsouffle',
  'Choixpeau magique',
  'Godric Gryffondor',
  'Salazar Serpentard',
  'Rowena Serdaigle',
  'Helga Poufsouffle',
  'Ministère de la Magie',
  'Vernon Dursley',
  'Pétunia Dursley',
  'Dudley Dursley',
  'Quirinus Quirrell',
  'Firenze',
  'Gilderoy Lockhart',
  'Cédric Diggory',
  'Tournoi des Trois Sorciers',
  'La Gazette du sorcier',
  'Mondingus Fletcher',
  'Frank Londubat',
  'Alice Londubat',
  'Cho Chang',
  'James Potter',
  'Lily Potter',
  'George Weasley',
  'Fred Weasley',
  'Charlie Weasley',
  'Fumseck',
  'Nagini',
  'Abelforth Dumbledore',
  'Horcruxe',
  'Cartes de Chocogrenouille',
  'Mimi Geignarde',
  'Basilic',
  'Aragog',
  'Épée de Gryffondor',
  'Baguette de Sureau',
  'Regulus Black',
  'Dobby',
  'Kreattur',
  'Cape d\'Invisibilité',
  'Pierre de Résurrection',
  'Vif d\'or',
  'Pierre philosophale',
  'Nicolas Flamel',
  'Beauxbâtons',
  'Allée des Embrumes',
  'Chemin de Traverse',
  'Miroir du Riséd',
  'Détraqueur',
  'Cracmol',
  'Argus Rusard',
  'Miss Teigne',
  'Olympe Maxime',
  'Viktor Krum',
  'Durmstrang',
  'Forêt de Dean',
  'Gringotts',
  'Gobelins',
  'Gripsec',
  'Salle sur Demande',
  'Éclair de Feu',
  'Gare de King\'s Cross',
  'Pré-au-Lard',
  'Feudeymon',
  'Forêt interdite',
  'Sombrals',
  'Obscurus',
  'Croyance Bellebosse',
  'Norbert Dragonneau',
  'Bathilda Tourdesac',
  'Godric\'s Hollow',
  'Igor Karkaroff',
  'Norbert',
  'Pattenrond',
  'Crockdur',
  'Trevor',
  'Voie 9¾',
  'Pompom Pomfresh',
  'Polynectar',
  'Poudlard Express',
  'Ford Anglia',
  'Carte du Maraudeur',
  'Touffu',
  'Hedwige',
  'Croûtard',
  'Buck',
  'Le Chaudron Baveur',
  'Ollivander',
  '4, Privet Drive',
  'Beuglante',
  'Auror',
  'Baguette magique',
  'Gallions',
  'Weasley, Farces pour sorciers facétieux',
  'Zonko',
  'Mornilles',
  'Noises',
  'Coupe de Feu',
  'Coupe de Helga Poufsouffle',
  'Médaillon de Salazar Serpentard',
  'Impero',
  'Endoloris',
  'Avada Kedavra',
  'Expelliarmus',
  'Stupéfix',
  'Wingardium Leviosa',
  'Collier d\'opale',
  'Barjow et Beurk',
  'Déluminateur',
  'Glace à l\'Ennemi',
  'Pensine',
  'Oubliettes',
  'Plume à Papote',
  'Rita Skeeter',
  'Rapeltout',
  'Retourneur de Temps',
  'Sac en perles d\'Hermione',
  'Enervatum',
  'Accio',
  'Aguamenti',
  'Alohomora',
  'Amplificatum',
  'Anapneo',
  'Anteoculatia',
  'Aparecium',
  'Aqua Eructo',
  'Arania Exumai',
  'Aresto Momentum',
  'Assurdiato',
  'Avis',
  'Bloclang',
  'Bombarda',
  'Bombarda Maxima',
  'Brackium Emendo',
  'Calvorio',
  'Carpe Retractum',
  'Cave inimicum',
  'Collaporta',
  'Colovaria',
  'Confringo',
  'Confundo',
  'Cracbadabum',
  'Dentesaugmento',
  'Deprimo',
  'Descendo',
  'Destructum',
  'Diffindo',
  'Dissendium',
  'Draconifors',
  'Duro',
  'Elasticus',
  'Engorgio Cranius',
  'Entomorphis',
  'Episkey',
  'Erigo',
  'Evanesco',
  'Expecto Patronum',
  'Expulso',
  'Failamalle',
  'Ferula',
  'Finite',
  'Finite Incantatem',
  'Flambios',
  'Flipendo',
  'Furunculus',
  'Gemino',
  'Glacius',
  'Glisseo',
  'Harmonia Nectere Passus',
  'Herbivicus',
  'Herbifors',
  'Hominum revelio',
  'Immobulus',
  'Impedimenta',
  'Impervius',
  'Incarcerem',
  'Incarcifors',
  'Incendio',
  'Lacarnum Inflamarae',
  'Lapifors',
  'Lashlabask',
  'Legilimens',
  'Levicorpus',
  'Liberacorpus',
  'Limacius Eructo',
  'Locomotor',
  'Locomotor Mortis',
  'Lumos',
  'Lumos Maxima',
  'Lumos Solem',
  'Magicus Extremos',
  'Meteorribilis recanto',
  'Mobiliarbus',
  'Mobilicorpus',
  'Morsmordre',
  'Multicorfors',
  'Mutinlutin Malinpesti',
  'Nox',
  'Obscuro',
  'Oculus Reparo',
  'Oppugno',
  'Orbis',
  'Orchideus',
  'Oubliettes',
  'Partis Temporus',
  'Periculum',
  'Petrificus Totalus',
  'Piertotum locomotor',
  'Pointe au nord',
  'Portus',
  'Prior Incanto',
  'Priori Incantatum',
  'Protego',
  'Protego horribilis',
  'Protego totalum',
  'Récurvite',
  'Redactum Cranius',
  'Reducto',
  'Reparo',
  'Repello Moldum',
  'Repulso',
  'Rictusempra',
  'Riddikulus',
  'Salveo maleficia',
  'Sectumsempra',
  'Serpensortia',
  'Silencio',
  'Sonorus',
  'Sourdinam',
  'Specialis revelio',
  'Stupéfix',
  'Tarentallegra',
  'Tergeo',
  'Volatilors',
  'Vulnera Sanentur',
  'Waddiwasi',
  'Peeves',
  'Attrapeur',
  'Batteur',
  'Poursuiveur',
  'Gardien',
  'Capitaine',
  'Balai volant',
  'Cognard',
  'Souafle',
  'Préfèt',
  'Professeur',
  'Renée Bibine',
];

List<String> hpsorts = [
  'Accio',
  'Aguamenti',
  'Alohomora',
  'Amplificatum',
  'Anapneo',
  'Anteoculatia',
  'Aparecium',
  'Aqua Eructo',
  'Arania Exumai',
  'Aresto Momentum',
  'Assurdiato',
  'Avis',
  'Bloclang',
  'Bombarda',
  'Bombarda Maxima',
  'Brackium Emendo',
  'Calvorio',
  'Carpe Retractum',
  'Cave inimicum',
  'Collaporta',
  'Colovaria',
  'Confringo',
  'Confundo',
  'Cracbadabum',
  'Dentesaugmento',
  'Deprimo',
  'Descendo',
  'Destructum',
  'Diffindo',
  'Dissendium',
  'Draconifors',
  'Duro',
  'Elasticus',
  'Enervatum',
  'Engorgio Cranius',
  'Entomorphis',
  'Episkey',
  'Erigo',
  'Evanesco',
  'Expecto Patronum',
  'Expulso',
  'Expelliarmus',
  'Failamalle',
  'Ferula',
  'Finite',
  'Finite Incantatem',
  'Flambios',
  'Flipendo',
  'Furunculus',
  'Gemino',
  'Glacius',
  'Glisseo',
  'Harmonia Nectere Passus',
  'Herbivicus',
  'Herbifors',
  'Hominum revelio',
  'Immobulus',
  'Impedimenta',
  'Impervius',
  'Incarcerem',
  'Incarcifors',
  'Incendio',
  'Lacarnum Inflamarae',
  'Lapifors',
  'Lashlabask',
  'Legilimens',
  'Levicorpus',
  'Liberacorpus',
  'Limacius Eructo',
  'Locomotor',
  'Locomotor Mortis',
  'Lumos',
  'Lumos Maxima',
  'Lumos Solem',
  'Magicus Extremos',
  'Meteorribilis recanto',
  'Mobiliarbus',
  'Mobilicorpus',
  'Morsmordre',
  'Multicorfors',
  'Mutinlutin Malinpesti',
  'Nox',
  'Obscuro',
  'Oculus Reparo',
  'Oppugno',
  'Orbis',
  'Orchideus',
  'Oubliettes',
  'Partis Temporus',
  'Periculum',
  'Petrificus Totalus',
  'Piertotum locomotor',
  'Pointe au nord',
  'Portus',
  'Prior Incanto',
  'Priori Incantatum',
  'Protego',
  'Protego horribilis',
  'Protego totalum',
  'Récurvite',
  'Redactum Cranius',
  'Reparo',
  'Repello Moldum',
  'Repulso',
  'Revigor',
  'Rictusempra',
  'Riddikulus',
  'Salveo maleficia',
  'Sectumsempra',
  'Serpensortia',
  'Silencio',
  'Sonorus',
  'Sourdinam',
  'Specialis revelio',
  'Spero Patronum',
  'Stupéfix',
  'Tarentallegra',
  'Tergeo',
  'Volatilors',
  'Vulnera Sanentur',
  'Waddiwasi',
  'Wingardium Leviosa',
];

List<String> nct = [
  'Taeil',
  'Johnny',
  'Taeyong',
  'Yuta',
  'Kun',
  'Doyong',
  'Ten',
  'Jaehyun',
  'Winwin',
  'Jungwoo',
  'Lucas',
  'Mark',
  'Xiaojun',
  'Hendery',
  'Renjun',
  'Jeno',
  'Haechan',
  'Jaemin',
  'Yangyang',
  'Shotaro',
  'Sungchan',
  'Chenle',
  'Jisung',
  'NCT 127',
  'NCT',
  'NCT Dream',
  'WayV',
  '0 Mile',
  '1, 2, 3',
  '100',
  '119',
  '7 Days',
  '90\'s Love',
  'After Midnight',
  'Angel',
  'Another World',
  'Baby Don\'t Like It',
  'Baby Don\'t Stop\'',
  'Back 2 U (AM 01:27)',
  'Bad Alive',
  'Beautiful Time',
  'Best Friend',
  'Black on Black',
  'Blow My Mind',
  'BOOM',
  'Boom',
  'BOSS',
  'Bye My First…',
  'Candle Light',
  'Chain',
  'Cherry Bomb',
  'Chewing Gum',
  'City 127',
  'Come Back',
  'Come Back (WayV)',
  'Coming Home',
  'Dancing In The Rain',
  'Day Dream',
  'Dear DREAM',
  'Domino',
  'Don\'t Need Your Love',
  'Dream Launch',
  'Dream Run',
  'Dreaming',
  'Dreams Come True',
  'Drippin\'',
  'Dunk Shot',
  'Déjà Vu',
  'Electric Hearts',
  'Elevator (127F)',
  'End to Start',
  'Face to Face',
  'Faded In My Last Song',
  'Fire Truck',
  'Fly Away With Me',
  'FOOL',
  'From Home',
  'Go',
  'Good Thing',
  'Heartbreaker',
  'Highway to Heaven',
  'Interlude: Awaken The World',
  'Interlude: Neo Zone',
  'Interlude: Past to Present',
  'Interlude: Regular to Irregular',
  'INTRO: Neo Got My Back',
  'Jet Lag',
  'Joy',
  'Kick It',
  'King of Hearts',
  'Kitchen Beat',
  'Knock On',
  'La La Love',
  'Let me love u',
  'Light Bulb',
  'Limitless',
  'Long Flight',
  'Long Slow Distance',
  'Love Again',
  'Love Me Now',
  'Love Song',
  'Love Talk',
  'Mad City',
  'Mad Dog',
  'Make A Wish',
  'Make Your Day',
  'Misfit',
  'Moonwalk',
  'Music, Dance',
  'My First and Last',
  'My Page',
  'My Van',
  'Nectar',
  'No Longer',
  'Non Stop',
  'Not Alone',
  'Once Again',
  'Only Human',
  'OUTRO: VISION',
  'OUTRO: WE ARE 127',
  'Pandora\'s Box',
  'Paper Plane',
  'Paradise',
  'Prelude',
  'Punch',
  'Puzzle Piece',
  'Quiet Down',
  'Regular',
  'Regular (WayV)',
  'Replay (PM 01:27)',
  'Ridin',
  'Run Back 2 U',
  'Running 2 U',
  'Say It',
  'Simon Says',
  'Sit Down!',
  'Stand By Me',
  'STRONGER',
  'Summer 127',
  'Sun & Moon',
  'Superhuman',
  'Switch',
  'Take Off',
  'The 7th Sense',
  'Timeless',
  'Touch',
  'Trigger The Fever',
  'Turn Back Time',
  'Unbreakable',
  'Up From Here',
  'Volcano',
  'Wake Up',
  'Wakey-Wakey',
  'Walk You Home',
  'We go nanana',
  'We Go Up',
  'We Young',
  'Welcome To My Playground',
  'Whiplash',
  'White Night',
  'Without You',
  'Work It',
  'Yeah Yeah Yeah',
  'Yestoday',
  'Empathy',
  'Regular-Irregular',
  'Awaken',
  'Neo Zone',
  'Awaken the World',
  'Resonance Part. 1',
];

List<String> vd = [];

List<String> capitales = [
  'Tokyo',
  'Mexico',
  'Séoul',
  'Jakarta',
  'New Delhi',
  'Le Caire',
  'Moscou',
  'Buenos Aires',
  'Manille',
  'Londres',
  'Dhâkâ',
  'Paris',
  'Pékin',
  'Bangkok',
  'Lima',
  'Lisbonne',
  'Téhéran',
  'Kinshasa',
  'Santiago',
  'Madrid',
  'Naypyidaw',
  'Damas',
  'Singapour',
  'Ankara',
  'Luanda',
  'Bagdad',
  'Riyad',
  'Caracas',
  'Athènes',
  'Berlin',
  'Accra',
  'Hanoï',
  'Kiev',
  'Rome',
  'Addis-Abeba',
  'Guatemala',
  'Pyongyang',
  'Tachkent',
  'Saint-Domingue',
  'Brasilia',
  'Nairobi',
  'San José',
  'Tunis',
  'Alger',
  'Bucarest',
  'Budapest',
  'Conakry',
  'La Havane',
  'Port-au-Prince',
  'Dakar',
  'Amman',
  'Bogota',
  'Stockholm',
  'Kaboul',
  'Bakou',
  'San Salvador',
  'Minsk',
  'Varsovie',
  'Vienne',
  'Astana',
  'Harare',
  'Katmandou',
  'Khartoum',
  'Montevideo',
  'Quito',
  'Tananarive',
  'Colombo',
  'Kuala Lumpur',
  'Erevan',
  'Tripoli',
  'Phnom Penh',
  'Sofia et bruxelles',
  'Belgrade',
  'Mogadiscio',
  'Prague',
  'Tegucigalpa',
  'Yaoundé',
  'Maputo',
  'Tbilissi',
  'Pretoria',
  'Kampala',
  'Ottawa',
  'Abou Dabi',
  'Bamako',
  'Beyrouth',
  'Lusaka',
  'Managua',
  'Ndjamena',
  'Ouagadougou',
  'Sanaa',
  'Mascate',
  'Lomé',
  'Panama',
  'Brazzaville',
  'Islamabad',
  'Kigali',
  'Zagreb',
  'Jerusalem',
  'Monrovia',
  'Rīga',
  'Amsterdam',
  'Niamey',
  'Tirana',
  'Oulan-Bator',
  'Bangui',
  'Libreville',
  'Chişinău',
  'Rabat',
  'Vientiane',
  'Kingston',
  'Bichkek',
  'Achgabat',
  'Skopje',
  'Washington',
  'Helsinki',
  'Nouakchott',
  'Vilnius',
  'Freetown',
  'Asuncion',
  'Oslo',
  'Douchanbé',
  'Copenhague',
  'Dublin',
  'Asmara',
  'Bratislava',
  'Koweït',
  'Lilongwe',
  'Tallinn',
  'Sarajevo',
  'Djibouti',
  'Doha',
  'Wellington',
  'Canberra',
  'Port Moresby',
  'Bujumbura',
  'Port-d\'Espagne',
  'Porto-Novo',
  'Sucre (Bolivie)',
  'Bissau',
  'Ljubljana',
  'Georgetown',
  'Paramaribo',
  'Windhoek',
  'Nassau',
  'Nicosie',
  'Dodoma',
  'Gaborone',
  'Maseru',
  'Suva',
  'Manama',
  'Port-Louis',
  'Podgorica',
  'Berne',
  'Reykjavik',
  'Yamoussoukro',
  'Praia',
  'Abuja',
  'Bandar Seri Begawan',
  'Luxembourg',
  'Malé',
  'Castries',
  'Dili',
  'Moroni',
  'Mbabane',
  'Thimphou',
  'Malabo',
  'São Tomé',
  'Banjul',
  'Apia',
  'Nuku\'alofa',
  'Saint-Georges',
  'Monaco',
  'Honiara',
  'Port-Vila',
  'Saint John\'s',
  'Tarawa',
  'Victoria',
  'Delap-Uliga-Darrit',
  'Andorre-la-Vieille',
  'Kingstown',
  'Roseau',
  'Basseterre',
  'Palikir',
  'Belmopan',
  'La Valette',
  'Bridgetown',
  'Vaduz',
  'Funafuti',
  'Ville de Saint-Marin',
  'Cité du Vatican',
  'Melekeok',
  'Hargeisha',
  'Taipei',
  'Pristina',
  'Soukhoumi',
  'Stepanakert',
  'Tiraspol',
  'Tskhinvali',
];

List<String> countries = [
  'Japon',
  'Mexique',
  'Corée du Sud',
  'Indonésie',
  'Inde',
  'Égypte',
  'Russie',
  'Argentine',
  'Philippines',
  'Royaume-Uni',
  'Bangladesh',
  'France',
  'Chine',
  'Thaïlande',
  'Pérou',
  'Portugal',
  'Iran',
  'République démocratique du Congo',
  'Chili',
  'Espagne',
  'Birmanie',
  'Syrie',
  'Singapour',
  'Turquie',
  'Angola',
  'Irak',
  'Arabie saoudite',
  'Venezuela',
  'Grèce',
  'Allemagne',
  'Ghana',
  'Viêt Nam',
  'Ukraine',
  'Italie',
  'Éthiopie',
  'Guatemala',
  'Corée du Nord',
  'Ouzbékistan',
  'République dominicaine',
  'Brésil',
  'Kenya',
  'Costa Rica',
  'Tunisie',
  'Algérie',
  'Roumanie',
  'Hongrie',
  'Guinée',
  'Cuba',
  'Haïti',
  'Sénégal',
  'Jordanie',
  'Colombie',
  'Suède',
  'Afghanistan',
  'Azerbaïdjan',
  'Salvador',
  'Biélorussie',
  'Pologne',
  'Autriche',
  'Kazakhstan',
  'Zimbabwe',
  'Népal',
  'Soudan',
  'Uruguay',
  'Équateur',
  'Madagascar',
  'Sri Lanka',
  'Malaisie',
  'Arménie',
  'Libye',
  'Cambodge',
  'Bulgarie et belgique',
  'Serbie',
  'Somalie',
  'République tchèque',
  'Honduras',
  'Cameroun',
  'Mozambique',
  'Géorgie',
  'Afrique du Sud',
  'Ouganda',
  'Canada',
  'Émirats arabes unis',
  'Mali',
  'Liban',
  'Zambie',
  'Nicaragua',
  'Tchad',
  'Burkina Faso',
  'Yémen',
  'Oman',
  'Togo',
  'Panama',
  'République du Congo',
  'Pakistan',
  'Rwanda',
  'Croatie',
  'Israël',
  'Libéria',
  'Lettonie',
  'Pays-Bas',
  'Niger',
  'Albanie',
  'Mongolie',
  'République centrafricaine',
  'Gabon',
  'Moldavie',
  'Maroc',
  'Laos',
  'Jamaïque',
  'Kirghizistan',
  'Turkménistan',
  'Macédoine',
  'États-Unis',
  'Finlande',
  'Mauritanie',
  'Lituanie',
  'Sierra Leone',
  'Paraguay',
  'Norvège',
  'Tadjikistan',
  'Danemark',
  'Irlande',
  'Érythrée',
  'Slovaquie',
  'Koweït',
  'Malawi',
  'Estonie',
  'Bosnie-Herzégovine',
  'Djibouti',
  'Qatar',
  'Nouvelle-Zélande',
  'Australie',
  'Papouasie-Nouvelle-Guinée',
  'Burundi',
  'Trinité-et-Tobago',
  'Bénin',
  'Bolivie',
  'Guinée-Bissau',
  'Slovénie',
  'Guyana',
  'Suriname',
  'Namibie',
  'Bahamas',
  'Chypre',
  'Tanzanie',
  'Botswana',
  'Lesotho',
  'Fidji',
  'Bahreïn',
  'Maurice',
  'Monténégro',
  'Suisse',
  'Islande',
  'Côte d\'Ivoire',
  'Cap-Vert',
  'Nigeria',
  'Brunei',
  'Luxembourg',
  'Maldives',
  'Sainte-Lucie',
  'Timor oriental',
  'Comores',
  'Swaziland',
  'Bhoutan',
  'Guinée équatoriale',
  'Sao Tomé-et-Principe',
  'Gambie',
  'Samoa',
  'Tonga',
  'Grenade',
  'Monaco',
  'Salomon',
  'Vanuatu',
  'Antigua-et-Barbuda',
  'Kiribati',
  'Seychelles',
  'Marshall',
  'Andorre',
  'Saint-Vincent-et-les Grenadines',
  'Dominique',
  'Saint-Christophe-et-Niévès',
  'Micronésie',
  'Belize',
  'Malte',
  'Barbade',
  'Liechtenstein',
  'Tuvalu',
  'Saint-Marin',
  'Saint-Siège',
  'Palaos',
  'Somaliland',
  'Taïwan',
  'Chypre du Nord',
  'Kosovo',
  'Abkhazie',
  'Haut-Karabagh',
  'Transnistrie',
  'Ossétie du Sud',
];

List<String> disneyHV = [
  'Blanche-Neige',
  'Cendrillon',
  'Aurore',
  'Ariel',
  'Belle',
  'Jasmine',
  'Pocahontas',
  'Mulan',
  'Tiana',
  'Raiponce',
  'Mérida',
  'Vaiana',
  'Éloïse',
  'Mélodie',
  'Kida Nedakh',
  'Ting-Ting, Su, et Mei',
  'Kilala Reno',
  'Kairi',
  'Princesse de Gentlehaven',
  'Vanellope von Schweetz',
  'Sofia',
  'Elena',
  'Anna',
  'Elsa',
  'Alice',
  'Wendy Darling',
  'Clochette',
  'Esméralda',
  'Marianne',
  'Mégara',
  'Nala',
  'Jane Porter',
  'Raya',
  'La Reine',
  'Chernabog',
  'Reine de Cœur',
  'Capitaine Crochet',
  'Maléfique',
  'Cruella d\'Enfer',
  'Ursula',
  'Jafar',
  'Scar',
  'Hadès',
  'Docteur Facilier',
  'Grand Méchant Loup',
  'Pat Hibulaire',
  'Cavalier Sans Tête',
  'Mortimer Mouse',
  'Frère Renard',
  'Frère Ours',
  'Grand Coquin',
  'Gédéon',
  'Stromboli',
  'Le Cocher',
  'Monstro',
  'Monsieur Loyal',
  'Éléphants roses',
  'Diablo',
  'Fantômes auto-stoppeur',
  'Les Revenants Solitaires',
  'Madame de Trémaine',
  'Anastasie de Trémaine',
  'Javotte de Trémaine',
  'Lucifer',
  'Monsieur Mouche',
  'Si et Am',
  'Jasper etHorace',
  'Madame Mim',
  'Kaa',
  'Shere Khan',
  'Edgar Balthazar',
  'Prince Jean',
  'Triste Sire',
  'Shérif de Nottingham',
  'Madame Médusa',
  'Amos Slade',
  'Seigneur des Ténèbres',
  'Ratigan',
  'Félicia',
  'Bill Sykes',
  'Efélants',
  'Nouifs',
  'Flotsam et Jetsam',
  'Percival McLeach',
  'Gaston',
  'Iago',
  'Shenzi, Banzai et Ed',
  'Oogie Boogie',
  'Gouverneur Ratcliffe',
  'Claude Frollo',
  'Peine et Panique',
  'Moires',
  'Shan Yu',
  'Clayton',
  'Yzma',
  'Kronk',
  'Capitaine Gantu',
  'Docteur Hämsterviel',
  'DOR-15',
  'Michael "Goob" Yagoobian',
  'Reine Narissa',
  'Lawrence',
  'Mère Gothel',
  'Les Frères Stabbington',
  'Sa Sucrerie',
  'Aigre Bill',
  'Hans',
  'Yokai',
  'Tamatoa',
  'Sid Phillips',
  'Le Borgne',
  'Empereur Zurg',
  'Papi Pépite',
  'Léon "Le Caméléon"',
  'Henry J. Waternoose III',
  'Syndrome',
  'Chick Hicks',
  'AUTO',
  'Charles Muntz',
  'Lotso',
  'Professeur Zündapp',
  'Mor\'du',
  'Coup de Tonnerre',
  'Miss Fritter',
  'Ernesto de la Cruz',
  'Evelyn Deavor',
  'l\'Hypnotiseur',
  'Sarah Sanderson',
  'Winifred Sanderson',
  'Mary Sanderson',
  'Florian',
  'Henry',
  'Philippe',
  'Éric',
  'La Bête',
  'Aladdin',
  'John Smith',
  'Li Shang',
  'Naveen',
  'Flynn Rider',
  'Bambi',
  'Arthur Pendragon',
  'Prince Edward',
  'Rei',
  'Simba',
  'Hercule',
  'Milo Thatch',
  'Kovu',
  'Empereur Kuzco',
  'Harris, Hubert, et Hamish',
  'Mickey Mouse',
  'Donald Duck',
  'Dingo',
  'Tilt',
  'Peter Pan',
  'Mowgli',
  'Jack Skellington',
  'Quasimodo',
  'Tarzan',
  'John Rolfe',
  'Taram',
  'Phœbus',
  'Sora',
  'Ralph-la-casse',
  'Jim Hawkins',
  'Kristoff',
  'Yao, Ling et Chien Po',
  'Robin des Bois',
];

List<String> disneyMovies = [
  'Blanche-Neige et les Sept Nains',
  'Pinocchio',
  'Fantasia',
  'Dumbo',
  'Bambi',
  'Saludos Amigos',
  'Les Trois Caballeros',
  'La Boîte à musique',
  'Coquin de Printemps',
  'Mélodie Cocktail',
  'Le Crapaud et le Maître d\'École',
  'Cendrillon',
  'Alice au Pays des Merveilles',
  'Peter Pan',
  'La Belle et le Clochard',
  'La Belle au Bois Dormant',
  'Les 101 Dalmatiens',
  'Merlin l\'Enchanteur',
  'Le Livre de la Jungle',
  'Les Aristochats',
  'Robin des Bois',
  'Les Aventures de Winnie l\'Ourson',
  'Les Aventures de Bernard et Bianca',
  'Rox et Rouky',
  'Taram et le Chaudron magique',
  'Basil, détective privé',
  'Oliver et Compagnie',
  'La Petite Sirène',
  'Bernard et Bianca au pays des kangourous',
  'La Belle et la Bête',
  'Aladdin',
  'Le Roi Lion',
  'Pocahontas : une légende indienne',
  'Le Bossu de Notre-Dame',
  'Hercule',
  'Mulan',
  'Tarzan',
  'Fantasia 2000',
  'Dinosaure',
  'Kuzco, l\'empereur mégalo',
  'Atlantide, l\'empire perdu',
  'Lilo et Stitch',
  'La Planète au trésor, un nouvel univers',
  'Frère des Ours',
  'La Ferme se rebelle',
  'Chicken Little',
  'Bienvenue chez les Robinson',
  'Volt, star malgré lui',
  'La Princesse et la Grenouille',
  'Raiponce',
  'Winnie l\'Ourson',
  'Les Mondes de Ralph',
  'La Reine des Neiges',
  'Les Nouveaux Héros',
  'Zootopie',
  'Vaiana, la légende du bout du monde',
  'Les Mondes de Ralph 2',
  'La Reine des Neiges 2',
  'Raya et le Dernier Dragon',
  'Toy Story',
  '1001 pattes',
  'Toy Story 2',
  'Monstres et Cie',
  'Le Monde de Nemo',
  'Les Indestructibles',
  'Cars : Quatre Roues',
  'Ratatouille',
  'WALL·E',
  'Là-haut',
  'Toy Story 3',
  'Cars 2',
  'Rebelle',
  'Monstres Academy',
  'Vice-Versa',
  'Le Voyage d\'Arlo',
  'Le Monde de Dory',
  'Cars 3',
  'Coco',
  'Les Indestructibles 2',
  'Toy Story 4',
  'En avant',
  'Soul',
  'La Bande à Picsou, le Film : Le Trésor de la Lampe Perdue',
  'Le Retour de Jafar',
  'Dingo et Max',
  'Aladdin et le Roi des Voleurs',
  'Winnie l\'Ourson 2 : Le Grand Voyage',
  'La Belle et la Bête 2 : Le Noël Enchanté',
  'Le Monde Magique de la Belle et la Bête',
  'Pocahontas 2 : Un Monde Nouveau',
  'Le Roi Lion 2 : L\'Honneur de la Tribu',
  'Mickey, il était une fois Noël',
  'Winnie l\'Ourson : Joyeux Noël',
  'Les Aventures de Tigrou',
  'Dingo et Max 2 : Les Sportifs de l\'Extrême',
  'La Petite Sirène 2 : Retour à l\'Océan',
  'La Belle et le Clochard 2 : L\'Appel de la Rue',
  'Peter Pan 2 : Retour au Pays Imaginaire',
  'Cendrillon 2 : une vie de princesse',
  'Le Bossu de Notre-Dame 2 : Le Secret de Quasimodo',
  'Winnie l\'Ourson : Bonne Année',
  'Les 101 Dalmatiens 2 : Sur la Trace des Héros',
  'Le Livre de la Jungle 2',
  'Les Aventures de Porcinet',
  'Les Énigmes de l\'Atlantide',
  'Le Roi Lion 3 : Hakuna Matata',
  'Les Aventures de Petit Gourou',
  'Mickey, Donald, Dingo : Les Trois Mousquetaires',
  'Mickey, il était deux fois Noël',
  'Mulan 2 : La mission de l\'Empereur',
  'Winnie l\'Ourson et l\'Éfélant',
  'Tarzan 2 : L\'Enfance d\'un Héros',
  'Lilo et Stitch 2 : Hawaï, Nous avons un Problème!',
  'Winnie l\'Ourson : Lumpy fête Halloween',
  'Kuzco 2 : King Kronk',
  'Bambi 2',
  'Frère des Ours 2',
  'Rox et Rouky 2',
  'Le Sortilège de Cendrillon',
  'Les Histoires Merveilleuses - Vis tes Rêves',
  'Le Secret de la Petite Sirène',
  'La Fée Clochette',
  'Clochette et la Pierre de Lune',
  'Clochette et l\'Expédition Féerique',
  'Clochette et le Secret des Fées',
  'Planes',
  'Clochette et la Fée Pirate',
  'Planes 2',
  'Clochette et la Créature Légendaire',
];

List<String> hercule = [
  'Gospel Pur',
  'Le monde qui est le mien',
  'Il me reste un espoir',
  'De Zéro en Héros',
  'Jamais je n\'avouerai',
  'Une Étoile est née',
  'Hercule',
  'Hadès',
  'Pégase',
  'Philoctète',
  'Mégara',
  'Peine et Panique',
  'les Moires',
  'les Muses',
  'Zeus',
  'Héra',
  'Hermès',
  'Hestia',
  'Héphaïstos',
  'Athéna',
  'Arès',
  'Poséidon',
  'Aphrodite',
  'Artémis',
  'Apollon',
  'les Thébains',
  'Dionysos',
  'Titans',
  'Cerbère',
  'l\'Hydre de Lerne',
  'le Minotaure',
  'Sthéno',
  'Lion de Némée',
  'Nessus',
  'les Furies',
  'les Nymphes',
  'Amphitryon',
  'Alcmène',
  'Dieux de l\'Olympe',
  'Lythos',
  'Hydros',
  'Pyros',
  'Stratos',
  'Cyclope',
  'Calliope',
  'Clio',
  'Thalie',
  'Terpsichore',
  'Melpomène',
  'Lachesis',
  'Clotho',
  'Atropos',
  'Déméter',
  'Amphitrite',
  'Boreas',
  'Cupidon',
  'Morphée',
  'Phantasos',
  'Trivia',
  'Triton',
  'Circée',
  'Narcisse',
  'Erato',
  'Polyhymnia',
  'Euterpe',
  'Urania',
  'Grèce antique',
  'Mont Olympe',
  'Enfers',
  'Île de Philoctète',
  'Thèbes',
  'Académie Prométhée',
  'Atlantide',
  'Eclairs de Zeus',
  'Fiole Mortel',
  'Trident',
];

List<String> aristochats = [
  'Duchesse',
  'Thomas O\'Malley',
  'Toulouse',
  'Marie',
  'Berlioz',
  'Roquefort',
  'Frou-Frou',
  'Edgar Balthazar',
  'Adélaïde de Bonnefamille',
  'Georges Hautecourt',
  'le Laitier',
  'Napoléon',
  'Lafayette',
  'Amélie et Amelia Jacasse',
  'Waldo',
  'Scat Cat',
  'France',
  'Paris',
  'Manoir de Bonnefamille',
  'Ferme',
  'Repaire des Chats de Gouttière',
  '	Les Aristocats',
  'Gammes et Arpèges',
  'Thomas O\'Malley (chanson)',
  'Tout le monde veut devenir un Cat',
  'La Donna è mobile',
];
